"""Indian Railways G&SR Regulatory Rulebook Section 005."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_005: Dict[str, GSRSafetyRule] = {
    "GSR_SEC05_0001": GSRSafetyRule(
        rule_id="GSR_SEC05_0001",
        section_number="G&SR 5.2.2",
        title="Safety Protocol Compliance Clause 5-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0002": GSRSafetyRule(
        rule_id="GSR_SEC05_0002",
        section_number="G&SR 5.3.3",
        title="Safety Protocol Compliance Clause 5-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0003": GSRSafetyRule(
        rule_id="GSR_SEC05_0003",
        section_number="G&SR 5.4.4",
        title="Safety Protocol Compliance Clause 5-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0004": GSRSafetyRule(
        rule_id="GSR_SEC05_0004",
        section_number="G&SR 5.5.5",
        title="Safety Protocol Compliance Clause 5-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0005": GSRSafetyRule(
        rule_id="GSR_SEC05_0005",
        section_number="G&SR 5.6.6",
        title="Safety Protocol Compliance Clause 5-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0006": GSRSafetyRule(
        rule_id="GSR_SEC05_0006",
        section_number="G&SR 5.7.7",
        title="Safety Protocol Compliance Clause 5-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0007": GSRSafetyRule(
        rule_id="GSR_SEC05_0007",
        section_number="G&SR 5.8.8",
        title="Safety Protocol Compliance Clause 5-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0008": GSRSafetyRule(
        rule_id="GSR_SEC05_0008",
        section_number="G&SR 5.9.9",
        title="Safety Protocol Compliance Clause 5-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0009": GSRSafetyRule(
        rule_id="GSR_SEC05_0009",
        section_number="G&SR 5.10.1",
        title="Safety Protocol Compliance Clause 5-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0010": GSRSafetyRule(
        rule_id="GSR_SEC05_0010",
        section_number="G&SR 5.11.2",
        title="Safety Protocol Compliance Clause 5-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0011": GSRSafetyRule(
        rule_id="GSR_SEC05_0011",
        section_number="G&SR 5.12.3",
        title="Safety Protocol Compliance Clause 5-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0012": GSRSafetyRule(
        rule_id="GSR_SEC05_0012",
        section_number="G&SR 5.13.4",
        title="Safety Protocol Compliance Clause 5-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0013": GSRSafetyRule(
        rule_id="GSR_SEC05_0013",
        section_number="G&SR 5.14.5",
        title="Safety Protocol Compliance Clause 5-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0014": GSRSafetyRule(
        rule_id="GSR_SEC05_0014",
        section_number="G&SR 5.15.6",
        title="Safety Protocol Compliance Clause 5-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0015": GSRSafetyRule(
        rule_id="GSR_SEC05_0015",
        section_number="G&SR 5.16.7",
        title="Safety Protocol Compliance Clause 5-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0016": GSRSafetyRule(
        rule_id="GSR_SEC05_0016",
        section_number="G&SR 5.17.8",
        title="Safety Protocol Compliance Clause 5-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0017": GSRSafetyRule(
        rule_id="GSR_SEC05_0017",
        section_number="G&SR 5.18.9",
        title="Safety Protocol Compliance Clause 5-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0018": GSRSafetyRule(
        rule_id="GSR_SEC05_0018",
        section_number="G&SR 5.19.1",
        title="Safety Protocol Compliance Clause 5-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0019": GSRSafetyRule(
        rule_id="GSR_SEC05_0019",
        section_number="G&SR 5.20.2",
        title="Safety Protocol Compliance Clause 5-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0020": GSRSafetyRule(
        rule_id="GSR_SEC05_0020",
        section_number="G&SR 5.1.3",
        title="Safety Protocol Compliance Clause 5-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0021": GSRSafetyRule(
        rule_id="GSR_SEC05_0021",
        section_number="G&SR 5.2.4",
        title="Safety Protocol Compliance Clause 5-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0022": GSRSafetyRule(
        rule_id="GSR_SEC05_0022",
        section_number="G&SR 5.3.5",
        title="Safety Protocol Compliance Clause 5-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0023": GSRSafetyRule(
        rule_id="GSR_SEC05_0023",
        section_number="G&SR 5.4.6",
        title="Safety Protocol Compliance Clause 5-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0024": GSRSafetyRule(
        rule_id="GSR_SEC05_0024",
        section_number="G&SR 5.5.7",
        title="Safety Protocol Compliance Clause 5-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0025": GSRSafetyRule(
        rule_id="GSR_SEC05_0025",
        section_number="G&SR 5.6.8",
        title="Safety Protocol Compliance Clause 5-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0026": GSRSafetyRule(
        rule_id="GSR_SEC05_0026",
        section_number="G&SR 5.7.9",
        title="Safety Protocol Compliance Clause 5-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0027": GSRSafetyRule(
        rule_id="GSR_SEC05_0027",
        section_number="G&SR 5.8.1",
        title="Safety Protocol Compliance Clause 5-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0028": GSRSafetyRule(
        rule_id="GSR_SEC05_0028",
        section_number="G&SR 5.9.2",
        title="Safety Protocol Compliance Clause 5-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0029": GSRSafetyRule(
        rule_id="GSR_SEC05_0029",
        section_number="G&SR 5.10.3",
        title="Safety Protocol Compliance Clause 5-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0030": GSRSafetyRule(
        rule_id="GSR_SEC05_0030",
        section_number="G&SR 5.11.4",
        title="Safety Protocol Compliance Clause 5-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0031": GSRSafetyRule(
        rule_id="GSR_SEC05_0031",
        section_number="G&SR 5.12.5",
        title="Safety Protocol Compliance Clause 5-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0032": GSRSafetyRule(
        rule_id="GSR_SEC05_0032",
        section_number="G&SR 5.13.6",
        title="Safety Protocol Compliance Clause 5-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0033": GSRSafetyRule(
        rule_id="GSR_SEC05_0033",
        section_number="G&SR 5.14.7",
        title="Safety Protocol Compliance Clause 5-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0034": GSRSafetyRule(
        rule_id="GSR_SEC05_0034",
        section_number="G&SR 5.15.8",
        title="Safety Protocol Compliance Clause 5-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0035": GSRSafetyRule(
        rule_id="GSR_SEC05_0035",
        section_number="G&SR 5.16.9",
        title="Safety Protocol Compliance Clause 5-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0036": GSRSafetyRule(
        rule_id="GSR_SEC05_0036",
        section_number="G&SR 5.17.1",
        title="Safety Protocol Compliance Clause 5-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0037": GSRSafetyRule(
        rule_id="GSR_SEC05_0037",
        section_number="G&SR 5.18.2",
        title="Safety Protocol Compliance Clause 5-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0038": GSRSafetyRule(
        rule_id="GSR_SEC05_0038",
        section_number="G&SR 5.19.3",
        title="Safety Protocol Compliance Clause 5-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0039": GSRSafetyRule(
        rule_id="GSR_SEC05_0039",
        section_number="G&SR 5.20.4",
        title="Safety Protocol Compliance Clause 5-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0040": GSRSafetyRule(
        rule_id="GSR_SEC05_0040",
        section_number="G&SR 5.1.5",
        title="Safety Protocol Compliance Clause 5-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0041": GSRSafetyRule(
        rule_id="GSR_SEC05_0041",
        section_number="G&SR 5.2.6",
        title="Safety Protocol Compliance Clause 5-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0042": GSRSafetyRule(
        rule_id="GSR_SEC05_0042",
        section_number="G&SR 5.3.7",
        title="Safety Protocol Compliance Clause 5-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0043": GSRSafetyRule(
        rule_id="GSR_SEC05_0043",
        section_number="G&SR 5.4.8",
        title="Safety Protocol Compliance Clause 5-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0044": GSRSafetyRule(
        rule_id="GSR_SEC05_0044",
        section_number="G&SR 5.5.9",
        title="Safety Protocol Compliance Clause 5-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0045": GSRSafetyRule(
        rule_id="GSR_SEC05_0045",
        section_number="G&SR 5.6.1",
        title="Safety Protocol Compliance Clause 5-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0046": GSRSafetyRule(
        rule_id="GSR_SEC05_0046",
        section_number="G&SR 5.7.2",
        title="Safety Protocol Compliance Clause 5-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0047": GSRSafetyRule(
        rule_id="GSR_SEC05_0047",
        section_number="G&SR 5.8.3",
        title="Safety Protocol Compliance Clause 5-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0048": GSRSafetyRule(
        rule_id="GSR_SEC05_0048",
        section_number="G&SR 5.9.4",
        title="Safety Protocol Compliance Clause 5-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0049": GSRSafetyRule(
        rule_id="GSR_SEC05_0049",
        section_number="G&SR 5.10.5",
        title="Safety Protocol Compliance Clause 5-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0050": GSRSafetyRule(
        rule_id="GSR_SEC05_0050",
        section_number="G&SR 5.11.6",
        title="Safety Protocol Compliance Clause 5-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0051": GSRSafetyRule(
        rule_id="GSR_SEC05_0051",
        section_number="G&SR 5.12.7",
        title="Safety Protocol Compliance Clause 5-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0052": GSRSafetyRule(
        rule_id="GSR_SEC05_0052",
        section_number="G&SR 5.13.8",
        title="Safety Protocol Compliance Clause 5-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0053": GSRSafetyRule(
        rule_id="GSR_SEC05_0053",
        section_number="G&SR 5.14.9",
        title="Safety Protocol Compliance Clause 5-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0054": GSRSafetyRule(
        rule_id="GSR_SEC05_0054",
        section_number="G&SR 5.15.1",
        title="Safety Protocol Compliance Clause 5-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0055": GSRSafetyRule(
        rule_id="GSR_SEC05_0055",
        section_number="G&SR 5.16.2",
        title="Safety Protocol Compliance Clause 5-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0056": GSRSafetyRule(
        rule_id="GSR_SEC05_0056",
        section_number="G&SR 5.17.3",
        title="Safety Protocol Compliance Clause 5-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0057": GSRSafetyRule(
        rule_id="GSR_SEC05_0057",
        section_number="G&SR 5.18.4",
        title="Safety Protocol Compliance Clause 5-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0058": GSRSafetyRule(
        rule_id="GSR_SEC05_0058",
        section_number="G&SR 5.19.5",
        title="Safety Protocol Compliance Clause 5-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0059": GSRSafetyRule(
        rule_id="GSR_SEC05_0059",
        section_number="G&SR 5.20.6",
        title="Safety Protocol Compliance Clause 5-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0060": GSRSafetyRule(
        rule_id="GSR_SEC05_0060",
        section_number="G&SR 5.1.7",
        title="Safety Protocol Compliance Clause 5-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0061": GSRSafetyRule(
        rule_id="GSR_SEC05_0061",
        section_number="G&SR 5.2.8",
        title="Safety Protocol Compliance Clause 5-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0062": GSRSafetyRule(
        rule_id="GSR_SEC05_0062",
        section_number="G&SR 5.3.9",
        title="Safety Protocol Compliance Clause 5-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0063": GSRSafetyRule(
        rule_id="GSR_SEC05_0063",
        section_number="G&SR 5.4.1",
        title="Safety Protocol Compliance Clause 5-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0064": GSRSafetyRule(
        rule_id="GSR_SEC05_0064",
        section_number="G&SR 5.5.2",
        title="Safety Protocol Compliance Clause 5-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0065": GSRSafetyRule(
        rule_id="GSR_SEC05_0065",
        section_number="G&SR 5.6.3",
        title="Safety Protocol Compliance Clause 5-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0066": GSRSafetyRule(
        rule_id="GSR_SEC05_0066",
        section_number="G&SR 5.7.4",
        title="Safety Protocol Compliance Clause 5-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0067": GSRSafetyRule(
        rule_id="GSR_SEC05_0067",
        section_number="G&SR 5.8.5",
        title="Safety Protocol Compliance Clause 5-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0068": GSRSafetyRule(
        rule_id="GSR_SEC05_0068",
        section_number="G&SR 5.9.6",
        title="Safety Protocol Compliance Clause 5-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0069": GSRSafetyRule(
        rule_id="GSR_SEC05_0069",
        section_number="G&SR 5.10.7",
        title="Safety Protocol Compliance Clause 5-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0070": GSRSafetyRule(
        rule_id="GSR_SEC05_0070",
        section_number="G&SR 5.11.8",
        title="Safety Protocol Compliance Clause 5-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0071": GSRSafetyRule(
        rule_id="GSR_SEC05_0071",
        section_number="G&SR 5.12.9",
        title="Safety Protocol Compliance Clause 5-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0072": GSRSafetyRule(
        rule_id="GSR_SEC05_0072",
        section_number="G&SR 5.13.1",
        title="Safety Protocol Compliance Clause 5-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0073": GSRSafetyRule(
        rule_id="GSR_SEC05_0073",
        section_number="G&SR 5.14.2",
        title="Safety Protocol Compliance Clause 5-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0074": GSRSafetyRule(
        rule_id="GSR_SEC05_0074",
        section_number="G&SR 5.15.3",
        title="Safety Protocol Compliance Clause 5-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0075": GSRSafetyRule(
        rule_id="GSR_SEC05_0075",
        section_number="G&SR 5.16.4",
        title="Safety Protocol Compliance Clause 5-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0076": GSRSafetyRule(
        rule_id="GSR_SEC05_0076",
        section_number="G&SR 5.17.5",
        title="Safety Protocol Compliance Clause 5-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0077": GSRSafetyRule(
        rule_id="GSR_SEC05_0077",
        section_number="G&SR 5.18.6",
        title="Safety Protocol Compliance Clause 5-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0078": GSRSafetyRule(
        rule_id="GSR_SEC05_0078",
        section_number="G&SR 5.19.7",
        title="Safety Protocol Compliance Clause 5-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0079": GSRSafetyRule(
        rule_id="GSR_SEC05_0079",
        section_number="G&SR 5.20.8",
        title="Safety Protocol Compliance Clause 5-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0080": GSRSafetyRule(
        rule_id="GSR_SEC05_0080",
        section_number="G&SR 5.1.9",
        title="Safety Protocol Compliance Clause 5-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0081": GSRSafetyRule(
        rule_id="GSR_SEC05_0081",
        section_number="G&SR 5.2.1",
        title="Safety Protocol Compliance Clause 5-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0082": GSRSafetyRule(
        rule_id="GSR_SEC05_0082",
        section_number="G&SR 5.3.2",
        title="Safety Protocol Compliance Clause 5-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0083": GSRSafetyRule(
        rule_id="GSR_SEC05_0083",
        section_number="G&SR 5.4.3",
        title="Safety Protocol Compliance Clause 5-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0084": GSRSafetyRule(
        rule_id="GSR_SEC05_0084",
        section_number="G&SR 5.5.4",
        title="Safety Protocol Compliance Clause 5-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0085": GSRSafetyRule(
        rule_id="GSR_SEC05_0085",
        section_number="G&SR 5.6.5",
        title="Safety Protocol Compliance Clause 5-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0086": GSRSafetyRule(
        rule_id="GSR_SEC05_0086",
        section_number="G&SR 5.7.6",
        title="Safety Protocol Compliance Clause 5-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0087": GSRSafetyRule(
        rule_id="GSR_SEC05_0087",
        section_number="G&SR 5.8.7",
        title="Safety Protocol Compliance Clause 5-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0088": GSRSafetyRule(
        rule_id="GSR_SEC05_0088",
        section_number="G&SR 5.9.8",
        title="Safety Protocol Compliance Clause 5-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0089": GSRSafetyRule(
        rule_id="GSR_SEC05_0089",
        section_number="G&SR 5.10.9",
        title="Safety Protocol Compliance Clause 5-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0090": GSRSafetyRule(
        rule_id="GSR_SEC05_0090",
        section_number="G&SR 5.11.1",
        title="Safety Protocol Compliance Clause 5-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0091": GSRSafetyRule(
        rule_id="GSR_SEC05_0091",
        section_number="G&SR 5.12.2",
        title="Safety Protocol Compliance Clause 5-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0092": GSRSafetyRule(
        rule_id="GSR_SEC05_0092",
        section_number="G&SR 5.13.3",
        title="Safety Protocol Compliance Clause 5-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0093": GSRSafetyRule(
        rule_id="GSR_SEC05_0093",
        section_number="G&SR 5.14.4",
        title="Safety Protocol Compliance Clause 5-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0094": GSRSafetyRule(
        rule_id="GSR_SEC05_0094",
        section_number="G&SR 5.15.5",
        title="Safety Protocol Compliance Clause 5-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0095": GSRSafetyRule(
        rule_id="GSR_SEC05_0095",
        section_number="G&SR 5.16.6",
        title="Safety Protocol Compliance Clause 5-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0096": GSRSafetyRule(
        rule_id="GSR_SEC05_0096",
        section_number="G&SR 5.17.7",
        title="Safety Protocol Compliance Clause 5-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0097": GSRSafetyRule(
        rule_id="GSR_SEC05_0097",
        section_number="G&SR 5.18.8",
        title="Safety Protocol Compliance Clause 5-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0098": GSRSafetyRule(
        rule_id="GSR_SEC05_0098",
        section_number="G&SR 5.19.9",
        title="Safety Protocol Compliance Clause 5-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0099": GSRSafetyRule(
        rule_id="GSR_SEC05_0099",
        section_number="G&SR 5.20.1",
        title="Safety Protocol Compliance Clause 5-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0100": GSRSafetyRule(
        rule_id="GSR_SEC05_0100",
        section_number="G&SR 5.1.2",
        title="Safety Protocol Compliance Clause 5-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0101": GSRSafetyRule(
        rule_id="GSR_SEC05_0101",
        section_number="G&SR 5.2.3",
        title="Safety Protocol Compliance Clause 5-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0102": GSRSafetyRule(
        rule_id="GSR_SEC05_0102",
        section_number="G&SR 5.3.4",
        title="Safety Protocol Compliance Clause 5-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0103": GSRSafetyRule(
        rule_id="GSR_SEC05_0103",
        section_number="G&SR 5.4.5",
        title="Safety Protocol Compliance Clause 5-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0104": GSRSafetyRule(
        rule_id="GSR_SEC05_0104",
        section_number="G&SR 5.5.6",
        title="Safety Protocol Compliance Clause 5-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0105": GSRSafetyRule(
        rule_id="GSR_SEC05_0105",
        section_number="G&SR 5.6.7",
        title="Safety Protocol Compliance Clause 5-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0106": GSRSafetyRule(
        rule_id="GSR_SEC05_0106",
        section_number="G&SR 5.7.8",
        title="Safety Protocol Compliance Clause 5-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0107": GSRSafetyRule(
        rule_id="GSR_SEC05_0107",
        section_number="G&SR 5.8.9",
        title="Safety Protocol Compliance Clause 5-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0108": GSRSafetyRule(
        rule_id="GSR_SEC05_0108",
        section_number="G&SR 5.9.1",
        title="Safety Protocol Compliance Clause 5-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0109": GSRSafetyRule(
        rule_id="GSR_SEC05_0109",
        section_number="G&SR 5.10.2",
        title="Safety Protocol Compliance Clause 5-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0110": GSRSafetyRule(
        rule_id="GSR_SEC05_0110",
        section_number="G&SR 5.11.3",
        title="Safety Protocol Compliance Clause 5-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0111": GSRSafetyRule(
        rule_id="GSR_SEC05_0111",
        section_number="G&SR 5.12.4",
        title="Safety Protocol Compliance Clause 5-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0112": GSRSafetyRule(
        rule_id="GSR_SEC05_0112",
        section_number="G&SR 5.13.5",
        title="Safety Protocol Compliance Clause 5-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0113": GSRSafetyRule(
        rule_id="GSR_SEC05_0113",
        section_number="G&SR 5.14.6",
        title="Safety Protocol Compliance Clause 5-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0114": GSRSafetyRule(
        rule_id="GSR_SEC05_0114",
        section_number="G&SR 5.15.7",
        title="Safety Protocol Compliance Clause 5-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0115": GSRSafetyRule(
        rule_id="GSR_SEC05_0115",
        section_number="G&SR 5.16.8",
        title="Safety Protocol Compliance Clause 5-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0116": GSRSafetyRule(
        rule_id="GSR_SEC05_0116",
        section_number="G&SR 5.17.9",
        title="Safety Protocol Compliance Clause 5-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0117": GSRSafetyRule(
        rule_id="GSR_SEC05_0117",
        section_number="G&SR 5.18.1",
        title="Safety Protocol Compliance Clause 5-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0118": GSRSafetyRule(
        rule_id="GSR_SEC05_0118",
        section_number="G&SR 5.19.2",
        title="Safety Protocol Compliance Clause 5-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0119": GSRSafetyRule(
        rule_id="GSR_SEC05_0119",
        section_number="G&SR 5.20.3",
        title="Safety Protocol Compliance Clause 5-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0120": GSRSafetyRule(
        rule_id="GSR_SEC05_0120",
        section_number="G&SR 5.1.4",
        title="Safety Protocol Compliance Clause 5-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0121": GSRSafetyRule(
        rule_id="GSR_SEC05_0121",
        section_number="G&SR 5.2.5",
        title="Safety Protocol Compliance Clause 5-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0122": GSRSafetyRule(
        rule_id="GSR_SEC05_0122",
        section_number="G&SR 5.3.6",
        title="Safety Protocol Compliance Clause 5-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0123": GSRSafetyRule(
        rule_id="GSR_SEC05_0123",
        section_number="G&SR 5.4.7",
        title="Safety Protocol Compliance Clause 5-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0124": GSRSafetyRule(
        rule_id="GSR_SEC05_0124",
        section_number="G&SR 5.5.8",
        title="Safety Protocol Compliance Clause 5-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0125": GSRSafetyRule(
        rule_id="GSR_SEC05_0125",
        section_number="G&SR 5.6.9",
        title="Safety Protocol Compliance Clause 5-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0126": GSRSafetyRule(
        rule_id="GSR_SEC05_0126",
        section_number="G&SR 5.7.1",
        title="Safety Protocol Compliance Clause 5-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0127": GSRSafetyRule(
        rule_id="GSR_SEC05_0127",
        section_number="G&SR 5.8.2",
        title="Safety Protocol Compliance Clause 5-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0128": GSRSafetyRule(
        rule_id="GSR_SEC05_0128",
        section_number="G&SR 5.9.3",
        title="Safety Protocol Compliance Clause 5-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0129": GSRSafetyRule(
        rule_id="GSR_SEC05_0129",
        section_number="G&SR 5.10.4",
        title="Safety Protocol Compliance Clause 5-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0130": GSRSafetyRule(
        rule_id="GSR_SEC05_0130",
        section_number="G&SR 5.11.5",
        title="Safety Protocol Compliance Clause 5-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0131": GSRSafetyRule(
        rule_id="GSR_SEC05_0131",
        section_number="G&SR 5.12.6",
        title="Safety Protocol Compliance Clause 5-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0132": GSRSafetyRule(
        rule_id="GSR_SEC05_0132",
        section_number="G&SR 5.13.7",
        title="Safety Protocol Compliance Clause 5-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0133": GSRSafetyRule(
        rule_id="GSR_SEC05_0133",
        section_number="G&SR 5.14.8",
        title="Safety Protocol Compliance Clause 5-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0134": GSRSafetyRule(
        rule_id="GSR_SEC05_0134",
        section_number="G&SR 5.15.9",
        title="Safety Protocol Compliance Clause 5-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0135": GSRSafetyRule(
        rule_id="GSR_SEC05_0135",
        section_number="G&SR 5.16.1",
        title="Safety Protocol Compliance Clause 5-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0136": GSRSafetyRule(
        rule_id="GSR_SEC05_0136",
        section_number="G&SR 5.17.2",
        title="Safety Protocol Compliance Clause 5-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0137": GSRSafetyRule(
        rule_id="GSR_SEC05_0137",
        section_number="G&SR 5.18.3",
        title="Safety Protocol Compliance Clause 5-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0138": GSRSafetyRule(
        rule_id="GSR_SEC05_0138",
        section_number="G&SR 5.19.4",
        title="Safety Protocol Compliance Clause 5-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0139": GSRSafetyRule(
        rule_id="GSR_SEC05_0139",
        section_number="G&SR 5.20.5",
        title="Safety Protocol Compliance Clause 5-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0140": GSRSafetyRule(
        rule_id="GSR_SEC05_0140",
        section_number="G&SR 5.1.6",
        title="Safety Protocol Compliance Clause 5-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0141": GSRSafetyRule(
        rule_id="GSR_SEC05_0141",
        section_number="G&SR 5.2.7",
        title="Safety Protocol Compliance Clause 5-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0142": GSRSafetyRule(
        rule_id="GSR_SEC05_0142",
        section_number="G&SR 5.3.8",
        title="Safety Protocol Compliance Clause 5-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0143": GSRSafetyRule(
        rule_id="GSR_SEC05_0143",
        section_number="G&SR 5.4.9",
        title="Safety Protocol Compliance Clause 5-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0144": GSRSafetyRule(
        rule_id="GSR_SEC05_0144",
        section_number="G&SR 5.5.1",
        title="Safety Protocol Compliance Clause 5-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0145": GSRSafetyRule(
        rule_id="GSR_SEC05_0145",
        section_number="G&SR 5.6.2",
        title="Safety Protocol Compliance Clause 5-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0146": GSRSafetyRule(
        rule_id="GSR_SEC05_0146",
        section_number="G&SR 5.7.3",
        title="Safety Protocol Compliance Clause 5-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0147": GSRSafetyRule(
        rule_id="GSR_SEC05_0147",
        section_number="G&SR 5.8.4",
        title="Safety Protocol Compliance Clause 5-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0148": GSRSafetyRule(
        rule_id="GSR_SEC05_0148",
        section_number="G&SR 5.9.5",
        title="Safety Protocol Compliance Clause 5-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0149": GSRSafetyRule(
        rule_id="GSR_SEC05_0149",
        section_number="G&SR 5.10.6",
        title="Safety Protocol Compliance Clause 5-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0150": GSRSafetyRule(
        rule_id="GSR_SEC05_0150",
        section_number="G&SR 5.11.7",
        title="Safety Protocol Compliance Clause 5-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0151": GSRSafetyRule(
        rule_id="GSR_SEC05_0151",
        section_number="G&SR 5.12.8",
        title="Safety Protocol Compliance Clause 5-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0152": GSRSafetyRule(
        rule_id="GSR_SEC05_0152",
        section_number="G&SR 5.13.9",
        title="Safety Protocol Compliance Clause 5-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0153": GSRSafetyRule(
        rule_id="GSR_SEC05_0153",
        section_number="G&SR 5.14.1",
        title="Safety Protocol Compliance Clause 5-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0154": GSRSafetyRule(
        rule_id="GSR_SEC05_0154",
        section_number="G&SR 5.15.2",
        title="Safety Protocol Compliance Clause 5-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0155": GSRSafetyRule(
        rule_id="GSR_SEC05_0155",
        section_number="G&SR 5.16.3",
        title="Safety Protocol Compliance Clause 5-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0156": GSRSafetyRule(
        rule_id="GSR_SEC05_0156",
        section_number="G&SR 5.17.4",
        title="Safety Protocol Compliance Clause 5-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0157": GSRSafetyRule(
        rule_id="GSR_SEC05_0157",
        section_number="G&SR 5.18.5",
        title="Safety Protocol Compliance Clause 5-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0158": GSRSafetyRule(
        rule_id="GSR_SEC05_0158",
        section_number="G&SR 5.19.6",
        title="Safety Protocol Compliance Clause 5-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0159": GSRSafetyRule(
        rule_id="GSR_SEC05_0159",
        section_number="G&SR 5.20.7",
        title="Safety Protocol Compliance Clause 5-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0160": GSRSafetyRule(
        rule_id="GSR_SEC05_0160",
        section_number="G&SR 5.1.8",
        title="Safety Protocol Compliance Clause 5-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0161": GSRSafetyRule(
        rule_id="GSR_SEC05_0161",
        section_number="G&SR 5.2.9",
        title="Safety Protocol Compliance Clause 5-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0162": GSRSafetyRule(
        rule_id="GSR_SEC05_0162",
        section_number="G&SR 5.3.1",
        title="Safety Protocol Compliance Clause 5-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0163": GSRSafetyRule(
        rule_id="GSR_SEC05_0163",
        section_number="G&SR 5.4.2",
        title="Safety Protocol Compliance Clause 5-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0164": GSRSafetyRule(
        rule_id="GSR_SEC05_0164",
        section_number="G&SR 5.5.3",
        title="Safety Protocol Compliance Clause 5-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0165": GSRSafetyRule(
        rule_id="GSR_SEC05_0165",
        section_number="G&SR 5.6.4",
        title="Safety Protocol Compliance Clause 5-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0166": GSRSafetyRule(
        rule_id="GSR_SEC05_0166",
        section_number="G&SR 5.7.5",
        title="Safety Protocol Compliance Clause 5-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0167": GSRSafetyRule(
        rule_id="GSR_SEC05_0167",
        section_number="G&SR 5.8.6",
        title="Safety Protocol Compliance Clause 5-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0168": GSRSafetyRule(
        rule_id="GSR_SEC05_0168",
        section_number="G&SR 5.9.7",
        title="Safety Protocol Compliance Clause 5-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0169": GSRSafetyRule(
        rule_id="GSR_SEC05_0169",
        section_number="G&SR 5.10.8",
        title="Safety Protocol Compliance Clause 5-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0170": GSRSafetyRule(
        rule_id="GSR_SEC05_0170",
        section_number="G&SR 5.11.9",
        title="Safety Protocol Compliance Clause 5-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0171": GSRSafetyRule(
        rule_id="GSR_SEC05_0171",
        section_number="G&SR 5.12.1",
        title="Safety Protocol Compliance Clause 5-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0172": GSRSafetyRule(
        rule_id="GSR_SEC05_0172",
        section_number="G&SR 5.13.2",
        title="Safety Protocol Compliance Clause 5-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0173": GSRSafetyRule(
        rule_id="GSR_SEC05_0173",
        section_number="G&SR 5.14.3",
        title="Safety Protocol Compliance Clause 5-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC05_0174": GSRSafetyRule(
        rule_id="GSR_SEC05_0174",
        section_number="G&SR 5.15.4",
        title="Safety Protocol Compliance Clause 5-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
