"""Indian Railways G&SR Regulatory Rulebook Section 022."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_022: Dict[str, GSRSafetyRule] = {
    "GSR_SEC22_0001": GSRSafetyRule(
        rule_id="GSR_SEC22_0001",
        section_number="G&SR 22.2.2",
        title="Safety Protocol Compliance Clause 22-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0002": GSRSafetyRule(
        rule_id="GSR_SEC22_0002",
        section_number="G&SR 22.3.3",
        title="Safety Protocol Compliance Clause 22-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0003": GSRSafetyRule(
        rule_id="GSR_SEC22_0003",
        section_number="G&SR 22.4.4",
        title="Safety Protocol Compliance Clause 22-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0004": GSRSafetyRule(
        rule_id="GSR_SEC22_0004",
        section_number="G&SR 22.5.5",
        title="Safety Protocol Compliance Clause 22-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0005": GSRSafetyRule(
        rule_id="GSR_SEC22_0005",
        section_number="G&SR 22.6.6",
        title="Safety Protocol Compliance Clause 22-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0006": GSRSafetyRule(
        rule_id="GSR_SEC22_0006",
        section_number="G&SR 22.7.7",
        title="Safety Protocol Compliance Clause 22-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0007": GSRSafetyRule(
        rule_id="GSR_SEC22_0007",
        section_number="G&SR 22.8.8",
        title="Safety Protocol Compliance Clause 22-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0008": GSRSafetyRule(
        rule_id="GSR_SEC22_0008",
        section_number="G&SR 22.9.9",
        title="Safety Protocol Compliance Clause 22-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0009": GSRSafetyRule(
        rule_id="GSR_SEC22_0009",
        section_number="G&SR 22.10.1",
        title="Safety Protocol Compliance Clause 22-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0010": GSRSafetyRule(
        rule_id="GSR_SEC22_0010",
        section_number="G&SR 22.11.2",
        title="Safety Protocol Compliance Clause 22-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0011": GSRSafetyRule(
        rule_id="GSR_SEC22_0011",
        section_number="G&SR 22.12.3",
        title="Safety Protocol Compliance Clause 22-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0012": GSRSafetyRule(
        rule_id="GSR_SEC22_0012",
        section_number="G&SR 22.13.4",
        title="Safety Protocol Compliance Clause 22-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0013": GSRSafetyRule(
        rule_id="GSR_SEC22_0013",
        section_number="G&SR 22.14.5",
        title="Safety Protocol Compliance Clause 22-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0014": GSRSafetyRule(
        rule_id="GSR_SEC22_0014",
        section_number="G&SR 22.15.6",
        title="Safety Protocol Compliance Clause 22-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0015": GSRSafetyRule(
        rule_id="GSR_SEC22_0015",
        section_number="G&SR 22.16.7",
        title="Safety Protocol Compliance Clause 22-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0016": GSRSafetyRule(
        rule_id="GSR_SEC22_0016",
        section_number="G&SR 22.17.8",
        title="Safety Protocol Compliance Clause 22-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0017": GSRSafetyRule(
        rule_id="GSR_SEC22_0017",
        section_number="G&SR 22.18.9",
        title="Safety Protocol Compliance Clause 22-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0018": GSRSafetyRule(
        rule_id="GSR_SEC22_0018",
        section_number="G&SR 22.19.1",
        title="Safety Protocol Compliance Clause 22-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0019": GSRSafetyRule(
        rule_id="GSR_SEC22_0019",
        section_number="G&SR 22.20.2",
        title="Safety Protocol Compliance Clause 22-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0020": GSRSafetyRule(
        rule_id="GSR_SEC22_0020",
        section_number="G&SR 22.1.3",
        title="Safety Protocol Compliance Clause 22-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0021": GSRSafetyRule(
        rule_id="GSR_SEC22_0021",
        section_number="G&SR 22.2.4",
        title="Safety Protocol Compliance Clause 22-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0022": GSRSafetyRule(
        rule_id="GSR_SEC22_0022",
        section_number="G&SR 22.3.5",
        title="Safety Protocol Compliance Clause 22-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0023": GSRSafetyRule(
        rule_id="GSR_SEC22_0023",
        section_number="G&SR 22.4.6",
        title="Safety Protocol Compliance Clause 22-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0024": GSRSafetyRule(
        rule_id="GSR_SEC22_0024",
        section_number="G&SR 22.5.7",
        title="Safety Protocol Compliance Clause 22-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0025": GSRSafetyRule(
        rule_id="GSR_SEC22_0025",
        section_number="G&SR 22.6.8",
        title="Safety Protocol Compliance Clause 22-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0026": GSRSafetyRule(
        rule_id="GSR_SEC22_0026",
        section_number="G&SR 22.7.9",
        title="Safety Protocol Compliance Clause 22-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0027": GSRSafetyRule(
        rule_id="GSR_SEC22_0027",
        section_number="G&SR 22.8.1",
        title="Safety Protocol Compliance Clause 22-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0028": GSRSafetyRule(
        rule_id="GSR_SEC22_0028",
        section_number="G&SR 22.9.2",
        title="Safety Protocol Compliance Clause 22-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0029": GSRSafetyRule(
        rule_id="GSR_SEC22_0029",
        section_number="G&SR 22.10.3",
        title="Safety Protocol Compliance Clause 22-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0030": GSRSafetyRule(
        rule_id="GSR_SEC22_0030",
        section_number="G&SR 22.11.4",
        title="Safety Protocol Compliance Clause 22-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0031": GSRSafetyRule(
        rule_id="GSR_SEC22_0031",
        section_number="G&SR 22.12.5",
        title="Safety Protocol Compliance Clause 22-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0032": GSRSafetyRule(
        rule_id="GSR_SEC22_0032",
        section_number="G&SR 22.13.6",
        title="Safety Protocol Compliance Clause 22-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0033": GSRSafetyRule(
        rule_id="GSR_SEC22_0033",
        section_number="G&SR 22.14.7",
        title="Safety Protocol Compliance Clause 22-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0034": GSRSafetyRule(
        rule_id="GSR_SEC22_0034",
        section_number="G&SR 22.15.8",
        title="Safety Protocol Compliance Clause 22-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0035": GSRSafetyRule(
        rule_id="GSR_SEC22_0035",
        section_number="G&SR 22.16.9",
        title="Safety Protocol Compliance Clause 22-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0036": GSRSafetyRule(
        rule_id="GSR_SEC22_0036",
        section_number="G&SR 22.17.1",
        title="Safety Protocol Compliance Clause 22-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0037": GSRSafetyRule(
        rule_id="GSR_SEC22_0037",
        section_number="G&SR 22.18.2",
        title="Safety Protocol Compliance Clause 22-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0038": GSRSafetyRule(
        rule_id="GSR_SEC22_0038",
        section_number="G&SR 22.19.3",
        title="Safety Protocol Compliance Clause 22-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0039": GSRSafetyRule(
        rule_id="GSR_SEC22_0039",
        section_number="G&SR 22.20.4",
        title="Safety Protocol Compliance Clause 22-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0040": GSRSafetyRule(
        rule_id="GSR_SEC22_0040",
        section_number="G&SR 22.1.5",
        title="Safety Protocol Compliance Clause 22-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0041": GSRSafetyRule(
        rule_id="GSR_SEC22_0041",
        section_number="G&SR 22.2.6",
        title="Safety Protocol Compliance Clause 22-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0042": GSRSafetyRule(
        rule_id="GSR_SEC22_0042",
        section_number="G&SR 22.3.7",
        title="Safety Protocol Compliance Clause 22-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0043": GSRSafetyRule(
        rule_id="GSR_SEC22_0043",
        section_number="G&SR 22.4.8",
        title="Safety Protocol Compliance Clause 22-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0044": GSRSafetyRule(
        rule_id="GSR_SEC22_0044",
        section_number="G&SR 22.5.9",
        title="Safety Protocol Compliance Clause 22-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0045": GSRSafetyRule(
        rule_id="GSR_SEC22_0045",
        section_number="G&SR 22.6.1",
        title="Safety Protocol Compliance Clause 22-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0046": GSRSafetyRule(
        rule_id="GSR_SEC22_0046",
        section_number="G&SR 22.7.2",
        title="Safety Protocol Compliance Clause 22-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0047": GSRSafetyRule(
        rule_id="GSR_SEC22_0047",
        section_number="G&SR 22.8.3",
        title="Safety Protocol Compliance Clause 22-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0048": GSRSafetyRule(
        rule_id="GSR_SEC22_0048",
        section_number="G&SR 22.9.4",
        title="Safety Protocol Compliance Clause 22-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0049": GSRSafetyRule(
        rule_id="GSR_SEC22_0049",
        section_number="G&SR 22.10.5",
        title="Safety Protocol Compliance Clause 22-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0050": GSRSafetyRule(
        rule_id="GSR_SEC22_0050",
        section_number="G&SR 22.11.6",
        title="Safety Protocol Compliance Clause 22-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0051": GSRSafetyRule(
        rule_id="GSR_SEC22_0051",
        section_number="G&SR 22.12.7",
        title="Safety Protocol Compliance Clause 22-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0052": GSRSafetyRule(
        rule_id="GSR_SEC22_0052",
        section_number="G&SR 22.13.8",
        title="Safety Protocol Compliance Clause 22-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0053": GSRSafetyRule(
        rule_id="GSR_SEC22_0053",
        section_number="G&SR 22.14.9",
        title="Safety Protocol Compliance Clause 22-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0054": GSRSafetyRule(
        rule_id="GSR_SEC22_0054",
        section_number="G&SR 22.15.1",
        title="Safety Protocol Compliance Clause 22-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0055": GSRSafetyRule(
        rule_id="GSR_SEC22_0055",
        section_number="G&SR 22.16.2",
        title="Safety Protocol Compliance Clause 22-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0056": GSRSafetyRule(
        rule_id="GSR_SEC22_0056",
        section_number="G&SR 22.17.3",
        title="Safety Protocol Compliance Clause 22-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0057": GSRSafetyRule(
        rule_id="GSR_SEC22_0057",
        section_number="G&SR 22.18.4",
        title="Safety Protocol Compliance Clause 22-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0058": GSRSafetyRule(
        rule_id="GSR_SEC22_0058",
        section_number="G&SR 22.19.5",
        title="Safety Protocol Compliance Clause 22-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0059": GSRSafetyRule(
        rule_id="GSR_SEC22_0059",
        section_number="G&SR 22.20.6",
        title="Safety Protocol Compliance Clause 22-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0060": GSRSafetyRule(
        rule_id="GSR_SEC22_0060",
        section_number="G&SR 22.1.7",
        title="Safety Protocol Compliance Clause 22-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0061": GSRSafetyRule(
        rule_id="GSR_SEC22_0061",
        section_number="G&SR 22.2.8",
        title="Safety Protocol Compliance Clause 22-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0062": GSRSafetyRule(
        rule_id="GSR_SEC22_0062",
        section_number="G&SR 22.3.9",
        title="Safety Protocol Compliance Clause 22-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0063": GSRSafetyRule(
        rule_id="GSR_SEC22_0063",
        section_number="G&SR 22.4.1",
        title="Safety Protocol Compliance Clause 22-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0064": GSRSafetyRule(
        rule_id="GSR_SEC22_0064",
        section_number="G&SR 22.5.2",
        title="Safety Protocol Compliance Clause 22-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0065": GSRSafetyRule(
        rule_id="GSR_SEC22_0065",
        section_number="G&SR 22.6.3",
        title="Safety Protocol Compliance Clause 22-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0066": GSRSafetyRule(
        rule_id="GSR_SEC22_0066",
        section_number="G&SR 22.7.4",
        title="Safety Protocol Compliance Clause 22-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0067": GSRSafetyRule(
        rule_id="GSR_SEC22_0067",
        section_number="G&SR 22.8.5",
        title="Safety Protocol Compliance Clause 22-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0068": GSRSafetyRule(
        rule_id="GSR_SEC22_0068",
        section_number="G&SR 22.9.6",
        title="Safety Protocol Compliance Clause 22-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0069": GSRSafetyRule(
        rule_id="GSR_SEC22_0069",
        section_number="G&SR 22.10.7",
        title="Safety Protocol Compliance Clause 22-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0070": GSRSafetyRule(
        rule_id="GSR_SEC22_0070",
        section_number="G&SR 22.11.8",
        title="Safety Protocol Compliance Clause 22-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0071": GSRSafetyRule(
        rule_id="GSR_SEC22_0071",
        section_number="G&SR 22.12.9",
        title="Safety Protocol Compliance Clause 22-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0072": GSRSafetyRule(
        rule_id="GSR_SEC22_0072",
        section_number="G&SR 22.13.1",
        title="Safety Protocol Compliance Clause 22-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0073": GSRSafetyRule(
        rule_id="GSR_SEC22_0073",
        section_number="G&SR 22.14.2",
        title="Safety Protocol Compliance Clause 22-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0074": GSRSafetyRule(
        rule_id="GSR_SEC22_0074",
        section_number="G&SR 22.15.3",
        title="Safety Protocol Compliance Clause 22-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0075": GSRSafetyRule(
        rule_id="GSR_SEC22_0075",
        section_number="G&SR 22.16.4",
        title="Safety Protocol Compliance Clause 22-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0076": GSRSafetyRule(
        rule_id="GSR_SEC22_0076",
        section_number="G&SR 22.17.5",
        title="Safety Protocol Compliance Clause 22-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0077": GSRSafetyRule(
        rule_id="GSR_SEC22_0077",
        section_number="G&SR 22.18.6",
        title="Safety Protocol Compliance Clause 22-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0078": GSRSafetyRule(
        rule_id="GSR_SEC22_0078",
        section_number="G&SR 22.19.7",
        title="Safety Protocol Compliance Clause 22-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0079": GSRSafetyRule(
        rule_id="GSR_SEC22_0079",
        section_number="G&SR 22.20.8",
        title="Safety Protocol Compliance Clause 22-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0080": GSRSafetyRule(
        rule_id="GSR_SEC22_0080",
        section_number="G&SR 22.1.9",
        title="Safety Protocol Compliance Clause 22-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0081": GSRSafetyRule(
        rule_id="GSR_SEC22_0081",
        section_number="G&SR 22.2.1",
        title="Safety Protocol Compliance Clause 22-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0082": GSRSafetyRule(
        rule_id="GSR_SEC22_0082",
        section_number="G&SR 22.3.2",
        title="Safety Protocol Compliance Clause 22-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0083": GSRSafetyRule(
        rule_id="GSR_SEC22_0083",
        section_number="G&SR 22.4.3",
        title="Safety Protocol Compliance Clause 22-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0084": GSRSafetyRule(
        rule_id="GSR_SEC22_0084",
        section_number="G&SR 22.5.4",
        title="Safety Protocol Compliance Clause 22-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0085": GSRSafetyRule(
        rule_id="GSR_SEC22_0085",
        section_number="G&SR 22.6.5",
        title="Safety Protocol Compliance Clause 22-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0086": GSRSafetyRule(
        rule_id="GSR_SEC22_0086",
        section_number="G&SR 22.7.6",
        title="Safety Protocol Compliance Clause 22-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0087": GSRSafetyRule(
        rule_id="GSR_SEC22_0087",
        section_number="G&SR 22.8.7",
        title="Safety Protocol Compliance Clause 22-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0088": GSRSafetyRule(
        rule_id="GSR_SEC22_0088",
        section_number="G&SR 22.9.8",
        title="Safety Protocol Compliance Clause 22-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0089": GSRSafetyRule(
        rule_id="GSR_SEC22_0089",
        section_number="G&SR 22.10.9",
        title="Safety Protocol Compliance Clause 22-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0090": GSRSafetyRule(
        rule_id="GSR_SEC22_0090",
        section_number="G&SR 22.11.1",
        title="Safety Protocol Compliance Clause 22-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0091": GSRSafetyRule(
        rule_id="GSR_SEC22_0091",
        section_number="G&SR 22.12.2",
        title="Safety Protocol Compliance Clause 22-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0092": GSRSafetyRule(
        rule_id="GSR_SEC22_0092",
        section_number="G&SR 22.13.3",
        title="Safety Protocol Compliance Clause 22-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0093": GSRSafetyRule(
        rule_id="GSR_SEC22_0093",
        section_number="G&SR 22.14.4",
        title="Safety Protocol Compliance Clause 22-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0094": GSRSafetyRule(
        rule_id="GSR_SEC22_0094",
        section_number="G&SR 22.15.5",
        title="Safety Protocol Compliance Clause 22-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0095": GSRSafetyRule(
        rule_id="GSR_SEC22_0095",
        section_number="G&SR 22.16.6",
        title="Safety Protocol Compliance Clause 22-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0096": GSRSafetyRule(
        rule_id="GSR_SEC22_0096",
        section_number="G&SR 22.17.7",
        title="Safety Protocol Compliance Clause 22-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0097": GSRSafetyRule(
        rule_id="GSR_SEC22_0097",
        section_number="G&SR 22.18.8",
        title="Safety Protocol Compliance Clause 22-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0098": GSRSafetyRule(
        rule_id="GSR_SEC22_0098",
        section_number="G&SR 22.19.9",
        title="Safety Protocol Compliance Clause 22-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0099": GSRSafetyRule(
        rule_id="GSR_SEC22_0099",
        section_number="G&SR 22.20.1",
        title="Safety Protocol Compliance Clause 22-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0100": GSRSafetyRule(
        rule_id="GSR_SEC22_0100",
        section_number="G&SR 22.1.2",
        title="Safety Protocol Compliance Clause 22-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0101": GSRSafetyRule(
        rule_id="GSR_SEC22_0101",
        section_number="G&SR 22.2.3",
        title="Safety Protocol Compliance Clause 22-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0102": GSRSafetyRule(
        rule_id="GSR_SEC22_0102",
        section_number="G&SR 22.3.4",
        title="Safety Protocol Compliance Clause 22-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0103": GSRSafetyRule(
        rule_id="GSR_SEC22_0103",
        section_number="G&SR 22.4.5",
        title="Safety Protocol Compliance Clause 22-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0104": GSRSafetyRule(
        rule_id="GSR_SEC22_0104",
        section_number="G&SR 22.5.6",
        title="Safety Protocol Compliance Clause 22-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0105": GSRSafetyRule(
        rule_id="GSR_SEC22_0105",
        section_number="G&SR 22.6.7",
        title="Safety Protocol Compliance Clause 22-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0106": GSRSafetyRule(
        rule_id="GSR_SEC22_0106",
        section_number="G&SR 22.7.8",
        title="Safety Protocol Compliance Clause 22-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0107": GSRSafetyRule(
        rule_id="GSR_SEC22_0107",
        section_number="G&SR 22.8.9",
        title="Safety Protocol Compliance Clause 22-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0108": GSRSafetyRule(
        rule_id="GSR_SEC22_0108",
        section_number="G&SR 22.9.1",
        title="Safety Protocol Compliance Clause 22-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0109": GSRSafetyRule(
        rule_id="GSR_SEC22_0109",
        section_number="G&SR 22.10.2",
        title="Safety Protocol Compliance Clause 22-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0110": GSRSafetyRule(
        rule_id="GSR_SEC22_0110",
        section_number="G&SR 22.11.3",
        title="Safety Protocol Compliance Clause 22-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0111": GSRSafetyRule(
        rule_id="GSR_SEC22_0111",
        section_number="G&SR 22.12.4",
        title="Safety Protocol Compliance Clause 22-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0112": GSRSafetyRule(
        rule_id="GSR_SEC22_0112",
        section_number="G&SR 22.13.5",
        title="Safety Protocol Compliance Clause 22-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0113": GSRSafetyRule(
        rule_id="GSR_SEC22_0113",
        section_number="G&SR 22.14.6",
        title="Safety Protocol Compliance Clause 22-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0114": GSRSafetyRule(
        rule_id="GSR_SEC22_0114",
        section_number="G&SR 22.15.7",
        title="Safety Protocol Compliance Clause 22-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0115": GSRSafetyRule(
        rule_id="GSR_SEC22_0115",
        section_number="G&SR 22.16.8",
        title="Safety Protocol Compliance Clause 22-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0116": GSRSafetyRule(
        rule_id="GSR_SEC22_0116",
        section_number="G&SR 22.17.9",
        title="Safety Protocol Compliance Clause 22-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0117": GSRSafetyRule(
        rule_id="GSR_SEC22_0117",
        section_number="G&SR 22.18.1",
        title="Safety Protocol Compliance Clause 22-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0118": GSRSafetyRule(
        rule_id="GSR_SEC22_0118",
        section_number="G&SR 22.19.2",
        title="Safety Protocol Compliance Clause 22-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0119": GSRSafetyRule(
        rule_id="GSR_SEC22_0119",
        section_number="G&SR 22.20.3",
        title="Safety Protocol Compliance Clause 22-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0120": GSRSafetyRule(
        rule_id="GSR_SEC22_0120",
        section_number="G&SR 22.1.4",
        title="Safety Protocol Compliance Clause 22-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0121": GSRSafetyRule(
        rule_id="GSR_SEC22_0121",
        section_number="G&SR 22.2.5",
        title="Safety Protocol Compliance Clause 22-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0122": GSRSafetyRule(
        rule_id="GSR_SEC22_0122",
        section_number="G&SR 22.3.6",
        title="Safety Protocol Compliance Clause 22-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0123": GSRSafetyRule(
        rule_id="GSR_SEC22_0123",
        section_number="G&SR 22.4.7",
        title="Safety Protocol Compliance Clause 22-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0124": GSRSafetyRule(
        rule_id="GSR_SEC22_0124",
        section_number="G&SR 22.5.8",
        title="Safety Protocol Compliance Clause 22-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0125": GSRSafetyRule(
        rule_id="GSR_SEC22_0125",
        section_number="G&SR 22.6.9",
        title="Safety Protocol Compliance Clause 22-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0126": GSRSafetyRule(
        rule_id="GSR_SEC22_0126",
        section_number="G&SR 22.7.1",
        title="Safety Protocol Compliance Clause 22-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0127": GSRSafetyRule(
        rule_id="GSR_SEC22_0127",
        section_number="G&SR 22.8.2",
        title="Safety Protocol Compliance Clause 22-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0128": GSRSafetyRule(
        rule_id="GSR_SEC22_0128",
        section_number="G&SR 22.9.3",
        title="Safety Protocol Compliance Clause 22-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0129": GSRSafetyRule(
        rule_id="GSR_SEC22_0129",
        section_number="G&SR 22.10.4",
        title="Safety Protocol Compliance Clause 22-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0130": GSRSafetyRule(
        rule_id="GSR_SEC22_0130",
        section_number="G&SR 22.11.5",
        title="Safety Protocol Compliance Clause 22-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0131": GSRSafetyRule(
        rule_id="GSR_SEC22_0131",
        section_number="G&SR 22.12.6",
        title="Safety Protocol Compliance Clause 22-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0132": GSRSafetyRule(
        rule_id="GSR_SEC22_0132",
        section_number="G&SR 22.13.7",
        title="Safety Protocol Compliance Clause 22-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0133": GSRSafetyRule(
        rule_id="GSR_SEC22_0133",
        section_number="G&SR 22.14.8",
        title="Safety Protocol Compliance Clause 22-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0134": GSRSafetyRule(
        rule_id="GSR_SEC22_0134",
        section_number="G&SR 22.15.9",
        title="Safety Protocol Compliance Clause 22-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0135": GSRSafetyRule(
        rule_id="GSR_SEC22_0135",
        section_number="G&SR 22.16.1",
        title="Safety Protocol Compliance Clause 22-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0136": GSRSafetyRule(
        rule_id="GSR_SEC22_0136",
        section_number="G&SR 22.17.2",
        title="Safety Protocol Compliance Clause 22-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0137": GSRSafetyRule(
        rule_id="GSR_SEC22_0137",
        section_number="G&SR 22.18.3",
        title="Safety Protocol Compliance Clause 22-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0138": GSRSafetyRule(
        rule_id="GSR_SEC22_0138",
        section_number="G&SR 22.19.4",
        title="Safety Protocol Compliance Clause 22-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0139": GSRSafetyRule(
        rule_id="GSR_SEC22_0139",
        section_number="G&SR 22.20.5",
        title="Safety Protocol Compliance Clause 22-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0140": GSRSafetyRule(
        rule_id="GSR_SEC22_0140",
        section_number="G&SR 22.1.6",
        title="Safety Protocol Compliance Clause 22-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0141": GSRSafetyRule(
        rule_id="GSR_SEC22_0141",
        section_number="G&SR 22.2.7",
        title="Safety Protocol Compliance Clause 22-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0142": GSRSafetyRule(
        rule_id="GSR_SEC22_0142",
        section_number="G&SR 22.3.8",
        title="Safety Protocol Compliance Clause 22-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0143": GSRSafetyRule(
        rule_id="GSR_SEC22_0143",
        section_number="G&SR 22.4.9",
        title="Safety Protocol Compliance Clause 22-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0144": GSRSafetyRule(
        rule_id="GSR_SEC22_0144",
        section_number="G&SR 22.5.1",
        title="Safety Protocol Compliance Clause 22-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0145": GSRSafetyRule(
        rule_id="GSR_SEC22_0145",
        section_number="G&SR 22.6.2",
        title="Safety Protocol Compliance Clause 22-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0146": GSRSafetyRule(
        rule_id="GSR_SEC22_0146",
        section_number="G&SR 22.7.3",
        title="Safety Protocol Compliance Clause 22-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0147": GSRSafetyRule(
        rule_id="GSR_SEC22_0147",
        section_number="G&SR 22.8.4",
        title="Safety Protocol Compliance Clause 22-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0148": GSRSafetyRule(
        rule_id="GSR_SEC22_0148",
        section_number="G&SR 22.9.5",
        title="Safety Protocol Compliance Clause 22-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0149": GSRSafetyRule(
        rule_id="GSR_SEC22_0149",
        section_number="G&SR 22.10.6",
        title="Safety Protocol Compliance Clause 22-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0150": GSRSafetyRule(
        rule_id="GSR_SEC22_0150",
        section_number="G&SR 22.11.7",
        title="Safety Protocol Compliance Clause 22-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0151": GSRSafetyRule(
        rule_id="GSR_SEC22_0151",
        section_number="G&SR 22.12.8",
        title="Safety Protocol Compliance Clause 22-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0152": GSRSafetyRule(
        rule_id="GSR_SEC22_0152",
        section_number="G&SR 22.13.9",
        title="Safety Protocol Compliance Clause 22-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0153": GSRSafetyRule(
        rule_id="GSR_SEC22_0153",
        section_number="G&SR 22.14.1",
        title="Safety Protocol Compliance Clause 22-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0154": GSRSafetyRule(
        rule_id="GSR_SEC22_0154",
        section_number="G&SR 22.15.2",
        title="Safety Protocol Compliance Clause 22-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0155": GSRSafetyRule(
        rule_id="GSR_SEC22_0155",
        section_number="G&SR 22.16.3",
        title="Safety Protocol Compliance Clause 22-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0156": GSRSafetyRule(
        rule_id="GSR_SEC22_0156",
        section_number="G&SR 22.17.4",
        title="Safety Protocol Compliance Clause 22-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0157": GSRSafetyRule(
        rule_id="GSR_SEC22_0157",
        section_number="G&SR 22.18.5",
        title="Safety Protocol Compliance Clause 22-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0158": GSRSafetyRule(
        rule_id="GSR_SEC22_0158",
        section_number="G&SR 22.19.6",
        title="Safety Protocol Compliance Clause 22-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0159": GSRSafetyRule(
        rule_id="GSR_SEC22_0159",
        section_number="G&SR 22.20.7",
        title="Safety Protocol Compliance Clause 22-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0160": GSRSafetyRule(
        rule_id="GSR_SEC22_0160",
        section_number="G&SR 22.1.8",
        title="Safety Protocol Compliance Clause 22-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0161": GSRSafetyRule(
        rule_id="GSR_SEC22_0161",
        section_number="G&SR 22.2.9",
        title="Safety Protocol Compliance Clause 22-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0162": GSRSafetyRule(
        rule_id="GSR_SEC22_0162",
        section_number="G&SR 22.3.1",
        title="Safety Protocol Compliance Clause 22-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0163": GSRSafetyRule(
        rule_id="GSR_SEC22_0163",
        section_number="G&SR 22.4.2",
        title="Safety Protocol Compliance Clause 22-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0164": GSRSafetyRule(
        rule_id="GSR_SEC22_0164",
        section_number="G&SR 22.5.3",
        title="Safety Protocol Compliance Clause 22-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0165": GSRSafetyRule(
        rule_id="GSR_SEC22_0165",
        section_number="G&SR 22.6.4",
        title="Safety Protocol Compliance Clause 22-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0166": GSRSafetyRule(
        rule_id="GSR_SEC22_0166",
        section_number="G&SR 22.7.5",
        title="Safety Protocol Compliance Clause 22-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0167": GSRSafetyRule(
        rule_id="GSR_SEC22_0167",
        section_number="G&SR 22.8.6",
        title="Safety Protocol Compliance Clause 22-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0168": GSRSafetyRule(
        rule_id="GSR_SEC22_0168",
        section_number="G&SR 22.9.7",
        title="Safety Protocol Compliance Clause 22-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0169": GSRSafetyRule(
        rule_id="GSR_SEC22_0169",
        section_number="G&SR 22.10.8",
        title="Safety Protocol Compliance Clause 22-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0170": GSRSafetyRule(
        rule_id="GSR_SEC22_0170",
        section_number="G&SR 22.11.9",
        title="Safety Protocol Compliance Clause 22-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0171": GSRSafetyRule(
        rule_id="GSR_SEC22_0171",
        section_number="G&SR 22.12.1",
        title="Safety Protocol Compliance Clause 22-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0172": GSRSafetyRule(
        rule_id="GSR_SEC22_0172",
        section_number="G&SR 22.13.2",
        title="Safety Protocol Compliance Clause 22-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0173": GSRSafetyRule(
        rule_id="GSR_SEC22_0173",
        section_number="G&SR 22.14.3",
        title="Safety Protocol Compliance Clause 22-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC22_0174": GSRSafetyRule(
        rule_id="GSR_SEC22_0174",
        section_number="G&SR 22.15.4",
        title="Safety Protocol Compliance Clause 22-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
