"""Indian Railways G&SR Regulatory Rulebook Section 017."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_017: Dict[str, GSRSafetyRule] = {
    "GSR_SEC17_0001": GSRSafetyRule(
        rule_id="GSR_SEC17_0001",
        section_number="G&SR 17.2.2",
        title="Safety Protocol Compliance Clause 17-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0002": GSRSafetyRule(
        rule_id="GSR_SEC17_0002",
        section_number="G&SR 17.3.3",
        title="Safety Protocol Compliance Clause 17-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0003": GSRSafetyRule(
        rule_id="GSR_SEC17_0003",
        section_number="G&SR 17.4.4",
        title="Safety Protocol Compliance Clause 17-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0004": GSRSafetyRule(
        rule_id="GSR_SEC17_0004",
        section_number="G&SR 17.5.5",
        title="Safety Protocol Compliance Clause 17-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0005": GSRSafetyRule(
        rule_id="GSR_SEC17_0005",
        section_number="G&SR 17.6.6",
        title="Safety Protocol Compliance Clause 17-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0006": GSRSafetyRule(
        rule_id="GSR_SEC17_0006",
        section_number="G&SR 17.7.7",
        title="Safety Protocol Compliance Clause 17-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0007": GSRSafetyRule(
        rule_id="GSR_SEC17_0007",
        section_number="G&SR 17.8.8",
        title="Safety Protocol Compliance Clause 17-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0008": GSRSafetyRule(
        rule_id="GSR_SEC17_0008",
        section_number="G&SR 17.9.9",
        title="Safety Protocol Compliance Clause 17-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0009": GSRSafetyRule(
        rule_id="GSR_SEC17_0009",
        section_number="G&SR 17.10.1",
        title="Safety Protocol Compliance Clause 17-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0010": GSRSafetyRule(
        rule_id="GSR_SEC17_0010",
        section_number="G&SR 17.11.2",
        title="Safety Protocol Compliance Clause 17-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0011": GSRSafetyRule(
        rule_id="GSR_SEC17_0011",
        section_number="G&SR 17.12.3",
        title="Safety Protocol Compliance Clause 17-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0012": GSRSafetyRule(
        rule_id="GSR_SEC17_0012",
        section_number="G&SR 17.13.4",
        title="Safety Protocol Compliance Clause 17-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0013": GSRSafetyRule(
        rule_id="GSR_SEC17_0013",
        section_number="G&SR 17.14.5",
        title="Safety Protocol Compliance Clause 17-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0014": GSRSafetyRule(
        rule_id="GSR_SEC17_0014",
        section_number="G&SR 17.15.6",
        title="Safety Protocol Compliance Clause 17-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0015": GSRSafetyRule(
        rule_id="GSR_SEC17_0015",
        section_number="G&SR 17.16.7",
        title="Safety Protocol Compliance Clause 17-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0016": GSRSafetyRule(
        rule_id="GSR_SEC17_0016",
        section_number="G&SR 17.17.8",
        title="Safety Protocol Compliance Clause 17-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0017": GSRSafetyRule(
        rule_id="GSR_SEC17_0017",
        section_number="G&SR 17.18.9",
        title="Safety Protocol Compliance Clause 17-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0018": GSRSafetyRule(
        rule_id="GSR_SEC17_0018",
        section_number="G&SR 17.19.1",
        title="Safety Protocol Compliance Clause 17-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0019": GSRSafetyRule(
        rule_id="GSR_SEC17_0019",
        section_number="G&SR 17.20.2",
        title="Safety Protocol Compliance Clause 17-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0020": GSRSafetyRule(
        rule_id="GSR_SEC17_0020",
        section_number="G&SR 17.1.3",
        title="Safety Protocol Compliance Clause 17-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0021": GSRSafetyRule(
        rule_id="GSR_SEC17_0021",
        section_number="G&SR 17.2.4",
        title="Safety Protocol Compliance Clause 17-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0022": GSRSafetyRule(
        rule_id="GSR_SEC17_0022",
        section_number="G&SR 17.3.5",
        title="Safety Protocol Compliance Clause 17-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0023": GSRSafetyRule(
        rule_id="GSR_SEC17_0023",
        section_number="G&SR 17.4.6",
        title="Safety Protocol Compliance Clause 17-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0024": GSRSafetyRule(
        rule_id="GSR_SEC17_0024",
        section_number="G&SR 17.5.7",
        title="Safety Protocol Compliance Clause 17-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0025": GSRSafetyRule(
        rule_id="GSR_SEC17_0025",
        section_number="G&SR 17.6.8",
        title="Safety Protocol Compliance Clause 17-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0026": GSRSafetyRule(
        rule_id="GSR_SEC17_0026",
        section_number="G&SR 17.7.9",
        title="Safety Protocol Compliance Clause 17-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0027": GSRSafetyRule(
        rule_id="GSR_SEC17_0027",
        section_number="G&SR 17.8.1",
        title="Safety Protocol Compliance Clause 17-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0028": GSRSafetyRule(
        rule_id="GSR_SEC17_0028",
        section_number="G&SR 17.9.2",
        title="Safety Protocol Compliance Clause 17-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0029": GSRSafetyRule(
        rule_id="GSR_SEC17_0029",
        section_number="G&SR 17.10.3",
        title="Safety Protocol Compliance Clause 17-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0030": GSRSafetyRule(
        rule_id="GSR_SEC17_0030",
        section_number="G&SR 17.11.4",
        title="Safety Protocol Compliance Clause 17-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0031": GSRSafetyRule(
        rule_id="GSR_SEC17_0031",
        section_number="G&SR 17.12.5",
        title="Safety Protocol Compliance Clause 17-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0032": GSRSafetyRule(
        rule_id="GSR_SEC17_0032",
        section_number="G&SR 17.13.6",
        title="Safety Protocol Compliance Clause 17-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0033": GSRSafetyRule(
        rule_id="GSR_SEC17_0033",
        section_number="G&SR 17.14.7",
        title="Safety Protocol Compliance Clause 17-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0034": GSRSafetyRule(
        rule_id="GSR_SEC17_0034",
        section_number="G&SR 17.15.8",
        title="Safety Protocol Compliance Clause 17-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0035": GSRSafetyRule(
        rule_id="GSR_SEC17_0035",
        section_number="G&SR 17.16.9",
        title="Safety Protocol Compliance Clause 17-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0036": GSRSafetyRule(
        rule_id="GSR_SEC17_0036",
        section_number="G&SR 17.17.1",
        title="Safety Protocol Compliance Clause 17-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0037": GSRSafetyRule(
        rule_id="GSR_SEC17_0037",
        section_number="G&SR 17.18.2",
        title="Safety Protocol Compliance Clause 17-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0038": GSRSafetyRule(
        rule_id="GSR_SEC17_0038",
        section_number="G&SR 17.19.3",
        title="Safety Protocol Compliance Clause 17-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0039": GSRSafetyRule(
        rule_id="GSR_SEC17_0039",
        section_number="G&SR 17.20.4",
        title="Safety Protocol Compliance Clause 17-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0040": GSRSafetyRule(
        rule_id="GSR_SEC17_0040",
        section_number="G&SR 17.1.5",
        title="Safety Protocol Compliance Clause 17-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0041": GSRSafetyRule(
        rule_id="GSR_SEC17_0041",
        section_number="G&SR 17.2.6",
        title="Safety Protocol Compliance Clause 17-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0042": GSRSafetyRule(
        rule_id="GSR_SEC17_0042",
        section_number="G&SR 17.3.7",
        title="Safety Protocol Compliance Clause 17-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0043": GSRSafetyRule(
        rule_id="GSR_SEC17_0043",
        section_number="G&SR 17.4.8",
        title="Safety Protocol Compliance Clause 17-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0044": GSRSafetyRule(
        rule_id="GSR_SEC17_0044",
        section_number="G&SR 17.5.9",
        title="Safety Protocol Compliance Clause 17-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0045": GSRSafetyRule(
        rule_id="GSR_SEC17_0045",
        section_number="G&SR 17.6.1",
        title="Safety Protocol Compliance Clause 17-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0046": GSRSafetyRule(
        rule_id="GSR_SEC17_0046",
        section_number="G&SR 17.7.2",
        title="Safety Protocol Compliance Clause 17-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0047": GSRSafetyRule(
        rule_id="GSR_SEC17_0047",
        section_number="G&SR 17.8.3",
        title="Safety Protocol Compliance Clause 17-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0048": GSRSafetyRule(
        rule_id="GSR_SEC17_0048",
        section_number="G&SR 17.9.4",
        title="Safety Protocol Compliance Clause 17-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0049": GSRSafetyRule(
        rule_id="GSR_SEC17_0049",
        section_number="G&SR 17.10.5",
        title="Safety Protocol Compliance Clause 17-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0050": GSRSafetyRule(
        rule_id="GSR_SEC17_0050",
        section_number="G&SR 17.11.6",
        title="Safety Protocol Compliance Clause 17-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0051": GSRSafetyRule(
        rule_id="GSR_SEC17_0051",
        section_number="G&SR 17.12.7",
        title="Safety Protocol Compliance Clause 17-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0052": GSRSafetyRule(
        rule_id="GSR_SEC17_0052",
        section_number="G&SR 17.13.8",
        title="Safety Protocol Compliance Clause 17-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0053": GSRSafetyRule(
        rule_id="GSR_SEC17_0053",
        section_number="G&SR 17.14.9",
        title="Safety Protocol Compliance Clause 17-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0054": GSRSafetyRule(
        rule_id="GSR_SEC17_0054",
        section_number="G&SR 17.15.1",
        title="Safety Protocol Compliance Clause 17-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0055": GSRSafetyRule(
        rule_id="GSR_SEC17_0055",
        section_number="G&SR 17.16.2",
        title="Safety Protocol Compliance Clause 17-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0056": GSRSafetyRule(
        rule_id="GSR_SEC17_0056",
        section_number="G&SR 17.17.3",
        title="Safety Protocol Compliance Clause 17-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0057": GSRSafetyRule(
        rule_id="GSR_SEC17_0057",
        section_number="G&SR 17.18.4",
        title="Safety Protocol Compliance Clause 17-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0058": GSRSafetyRule(
        rule_id="GSR_SEC17_0058",
        section_number="G&SR 17.19.5",
        title="Safety Protocol Compliance Clause 17-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0059": GSRSafetyRule(
        rule_id="GSR_SEC17_0059",
        section_number="G&SR 17.20.6",
        title="Safety Protocol Compliance Clause 17-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0060": GSRSafetyRule(
        rule_id="GSR_SEC17_0060",
        section_number="G&SR 17.1.7",
        title="Safety Protocol Compliance Clause 17-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0061": GSRSafetyRule(
        rule_id="GSR_SEC17_0061",
        section_number="G&SR 17.2.8",
        title="Safety Protocol Compliance Clause 17-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0062": GSRSafetyRule(
        rule_id="GSR_SEC17_0062",
        section_number="G&SR 17.3.9",
        title="Safety Protocol Compliance Clause 17-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0063": GSRSafetyRule(
        rule_id="GSR_SEC17_0063",
        section_number="G&SR 17.4.1",
        title="Safety Protocol Compliance Clause 17-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0064": GSRSafetyRule(
        rule_id="GSR_SEC17_0064",
        section_number="G&SR 17.5.2",
        title="Safety Protocol Compliance Clause 17-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0065": GSRSafetyRule(
        rule_id="GSR_SEC17_0065",
        section_number="G&SR 17.6.3",
        title="Safety Protocol Compliance Clause 17-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0066": GSRSafetyRule(
        rule_id="GSR_SEC17_0066",
        section_number="G&SR 17.7.4",
        title="Safety Protocol Compliance Clause 17-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0067": GSRSafetyRule(
        rule_id="GSR_SEC17_0067",
        section_number="G&SR 17.8.5",
        title="Safety Protocol Compliance Clause 17-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0068": GSRSafetyRule(
        rule_id="GSR_SEC17_0068",
        section_number="G&SR 17.9.6",
        title="Safety Protocol Compliance Clause 17-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0069": GSRSafetyRule(
        rule_id="GSR_SEC17_0069",
        section_number="G&SR 17.10.7",
        title="Safety Protocol Compliance Clause 17-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0070": GSRSafetyRule(
        rule_id="GSR_SEC17_0070",
        section_number="G&SR 17.11.8",
        title="Safety Protocol Compliance Clause 17-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0071": GSRSafetyRule(
        rule_id="GSR_SEC17_0071",
        section_number="G&SR 17.12.9",
        title="Safety Protocol Compliance Clause 17-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0072": GSRSafetyRule(
        rule_id="GSR_SEC17_0072",
        section_number="G&SR 17.13.1",
        title="Safety Protocol Compliance Clause 17-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0073": GSRSafetyRule(
        rule_id="GSR_SEC17_0073",
        section_number="G&SR 17.14.2",
        title="Safety Protocol Compliance Clause 17-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0074": GSRSafetyRule(
        rule_id="GSR_SEC17_0074",
        section_number="G&SR 17.15.3",
        title="Safety Protocol Compliance Clause 17-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0075": GSRSafetyRule(
        rule_id="GSR_SEC17_0075",
        section_number="G&SR 17.16.4",
        title="Safety Protocol Compliance Clause 17-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0076": GSRSafetyRule(
        rule_id="GSR_SEC17_0076",
        section_number="G&SR 17.17.5",
        title="Safety Protocol Compliance Clause 17-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0077": GSRSafetyRule(
        rule_id="GSR_SEC17_0077",
        section_number="G&SR 17.18.6",
        title="Safety Protocol Compliance Clause 17-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0078": GSRSafetyRule(
        rule_id="GSR_SEC17_0078",
        section_number="G&SR 17.19.7",
        title="Safety Protocol Compliance Clause 17-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0079": GSRSafetyRule(
        rule_id="GSR_SEC17_0079",
        section_number="G&SR 17.20.8",
        title="Safety Protocol Compliance Clause 17-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0080": GSRSafetyRule(
        rule_id="GSR_SEC17_0080",
        section_number="G&SR 17.1.9",
        title="Safety Protocol Compliance Clause 17-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0081": GSRSafetyRule(
        rule_id="GSR_SEC17_0081",
        section_number="G&SR 17.2.1",
        title="Safety Protocol Compliance Clause 17-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0082": GSRSafetyRule(
        rule_id="GSR_SEC17_0082",
        section_number="G&SR 17.3.2",
        title="Safety Protocol Compliance Clause 17-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0083": GSRSafetyRule(
        rule_id="GSR_SEC17_0083",
        section_number="G&SR 17.4.3",
        title="Safety Protocol Compliance Clause 17-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0084": GSRSafetyRule(
        rule_id="GSR_SEC17_0084",
        section_number="G&SR 17.5.4",
        title="Safety Protocol Compliance Clause 17-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0085": GSRSafetyRule(
        rule_id="GSR_SEC17_0085",
        section_number="G&SR 17.6.5",
        title="Safety Protocol Compliance Clause 17-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0086": GSRSafetyRule(
        rule_id="GSR_SEC17_0086",
        section_number="G&SR 17.7.6",
        title="Safety Protocol Compliance Clause 17-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0087": GSRSafetyRule(
        rule_id="GSR_SEC17_0087",
        section_number="G&SR 17.8.7",
        title="Safety Protocol Compliance Clause 17-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0088": GSRSafetyRule(
        rule_id="GSR_SEC17_0088",
        section_number="G&SR 17.9.8",
        title="Safety Protocol Compliance Clause 17-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0089": GSRSafetyRule(
        rule_id="GSR_SEC17_0089",
        section_number="G&SR 17.10.9",
        title="Safety Protocol Compliance Clause 17-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0090": GSRSafetyRule(
        rule_id="GSR_SEC17_0090",
        section_number="G&SR 17.11.1",
        title="Safety Protocol Compliance Clause 17-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0091": GSRSafetyRule(
        rule_id="GSR_SEC17_0091",
        section_number="G&SR 17.12.2",
        title="Safety Protocol Compliance Clause 17-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0092": GSRSafetyRule(
        rule_id="GSR_SEC17_0092",
        section_number="G&SR 17.13.3",
        title="Safety Protocol Compliance Clause 17-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0093": GSRSafetyRule(
        rule_id="GSR_SEC17_0093",
        section_number="G&SR 17.14.4",
        title="Safety Protocol Compliance Clause 17-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0094": GSRSafetyRule(
        rule_id="GSR_SEC17_0094",
        section_number="G&SR 17.15.5",
        title="Safety Protocol Compliance Clause 17-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0095": GSRSafetyRule(
        rule_id="GSR_SEC17_0095",
        section_number="G&SR 17.16.6",
        title="Safety Protocol Compliance Clause 17-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0096": GSRSafetyRule(
        rule_id="GSR_SEC17_0096",
        section_number="G&SR 17.17.7",
        title="Safety Protocol Compliance Clause 17-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0097": GSRSafetyRule(
        rule_id="GSR_SEC17_0097",
        section_number="G&SR 17.18.8",
        title="Safety Protocol Compliance Clause 17-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0098": GSRSafetyRule(
        rule_id="GSR_SEC17_0098",
        section_number="G&SR 17.19.9",
        title="Safety Protocol Compliance Clause 17-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0099": GSRSafetyRule(
        rule_id="GSR_SEC17_0099",
        section_number="G&SR 17.20.1",
        title="Safety Protocol Compliance Clause 17-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0100": GSRSafetyRule(
        rule_id="GSR_SEC17_0100",
        section_number="G&SR 17.1.2",
        title="Safety Protocol Compliance Clause 17-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0101": GSRSafetyRule(
        rule_id="GSR_SEC17_0101",
        section_number="G&SR 17.2.3",
        title="Safety Protocol Compliance Clause 17-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0102": GSRSafetyRule(
        rule_id="GSR_SEC17_0102",
        section_number="G&SR 17.3.4",
        title="Safety Protocol Compliance Clause 17-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0103": GSRSafetyRule(
        rule_id="GSR_SEC17_0103",
        section_number="G&SR 17.4.5",
        title="Safety Protocol Compliance Clause 17-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0104": GSRSafetyRule(
        rule_id="GSR_SEC17_0104",
        section_number="G&SR 17.5.6",
        title="Safety Protocol Compliance Clause 17-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0105": GSRSafetyRule(
        rule_id="GSR_SEC17_0105",
        section_number="G&SR 17.6.7",
        title="Safety Protocol Compliance Clause 17-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0106": GSRSafetyRule(
        rule_id="GSR_SEC17_0106",
        section_number="G&SR 17.7.8",
        title="Safety Protocol Compliance Clause 17-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0107": GSRSafetyRule(
        rule_id="GSR_SEC17_0107",
        section_number="G&SR 17.8.9",
        title="Safety Protocol Compliance Clause 17-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0108": GSRSafetyRule(
        rule_id="GSR_SEC17_0108",
        section_number="G&SR 17.9.1",
        title="Safety Protocol Compliance Clause 17-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0109": GSRSafetyRule(
        rule_id="GSR_SEC17_0109",
        section_number="G&SR 17.10.2",
        title="Safety Protocol Compliance Clause 17-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0110": GSRSafetyRule(
        rule_id="GSR_SEC17_0110",
        section_number="G&SR 17.11.3",
        title="Safety Protocol Compliance Clause 17-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0111": GSRSafetyRule(
        rule_id="GSR_SEC17_0111",
        section_number="G&SR 17.12.4",
        title="Safety Protocol Compliance Clause 17-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0112": GSRSafetyRule(
        rule_id="GSR_SEC17_0112",
        section_number="G&SR 17.13.5",
        title="Safety Protocol Compliance Clause 17-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0113": GSRSafetyRule(
        rule_id="GSR_SEC17_0113",
        section_number="G&SR 17.14.6",
        title="Safety Protocol Compliance Clause 17-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0114": GSRSafetyRule(
        rule_id="GSR_SEC17_0114",
        section_number="G&SR 17.15.7",
        title="Safety Protocol Compliance Clause 17-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0115": GSRSafetyRule(
        rule_id="GSR_SEC17_0115",
        section_number="G&SR 17.16.8",
        title="Safety Protocol Compliance Clause 17-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0116": GSRSafetyRule(
        rule_id="GSR_SEC17_0116",
        section_number="G&SR 17.17.9",
        title="Safety Protocol Compliance Clause 17-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0117": GSRSafetyRule(
        rule_id="GSR_SEC17_0117",
        section_number="G&SR 17.18.1",
        title="Safety Protocol Compliance Clause 17-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0118": GSRSafetyRule(
        rule_id="GSR_SEC17_0118",
        section_number="G&SR 17.19.2",
        title="Safety Protocol Compliance Clause 17-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0119": GSRSafetyRule(
        rule_id="GSR_SEC17_0119",
        section_number="G&SR 17.20.3",
        title="Safety Protocol Compliance Clause 17-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0120": GSRSafetyRule(
        rule_id="GSR_SEC17_0120",
        section_number="G&SR 17.1.4",
        title="Safety Protocol Compliance Clause 17-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0121": GSRSafetyRule(
        rule_id="GSR_SEC17_0121",
        section_number="G&SR 17.2.5",
        title="Safety Protocol Compliance Clause 17-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0122": GSRSafetyRule(
        rule_id="GSR_SEC17_0122",
        section_number="G&SR 17.3.6",
        title="Safety Protocol Compliance Clause 17-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0123": GSRSafetyRule(
        rule_id="GSR_SEC17_0123",
        section_number="G&SR 17.4.7",
        title="Safety Protocol Compliance Clause 17-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0124": GSRSafetyRule(
        rule_id="GSR_SEC17_0124",
        section_number="G&SR 17.5.8",
        title="Safety Protocol Compliance Clause 17-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0125": GSRSafetyRule(
        rule_id="GSR_SEC17_0125",
        section_number="G&SR 17.6.9",
        title="Safety Protocol Compliance Clause 17-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0126": GSRSafetyRule(
        rule_id="GSR_SEC17_0126",
        section_number="G&SR 17.7.1",
        title="Safety Protocol Compliance Clause 17-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0127": GSRSafetyRule(
        rule_id="GSR_SEC17_0127",
        section_number="G&SR 17.8.2",
        title="Safety Protocol Compliance Clause 17-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0128": GSRSafetyRule(
        rule_id="GSR_SEC17_0128",
        section_number="G&SR 17.9.3",
        title="Safety Protocol Compliance Clause 17-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0129": GSRSafetyRule(
        rule_id="GSR_SEC17_0129",
        section_number="G&SR 17.10.4",
        title="Safety Protocol Compliance Clause 17-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0130": GSRSafetyRule(
        rule_id="GSR_SEC17_0130",
        section_number="G&SR 17.11.5",
        title="Safety Protocol Compliance Clause 17-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0131": GSRSafetyRule(
        rule_id="GSR_SEC17_0131",
        section_number="G&SR 17.12.6",
        title="Safety Protocol Compliance Clause 17-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0132": GSRSafetyRule(
        rule_id="GSR_SEC17_0132",
        section_number="G&SR 17.13.7",
        title="Safety Protocol Compliance Clause 17-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0133": GSRSafetyRule(
        rule_id="GSR_SEC17_0133",
        section_number="G&SR 17.14.8",
        title="Safety Protocol Compliance Clause 17-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0134": GSRSafetyRule(
        rule_id="GSR_SEC17_0134",
        section_number="G&SR 17.15.9",
        title="Safety Protocol Compliance Clause 17-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0135": GSRSafetyRule(
        rule_id="GSR_SEC17_0135",
        section_number="G&SR 17.16.1",
        title="Safety Protocol Compliance Clause 17-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0136": GSRSafetyRule(
        rule_id="GSR_SEC17_0136",
        section_number="G&SR 17.17.2",
        title="Safety Protocol Compliance Clause 17-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0137": GSRSafetyRule(
        rule_id="GSR_SEC17_0137",
        section_number="G&SR 17.18.3",
        title="Safety Protocol Compliance Clause 17-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0138": GSRSafetyRule(
        rule_id="GSR_SEC17_0138",
        section_number="G&SR 17.19.4",
        title="Safety Protocol Compliance Clause 17-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0139": GSRSafetyRule(
        rule_id="GSR_SEC17_0139",
        section_number="G&SR 17.20.5",
        title="Safety Protocol Compliance Clause 17-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0140": GSRSafetyRule(
        rule_id="GSR_SEC17_0140",
        section_number="G&SR 17.1.6",
        title="Safety Protocol Compliance Clause 17-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0141": GSRSafetyRule(
        rule_id="GSR_SEC17_0141",
        section_number="G&SR 17.2.7",
        title="Safety Protocol Compliance Clause 17-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0142": GSRSafetyRule(
        rule_id="GSR_SEC17_0142",
        section_number="G&SR 17.3.8",
        title="Safety Protocol Compliance Clause 17-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0143": GSRSafetyRule(
        rule_id="GSR_SEC17_0143",
        section_number="G&SR 17.4.9",
        title="Safety Protocol Compliance Clause 17-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0144": GSRSafetyRule(
        rule_id="GSR_SEC17_0144",
        section_number="G&SR 17.5.1",
        title="Safety Protocol Compliance Clause 17-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0145": GSRSafetyRule(
        rule_id="GSR_SEC17_0145",
        section_number="G&SR 17.6.2",
        title="Safety Protocol Compliance Clause 17-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0146": GSRSafetyRule(
        rule_id="GSR_SEC17_0146",
        section_number="G&SR 17.7.3",
        title="Safety Protocol Compliance Clause 17-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0147": GSRSafetyRule(
        rule_id="GSR_SEC17_0147",
        section_number="G&SR 17.8.4",
        title="Safety Protocol Compliance Clause 17-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0148": GSRSafetyRule(
        rule_id="GSR_SEC17_0148",
        section_number="G&SR 17.9.5",
        title="Safety Protocol Compliance Clause 17-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0149": GSRSafetyRule(
        rule_id="GSR_SEC17_0149",
        section_number="G&SR 17.10.6",
        title="Safety Protocol Compliance Clause 17-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0150": GSRSafetyRule(
        rule_id="GSR_SEC17_0150",
        section_number="G&SR 17.11.7",
        title="Safety Protocol Compliance Clause 17-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0151": GSRSafetyRule(
        rule_id="GSR_SEC17_0151",
        section_number="G&SR 17.12.8",
        title="Safety Protocol Compliance Clause 17-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0152": GSRSafetyRule(
        rule_id="GSR_SEC17_0152",
        section_number="G&SR 17.13.9",
        title="Safety Protocol Compliance Clause 17-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0153": GSRSafetyRule(
        rule_id="GSR_SEC17_0153",
        section_number="G&SR 17.14.1",
        title="Safety Protocol Compliance Clause 17-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0154": GSRSafetyRule(
        rule_id="GSR_SEC17_0154",
        section_number="G&SR 17.15.2",
        title="Safety Protocol Compliance Clause 17-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0155": GSRSafetyRule(
        rule_id="GSR_SEC17_0155",
        section_number="G&SR 17.16.3",
        title="Safety Protocol Compliance Clause 17-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0156": GSRSafetyRule(
        rule_id="GSR_SEC17_0156",
        section_number="G&SR 17.17.4",
        title="Safety Protocol Compliance Clause 17-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0157": GSRSafetyRule(
        rule_id="GSR_SEC17_0157",
        section_number="G&SR 17.18.5",
        title="Safety Protocol Compliance Clause 17-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0158": GSRSafetyRule(
        rule_id="GSR_SEC17_0158",
        section_number="G&SR 17.19.6",
        title="Safety Protocol Compliance Clause 17-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0159": GSRSafetyRule(
        rule_id="GSR_SEC17_0159",
        section_number="G&SR 17.20.7",
        title="Safety Protocol Compliance Clause 17-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0160": GSRSafetyRule(
        rule_id="GSR_SEC17_0160",
        section_number="G&SR 17.1.8",
        title="Safety Protocol Compliance Clause 17-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0161": GSRSafetyRule(
        rule_id="GSR_SEC17_0161",
        section_number="G&SR 17.2.9",
        title="Safety Protocol Compliance Clause 17-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0162": GSRSafetyRule(
        rule_id="GSR_SEC17_0162",
        section_number="G&SR 17.3.1",
        title="Safety Protocol Compliance Clause 17-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0163": GSRSafetyRule(
        rule_id="GSR_SEC17_0163",
        section_number="G&SR 17.4.2",
        title="Safety Protocol Compliance Clause 17-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0164": GSRSafetyRule(
        rule_id="GSR_SEC17_0164",
        section_number="G&SR 17.5.3",
        title="Safety Protocol Compliance Clause 17-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0165": GSRSafetyRule(
        rule_id="GSR_SEC17_0165",
        section_number="G&SR 17.6.4",
        title="Safety Protocol Compliance Clause 17-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0166": GSRSafetyRule(
        rule_id="GSR_SEC17_0166",
        section_number="G&SR 17.7.5",
        title="Safety Protocol Compliance Clause 17-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0167": GSRSafetyRule(
        rule_id="GSR_SEC17_0167",
        section_number="G&SR 17.8.6",
        title="Safety Protocol Compliance Clause 17-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0168": GSRSafetyRule(
        rule_id="GSR_SEC17_0168",
        section_number="G&SR 17.9.7",
        title="Safety Protocol Compliance Clause 17-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0169": GSRSafetyRule(
        rule_id="GSR_SEC17_0169",
        section_number="G&SR 17.10.8",
        title="Safety Protocol Compliance Clause 17-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0170": GSRSafetyRule(
        rule_id="GSR_SEC17_0170",
        section_number="G&SR 17.11.9",
        title="Safety Protocol Compliance Clause 17-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0171": GSRSafetyRule(
        rule_id="GSR_SEC17_0171",
        section_number="G&SR 17.12.1",
        title="Safety Protocol Compliance Clause 17-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0172": GSRSafetyRule(
        rule_id="GSR_SEC17_0172",
        section_number="G&SR 17.13.2",
        title="Safety Protocol Compliance Clause 17-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0173": GSRSafetyRule(
        rule_id="GSR_SEC17_0173",
        section_number="G&SR 17.14.3",
        title="Safety Protocol Compliance Clause 17-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC17_0174": GSRSafetyRule(
        rule_id="GSR_SEC17_0174",
        section_number="G&SR 17.15.4",
        title="Safety Protocol Compliance Clause 17-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
