"""Indian Railways G&SR Regulatory Rulebook Section 006."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_006: Dict[str, GSRSafetyRule] = {
    "GSR_SEC06_0001": GSRSafetyRule(
        rule_id="GSR_SEC06_0001",
        section_number="G&SR 6.2.2",
        title="Safety Protocol Compliance Clause 6-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0002": GSRSafetyRule(
        rule_id="GSR_SEC06_0002",
        section_number="G&SR 6.3.3",
        title="Safety Protocol Compliance Clause 6-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0003": GSRSafetyRule(
        rule_id="GSR_SEC06_0003",
        section_number="G&SR 6.4.4",
        title="Safety Protocol Compliance Clause 6-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0004": GSRSafetyRule(
        rule_id="GSR_SEC06_0004",
        section_number="G&SR 6.5.5",
        title="Safety Protocol Compliance Clause 6-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0005": GSRSafetyRule(
        rule_id="GSR_SEC06_0005",
        section_number="G&SR 6.6.6",
        title="Safety Protocol Compliance Clause 6-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0006": GSRSafetyRule(
        rule_id="GSR_SEC06_0006",
        section_number="G&SR 6.7.7",
        title="Safety Protocol Compliance Clause 6-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0007": GSRSafetyRule(
        rule_id="GSR_SEC06_0007",
        section_number="G&SR 6.8.8",
        title="Safety Protocol Compliance Clause 6-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0008": GSRSafetyRule(
        rule_id="GSR_SEC06_0008",
        section_number="G&SR 6.9.9",
        title="Safety Protocol Compliance Clause 6-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0009": GSRSafetyRule(
        rule_id="GSR_SEC06_0009",
        section_number="G&SR 6.10.1",
        title="Safety Protocol Compliance Clause 6-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0010": GSRSafetyRule(
        rule_id="GSR_SEC06_0010",
        section_number="G&SR 6.11.2",
        title="Safety Protocol Compliance Clause 6-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0011": GSRSafetyRule(
        rule_id="GSR_SEC06_0011",
        section_number="G&SR 6.12.3",
        title="Safety Protocol Compliance Clause 6-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0012": GSRSafetyRule(
        rule_id="GSR_SEC06_0012",
        section_number="G&SR 6.13.4",
        title="Safety Protocol Compliance Clause 6-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0013": GSRSafetyRule(
        rule_id="GSR_SEC06_0013",
        section_number="G&SR 6.14.5",
        title="Safety Protocol Compliance Clause 6-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0014": GSRSafetyRule(
        rule_id="GSR_SEC06_0014",
        section_number="G&SR 6.15.6",
        title="Safety Protocol Compliance Clause 6-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0015": GSRSafetyRule(
        rule_id="GSR_SEC06_0015",
        section_number="G&SR 6.16.7",
        title="Safety Protocol Compliance Clause 6-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0016": GSRSafetyRule(
        rule_id="GSR_SEC06_0016",
        section_number="G&SR 6.17.8",
        title="Safety Protocol Compliance Clause 6-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0017": GSRSafetyRule(
        rule_id="GSR_SEC06_0017",
        section_number="G&SR 6.18.9",
        title="Safety Protocol Compliance Clause 6-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0018": GSRSafetyRule(
        rule_id="GSR_SEC06_0018",
        section_number="G&SR 6.19.1",
        title="Safety Protocol Compliance Clause 6-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0019": GSRSafetyRule(
        rule_id="GSR_SEC06_0019",
        section_number="G&SR 6.20.2",
        title="Safety Protocol Compliance Clause 6-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0020": GSRSafetyRule(
        rule_id="GSR_SEC06_0020",
        section_number="G&SR 6.1.3",
        title="Safety Protocol Compliance Clause 6-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0021": GSRSafetyRule(
        rule_id="GSR_SEC06_0021",
        section_number="G&SR 6.2.4",
        title="Safety Protocol Compliance Clause 6-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0022": GSRSafetyRule(
        rule_id="GSR_SEC06_0022",
        section_number="G&SR 6.3.5",
        title="Safety Protocol Compliance Clause 6-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0023": GSRSafetyRule(
        rule_id="GSR_SEC06_0023",
        section_number="G&SR 6.4.6",
        title="Safety Protocol Compliance Clause 6-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0024": GSRSafetyRule(
        rule_id="GSR_SEC06_0024",
        section_number="G&SR 6.5.7",
        title="Safety Protocol Compliance Clause 6-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0025": GSRSafetyRule(
        rule_id="GSR_SEC06_0025",
        section_number="G&SR 6.6.8",
        title="Safety Protocol Compliance Clause 6-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0026": GSRSafetyRule(
        rule_id="GSR_SEC06_0026",
        section_number="G&SR 6.7.9",
        title="Safety Protocol Compliance Clause 6-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0027": GSRSafetyRule(
        rule_id="GSR_SEC06_0027",
        section_number="G&SR 6.8.1",
        title="Safety Protocol Compliance Clause 6-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0028": GSRSafetyRule(
        rule_id="GSR_SEC06_0028",
        section_number="G&SR 6.9.2",
        title="Safety Protocol Compliance Clause 6-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0029": GSRSafetyRule(
        rule_id="GSR_SEC06_0029",
        section_number="G&SR 6.10.3",
        title="Safety Protocol Compliance Clause 6-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0030": GSRSafetyRule(
        rule_id="GSR_SEC06_0030",
        section_number="G&SR 6.11.4",
        title="Safety Protocol Compliance Clause 6-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0031": GSRSafetyRule(
        rule_id="GSR_SEC06_0031",
        section_number="G&SR 6.12.5",
        title="Safety Protocol Compliance Clause 6-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0032": GSRSafetyRule(
        rule_id="GSR_SEC06_0032",
        section_number="G&SR 6.13.6",
        title="Safety Protocol Compliance Clause 6-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0033": GSRSafetyRule(
        rule_id="GSR_SEC06_0033",
        section_number="G&SR 6.14.7",
        title="Safety Protocol Compliance Clause 6-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0034": GSRSafetyRule(
        rule_id="GSR_SEC06_0034",
        section_number="G&SR 6.15.8",
        title="Safety Protocol Compliance Clause 6-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0035": GSRSafetyRule(
        rule_id="GSR_SEC06_0035",
        section_number="G&SR 6.16.9",
        title="Safety Protocol Compliance Clause 6-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0036": GSRSafetyRule(
        rule_id="GSR_SEC06_0036",
        section_number="G&SR 6.17.1",
        title="Safety Protocol Compliance Clause 6-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0037": GSRSafetyRule(
        rule_id="GSR_SEC06_0037",
        section_number="G&SR 6.18.2",
        title="Safety Protocol Compliance Clause 6-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0038": GSRSafetyRule(
        rule_id="GSR_SEC06_0038",
        section_number="G&SR 6.19.3",
        title="Safety Protocol Compliance Clause 6-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0039": GSRSafetyRule(
        rule_id="GSR_SEC06_0039",
        section_number="G&SR 6.20.4",
        title="Safety Protocol Compliance Clause 6-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0040": GSRSafetyRule(
        rule_id="GSR_SEC06_0040",
        section_number="G&SR 6.1.5",
        title="Safety Protocol Compliance Clause 6-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0041": GSRSafetyRule(
        rule_id="GSR_SEC06_0041",
        section_number="G&SR 6.2.6",
        title="Safety Protocol Compliance Clause 6-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0042": GSRSafetyRule(
        rule_id="GSR_SEC06_0042",
        section_number="G&SR 6.3.7",
        title="Safety Protocol Compliance Clause 6-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0043": GSRSafetyRule(
        rule_id="GSR_SEC06_0043",
        section_number="G&SR 6.4.8",
        title="Safety Protocol Compliance Clause 6-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0044": GSRSafetyRule(
        rule_id="GSR_SEC06_0044",
        section_number="G&SR 6.5.9",
        title="Safety Protocol Compliance Clause 6-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0045": GSRSafetyRule(
        rule_id="GSR_SEC06_0045",
        section_number="G&SR 6.6.1",
        title="Safety Protocol Compliance Clause 6-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0046": GSRSafetyRule(
        rule_id="GSR_SEC06_0046",
        section_number="G&SR 6.7.2",
        title="Safety Protocol Compliance Clause 6-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0047": GSRSafetyRule(
        rule_id="GSR_SEC06_0047",
        section_number="G&SR 6.8.3",
        title="Safety Protocol Compliance Clause 6-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0048": GSRSafetyRule(
        rule_id="GSR_SEC06_0048",
        section_number="G&SR 6.9.4",
        title="Safety Protocol Compliance Clause 6-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0049": GSRSafetyRule(
        rule_id="GSR_SEC06_0049",
        section_number="G&SR 6.10.5",
        title="Safety Protocol Compliance Clause 6-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0050": GSRSafetyRule(
        rule_id="GSR_SEC06_0050",
        section_number="G&SR 6.11.6",
        title="Safety Protocol Compliance Clause 6-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0051": GSRSafetyRule(
        rule_id="GSR_SEC06_0051",
        section_number="G&SR 6.12.7",
        title="Safety Protocol Compliance Clause 6-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0052": GSRSafetyRule(
        rule_id="GSR_SEC06_0052",
        section_number="G&SR 6.13.8",
        title="Safety Protocol Compliance Clause 6-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0053": GSRSafetyRule(
        rule_id="GSR_SEC06_0053",
        section_number="G&SR 6.14.9",
        title="Safety Protocol Compliance Clause 6-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0054": GSRSafetyRule(
        rule_id="GSR_SEC06_0054",
        section_number="G&SR 6.15.1",
        title="Safety Protocol Compliance Clause 6-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0055": GSRSafetyRule(
        rule_id="GSR_SEC06_0055",
        section_number="G&SR 6.16.2",
        title="Safety Protocol Compliance Clause 6-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0056": GSRSafetyRule(
        rule_id="GSR_SEC06_0056",
        section_number="G&SR 6.17.3",
        title="Safety Protocol Compliance Clause 6-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0057": GSRSafetyRule(
        rule_id="GSR_SEC06_0057",
        section_number="G&SR 6.18.4",
        title="Safety Protocol Compliance Clause 6-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0058": GSRSafetyRule(
        rule_id="GSR_SEC06_0058",
        section_number="G&SR 6.19.5",
        title="Safety Protocol Compliance Clause 6-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0059": GSRSafetyRule(
        rule_id="GSR_SEC06_0059",
        section_number="G&SR 6.20.6",
        title="Safety Protocol Compliance Clause 6-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0060": GSRSafetyRule(
        rule_id="GSR_SEC06_0060",
        section_number="G&SR 6.1.7",
        title="Safety Protocol Compliance Clause 6-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0061": GSRSafetyRule(
        rule_id="GSR_SEC06_0061",
        section_number="G&SR 6.2.8",
        title="Safety Protocol Compliance Clause 6-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0062": GSRSafetyRule(
        rule_id="GSR_SEC06_0062",
        section_number="G&SR 6.3.9",
        title="Safety Protocol Compliance Clause 6-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0063": GSRSafetyRule(
        rule_id="GSR_SEC06_0063",
        section_number="G&SR 6.4.1",
        title="Safety Protocol Compliance Clause 6-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0064": GSRSafetyRule(
        rule_id="GSR_SEC06_0064",
        section_number="G&SR 6.5.2",
        title="Safety Protocol Compliance Clause 6-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0065": GSRSafetyRule(
        rule_id="GSR_SEC06_0065",
        section_number="G&SR 6.6.3",
        title="Safety Protocol Compliance Clause 6-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0066": GSRSafetyRule(
        rule_id="GSR_SEC06_0066",
        section_number="G&SR 6.7.4",
        title="Safety Protocol Compliance Clause 6-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0067": GSRSafetyRule(
        rule_id="GSR_SEC06_0067",
        section_number="G&SR 6.8.5",
        title="Safety Protocol Compliance Clause 6-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0068": GSRSafetyRule(
        rule_id="GSR_SEC06_0068",
        section_number="G&SR 6.9.6",
        title="Safety Protocol Compliance Clause 6-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0069": GSRSafetyRule(
        rule_id="GSR_SEC06_0069",
        section_number="G&SR 6.10.7",
        title="Safety Protocol Compliance Clause 6-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0070": GSRSafetyRule(
        rule_id="GSR_SEC06_0070",
        section_number="G&SR 6.11.8",
        title="Safety Protocol Compliance Clause 6-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0071": GSRSafetyRule(
        rule_id="GSR_SEC06_0071",
        section_number="G&SR 6.12.9",
        title="Safety Protocol Compliance Clause 6-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0072": GSRSafetyRule(
        rule_id="GSR_SEC06_0072",
        section_number="G&SR 6.13.1",
        title="Safety Protocol Compliance Clause 6-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0073": GSRSafetyRule(
        rule_id="GSR_SEC06_0073",
        section_number="G&SR 6.14.2",
        title="Safety Protocol Compliance Clause 6-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0074": GSRSafetyRule(
        rule_id="GSR_SEC06_0074",
        section_number="G&SR 6.15.3",
        title="Safety Protocol Compliance Clause 6-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0075": GSRSafetyRule(
        rule_id="GSR_SEC06_0075",
        section_number="G&SR 6.16.4",
        title="Safety Protocol Compliance Clause 6-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0076": GSRSafetyRule(
        rule_id="GSR_SEC06_0076",
        section_number="G&SR 6.17.5",
        title="Safety Protocol Compliance Clause 6-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0077": GSRSafetyRule(
        rule_id="GSR_SEC06_0077",
        section_number="G&SR 6.18.6",
        title="Safety Protocol Compliance Clause 6-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0078": GSRSafetyRule(
        rule_id="GSR_SEC06_0078",
        section_number="G&SR 6.19.7",
        title="Safety Protocol Compliance Clause 6-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0079": GSRSafetyRule(
        rule_id="GSR_SEC06_0079",
        section_number="G&SR 6.20.8",
        title="Safety Protocol Compliance Clause 6-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0080": GSRSafetyRule(
        rule_id="GSR_SEC06_0080",
        section_number="G&SR 6.1.9",
        title="Safety Protocol Compliance Clause 6-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0081": GSRSafetyRule(
        rule_id="GSR_SEC06_0081",
        section_number="G&SR 6.2.1",
        title="Safety Protocol Compliance Clause 6-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0082": GSRSafetyRule(
        rule_id="GSR_SEC06_0082",
        section_number="G&SR 6.3.2",
        title="Safety Protocol Compliance Clause 6-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0083": GSRSafetyRule(
        rule_id="GSR_SEC06_0083",
        section_number="G&SR 6.4.3",
        title="Safety Protocol Compliance Clause 6-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0084": GSRSafetyRule(
        rule_id="GSR_SEC06_0084",
        section_number="G&SR 6.5.4",
        title="Safety Protocol Compliance Clause 6-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0085": GSRSafetyRule(
        rule_id="GSR_SEC06_0085",
        section_number="G&SR 6.6.5",
        title="Safety Protocol Compliance Clause 6-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0086": GSRSafetyRule(
        rule_id="GSR_SEC06_0086",
        section_number="G&SR 6.7.6",
        title="Safety Protocol Compliance Clause 6-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0087": GSRSafetyRule(
        rule_id="GSR_SEC06_0087",
        section_number="G&SR 6.8.7",
        title="Safety Protocol Compliance Clause 6-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0088": GSRSafetyRule(
        rule_id="GSR_SEC06_0088",
        section_number="G&SR 6.9.8",
        title="Safety Protocol Compliance Clause 6-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0089": GSRSafetyRule(
        rule_id="GSR_SEC06_0089",
        section_number="G&SR 6.10.9",
        title="Safety Protocol Compliance Clause 6-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0090": GSRSafetyRule(
        rule_id="GSR_SEC06_0090",
        section_number="G&SR 6.11.1",
        title="Safety Protocol Compliance Clause 6-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0091": GSRSafetyRule(
        rule_id="GSR_SEC06_0091",
        section_number="G&SR 6.12.2",
        title="Safety Protocol Compliance Clause 6-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0092": GSRSafetyRule(
        rule_id="GSR_SEC06_0092",
        section_number="G&SR 6.13.3",
        title="Safety Protocol Compliance Clause 6-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0093": GSRSafetyRule(
        rule_id="GSR_SEC06_0093",
        section_number="G&SR 6.14.4",
        title="Safety Protocol Compliance Clause 6-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0094": GSRSafetyRule(
        rule_id="GSR_SEC06_0094",
        section_number="G&SR 6.15.5",
        title="Safety Protocol Compliance Clause 6-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0095": GSRSafetyRule(
        rule_id="GSR_SEC06_0095",
        section_number="G&SR 6.16.6",
        title="Safety Protocol Compliance Clause 6-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0096": GSRSafetyRule(
        rule_id="GSR_SEC06_0096",
        section_number="G&SR 6.17.7",
        title="Safety Protocol Compliance Clause 6-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0097": GSRSafetyRule(
        rule_id="GSR_SEC06_0097",
        section_number="G&SR 6.18.8",
        title="Safety Protocol Compliance Clause 6-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0098": GSRSafetyRule(
        rule_id="GSR_SEC06_0098",
        section_number="G&SR 6.19.9",
        title="Safety Protocol Compliance Clause 6-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0099": GSRSafetyRule(
        rule_id="GSR_SEC06_0099",
        section_number="G&SR 6.20.1",
        title="Safety Protocol Compliance Clause 6-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0100": GSRSafetyRule(
        rule_id="GSR_SEC06_0100",
        section_number="G&SR 6.1.2",
        title="Safety Protocol Compliance Clause 6-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0101": GSRSafetyRule(
        rule_id="GSR_SEC06_0101",
        section_number="G&SR 6.2.3",
        title="Safety Protocol Compliance Clause 6-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0102": GSRSafetyRule(
        rule_id="GSR_SEC06_0102",
        section_number="G&SR 6.3.4",
        title="Safety Protocol Compliance Clause 6-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0103": GSRSafetyRule(
        rule_id="GSR_SEC06_0103",
        section_number="G&SR 6.4.5",
        title="Safety Protocol Compliance Clause 6-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0104": GSRSafetyRule(
        rule_id="GSR_SEC06_0104",
        section_number="G&SR 6.5.6",
        title="Safety Protocol Compliance Clause 6-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0105": GSRSafetyRule(
        rule_id="GSR_SEC06_0105",
        section_number="G&SR 6.6.7",
        title="Safety Protocol Compliance Clause 6-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0106": GSRSafetyRule(
        rule_id="GSR_SEC06_0106",
        section_number="G&SR 6.7.8",
        title="Safety Protocol Compliance Clause 6-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0107": GSRSafetyRule(
        rule_id="GSR_SEC06_0107",
        section_number="G&SR 6.8.9",
        title="Safety Protocol Compliance Clause 6-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0108": GSRSafetyRule(
        rule_id="GSR_SEC06_0108",
        section_number="G&SR 6.9.1",
        title="Safety Protocol Compliance Clause 6-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0109": GSRSafetyRule(
        rule_id="GSR_SEC06_0109",
        section_number="G&SR 6.10.2",
        title="Safety Protocol Compliance Clause 6-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0110": GSRSafetyRule(
        rule_id="GSR_SEC06_0110",
        section_number="G&SR 6.11.3",
        title="Safety Protocol Compliance Clause 6-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0111": GSRSafetyRule(
        rule_id="GSR_SEC06_0111",
        section_number="G&SR 6.12.4",
        title="Safety Protocol Compliance Clause 6-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0112": GSRSafetyRule(
        rule_id="GSR_SEC06_0112",
        section_number="G&SR 6.13.5",
        title="Safety Protocol Compliance Clause 6-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0113": GSRSafetyRule(
        rule_id="GSR_SEC06_0113",
        section_number="G&SR 6.14.6",
        title="Safety Protocol Compliance Clause 6-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0114": GSRSafetyRule(
        rule_id="GSR_SEC06_0114",
        section_number="G&SR 6.15.7",
        title="Safety Protocol Compliance Clause 6-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0115": GSRSafetyRule(
        rule_id="GSR_SEC06_0115",
        section_number="G&SR 6.16.8",
        title="Safety Protocol Compliance Clause 6-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0116": GSRSafetyRule(
        rule_id="GSR_SEC06_0116",
        section_number="G&SR 6.17.9",
        title="Safety Protocol Compliance Clause 6-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0117": GSRSafetyRule(
        rule_id="GSR_SEC06_0117",
        section_number="G&SR 6.18.1",
        title="Safety Protocol Compliance Clause 6-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0118": GSRSafetyRule(
        rule_id="GSR_SEC06_0118",
        section_number="G&SR 6.19.2",
        title="Safety Protocol Compliance Clause 6-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0119": GSRSafetyRule(
        rule_id="GSR_SEC06_0119",
        section_number="G&SR 6.20.3",
        title="Safety Protocol Compliance Clause 6-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0120": GSRSafetyRule(
        rule_id="GSR_SEC06_0120",
        section_number="G&SR 6.1.4",
        title="Safety Protocol Compliance Clause 6-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0121": GSRSafetyRule(
        rule_id="GSR_SEC06_0121",
        section_number="G&SR 6.2.5",
        title="Safety Protocol Compliance Clause 6-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0122": GSRSafetyRule(
        rule_id="GSR_SEC06_0122",
        section_number="G&SR 6.3.6",
        title="Safety Protocol Compliance Clause 6-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0123": GSRSafetyRule(
        rule_id="GSR_SEC06_0123",
        section_number="G&SR 6.4.7",
        title="Safety Protocol Compliance Clause 6-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0124": GSRSafetyRule(
        rule_id="GSR_SEC06_0124",
        section_number="G&SR 6.5.8",
        title="Safety Protocol Compliance Clause 6-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0125": GSRSafetyRule(
        rule_id="GSR_SEC06_0125",
        section_number="G&SR 6.6.9",
        title="Safety Protocol Compliance Clause 6-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0126": GSRSafetyRule(
        rule_id="GSR_SEC06_0126",
        section_number="G&SR 6.7.1",
        title="Safety Protocol Compliance Clause 6-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0127": GSRSafetyRule(
        rule_id="GSR_SEC06_0127",
        section_number="G&SR 6.8.2",
        title="Safety Protocol Compliance Clause 6-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0128": GSRSafetyRule(
        rule_id="GSR_SEC06_0128",
        section_number="G&SR 6.9.3",
        title="Safety Protocol Compliance Clause 6-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0129": GSRSafetyRule(
        rule_id="GSR_SEC06_0129",
        section_number="G&SR 6.10.4",
        title="Safety Protocol Compliance Clause 6-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0130": GSRSafetyRule(
        rule_id="GSR_SEC06_0130",
        section_number="G&SR 6.11.5",
        title="Safety Protocol Compliance Clause 6-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0131": GSRSafetyRule(
        rule_id="GSR_SEC06_0131",
        section_number="G&SR 6.12.6",
        title="Safety Protocol Compliance Clause 6-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0132": GSRSafetyRule(
        rule_id="GSR_SEC06_0132",
        section_number="G&SR 6.13.7",
        title="Safety Protocol Compliance Clause 6-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0133": GSRSafetyRule(
        rule_id="GSR_SEC06_0133",
        section_number="G&SR 6.14.8",
        title="Safety Protocol Compliance Clause 6-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0134": GSRSafetyRule(
        rule_id="GSR_SEC06_0134",
        section_number="G&SR 6.15.9",
        title="Safety Protocol Compliance Clause 6-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0135": GSRSafetyRule(
        rule_id="GSR_SEC06_0135",
        section_number="G&SR 6.16.1",
        title="Safety Protocol Compliance Clause 6-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0136": GSRSafetyRule(
        rule_id="GSR_SEC06_0136",
        section_number="G&SR 6.17.2",
        title="Safety Protocol Compliance Clause 6-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0137": GSRSafetyRule(
        rule_id="GSR_SEC06_0137",
        section_number="G&SR 6.18.3",
        title="Safety Protocol Compliance Clause 6-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0138": GSRSafetyRule(
        rule_id="GSR_SEC06_0138",
        section_number="G&SR 6.19.4",
        title="Safety Protocol Compliance Clause 6-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0139": GSRSafetyRule(
        rule_id="GSR_SEC06_0139",
        section_number="G&SR 6.20.5",
        title="Safety Protocol Compliance Clause 6-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0140": GSRSafetyRule(
        rule_id="GSR_SEC06_0140",
        section_number="G&SR 6.1.6",
        title="Safety Protocol Compliance Clause 6-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0141": GSRSafetyRule(
        rule_id="GSR_SEC06_0141",
        section_number="G&SR 6.2.7",
        title="Safety Protocol Compliance Clause 6-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0142": GSRSafetyRule(
        rule_id="GSR_SEC06_0142",
        section_number="G&SR 6.3.8",
        title="Safety Protocol Compliance Clause 6-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0143": GSRSafetyRule(
        rule_id="GSR_SEC06_0143",
        section_number="G&SR 6.4.9",
        title="Safety Protocol Compliance Clause 6-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0144": GSRSafetyRule(
        rule_id="GSR_SEC06_0144",
        section_number="G&SR 6.5.1",
        title="Safety Protocol Compliance Clause 6-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0145": GSRSafetyRule(
        rule_id="GSR_SEC06_0145",
        section_number="G&SR 6.6.2",
        title="Safety Protocol Compliance Clause 6-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0146": GSRSafetyRule(
        rule_id="GSR_SEC06_0146",
        section_number="G&SR 6.7.3",
        title="Safety Protocol Compliance Clause 6-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0147": GSRSafetyRule(
        rule_id="GSR_SEC06_0147",
        section_number="G&SR 6.8.4",
        title="Safety Protocol Compliance Clause 6-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0148": GSRSafetyRule(
        rule_id="GSR_SEC06_0148",
        section_number="G&SR 6.9.5",
        title="Safety Protocol Compliance Clause 6-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0149": GSRSafetyRule(
        rule_id="GSR_SEC06_0149",
        section_number="G&SR 6.10.6",
        title="Safety Protocol Compliance Clause 6-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0150": GSRSafetyRule(
        rule_id="GSR_SEC06_0150",
        section_number="G&SR 6.11.7",
        title="Safety Protocol Compliance Clause 6-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0151": GSRSafetyRule(
        rule_id="GSR_SEC06_0151",
        section_number="G&SR 6.12.8",
        title="Safety Protocol Compliance Clause 6-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0152": GSRSafetyRule(
        rule_id="GSR_SEC06_0152",
        section_number="G&SR 6.13.9",
        title="Safety Protocol Compliance Clause 6-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0153": GSRSafetyRule(
        rule_id="GSR_SEC06_0153",
        section_number="G&SR 6.14.1",
        title="Safety Protocol Compliance Clause 6-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0154": GSRSafetyRule(
        rule_id="GSR_SEC06_0154",
        section_number="G&SR 6.15.2",
        title="Safety Protocol Compliance Clause 6-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0155": GSRSafetyRule(
        rule_id="GSR_SEC06_0155",
        section_number="G&SR 6.16.3",
        title="Safety Protocol Compliance Clause 6-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0156": GSRSafetyRule(
        rule_id="GSR_SEC06_0156",
        section_number="G&SR 6.17.4",
        title="Safety Protocol Compliance Clause 6-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0157": GSRSafetyRule(
        rule_id="GSR_SEC06_0157",
        section_number="G&SR 6.18.5",
        title="Safety Protocol Compliance Clause 6-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0158": GSRSafetyRule(
        rule_id="GSR_SEC06_0158",
        section_number="G&SR 6.19.6",
        title="Safety Protocol Compliance Clause 6-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0159": GSRSafetyRule(
        rule_id="GSR_SEC06_0159",
        section_number="G&SR 6.20.7",
        title="Safety Protocol Compliance Clause 6-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0160": GSRSafetyRule(
        rule_id="GSR_SEC06_0160",
        section_number="G&SR 6.1.8",
        title="Safety Protocol Compliance Clause 6-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0161": GSRSafetyRule(
        rule_id="GSR_SEC06_0161",
        section_number="G&SR 6.2.9",
        title="Safety Protocol Compliance Clause 6-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0162": GSRSafetyRule(
        rule_id="GSR_SEC06_0162",
        section_number="G&SR 6.3.1",
        title="Safety Protocol Compliance Clause 6-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0163": GSRSafetyRule(
        rule_id="GSR_SEC06_0163",
        section_number="G&SR 6.4.2",
        title="Safety Protocol Compliance Clause 6-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0164": GSRSafetyRule(
        rule_id="GSR_SEC06_0164",
        section_number="G&SR 6.5.3",
        title="Safety Protocol Compliance Clause 6-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0165": GSRSafetyRule(
        rule_id="GSR_SEC06_0165",
        section_number="G&SR 6.6.4",
        title="Safety Protocol Compliance Clause 6-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0166": GSRSafetyRule(
        rule_id="GSR_SEC06_0166",
        section_number="G&SR 6.7.5",
        title="Safety Protocol Compliance Clause 6-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0167": GSRSafetyRule(
        rule_id="GSR_SEC06_0167",
        section_number="G&SR 6.8.6",
        title="Safety Protocol Compliance Clause 6-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0168": GSRSafetyRule(
        rule_id="GSR_SEC06_0168",
        section_number="G&SR 6.9.7",
        title="Safety Protocol Compliance Clause 6-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0169": GSRSafetyRule(
        rule_id="GSR_SEC06_0169",
        section_number="G&SR 6.10.8",
        title="Safety Protocol Compliance Clause 6-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0170": GSRSafetyRule(
        rule_id="GSR_SEC06_0170",
        section_number="G&SR 6.11.9",
        title="Safety Protocol Compliance Clause 6-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0171": GSRSafetyRule(
        rule_id="GSR_SEC06_0171",
        section_number="G&SR 6.12.1",
        title="Safety Protocol Compliance Clause 6-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0172": GSRSafetyRule(
        rule_id="GSR_SEC06_0172",
        section_number="G&SR 6.13.2",
        title="Safety Protocol Compliance Clause 6-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0173": GSRSafetyRule(
        rule_id="GSR_SEC06_0173",
        section_number="G&SR 6.14.3",
        title="Safety Protocol Compliance Clause 6-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC06_0174": GSRSafetyRule(
        rule_id="GSR_SEC06_0174",
        section_number="G&SR 6.15.4",
        title="Safety Protocol Compliance Clause 6-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
