"""Indian Railways G&SR Regulatory Rulebook Section 018."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_018: Dict[str, GSRSafetyRule] = {
    "GSR_SEC18_0001": GSRSafetyRule(
        rule_id="GSR_SEC18_0001",
        section_number="G&SR 18.2.2",
        title="Safety Protocol Compliance Clause 18-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0002": GSRSafetyRule(
        rule_id="GSR_SEC18_0002",
        section_number="G&SR 18.3.3",
        title="Safety Protocol Compliance Clause 18-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0003": GSRSafetyRule(
        rule_id="GSR_SEC18_0003",
        section_number="G&SR 18.4.4",
        title="Safety Protocol Compliance Clause 18-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0004": GSRSafetyRule(
        rule_id="GSR_SEC18_0004",
        section_number="G&SR 18.5.5",
        title="Safety Protocol Compliance Clause 18-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0005": GSRSafetyRule(
        rule_id="GSR_SEC18_0005",
        section_number="G&SR 18.6.6",
        title="Safety Protocol Compliance Clause 18-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0006": GSRSafetyRule(
        rule_id="GSR_SEC18_0006",
        section_number="G&SR 18.7.7",
        title="Safety Protocol Compliance Clause 18-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0007": GSRSafetyRule(
        rule_id="GSR_SEC18_0007",
        section_number="G&SR 18.8.8",
        title="Safety Protocol Compliance Clause 18-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0008": GSRSafetyRule(
        rule_id="GSR_SEC18_0008",
        section_number="G&SR 18.9.9",
        title="Safety Protocol Compliance Clause 18-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0009": GSRSafetyRule(
        rule_id="GSR_SEC18_0009",
        section_number="G&SR 18.10.1",
        title="Safety Protocol Compliance Clause 18-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0010": GSRSafetyRule(
        rule_id="GSR_SEC18_0010",
        section_number="G&SR 18.11.2",
        title="Safety Protocol Compliance Clause 18-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0011": GSRSafetyRule(
        rule_id="GSR_SEC18_0011",
        section_number="G&SR 18.12.3",
        title="Safety Protocol Compliance Clause 18-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0012": GSRSafetyRule(
        rule_id="GSR_SEC18_0012",
        section_number="G&SR 18.13.4",
        title="Safety Protocol Compliance Clause 18-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0013": GSRSafetyRule(
        rule_id="GSR_SEC18_0013",
        section_number="G&SR 18.14.5",
        title="Safety Protocol Compliance Clause 18-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0014": GSRSafetyRule(
        rule_id="GSR_SEC18_0014",
        section_number="G&SR 18.15.6",
        title="Safety Protocol Compliance Clause 18-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0015": GSRSafetyRule(
        rule_id="GSR_SEC18_0015",
        section_number="G&SR 18.16.7",
        title="Safety Protocol Compliance Clause 18-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0016": GSRSafetyRule(
        rule_id="GSR_SEC18_0016",
        section_number="G&SR 18.17.8",
        title="Safety Protocol Compliance Clause 18-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0017": GSRSafetyRule(
        rule_id="GSR_SEC18_0017",
        section_number="G&SR 18.18.9",
        title="Safety Protocol Compliance Clause 18-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0018": GSRSafetyRule(
        rule_id="GSR_SEC18_0018",
        section_number="G&SR 18.19.1",
        title="Safety Protocol Compliance Clause 18-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0019": GSRSafetyRule(
        rule_id="GSR_SEC18_0019",
        section_number="G&SR 18.20.2",
        title="Safety Protocol Compliance Clause 18-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0020": GSRSafetyRule(
        rule_id="GSR_SEC18_0020",
        section_number="G&SR 18.1.3",
        title="Safety Protocol Compliance Clause 18-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0021": GSRSafetyRule(
        rule_id="GSR_SEC18_0021",
        section_number="G&SR 18.2.4",
        title="Safety Protocol Compliance Clause 18-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0022": GSRSafetyRule(
        rule_id="GSR_SEC18_0022",
        section_number="G&SR 18.3.5",
        title="Safety Protocol Compliance Clause 18-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0023": GSRSafetyRule(
        rule_id="GSR_SEC18_0023",
        section_number="G&SR 18.4.6",
        title="Safety Protocol Compliance Clause 18-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0024": GSRSafetyRule(
        rule_id="GSR_SEC18_0024",
        section_number="G&SR 18.5.7",
        title="Safety Protocol Compliance Clause 18-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0025": GSRSafetyRule(
        rule_id="GSR_SEC18_0025",
        section_number="G&SR 18.6.8",
        title="Safety Protocol Compliance Clause 18-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0026": GSRSafetyRule(
        rule_id="GSR_SEC18_0026",
        section_number="G&SR 18.7.9",
        title="Safety Protocol Compliance Clause 18-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0027": GSRSafetyRule(
        rule_id="GSR_SEC18_0027",
        section_number="G&SR 18.8.1",
        title="Safety Protocol Compliance Clause 18-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0028": GSRSafetyRule(
        rule_id="GSR_SEC18_0028",
        section_number="G&SR 18.9.2",
        title="Safety Protocol Compliance Clause 18-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0029": GSRSafetyRule(
        rule_id="GSR_SEC18_0029",
        section_number="G&SR 18.10.3",
        title="Safety Protocol Compliance Clause 18-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0030": GSRSafetyRule(
        rule_id="GSR_SEC18_0030",
        section_number="G&SR 18.11.4",
        title="Safety Protocol Compliance Clause 18-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0031": GSRSafetyRule(
        rule_id="GSR_SEC18_0031",
        section_number="G&SR 18.12.5",
        title="Safety Protocol Compliance Clause 18-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0032": GSRSafetyRule(
        rule_id="GSR_SEC18_0032",
        section_number="G&SR 18.13.6",
        title="Safety Protocol Compliance Clause 18-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0033": GSRSafetyRule(
        rule_id="GSR_SEC18_0033",
        section_number="G&SR 18.14.7",
        title="Safety Protocol Compliance Clause 18-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0034": GSRSafetyRule(
        rule_id="GSR_SEC18_0034",
        section_number="G&SR 18.15.8",
        title="Safety Protocol Compliance Clause 18-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0035": GSRSafetyRule(
        rule_id="GSR_SEC18_0035",
        section_number="G&SR 18.16.9",
        title="Safety Protocol Compliance Clause 18-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0036": GSRSafetyRule(
        rule_id="GSR_SEC18_0036",
        section_number="G&SR 18.17.1",
        title="Safety Protocol Compliance Clause 18-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0037": GSRSafetyRule(
        rule_id="GSR_SEC18_0037",
        section_number="G&SR 18.18.2",
        title="Safety Protocol Compliance Clause 18-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0038": GSRSafetyRule(
        rule_id="GSR_SEC18_0038",
        section_number="G&SR 18.19.3",
        title="Safety Protocol Compliance Clause 18-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0039": GSRSafetyRule(
        rule_id="GSR_SEC18_0039",
        section_number="G&SR 18.20.4",
        title="Safety Protocol Compliance Clause 18-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0040": GSRSafetyRule(
        rule_id="GSR_SEC18_0040",
        section_number="G&SR 18.1.5",
        title="Safety Protocol Compliance Clause 18-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0041": GSRSafetyRule(
        rule_id="GSR_SEC18_0041",
        section_number="G&SR 18.2.6",
        title="Safety Protocol Compliance Clause 18-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0042": GSRSafetyRule(
        rule_id="GSR_SEC18_0042",
        section_number="G&SR 18.3.7",
        title="Safety Protocol Compliance Clause 18-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0043": GSRSafetyRule(
        rule_id="GSR_SEC18_0043",
        section_number="G&SR 18.4.8",
        title="Safety Protocol Compliance Clause 18-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0044": GSRSafetyRule(
        rule_id="GSR_SEC18_0044",
        section_number="G&SR 18.5.9",
        title="Safety Protocol Compliance Clause 18-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0045": GSRSafetyRule(
        rule_id="GSR_SEC18_0045",
        section_number="G&SR 18.6.1",
        title="Safety Protocol Compliance Clause 18-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0046": GSRSafetyRule(
        rule_id="GSR_SEC18_0046",
        section_number="G&SR 18.7.2",
        title="Safety Protocol Compliance Clause 18-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0047": GSRSafetyRule(
        rule_id="GSR_SEC18_0047",
        section_number="G&SR 18.8.3",
        title="Safety Protocol Compliance Clause 18-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0048": GSRSafetyRule(
        rule_id="GSR_SEC18_0048",
        section_number="G&SR 18.9.4",
        title="Safety Protocol Compliance Clause 18-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0049": GSRSafetyRule(
        rule_id="GSR_SEC18_0049",
        section_number="G&SR 18.10.5",
        title="Safety Protocol Compliance Clause 18-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0050": GSRSafetyRule(
        rule_id="GSR_SEC18_0050",
        section_number="G&SR 18.11.6",
        title="Safety Protocol Compliance Clause 18-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0051": GSRSafetyRule(
        rule_id="GSR_SEC18_0051",
        section_number="G&SR 18.12.7",
        title="Safety Protocol Compliance Clause 18-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0052": GSRSafetyRule(
        rule_id="GSR_SEC18_0052",
        section_number="G&SR 18.13.8",
        title="Safety Protocol Compliance Clause 18-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0053": GSRSafetyRule(
        rule_id="GSR_SEC18_0053",
        section_number="G&SR 18.14.9",
        title="Safety Protocol Compliance Clause 18-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0054": GSRSafetyRule(
        rule_id="GSR_SEC18_0054",
        section_number="G&SR 18.15.1",
        title="Safety Protocol Compliance Clause 18-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0055": GSRSafetyRule(
        rule_id="GSR_SEC18_0055",
        section_number="G&SR 18.16.2",
        title="Safety Protocol Compliance Clause 18-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0056": GSRSafetyRule(
        rule_id="GSR_SEC18_0056",
        section_number="G&SR 18.17.3",
        title="Safety Protocol Compliance Clause 18-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0057": GSRSafetyRule(
        rule_id="GSR_SEC18_0057",
        section_number="G&SR 18.18.4",
        title="Safety Protocol Compliance Clause 18-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0058": GSRSafetyRule(
        rule_id="GSR_SEC18_0058",
        section_number="G&SR 18.19.5",
        title="Safety Protocol Compliance Clause 18-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0059": GSRSafetyRule(
        rule_id="GSR_SEC18_0059",
        section_number="G&SR 18.20.6",
        title="Safety Protocol Compliance Clause 18-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0060": GSRSafetyRule(
        rule_id="GSR_SEC18_0060",
        section_number="G&SR 18.1.7",
        title="Safety Protocol Compliance Clause 18-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0061": GSRSafetyRule(
        rule_id="GSR_SEC18_0061",
        section_number="G&SR 18.2.8",
        title="Safety Protocol Compliance Clause 18-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0062": GSRSafetyRule(
        rule_id="GSR_SEC18_0062",
        section_number="G&SR 18.3.9",
        title="Safety Protocol Compliance Clause 18-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0063": GSRSafetyRule(
        rule_id="GSR_SEC18_0063",
        section_number="G&SR 18.4.1",
        title="Safety Protocol Compliance Clause 18-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0064": GSRSafetyRule(
        rule_id="GSR_SEC18_0064",
        section_number="G&SR 18.5.2",
        title="Safety Protocol Compliance Clause 18-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0065": GSRSafetyRule(
        rule_id="GSR_SEC18_0065",
        section_number="G&SR 18.6.3",
        title="Safety Protocol Compliance Clause 18-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0066": GSRSafetyRule(
        rule_id="GSR_SEC18_0066",
        section_number="G&SR 18.7.4",
        title="Safety Protocol Compliance Clause 18-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0067": GSRSafetyRule(
        rule_id="GSR_SEC18_0067",
        section_number="G&SR 18.8.5",
        title="Safety Protocol Compliance Clause 18-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0068": GSRSafetyRule(
        rule_id="GSR_SEC18_0068",
        section_number="G&SR 18.9.6",
        title="Safety Protocol Compliance Clause 18-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0069": GSRSafetyRule(
        rule_id="GSR_SEC18_0069",
        section_number="G&SR 18.10.7",
        title="Safety Protocol Compliance Clause 18-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0070": GSRSafetyRule(
        rule_id="GSR_SEC18_0070",
        section_number="G&SR 18.11.8",
        title="Safety Protocol Compliance Clause 18-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0071": GSRSafetyRule(
        rule_id="GSR_SEC18_0071",
        section_number="G&SR 18.12.9",
        title="Safety Protocol Compliance Clause 18-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0072": GSRSafetyRule(
        rule_id="GSR_SEC18_0072",
        section_number="G&SR 18.13.1",
        title="Safety Protocol Compliance Clause 18-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0073": GSRSafetyRule(
        rule_id="GSR_SEC18_0073",
        section_number="G&SR 18.14.2",
        title="Safety Protocol Compliance Clause 18-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0074": GSRSafetyRule(
        rule_id="GSR_SEC18_0074",
        section_number="G&SR 18.15.3",
        title="Safety Protocol Compliance Clause 18-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0075": GSRSafetyRule(
        rule_id="GSR_SEC18_0075",
        section_number="G&SR 18.16.4",
        title="Safety Protocol Compliance Clause 18-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0076": GSRSafetyRule(
        rule_id="GSR_SEC18_0076",
        section_number="G&SR 18.17.5",
        title="Safety Protocol Compliance Clause 18-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0077": GSRSafetyRule(
        rule_id="GSR_SEC18_0077",
        section_number="G&SR 18.18.6",
        title="Safety Protocol Compliance Clause 18-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0078": GSRSafetyRule(
        rule_id="GSR_SEC18_0078",
        section_number="G&SR 18.19.7",
        title="Safety Protocol Compliance Clause 18-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0079": GSRSafetyRule(
        rule_id="GSR_SEC18_0079",
        section_number="G&SR 18.20.8",
        title="Safety Protocol Compliance Clause 18-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0080": GSRSafetyRule(
        rule_id="GSR_SEC18_0080",
        section_number="G&SR 18.1.9",
        title="Safety Protocol Compliance Clause 18-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0081": GSRSafetyRule(
        rule_id="GSR_SEC18_0081",
        section_number="G&SR 18.2.1",
        title="Safety Protocol Compliance Clause 18-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0082": GSRSafetyRule(
        rule_id="GSR_SEC18_0082",
        section_number="G&SR 18.3.2",
        title="Safety Protocol Compliance Clause 18-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0083": GSRSafetyRule(
        rule_id="GSR_SEC18_0083",
        section_number="G&SR 18.4.3",
        title="Safety Protocol Compliance Clause 18-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0084": GSRSafetyRule(
        rule_id="GSR_SEC18_0084",
        section_number="G&SR 18.5.4",
        title="Safety Protocol Compliance Clause 18-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0085": GSRSafetyRule(
        rule_id="GSR_SEC18_0085",
        section_number="G&SR 18.6.5",
        title="Safety Protocol Compliance Clause 18-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0086": GSRSafetyRule(
        rule_id="GSR_SEC18_0086",
        section_number="G&SR 18.7.6",
        title="Safety Protocol Compliance Clause 18-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0087": GSRSafetyRule(
        rule_id="GSR_SEC18_0087",
        section_number="G&SR 18.8.7",
        title="Safety Protocol Compliance Clause 18-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0088": GSRSafetyRule(
        rule_id="GSR_SEC18_0088",
        section_number="G&SR 18.9.8",
        title="Safety Protocol Compliance Clause 18-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0089": GSRSafetyRule(
        rule_id="GSR_SEC18_0089",
        section_number="G&SR 18.10.9",
        title="Safety Protocol Compliance Clause 18-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0090": GSRSafetyRule(
        rule_id="GSR_SEC18_0090",
        section_number="G&SR 18.11.1",
        title="Safety Protocol Compliance Clause 18-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0091": GSRSafetyRule(
        rule_id="GSR_SEC18_0091",
        section_number="G&SR 18.12.2",
        title="Safety Protocol Compliance Clause 18-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0092": GSRSafetyRule(
        rule_id="GSR_SEC18_0092",
        section_number="G&SR 18.13.3",
        title="Safety Protocol Compliance Clause 18-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0093": GSRSafetyRule(
        rule_id="GSR_SEC18_0093",
        section_number="G&SR 18.14.4",
        title="Safety Protocol Compliance Clause 18-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0094": GSRSafetyRule(
        rule_id="GSR_SEC18_0094",
        section_number="G&SR 18.15.5",
        title="Safety Protocol Compliance Clause 18-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0095": GSRSafetyRule(
        rule_id="GSR_SEC18_0095",
        section_number="G&SR 18.16.6",
        title="Safety Protocol Compliance Clause 18-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0096": GSRSafetyRule(
        rule_id="GSR_SEC18_0096",
        section_number="G&SR 18.17.7",
        title="Safety Protocol Compliance Clause 18-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0097": GSRSafetyRule(
        rule_id="GSR_SEC18_0097",
        section_number="G&SR 18.18.8",
        title="Safety Protocol Compliance Clause 18-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0098": GSRSafetyRule(
        rule_id="GSR_SEC18_0098",
        section_number="G&SR 18.19.9",
        title="Safety Protocol Compliance Clause 18-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0099": GSRSafetyRule(
        rule_id="GSR_SEC18_0099",
        section_number="G&SR 18.20.1",
        title="Safety Protocol Compliance Clause 18-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0100": GSRSafetyRule(
        rule_id="GSR_SEC18_0100",
        section_number="G&SR 18.1.2",
        title="Safety Protocol Compliance Clause 18-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0101": GSRSafetyRule(
        rule_id="GSR_SEC18_0101",
        section_number="G&SR 18.2.3",
        title="Safety Protocol Compliance Clause 18-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0102": GSRSafetyRule(
        rule_id="GSR_SEC18_0102",
        section_number="G&SR 18.3.4",
        title="Safety Protocol Compliance Clause 18-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0103": GSRSafetyRule(
        rule_id="GSR_SEC18_0103",
        section_number="G&SR 18.4.5",
        title="Safety Protocol Compliance Clause 18-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0104": GSRSafetyRule(
        rule_id="GSR_SEC18_0104",
        section_number="G&SR 18.5.6",
        title="Safety Protocol Compliance Clause 18-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0105": GSRSafetyRule(
        rule_id="GSR_SEC18_0105",
        section_number="G&SR 18.6.7",
        title="Safety Protocol Compliance Clause 18-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0106": GSRSafetyRule(
        rule_id="GSR_SEC18_0106",
        section_number="G&SR 18.7.8",
        title="Safety Protocol Compliance Clause 18-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0107": GSRSafetyRule(
        rule_id="GSR_SEC18_0107",
        section_number="G&SR 18.8.9",
        title="Safety Protocol Compliance Clause 18-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0108": GSRSafetyRule(
        rule_id="GSR_SEC18_0108",
        section_number="G&SR 18.9.1",
        title="Safety Protocol Compliance Clause 18-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0109": GSRSafetyRule(
        rule_id="GSR_SEC18_0109",
        section_number="G&SR 18.10.2",
        title="Safety Protocol Compliance Clause 18-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0110": GSRSafetyRule(
        rule_id="GSR_SEC18_0110",
        section_number="G&SR 18.11.3",
        title="Safety Protocol Compliance Clause 18-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0111": GSRSafetyRule(
        rule_id="GSR_SEC18_0111",
        section_number="G&SR 18.12.4",
        title="Safety Protocol Compliance Clause 18-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0112": GSRSafetyRule(
        rule_id="GSR_SEC18_0112",
        section_number="G&SR 18.13.5",
        title="Safety Protocol Compliance Clause 18-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0113": GSRSafetyRule(
        rule_id="GSR_SEC18_0113",
        section_number="G&SR 18.14.6",
        title="Safety Protocol Compliance Clause 18-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0114": GSRSafetyRule(
        rule_id="GSR_SEC18_0114",
        section_number="G&SR 18.15.7",
        title="Safety Protocol Compliance Clause 18-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0115": GSRSafetyRule(
        rule_id="GSR_SEC18_0115",
        section_number="G&SR 18.16.8",
        title="Safety Protocol Compliance Clause 18-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0116": GSRSafetyRule(
        rule_id="GSR_SEC18_0116",
        section_number="G&SR 18.17.9",
        title="Safety Protocol Compliance Clause 18-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0117": GSRSafetyRule(
        rule_id="GSR_SEC18_0117",
        section_number="G&SR 18.18.1",
        title="Safety Protocol Compliance Clause 18-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0118": GSRSafetyRule(
        rule_id="GSR_SEC18_0118",
        section_number="G&SR 18.19.2",
        title="Safety Protocol Compliance Clause 18-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0119": GSRSafetyRule(
        rule_id="GSR_SEC18_0119",
        section_number="G&SR 18.20.3",
        title="Safety Protocol Compliance Clause 18-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0120": GSRSafetyRule(
        rule_id="GSR_SEC18_0120",
        section_number="G&SR 18.1.4",
        title="Safety Protocol Compliance Clause 18-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0121": GSRSafetyRule(
        rule_id="GSR_SEC18_0121",
        section_number="G&SR 18.2.5",
        title="Safety Protocol Compliance Clause 18-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0122": GSRSafetyRule(
        rule_id="GSR_SEC18_0122",
        section_number="G&SR 18.3.6",
        title="Safety Protocol Compliance Clause 18-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0123": GSRSafetyRule(
        rule_id="GSR_SEC18_0123",
        section_number="G&SR 18.4.7",
        title="Safety Protocol Compliance Clause 18-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0124": GSRSafetyRule(
        rule_id="GSR_SEC18_0124",
        section_number="G&SR 18.5.8",
        title="Safety Protocol Compliance Clause 18-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0125": GSRSafetyRule(
        rule_id="GSR_SEC18_0125",
        section_number="G&SR 18.6.9",
        title="Safety Protocol Compliance Clause 18-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0126": GSRSafetyRule(
        rule_id="GSR_SEC18_0126",
        section_number="G&SR 18.7.1",
        title="Safety Protocol Compliance Clause 18-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0127": GSRSafetyRule(
        rule_id="GSR_SEC18_0127",
        section_number="G&SR 18.8.2",
        title="Safety Protocol Compliance Clause 18-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0128": GSRSafetyRule(
        rule_id="GSR_SEC18_0128",
        section_number="G&SR 18.9.3",
        title="Safety Protocol Compliance Clause 18-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0129": GSRSafetyRule(
        rule_id="GSR_SEC18_0129",
        section_number="G&SR 18.10.4",
        title="Safety Protocol Compliance Clause 18-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0130": GSRSafetyRule(
        rule_id="GSR_SEC18_0130",
        section_number="G&SR 18.11.5",
        title="Safety Protocol Compliance Clause 18-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0131": GSRSafetyRule(
        rule_id="GSR_SEC18_0131",
        section_number="G&SR 18.12.6",
        title="Safety Protocol Compliance Clause 18-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0132": GSRSafetyRule(
        rule_id="GSR_SEC18_0132",
        section_number="G&SR 18.13.7",
        title="Safety Protocol Compliance Clause 18-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0133": GSRSafetyRule(
        rule_id="GSR_SEC18_0133",
        section_number="G&SR 18.14.8",
        title="Safety Protocol Compliance Clause 18-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0134": GSRSafetyRule(
        rule_id="GSR_SEC18_0134",
        section_number="G&SR 18.15.9",
        title="Safety Protocol Compliance Clause 18-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0135": GSRSafetyRule(
        rule_id="GSR_SEC18_0135",
        section_number="G&SR 18.16.1",
        title="Safety Protocol Compliance Clause 18-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0136": GSRSafetyRule(
        rule_id="GSR_SEC18_0136",
        section_number="G&SR 18.17.2",
        title="Safety Protocol Compliance Clause 18-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0137": GSRSafetyRule(
        rule_id="GSR_SEC18_0137",
        section_number="G&SR 18.18.3",
        title="Safety Protocol Compliance Clause 18-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0138": GSRSafetyRule(
        rule_id="GSR_SEC18_0138",
        section_number="G&SR 18.19.4",
        title="Safety Protocol Compliance Clause 18-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0139": GSRSafetyRule(
        rule_id="GSR_SEC18_0139",
        section_number="G&SR 18.20.5",
        title="Safety Protocol Compliance Clause 18-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0140": GSRSafetyRule(
        rule_id="GSR_SEC18_0140",
        section_number="G&SR 18.1.6",
        title="Safety Protocol Compliance Clause 18-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0141": GSRSafetyRule(
        rule_id="GSR_SEC18_0141",
        section_number="G&SR 18.2.7",
        title="Safety Protocol Compliance Clause 18-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0142": GSRSafetyRule(
        rule_id="GSR_SEC18_0142",
        section_number="G&SR 18.3.8",
        title="Safety Protocol Compliance Clause 18-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0143": GSRSafetyRule(
        rule_id="GSR_SEC18_0143",
        section_number="G&SR 18.4.9",
        title="Safety Protocol Compliance Clause 18-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0144": GSRSafetyRule(
        rule_id="GSR_SEC18_0144",
        section_number="G&SR 18.5.1",
        title="Safety Protocol Compliance Clause 18-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0145": GSRSafetyRule(
        rule_id="GSR_SEC18_0145",
        section_number="G&SR 18.6.2",
        title="Safety Protocol Compliance Clause 18-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0146": GSRSafetyRule(
        rule_id="GSR_SEC18_0146",
        section_number="G&SR 18.7.3",
        title="Safety Protocol Compliance Clause 18-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0147": GSRSafetyRule(
        rule_id="GSR_SEC18_0147",
        section_number="G&SR 18.8.4",
        title="Safety Protocol Compliance Clause 18-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0148": GSRSafetyRule(
        rule_id="GSR_SEC18_0148",
        section_number="G&SR 18.9.5",
        title="Safety Protocol Compliance Clause 18-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0149": GSRSafetyRule(
        rule_id="GSR_SEC18_0149",
        section_number="G&SR 18.10.6",
        title="Safety Protocol Compliance Clause 18-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0150": GSRSafetyRule(
        rule_id="GSR_SEC18_0150",
        section_number="G&SR 18.11.7",
        title="Safety Protocol Compliance Clause 18-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0151": GSRSafetyRule(
        rule_id="GSR_SEC18_0151",
        section_number="G&SR 18.12.8",
        title="Safety Protocol Compliance Clause 18-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0152": GSRSafetyRule(
        rule_id="GSR_SEC18_0152",
        section_number="G&SR 18.13.9",
        title="Safety Protocol Compliance Clause 18-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0153": GSRSafetyRule(
        rule_id="GSR_SEC18_0153",
        section_number="G&SR 18.14.1",
        title="Safety Protocol Compliance Clause 18-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0154": GSRSafetyRule(
        rule_id="GSR_SEC18_0154",
        section_number="G&SR 18.15.2",
        title="Safety Protocol Compliance Clause 18-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0155": GSRSafetyRule(
        rule_id="GSR_SEC18_0155",
        section_number="G&SR 18.16.3",
        title="Safety Protocol Compliance Clause 18-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0156": GSRSafetyRule(
        rule_id="GSR_SEC18_0156",
        section_number="G&SR 18.17.4",
        title="Safety Protocol Compliance Clause 18-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0157": GSRSafetyRule(
        rule_id="GSR_SEC18_0157",
        section_number="G&SR 18.18.5",
        title="Safety Protocol Compliance Clause 18-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0158": GSRSafetyRule(
        rule_id="GSR_SEC18_0158",
        section_number="G&SR 18.19.6",
        title="Safety Protocol Compliance Clause 18-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0159": GSRSafetyRule(
        rule_id="GSR_SEC18_0159",
        section_number="G&SR 18.20.7",
        title="Safety Protocol Compliance Clause 18-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0160": GSRSafetyRule(
        rule_id="GSR_SEC18_0160",
        section_number="G&SR 18.1.8",
        title="Safety Protocol Compliance Clause 18-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0161": GSRSafetyRule(
        rule_id="GSR_SEC18_0161",
        section_number="G&SR 18.2.9",
        title="Safety Protocol Compliance Clause 18-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0162": GSRSafetyRule(
        rule_id="GSR_SEC18_0162",
        section_number="G&SR 18.3.1",
        title="Safety Protocol Compliance Clause 18-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0163": GSRSafetyRule(
        rule_id="GSR_SEC18_0163",
        section_number="G&SR 18.4.2",
        title="Safety Protocol Compliance Clause 18-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0164": GSRSafetyRule(
        rule_id="GSR_SEC18_0164",
        section_number="G&SR 18.5.3",
        title="Safety Protocol Compliance Clause 18-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0165": GSRSafetyRule(
        rule_id="GSR_SEC18_0165",
        section_number="G&SR 18.6.4",
        title="Safety Protocol Compliance Clause 18-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0166": GSRSafetyRule(
        rule_id="GSR_SEC18_0166",
        section_number="G&SR 18.7.5",
        title="Safety Protocol Compliance Clause 18-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0167": GSRSafetyRule(
        rule_id="GSR_SEC18_0167",
        section_number="G&SR 18.8.6",
        title="Safety Protocol Compliance Clause 18-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0168": GSRSafetyRule(
        rule_id="GSR_SEC18_0168",
        section_number="G&SR 18.9.7",
        title="Safety Protocol Compliance Clause 18-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0169": GSRSafetyRule(
        rule_id="GSR_SEC18_0169",
        section_number="G&SR 18.10.8",
        title="Safety Protocol Compliance Clause 18-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0170": GSRSafetyRule(
        rule_id="GSR_SEC18_0170",
        section_number="G&SR 18.11.9",
        title="Safety Protocol Compliance Clause 18-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0171": GSRSafetyRule(
        rule_id="GSR_SEC18_0171",
        section_number="G&SR 18.12.1",
        title="Safety Protocol Compliance Clause 18-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0172": GSRSafetyRule(
        rule_id="GSR_SEC18_0172",
        section_number="G&SR 18.13.2",
        title="Safety Protocol Compliance Clause 18-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0173": GSRSafetyRule(
        rule_id="GSR_SEC18_0173",
        section_number="G&SR 18.14.3",
        title="Safety Protocol Compliance Clause 18-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC18_0174": GSRSafetyRule(
        rule_id="GSR_SEC18_0174",
        section_number="G&SR 18.15.4",
        title="Safety Protocol Compliance Clause 18-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
