"""Indian Railways G&SR Regulatory Rulebook Section 001."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_001: Dict[str, GSRSafetyRule] = {
    "GSR_SEC01_0001": GSRSafetyRule(
        rule_id="GSR_SEC01_0001",
        section_number="G&SR 1.2.2",
        title="Safety Protocol Compliance Clause 1-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0002": GSRSafetyRule(
        rule_id="GSR_SEC01_0002",
        section_number="G&SR 1.3.3",
        title="Safety Protocol Compliance Clause 1-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0003": GSRSafetyRule(
        rule_id="GSR_SEC01_0003",
        section_number="G&SR 1.4.4",
        title="Safety Protocol Compliance Clause 1-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0004": GSRSafetyRule(
        rule_id="GSR_SEC01_0004",
        section_number="G&SR 1.5.5",
        title="Safety Protocol Compliance Clause 1-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0005": GSRSafetyRule(
        rule_id="GSR_SEC01_0005",
        section_number="G&SR 1.6.6",
        title="Safety Protocol Compliance Clause 1-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0006": GSRSafetyRule(
        rule_id="GSR_SEC01_0006",
        section_number="G&SR 1.7.7",
        title="Safety Protocol Compliance Clause 1-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0007": GSRSafetyRule(
        rule_id="GSR_SEC01_0007",
        section_number="G&SR 1.8.8",
        title="Safety Protocol Compliance Clause 1-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0008": GSRSafetyRule(
        rule_id="GSR_SEC01_0008",
        section_number="G&SR 1.9.9",
        title="Safety Protocol Compliance Clause 1-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0009": GSRSafetyRule(
        rule_id="GSR_SEC01_0009",
        section_number="G&SR 1.10.1",
        title="Safety Protocol Compliance Clause 1-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0010": GSRSafetyRule(
        rule_id="GSR_SEC01_0010",
        section_number="G&SR 1.11.2",
        title="Safety Protocol Compliance Clause 1-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0011": GSRSafetyRule(
        rule_id="GSR_SEC01_0011",
        section_number="G&SR 1.12.3",
        title="Safety Protocol Compliance Clause 1-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0012": GSRSafetyRule(
        rule_id="GSR_SEC01_0012",
        section_number="G&SR 1.13.4",
        title="Safety Protocol Compliance Clause 1-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0013": GSRSafetyRule(
        rule_id="GSR_SEC01_0013",
        section_number="G&SR 1.14.5",
        title="Safety Protocol Compliance Clause 1-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0014": GSRSafetyRule(
        rule_id="GSR_SEC01_0014",
        section_number="G&SR 1.15.6",
        title="Safety Protocol Compliance Clause 1-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0015": GSRSafetyRule(
        rule_id="GSR_SEC01_0015",
        section_number="G&SR 1.16.7",
        title="Safety Protocol Compliance Clause 1-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0016": GSRSafetyRule(
        rule_id="GSR_SEC01_0016",
        section_number="G&SR 1.17.8",
        title="Safety Protocol Compliance Clause 1-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0017": GSRSafetyRule(
        rule_id="GSR_SEC01_0017",
        section_number="G&SR 1.18.9",
        title="Safety Protocol Compliance Clause 1-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0018": GSRSafetyRule(
        rule_id="GSR_SEC01_0018",
        section_number="G&SR 1.19.1",
        title="Safety Protocol Compliance Clause 1-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0019": GSRSafetyRule(
        rule_id="GSR_SEC01_0019",
        section_number="G&SR 1.20.2",
        title="Safety Protocol Compliance Clause 1-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0020": GSRSafetyRule(
        rule_id="GSR_SEC01_0020",
        section_number="G&SR 1.1.3",
        title="Safety Protocol Compliance Clause 1-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0021": GSRSafetyRule(
        rule_id="GSR_SEC01_0021",
        section_number="G&SR 1.2.4",
        title="Safety Protocol Compliance Clause 1-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0022": GSRSafetyRule(
        rule_id="GSR_SEC01_0022",
        section_number="G&SR 1.3.5",
        title="Safety Protocol Compliance Clause 1-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0023": GSRSafetyRule(
        rule_id="GSR_SEC01_0023",
        section_number="G&SR 1.4.6",
        title="Safety Protocol Compliance Clause 1-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0024": GSRSafetyRule(
        rule_id="GSR_SEC01_0024",
        section_number="G&SR 1.5.7",
        title="Safety Protocol Compliance Clause 1-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0025": GSRSafetyRule(
        rule_id="GSR_SEC01_0025",
        section_number="G&SR 1.6.8",
        title="Safety Protocol Compliance Clause 1-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0026": GSRSafetyRule(
        rule_id="GSR_SEC01_0026",
        section_number="G&SR 1.7.9",
        title="Safety Protocol Compliance Clause 1-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0027": GSRSafetyRule(
        rule_id="GSR_SEC01_0027",
        section_number="G&SR 1.8.1",
        title="Safety Protocol Compliance Clause 1-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0028": GSRSafetyRule(
        rule_id="GSR_SEC01_0028",
        section_number="G&SR 1.9.2",
        title="Safety Protocol Compliance Clause 1-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0029": GSRSafetyRule(
        rule_id="GSR_SEC01_0029",
        section_number="G&SR 1.10.3",
        title="Safety Protocol Compliance Clause 1-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0030": GSRSafetyRule(
        rule_id="GSR_SEC01_0030",
        section_number="G&SR 1.11.4",
        title="Safety Protocol Compliance Clause 1-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0031": GSRSafetyRule(
        rule_id="GSR_SEC01_0031",
        section_number="G&SR 1.12.5",
        title="Safety Protocol Compliance Clause 1-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0032": GSRSafetyRule(
        rule_id="GSR_SEC01_0032",
        section_number="G&SR 1.13.6",
        title="Safety Protocol Compliance Clause 1-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0033": GSRSafetyRule(
        rule_id="GSR_SEC01_0033",
        section_number="G&SR 1.14.7",
        title="Safety Protocol Compliance Clause 1-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0034": GSRSafetyRule(
        rule_id="GSR_SEC01_0034",
        section_number="G&SR 1.15.8",
        title="Safety Protocol Compliance Clause 1-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0035": GSRSafetyRule(
        rule_id="GSR_SEC01_0035",
        section_number="G&SR 1.16.9",
        title="Safety Protocol Compliance Clause 1-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0036": GSRSafetyRule(
        rule_id="GSR_SEC01_0036",
        section_number="G&SR 1.17.1",
        title="Safety Protocol Compliance Clause 1-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0037": GSRSafetyRule(
        rule_id="GSR_SEC01_0037",
        section_number="G&SR 1.18.2",
        title="Safety Protocol Compliance Clause 1-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0038": GSRSafetyRule(
        rule_id="GSR_SEC01_0038",
        section_number="G&SR 1.19.3",
        title="Safety Protocol Compliance Clause 1-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0039": GSRSafetyRule(
        rule_id="GSR_SEC01_0039",
        section_number="G&SR 1.20.4",
        title="Safety Protocol Compliance Clause 1-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0040": GSRSafetyRule(
        rule_id="GSR_SEC01_0040",
        section_number="G&SR 1.1.5",
        title="Safety Protocol Compliance Clause 1-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0041": GSRSafetyRule(
        rule_id="GSR_SEC01_0041",
        section_number="G&SR 1.2.6",
        title="Safety Protocol Compliance Clause 1-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0042": GSRSafetyRule(
        rule_id="GSR_SEC01_0042",
        section_number="G&SR 1.3.7",
        title="Safety Protocol Compliance Clause 1-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0043": GSRSafetyRule(
        rule_id="GSR_SEC01_0043",
        section_number="G&SR 1.4.8",
        title="Safety Protocol Compliance Clause 1-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0044": GSRSafetyRule(
        rule_id="GSR_SEC01_0044",
        section_number="G&SR 1.5.9",
        title="Safety Protocol Compliance Clause 1-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0045": GSRSafetyRule(
        rule_id="GSR_SEC01_0045",
        section_number="G&SR 1.6.1",
        title="Safety Protocol Compliance Clause 1-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0046": GSRSafetyRule(
        rule_id="GSR_SEC01_0046",
        section_number="G&SR 1.7.2",
        title="Safety Protocol Compliance Clause 1-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0047": GSRSafetyRule(
        rule_id="GSR_SEC01_0047",
        section_number="G&SR 1.8.3",
        title="Safety Protocol Compliance Clause 1-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0048": GSRSafetyRule(
        rule_id="GSR_SEC01_0048",
        section_number="G&SR 1.9.4",
        title="Safety Protocol Compliance Clause 1-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0049": GSRSafetyRule(
        rule_id="GSR_SEC01_0049",
        section_number="G&SR 1.10.5",
        title="Safety Protocol Compliance Clause 1-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0050": GSRSafetyRule(
        rule_id="GSR_SEC01_0050",
        section_number="G&SR 1.11.6",
        title="Safety Protocol Compliance Clause 1-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0051": GSRSafetyRule(
        rule_id="GSR_SEC01_0051",
        section_number="G&SR 1.12.7",
        title="Safety Protocol Compliance Clause 1-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0052": GSRSafetyRule(
        rule_id="GSR_SEC01_0052",
        section_number="G&SR 1.13.8",
        title="Safety Protocol Compliance Clause 1-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0053": GSRSafetyRule(
        rule_id="GSR_SEC01_0053",
        section_number="G&SR 1.14.9",
        title="Safety Protocol Compliance Clause 1-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0054": GSRSafetyRule(
        rule_id="GSR_SEC01_0054",
        section_number="G&SR 1.15.1",
        title="Safety Protocol Compliance Clause 1-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0055": GSRSafetyRule(
        rule_id="GSR_SEC01_0055",
        section_number="G&SR 1.16.2",
        title="Safety Protocol Compliance Clause 1-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0056": GSRSafetyRule(
        rule_id="GSR_SEC01_0056",
        section_number="G&SR 1.17.3",
        title="Safety Protocol Compliance Clause 1-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0057": GSRSafetyRule(
        rule_id="GSR_SEC01_0057",
        section_number="G&SR 1.18.4",
        title="Safety Protocol Compliance Clause 1-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0058": GSRSafetyRule(
        rule_id="GSR_SEC01_0058",
        section_number="G&SR 1.19.5",
        title="Safety Protocol Compliance Clause 1-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0059": GSRSafetyRule(
        rule_id="GSR_SEC01_0059",
        section_number="G&SR 1.20.6",
        title="Safety Protocol Compliance Clause 1-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0060": GSRSafetyRule(
        rule_id="GSR_SEC01_0060",
        section_number="G&SR 1.1.7",
        title="Safety Protocol Compliance Clause 1-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0061": GSRSafetyRule(
        rule_id="GSR_SEC01_0061",
        section_number="G&SR 1.2.8",
        title="Safety Protocol Compliance Clause 1-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0062": GSRSafetyRule(
        rule_id="GSR_SEC01_0062",
        section_number="G&SR 1.3.9",
        title="Safety Protocol Compliance Clause 1-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0063": GSRSafetyRule(
        rule_id="GSR_SEC01_0063",
        section_number="G&SR 1.4.1",
        title="Safety Protocol Compliance Clause 1-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0064": GSRSafetyRule(
        rule_id="GSR_SEC01_0064",
        section_number="G&SR 1.5.2",
        title="Safety Protocol Compliance Clause 1-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0065": GSRSafetyRule(
        rule_id="GSR_SEC01_0065",
        section_number="G&SR 1.6.3",
        title="Safety Protocol Compliance Clause 1-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0066": GSRSafetyRule(
        rule_id="GSR_SEC01_0066",
        section_number="G&SR 1.7.4",
        title="Safety Protocol Compliance Clause 1-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0067": GSRSafetyRule(
        rule_id="GSR_SEC01_0067",
        section_number="G&SR 1.8.5",
        title="Safety Protocol Compliance Clause 1-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0068": GSRSafetyRule(
        rule_id="GSR_SEC01_0068",
        section_number="G&SR 1.9.6",
        title="Safety Protocol Compliance Clause 1-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0069": GSRSafetyRule(
        rule_id="GSR_SEC01_0069",
        section_number="G&SR 1.10.7",
        title="Safety Protocol Compliance Clause 1-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0070": GSRSafetyRule(
        rule_id="GSR_SEC01_0070",
        section_number="G&SR 1.11.8",
        title="Safety Protocol Compliance Clause 1-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0071": GSRSafetyRule(
        rule_id="GSR_SEC01_0071",
        section_number="G&SR 1.12.9",
        title="Safety Protocol Compliance Clause 1-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0072": GSRSafetyRule(
        rule_id="GSR_SEC01_0072",
        section_number="G&SR 1.13.1",
        title="Safety Protocol Compliance Clause 1-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0073": GSRSafetyRule(
        rule_id="GSR_SEC01_0073",
        section_number="G&SR 1.14.2",
        title="Safety Protocol Compliance Clause 1-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0074": GSRSafetyRule(
        rule_id="GSR_SEC01_0074",
        section_number="G&SR 1.15.3",
        title="Safety Protocol Compliance Clause 1-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0075": GSRSafetyRule(
        rule_id="GSR_SEC01_0075",
        section_number="G&SR 1.16.4",
        title="Safety Protocol Compliance Clause 1-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0076": GSRSafetyRule(
        rule_id="GSR_SEC01_0076",
        section_number="G&SR 1.17.5",
        title="Safety Protocol Compliance Clause 1-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0077": GSRSafetyRule(
        rule_id="GSR_SEC01_0077",
        section_number="G&SR 1.18.6",
        title="Safety Protocol Compliance Clause 1-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0078": GSRSafetyRule(
        rule_id="GSR_SEC01_0078",
        section_number="G&SR 1.19.7",
        title="Safety Protocol Compliance Clause 1-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0079": GSRSafetyRule(
        rule_id="GSR_SEC01_0079",
        section_number="G&SR 1.20.8",
        title="Safety Protocol Compliance Clause 1-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0080": GSRSafetyRule(
        rule_id="GSR_SEC01_0080",
        section_number="G&SR 1.1.9",
        title="Safety Protocol Compliance Clause 1-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0081": GSRSafetyRule(
        rule_id="GSR_SEC01_0081",
        section_number="G&SR 1.2.1",
        title="Safety Protocol Compliance Clause 1-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0082": GSRSafetyRule(
        rule_id="GSR_SEC01_0082",
        section_number="G&SR 1.3.2",
        title="Safety Protocol Compliance Clause 1-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0083": GSRSafetyRule(
        rule_id="GSR_SEC01_0083",
        section_number="G&SR 1.4.3",
        title="Safety Protocol Compliance Clause 1-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0084": GSRSafetyRule(
        rule_id="GSR_SEC01_0084",
        section_number="G&SR 1.5.4",
        title="Safety Protocol Compliance Clause 1-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0085": GSRSafetyRule(
        rule_id="GSR_SEC01_0085",
        section_number="G&SR 1.6.5",
        title="Safety Protocol Compliance Clause 1-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0086": GSRSafetyRule(
        rule_id="GSR_SEC01_0086",
        section_number="G&SR 1.7.6",
        title="Safety Protocol Compliance Clause 1-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0087": GSRSafetyRule(
        rule_id="GSR_SEC01_0087",
        section_number="G&SR 1.8.7",
        title="Safety Protocol Compliance Clause 1-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0088": GSRSafetyRule(
        rule_id="GSR_SEC01_0088",
        section_number="G&SR 1.9.8",
        title="Safety Protocol Compliance Clause 1-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0089": GSRSafetyRule(
        rule_id="GSR_SEC01_0089",
        section_number="G&SR 1.10.9",
        title="Safety Protocol Compliance Clause 1-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0090": GSRSafetyRule(
        rule_id="GSR_SEC01_0090",
        section_number="G&SR 1.11.1",
        title="Safety Protocol Compliance Clause 1-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0091": GSRSafetyRule(
        rule_id="GSR_SEC01_0091",
        section_number="G&SR 1.12.2",
        title="Safety Protocol Compliance Clause 1-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0092": GSRSafetyRule(
        rule_id="GSR_SEC01_0092",
        section_number="G&SR 1.13.3",
        title="Safety Protocol Compliance Clause 1-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0093": GSRSafetyRule(
        rule_id="GSR_SEC01_0093",
        section_number="G&SR 1.14.4",
        title="Safety Protocol Compliance Clause 1-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0094": GSRSafetyRule(
        rule_id="GSR_SEC01_0094",
        section_number="G&SR 1.15.5",
        title="Safety Protocol Compliance Clause 1-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0095": GSRSafetyRule(
        rule_id="GSR_SEC01_0095",
        section_number="G&SR 1.16.6",
        title="Safety Protocol Compliance Clause 1-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0096": GSRSafetyRule(
        rule_id="GSR_SEC01_0096",
        section_number="G&SR 1.17.7",
        title="Safety Protocol Compliance Clause 1-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0097": GSRSafetyRule(
        rule_id="GSR_SEC01_0097",
        section_number="G&SR 1.18.8",
        title="Safety Protocol Compliance Clause 1-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0098": GSRSafetyRule(
        rule_id="GSR_SEC01_0098",
        section_number="G&SR 1.19.9",
        title="Safety Protocol Compliance Clause 1-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0099": GSRSafetyRule(
        rule_id="GSR_SEC01_0099",
        section_number="G&SR 1.20.1",
        title="Safety Protocol Compliance Clause 1-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0100": GSRSafetyRule(
        rule_id="GSR_SEC01_0100",
        section_number="G&SR 1.1.2",
        title="Safety Protocol Compliance Clause 1-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0101": GSRSafetyRule(
        rule_id="GSR_SEC01_0101",
        section_number="G&SR 1.2.3",
        title="Safety Protocol Compliance Clause 1-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0102": GSRSafetyRule(
        rule_id="GSR_SEC01_0102",
        section_number="G&SR 1.3.4",
        title="Safety Protocol Compliance Clause 1-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0103": GSRSafetyRule(
        rule_id="GSR_SEC01_0103",
        section_number="G&SR 1.4.5",
        title="Safety Protocol Compliance Clause 1-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0104": GSRSafetyRule(
        rule_id="GSR_SEC01_0104",
        section_number="G&SR 1.5.6",
        title="Safety Protocol Compliance Clause 1-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0105": GSRSafetyRule(
        rule_id="GSR_SEC01_0105",
        section_number="G&SR 1.6.7",
        title="Safety Protocol Compliance Clause 1-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0106": GSRSafetyRule(
        rule_id="GSR_SEC01_0106",
        section_number="G&SR 1.7.8",
        title="Safety Protocol Compliance Clause 1-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0107": GSRSafetyRule(
        rule_id="GSR_SEC01_0107",
        section_number="G&SR 1.8.9",
        title="Safety Protocol Compliance Clause 1-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0108": GSRSafetyRule(
        rule_id="GSR_SEC01_0108",
        section_number="G&SR 1.9.1",
        title="Safety Protocol Compliance Clause 1-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0109": GSRSafetyRule(
        rule_id="GSR_SEC01_0109",
        section_number="G&SR 1.10.2",
        title="Safety Protocol Compliance Clause 1-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0110": GSRSafetyRule(
        rule_id="GSR_SEC01_0110",
        section_number="G&SR 1.11.3",
        title="Safety Protocol Compliance Clause 1-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0111": GSRSafetyRule(
        rule_id="GSR_SEC01_0111",
        section_number="G&SR 1.12.4",
        title="Safety Protocol Compliance Clause 1-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0112": GSRSafetyRule(
        rule_id="GSR_SEC01_0112",
        section_number="G&SR 1.13.5",
        title="Safety Protocol Compliance Clause 1-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0113": GSRSafetyRule(
        rule_id="GSR_SEC01_0113",
        section_number="G&SR 1.14.6",
        title="Safety Protocol Compliance Clause 1-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0114": GSRSafetyRule(
        rule_id="GSR_SEC01_0114",
        section_number="G&SR 1.15.7",
        title="Safety Protocol Compliance Clause 1-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0115": GSRSafetyRule(
        rule_id="GSR_SEC01_0115",
        section_number="G&SR 1.16.8",
        title="Safety Protocol Compliance Clause 1-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0116": GSRSafetyRule(
        rule_id="GSR_SEC01_0116",
        section_number="G&SR 1.17.9",
        title="Safety Protocol Compliance Clause 1-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0117": GSRSafetyRule(
        rule_id="GSR_SEC01_0117",
        section_number="G&SR 1.18.1",
        title="Safety Protocol Compliance Clause 1-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0118": GSRSafetyRule(
        rule_id="GSR_SEC01_0118",
        section_number="G&SR 1.19.2",
        title="Safety Protocol Compliance Clause 1-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0119": GSRSafetyRule(
        rule_id="GSR_SEC01_0119",
        section_number="G&SR 1.20.3",
        title="Safety Protocol Compliance Clause 1-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0120": GSRSafetyRule(
        rule_id="GSR_SEC01_0120",
        section_number="G&SR 1.1.4",
        title="Safety Protocol Compliance Clause 1-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0121": GSRSafetyRule(
        rule_id="GSR_SEC01_0121",
        section_number="G&SR 1.2.5",
        title="Safety Protocol Compliance Clause 1-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0122": GSRSafetyRule(
        rule_id="GSR_SEC01_0122",
        section_number="G&SR 1.3.6",
        title="Safety Protocol Compliance Clause 1-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0123": GSRSafetyRule(
        rule_id="GSR_SEC01_0123",
        section_number="G&SR 1.4.7",
        title="Safety Protocol Compliance Clause 1-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0124": GSRSafetyRule(
        rule_id="GSR_SEC01_0124",
        section_number="G&SR 1.5.8",
        title="Safety Protocol Compliance Clause 1-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0125": GSRSafetyRule(
        rule_id="GSR_SEC01_0125",
        section_number="G&SR 1.6.9",
        title="Safety Protocol Compliance Clause 1-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0126": GSRSafetyRule(
        rule_id="GSR_SEC01_0126",
        section_number="G&SR 1.7.1",
        title="Safety Protocol Compliance Clause 1-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0127": GSRSafetyRule(
        rule_id="GSR_SEC01_0127",
        section_number="G&SR 1.8.2",
        title="Safety Protocol Compliance Clause 1-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0128": GSRSafetyRule(
        rule_id="GSR_SEC01_0128",
        section_number="G&SR 1.9.3",
        title="Safety Protocol Compliance Clause 1-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0129": GSRSafetyRule(
        rule_id="GSR_SEC01_0129",
        section_number="G&SR 1.10.4",
        title="Safety Protocol Compliance Clause 1-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0130": GSRSafetyRule(
        rule_id="GSR_SEC01_0130",
        section_number="G&SR 1.11.5",
        title="Safety Protocol Compliance Clause 1-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0131": GSRSafetyRule(
        rule_id="GSR_SEC01_0131",
        section_number="G&SR 1.12.6",
        title="Safety Protocol Compliance Clause 1-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0132": GSRSafetyRule(
        rule_id="GSR_SEC01_0132",
        section_number="G&SR 1.13.7",
        title="Safety Protocol Compliance Clause 1-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0133": GSRSafetyRule(
        rule_id="GSR_SEC01_0133",
        section_number="G&SR 1.14.8",
        title="Safety Protocol Compliance Clause 1-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0134": GSRSafetyRule(
        rule_id="GSR_SEC01_0134",
        section_number="G&SR 1.15.9",
        title="Safety Protocol Compliance Clause 1-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0135": GSRSafetyRule(
        rule_id="GSR_SEC01_0135",
        section_number="G&SR 1.16.1",
        title="Safety Protocol Compliance Clause 1-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0136": GSRSafetyRule(
        rule_id="GSR_SEC01_0136",
        section_number="G&SR 1.17.2",
        title="Safety Protocol Compliance Clause 1-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0137": GSRSafetyRule(
        rule_id="GSR_SEC01_0137",
        section_number="G&SR 1.18.3",
        title="Safety Protocol Compliance Clause 1-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0138": GSRSafetyRule(
        rule_id="GSR_SEC01_0138",
        section_number="G&SR 1.19.4",
        title="Safety Protocol Compliance Clause 1-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0139": GSRSafetyRule(
        rule_id="GSR_SEC01_0139",
        section_number="G&SR 1.20.5",
        title="Safety Protocol Compliance Clause 1-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0140": GSRSafetyRule(
        rule_id="GSR_SEC01_0140",
        section_number="G&SR 1.1.6",
        title="Safety Protocol Compliance Clause 1-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0141": GSRSafetyRule(
        rule_id="GSR_SEC01_0141",
        section_number="G&SR 1.2.7",
        title="Safety Protocol Compliance Clause 1-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0142": GSRSafetyRule(
        rule_id="GSR_SEC01_0142",
        section_number="G&SR 1.3.8",
        title="Safety Protocol Compliance Clause 1-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0143": GSRSafetyRule(
        rule_id="GSR_SEC01_0143",
        section_number="G&SR 1.4.9",
        title="Safety Protocol Compliance Clause 1-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0144": GSRSafetyRule(
        rule_id="GSR_SEC01_0144",
        section_number="G&SR 1.5.1",
        title="Safety Protocol Compliance Clause 1-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0145": GSRSafetyRule(
        rule_id="GSR_SEC01_0145",
        section_number="G&SR 1.6.2",
        title="Safety Protocol Compliance Clause 1-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0146": GSRSafetyRule(
        rule_id="GSR_SEC01_0146",
        section_number="G&SR 1.7.3",
        title="Safety Protocol Compliance Clause 1-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0147": GSRSafetyRule(
        rule_id="GSR_SEC01_0147",
        section_number="G&SR 1.8.4",
        title="Safety Protocol Compliance Clause 1-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0148": GSRSafetyRule(
        rule_id="GSR_SEC01_0148",
        section_number="G&SR 1.9.5",
        title="Safety Protocol Compliance Clause 1-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0149": GSRSafetyRule(
        rule_id="GSR_SEC01_0149",
        section_number="G&SR 1.10.6",
        title="Safety Protocol Compliance Clause 1-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0150": GSRSafetyRule(
        rule_id="GSR_SEC01_0150",
        section_number="G&SR 1.11.7",
        title="Safety Protocol Compliance Clause 1-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0151": GSRSafetyRule(
        rule_id="GSR_SEC01_0151",
        section_number="G&SR 1.12.8",
        title="Safety Protocol Compliance Clause 1-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0152": GSRSafetyRule(
        rule_id="GSR_SEC01_0152",
        section_number="G&SR 1.13.9",
        title="Safety Protocol Compliance Clause 1-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0153": GSRSafetyRule(
        rule_id="GSR_SEC01_0153",
        section_number="G&SR 1.14.1",
        title="Safety Protocol Compliance Clause 1-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0154": GSRSafetyRule(
        rule_id="GSR_SEC01_0154",
        section_number="G&SR 1.15.2",
        title="Safety Protocol Compliance Clause 1-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0155": GSRSafetyRule(
        rule_id="GSR_SEC01_0155",
        section_number="G&SR 1.16.3",
        title="Safety Protocol Compliance Clause 1-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0156": GSRSafetyRule(
        rule_id="GSR_SEC01_0156",
        section_number="G&SR 1.17.4",
        title="Safety Protocol Compliance Clause 1-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0157": GSRSafetyRule(
        rule_id="GSR_SEC01_0157",
        section_number="G&SR 1.18.5",
        title="Safety Protocol Compliance Clause 1-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0158": GSRSafetyRule(
        rule_id="GSR_SEC01_0158",
        section_number="G&SR 1.19.6",
        title="Safety Protocol Compliance Clause 1-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0159": GSRSafetyRule(
        rule_id="GSR_SEC01_0159",
        section_number="G&SR 1.20.7",
        title="Safety Protocol Compliance Clause 1-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0160": GSRSafetyRule(
        rule_id="GSR_SEC01_0160",
        section_number="G&SR 1.1.8",
        title="Safety Protocol Compliance Clause 1-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0161": GSRSafetyRule(
        rule_id="GSR_SEC01_0161",
        section_number="G&SR 1.2.9",
        title="Safety Protocol Compliance Clause 1-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0162": GSRSafetyRule(
        rule_id="GSR_SEC01_0162",
        section_number="G&SR 1.3.1",
        title="Safety Protocol Compliance Clause 1-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0163": GSRSafetyRule(
        rule_id="GSR_SEC01_0163",
        section_number="G&SR 1.4.2",
        title="Safety Protocol Compliance Clause 1-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0164": GSRSafetyRule(
        rule_id="GSR_SEC01_0164",
        section_number="G&SR 1.5.3",
        title="Safety Protocol Compliance Clause 1-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0165": GSRSafetyRule(
        rule_id="GSR_SEC01_0165",
        section_number="G&SR 1.6.4",
        title="Safety Protocol Compliance Clause 1-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0166": GSRSafetyRule(
        rule_id="GSR_SEC01_0166",
        section_number="G&SR 1.7.5",
        title="Safety Protocol Compliance Clause 1-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0167": GSRSafetyRule(
        rule_id="GSR_SEC01_0167",
        section_number="G&SR 1.8.6",
        title="Safety Protocol Compliance Clause 1-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0168": GSRSafetyRule(
        rule_id="GSR_SEC01_0168",
        section_number="G&SR 1.9.7",
        title="Safety Protocol Compliance Clause 1-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0169": GSRSafetyRule(
        rule_id="GSR_SEC01_0169",
        section_number="G&SR 1.10.8",
        title="Safety Protocol Compliance Clause 1-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0170": GSRSafetyRule(
        rule_id="GSR_SEC01_0170",
        section_number="G&SR 1.11.9",
        title="Safety Protocol Compliance Clause 1-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0171": GSRSafetyRule(
        rule_id="GSR_SEC01_0171",
        section_number="G&SR 1.12.1",
        title="Safety Protocol Compliance Clause 1-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0172": GSRSafetyRule(
        rule_id="GSR_SEC01_0172",
        section_number="G&SR 1.13.2",
        title="Safety Protocol Compliance Clause 1-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0173": GSRSafetyRule(
        rule_id="GSR_SEC01_0173",
        section_number="G&SR 1.14.3",
        title="Safety Protocol Compliance Clause 1-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC01_0174": GSRSafetyRule(
        rule_id="GSR_SEC01_0174",
        section_number="G&SR 1.15.4",
        title="Safety Protocol Compliance Clause 1-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
