"""Indian Railways G&SR Regulatory Rulebook Section 023."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_023: Dict[str, GSRSafetyRule] = {
    "GSR_SEC23_0001": GSRSafetyRule(
        rule_id="GSR_SEC23_0001",
        section_number="G&SR 23.2.2",
        title="Safety Protocol Compliance Clause 23-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0002": GSRSafetyRule(
        rule_id="GSR_SEC23_0002",
        section_number="G&SR 23.3.3",
        title="Safety Protocol Compliance Clause 23-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0003": GSRSafetyRule(
        rule_id="GSR_SEC23_0003",
        section_number="G&SR 23.4.4",
        title="Safety Protocol Compliance Clause 23-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0004": GSRSafetyRule(
        rule_id="GSR_SEC23_0004",
        section_number="G&SR 23.5.5",
        title="Safety Protocol Compliance Clause 23-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0005": GSRSafetyRule(
        rule_id="GSR_SEC23_0005",
        section_number="G&SR 23.6.6",
        title="Safety Protocol Compliance Clause 23-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0006": GSRSafetyRule(
        rule_id="GSR_SEC23_0006",
        section_number="G&SR 23.7.7",
        title="Safety Protocol Compliance Clause 23-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0007": GSRSafetyRule(
        rule_id="GSR_SEC23_0007",
        section_number="G&SR 23.8.8",
        title="Safety Protocol Compliance Clause 23-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0008": GSRSafetyRule(
        rule_id="GSR_SEC23_0008",
        section_number="G&SR 23.9.9",
        title="Safety Protocol Compliance Clause 23-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0009": GSRSafetyRule(
        rule_id="GSR_SEC23_0009",
        section_number="G&SR 23.10.1",
        title="Safety Protocol Compliance Clause 23-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0010": GSRSafetyRule(
        rule_id="GSR_SEC23_0010",
        section_number="G&SR 23.11.2",
        title="Safety Protocol Compliance Clause 23-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0011": GSRSafetyRule(
        rule_id="GSR_SEC23_0011",
        section_number="G&SR 23.12.3",
        title="Safety Protocol Compliance Clause 23-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0012": GSRSafetyRule(
        rule_id="GSR_SEC23_0012",
        section_number="G&SR 23.13.4",
        title="Safety Protocol Compliance Clause 23-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0013": GSRSafetyRule(
        rule_id="GSR_SEC23_0013",
        section_number="G&SR 23.14.5",
        title="Safety Protocol Compliance Clause 23-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0014": GSRSafetyRule(
        rule_id="GSR_SEC23_0014",
        section_number="G&SR 23.15.6",
        title="Safety Protocol Compliance Clause 23-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0015": GSRSafetyRule(
        rule_id="GSR_SEC23_0015",
        section_number="G&SR 23.16.7",
        title="Safety Protocol Compliance Clause 23-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0016": GSRSafetyRule(
        rule_id="GSR_SEC23_0016",
        section_number="G&SR 23.17.8",
        title="Safety Protocol Compliance Clause 23-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0017": GSRSafetyRule(
        rule_id="GSR_SEC23_0017",
        section_number="G&SR 23.18.9",
        title="Safety Protocol Compliance Clause 23-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0018": GSRSafetyRule(
        rule_id="GSR_SEC23_0018",
        section_number="G&SR 23.19.1",
        title="Safety Protocol Compliance Clause 23-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0019": GSRSafetyRule(
        rule_id="GSR_SEC23_0019",
        section_number="G&SR 23.20.2",
        title="Safety Protocol Compliance Clause 23-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0020": GSRSafetyRule(
        rule_id="GSR_SEC23_0020",
        section_number="G&SR 23.1.3",
        title="Safety Protocol Compliance Clause 23-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0021": GSRSafetyRule(
        rule_id="GSR_SEC23_0021",
        section_number="G&SR 23.2.4",
        title="Safety Protocol Compliance Clause 23-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0022": GSRSafetyRule(
        rule_id="GSR_SEC23_0022",
        section_number="G&SR 23.3.5",
        title="Safety Protocol Compliance Clause 23-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0023": GSRSafetyRule(
        rule_id="GSR_SEC23_0023",
        section_number="G&SR 23.4.6",
        title="Safety Protocol Compliance Clause 23-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0024": GSRSafetyRule(
        rule_id="GSR_SEC23_0024",
        section_number="G&SR 23.5.7",
        title="Safety Protocol Compliance Clause 23-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0025": GSRSafetyRule(
        rule_id="GSR_SEC23_0025",
        section_number="G&SR 23.6.8",
        title="Safety Protocol Compliance Clause 23-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0026": GSRSafetyRule(
        rule_id="GSR_SEC23_0026",
        section_number="G&SR 23.7.9",
        title="Safety Protocol Compliance Clause 23-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0027": GSRSafetyRule(
        rule_id="GSR_SEC23_0027",
        section_number="G&SR 23.8.1",
        title="Safety Protocol Compliance Clause 23-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0028": GSRSafetyRule(
        rule_id="GSR_SEC23_0028",
        section_number="G&SR 23.9.2",
        title="Safety Protocol Compliance Clause 23-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0029": GSRSafetyRule(
        rule_id="GSR_SEC23_0029",
        section_number="G&SR 23.10.3",
        title="Safety Protocol Compliance Clause 23-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0030": GSRSafetyRule(
        rule_id="GSR_SEC23_0030",
        section_number="G&SR 23.11.4",
        title="Safety Protocol Compliance Clause 23-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0031": GSRSafetyRule(
        rule_id="GSR_SEC23_0031",
        section_number="G&SR 23.12.5",
        title="Safety Protocol Compliance Clause 23-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0032": GSRSafetyRule(
        rule_id="GSR_SEC23_0032",
        section_number="G&SR 23.13.6",
        title="Safety Protocol Compliance Clause 23-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0033": GSRSafetyRule(
        rule_id="GSR_SEC23_0033",
        section_number="G&SR 23.14.7",
        title="Safety Protocol Compliance Clause 23-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0034": GSRSafetyRule(
        rule_id="GSR_SEC23_0034",
        section_number="G&SR 23.15.8",
        title="Safety Protocol Compliance Clause 23-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0035": GSRSafetyRule(
        rule_id="GSR_SEC23_0035",
        section_number="G&SR 23.16.9",
        title="Safety Protocol Compliance Clause 23-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0036": GSRSafetyRule(
        rule_id="GSR_SEC23_0036",
        section_number="G&SR 23.17.1",
        title="Safety Protocol Compliance Clause 23-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0037": GSRSafetyRule(
        rule_id="GSR_SEC23_0037",
        section_number="G&SR 23.18.2",
        title="Safety Protocol Compliance Clause 23-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0038": GSRSafetyRule(
        rule_id="GSR_SEC23_0038",
        section_number="G&SR 23.19.3",
        title="Safety Protocol Compliance Clause 23-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0039": GSRSafetyRule(
        rule_id="GSR_SEC23_0039",
        section_number="G&SR 23.20.4",
        title="Safety Protocol Compliance Clause 23-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0040": GSRSafetyRule(
        rule_id="GSR_SEC23_0040",
        section_number="G&SR 23.1.5",
        title="Safety Protocol Compliance Clause 23-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0041": GSRSafetyRule(
        rule_id="GSR_SEC23_0041",
        section_number="G&SR 23.2.6",
        title="Safety Protocol Compliance Clause 23-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0042": GSRSafetyRule(
        rule_id="GSR_SEC23_0042",
        section_number="G&SR 23.3.7",
        title="Safety Protocol Compliance Clause 23-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0043": GSRSafetyRule(
        rule_id="GSR_SEC23_0043",
        section_number="G&SR 23.4.8",
        title="Safety Protocol Compliance Clause 23-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0044": GSRSafetyRule(
        rule_id="GSR_SEC23_0044",
        section_number="G&SR 23.5.9",
        title="Safety Protocol Compliance Clause 23-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0045": GSRSafetyRule(
        rule_id="GSR_SEC23_0045",
        section_number="G&SR 23.6.1",
        title="Safety Protocol Compliance Clause 23-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0046": GSRSafetyRule(
        rule_id="GSR_SEC23_0046",
        section_number="G&SR 23.7.2",
        title="Safety Protocol Compliance Clause 23-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0047": GSRSafetyRule(
        rule_id="GSR_SEC23_0047",
        section_number="G&SR 23.8.3",
        title="Safety Protocol Compliance Clause 23-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0048": GSRSafetyRule(
        rule_id="GSR_SEC23_0048",
        section_number="G&SR 23.9.4",
        title="Safety Protocol Compliance Clause 23-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0049": GSRSafetyRule(
        rule_id="GSR_SEC23_0049",
        section_number="G&SR 23.10.5",
        title="Safety Protocol Compliance Clause 23-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0050": GSRSafetyRule(
        rule_id="GSR_SEC23_0050",
        section_number="G&SR 23.11.6",
        title="Safety Protocol Compliance Clause 23-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0051": GSRSafetyRule(
        rule_id="GSR_SEC23_0051",
        section_number="G&SR 23.12.7",
        title="Safety Protocol Compliance Clause 23-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0052": GSRSafetyRule(
        rule_id="GSR_SEC23_0052",
        section_number="G&SR 23.13.8",
        title="Safety Protocol Compliance Clause 23-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0053": GSRSafetyRule(
        rule_id="GSR_SEC23_0053",
        section_number="G&SR 23.14.9",
        title="Safety Protocol Compliance Clause 23-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0054": GSRSafetyRule(
        rule_id="GSR_SEC23_0054",
        section_number="G&SR 23.15.1",
        title="Safety Protocol Compliance Clause 23-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0055": GSRSafetyRule(
        rule_id="GSR_SEC23_0055",
        section_number="G&SR 23.16.2",
        title="Safety Protocol Compliance Clause 23-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0056": GSRSafetyRule(
        rule_id="GSR_SEC23_0056",
        section_number="G&SR 23.17.3",
        title="Safety Protocol Compliance Clause 23-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0057": GSRSafetyRule(
        rule_id="GSR_SEC23_0057",
        section_number="G&SR 23.18.4",
        title="Safety Protocol Compliance Clause 23-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0058": GSRSafetyRule(
        rule_id="GSR_SEC23_0058",
        section_number="G&SR 23.19.5",
        title="Safety Protocol Compliance Clause 23-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0059": GSRSafetyRule(
        rule_id="GSR_SEC23_0059",
        section_number="G&SR 23.20.6",
        title="Safety Protocol Compliance Clause 23-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0060": GSRSafetyRule(
        rule_id="GSR_SEC23_0060",
        section_number="G&SR 23.1.7",
        title="Safety Protocol Compliance Clause 23-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0061": GSRSafetyRule(
        rule_id="GSR_SEC23_0061",
        section_number="G&SR 23.2.8",
        title="Safety Protocol Compliance Clause 23-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0062": GSRSafetyRule(
        rule_id="GSR_SEC23_0062",
        section_number="G&SR 23.3.9",
        title="Safety Protocol Compliance Clause 23-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0063": GSRSafetyRule(
        rule_id="GSR_SEC23_0063",
        section_number="G&SR 23.4.1",
        title="Safety Protocol Compliance Clause 23-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0064": GSRSafetyRule(
        rule_id="GSR_SEC23_0064",
        section_number="G&SR 23.5.2",
        title="Safety Protocol Compliance Clause 23-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0065": GSRSafetyRule(
        rule_id="GSR_SEC23_0065",
        section_number="G&SR 23.6.3",
        title="Safety Protocol Compliance Clause 23-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0066": GSRSafetyRule(
        rule_id="GSR_SEC23_0066",
        section_number="G&SR 23.7.4",
        title="Safety Protocol Compliance Clause 23-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0067": GSRSafetyRule(
        rule_id="GSR_SEC23_0067",
        section_number="G&SR 23.8.5",
        title="Safety Protocol Compliance Clause 23-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0068": GSRSafetyRule(
        rule_id="GSR_SEC23_0068",
        section_number="G&SR 23.9.6",
        title="Safety Protocol Compliance Clause 23-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0069": GSRSafetyRule(
        rule_id="GSR_SEC23_0069",
        section_number="G&SR 23.10.7",
        title="Safety Protocol Compliance Clause 23-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0070": GSRSafetyRule(
        rule_id="GSR_SEC23_0070",
        section_number="G&SR 23.11.8",
        title="Safety Protocol Compliance Clause 23-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0071": GSRSafetyRule(
        rule_id="GSR_SEC23_0071",
        section_number="G&SR 23.12.9",
        title="Safety Protocol Compliance Clause 23-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0072": GSRSafetyRule(
        rule_id="GSR_SEC23_0072",
        section_number="G&SR 23.13.1",
        title="Safety Protocol Compliance Clause 23-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0073": GSRSafetyRule(
        rule_id="GSR_SEC23_0073",
        section_number="G&SR 23.14.2",
        title="Safety Protocol Compliance Clause 23-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0074": GSRSafetyRule(
        rule_id="GSR_SEC23_0074",
        section_number="G&SR 23.15.3",
        title="Safety Protocol Compliance Clause 23-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0075": GSRSafetyRule(
        rule_id="GSR_SEC23_0075",
        section_number="G&SR 23.16.4",
        title="Safety Protocol Compliance Clause 23-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0076": GSRSafetyRule(
        rule_id="GSR_SEC23_0076",
        section_number="G&SR 23.17.5",
        title="Safety Protocol Compliance Clause 23-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0077": GSRSafetyRule(
        rule_id="GSR_SEC23_0077",
        section_number="G&SR 23.18.6",
        title="Safety Protocol Compliance Clause 23-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0078": GSRSafetyRule(
        rule_id="GSR_SEC23_0078",
        section_number="G&SR 23.19.7",
        title="Safety Protocol Compliance Clause 23-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0079": GSRSafetyRule(
        rule_id="GSR_SEC23_0079",
        section_number="G&SR 23.20.8",
        title="Safety Protocol Compliance Clause 23-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0080": GSRSafetyRule(
        rule_id="GSR_SEC23_0080",
        section_number="G&SR 23.1.9",
        title="Safety Protocol Compliance Clause 23-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0081": GSRSafetyRule(
        rule_id="GSR_SEC23_0081",
        section_number="G&SR 23.2.1",
        title="Safety Protocol Compliance Clause 23-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0082": GSRSafetyRule(
        rule_id="GSR_SEC23_0082",
        section_number="G&SR 23.3.2",
        title="Safety Protocol Compliance Clause 23-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0083": GSRSafetyRule(
        rule_id="GSR_SEC23_0083",
        section_number="G&SR 23.4.3",
        title="Safety Protocol Compliance Clause 23-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0084": GSRSafetyRule(
        rule_id="GSR_SEC23_0084",
        section_number="G&SR 23.5.4",
        title="Safety Protocol Compliance Clause 23-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0085": GSRSafetyRule(
        rule_id="GSR_SEC23_0085",
        section_number="G&SR 23.6.5",
        title="Safety Protocol Compliance Clause 23-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0086": GSRSafetyRule(
        rule_id="GSR_SEC23_0086",
        section_number="G&SR 23.7.6",
        title="Safety Protocol Compliance Clause 23-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0087": GSRSafetyRule(
        rule_id="GSR_SEC23_0087",
        section_number="G&SR 23.8.7",
        title="Safety Protocol Compliance Clause 23-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0088": GSRSafetyRule(
        rule_id="GSR_SEC23_0088",
        section_number="G&SR 23.9.8",
        title="Safety Protocol Compliance Clause 23-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0089": GSRSafetyRule(
        rule_id="GSR_SEC23_0089",
        section_number="G&SR 23.10.9",
        title="Safety Protocol Compliance Clause 23-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0090": GSRSafetyRule(
        rule_id="GSR_SEC23_0090",
        section_number="G&SR 23.11.1",
        title="Safety Protocol Compliance Clause 23-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0091": GSRSafetyRule(
        rule_id="GSR_SEC23_0091",
        section_number="G&SR 23.12.2",
        title="Safety Protocol Compliance Clause 23-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0092": GSRSafetyRule(
        rule_id="GSR_SEC23_0092",
        section_number="G&SR 23.13.3",
        title="Safety Protocol Compliance Clause 23-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0093": GSRSafetyRule(
        rule_id="GSR_SEC23_0093",
        section_number="G&SR 23.14.4",
        title="Safety Protocol Compliance Clause 23-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0094": GSRSafetyRule(
        rule_id="GSR_SEC23_0094",
        section_number="G&SR 23.15.5",
        title="Safety Protocol Compliance Clause 23-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0095": GSRSafetyRule(
        rule_id="GSR_SEC23_0095",
        section_number="G&SR 23.16.6",
        title="Safety Protocol Compliance Clause 23-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0096": GSRSafetyRule(
        rule_id="GSR_SEC23_0096",
        section_number="G&SR 23.17.7",
        title="Safety Protocol Compliance Clause 23-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0097": GSRSafetyRule(
        rule_id="GSR_SEC23_0097",
        section_number="G&SR 23.18.8",
        title="Safety Protocol Compliance Clause 23-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0098": GSRSafetyRule(
        rule_id="GSR_SEC23_0098",
        section_number="G&SR 23.19.9",
        title="Safety Protocol Compliance Clause 23-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0099": GSRSafetyRule(
        rule_id="GSR_SEC23_0099",
        section_number="G&SR 23.20.1",
        title="Safety Protocol Compliance Clause 23-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0100": GSRSafetyRule(
        rule_id="GSR_SEC23_0100",
        section_number="G&SR 23.1.2",
        title="Safety Protocol Compliance Clause 23-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0101": GSRSafetyRule(
        rule_id="GSR_SEC23_0101",
        section_number="G&SR 23.2.3",
        title="Safety Protocol Compliance Clause 23-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0102": GSRSafetyRule(
        rule_id="GSR_SEC23_0102",
        section_number="G&SR 23.3.4",
        title="Safety Protocol Compliance Clause 23-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0103": GSRSafetyRule(
        rule_id="GSR_SEC23_0103",
        section_number="G&SR 23.4.5",
        title="Safety Protocol Compliance Clause 23-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0104": GSRSafetyRule(
        rule_id="GSR_SEC23_0104",
        section_number="G&SR 23.5.6",
        title="Safety Protocol Compliance Clause 23-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0105": GSRSafetyRule(
        rule_id="GSR_SEC23_0105",
        section_number="G&SR 23.6.7",
        title="Safety Protocol Compliance Clause 23-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0106": GSRSafetyRule(
        rule_id="GSR_SEC23_0106",
        section_number="G&SR 23.7.8",
        title="Safety Protocol Compliance Clause 23-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0107": GSRSafetyRule(
        rule_id="GSR_SEC23_0107",
        section_number="G&SR 23.8.9",
        title="Safety Protocol Compliance Clause 23-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0108": GSRSafetyRule(
        rule_id="GSR_SEC23_0108",
        section_number="G&SR 23.9.1",
        title="Safety Protocol Compliance Clause 23-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0109": GSRSafetyRule(
        rule_id="GSR_SEC23_0109",
        section_number="G&SR 23.10.2",
        title="Safety Protocol Compliance Clause 23-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0110": GSRSafetyRule(
        rule_id="GSR_SEC23_0110",
        section_number="G&SR 23.11.3",
        title="Safety Protocol Compliance Clause 23-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0111": GSRSafetyRule(
        rule_id="GSR_SEC23_0111",
        section_number="G&SR 23.12.4",
        title="Safety Protocol Compliance Clause 23-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0112": GSRSafetyRule(
        rule_id="GSR_SEC23_0112",
        section_number="G&SR 23.13.5",
        title="Safety Protocol Compliance Clause 23-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0113": GSRSafetyRule(
        rule_id="GSR_SEC23_0113",
        section_number="G&SR 23.14.6",
        title="Safety Protocol Compliance Clause 23-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0114": GSRSafetyRule(
        rule_id="GSR_SEC23_0114",
        section_number="G&SR 23.15.7",
        title="Safety Protocol Compliance Clause 23-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0115": GSRSafetyRule(
        rule_id="GSR_SEC23_0115",
        section_number="G&SR 23.16.8",
        title="Safety Protocol Compliance Clause 23-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0116": GSRSafetyRule(
        rule_id="GSR_SEC23_0116",
        section_number="G&SR 23.17.9",
        title="Safety Protocol Compliance Clause 23-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0117": GSRSafetyRule(
        rule_id="GSR_SEC23_0117",
        section_number="G&SR 23.18.1",
        title="Safety Protocol Compliance Clause 23-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0118": GSRSafetyRule(
        rule_id="GSR_SEC23_0118",
        section_number="G&SR 23.19.2",
        title="Safety Protocol Compliance Clause 23-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0119": GSRSafetyRule(
        rule_id="GSR_SEC23_0119",
        section_number="G&SR 23.20.3",
        title="Safety Protocol Compliance Clause 23-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0120": GSRSafetyRule(
        rule_id="GSR_SEC23_0120",
        section_number="G&SR 23.1.4",
        title="Safety Protocol Compliance Clause 23-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0121": GSRSafetyRule(
        rule_id="GSR_SEC23_0121",
        section_number="G&SR 23.2.5",
        title="Safety Protocol Compliance Clause 23-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0122": GSRSafetyRule(
        rule_id="GSR_SEC23_0122",
        section_number="G&SR 23.3.6",
        title="Safety Protocol Compliance Clause 23-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0123": GSRSafetyRule(
        rule_id="GSR_SEC23_0123",
        section_number="G&SR 23.4.7",
        title="Safety Protocol Compliance Clause 23-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0124": GSRSafetyRule(
        rule_id="GSR_SEC23_0124",
        section_number="G&SR 23.5.8",
        title="Safety Protocol Compliance Clause 23-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0125": GSRSafetyRule(
        rule_id="GSR_SEC23_0125",
        section_number="G&SR 23.6.9",
        title="Safety Protocol Compliance Clause 23-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0126": GSRSafetyRule(
        rule_id="GSR_SEC23_0126",
        section_number="G&SR 23.7.1",
        title="Safety Protocol Compliance Clause 23-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0127": GSRSafetyRule(
        rule_id="GSR_SEC23_0127",
        section_number="G&SR 23.8.2",
        title="Safety Protocol Compliance Clause 23-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0128": GSRSafetyRule(
        rule_id="GSR_SEC23_0128",
        section_number="G&SR 23.9.3",
        title="Safety Protocol Compliance Clause 23-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0129": GSRSafetyRule(
        rule_id="GSR_SEC23_0129",
        section_number="G&SR 23.10.4",
        title="Safety Protocol Compliance Clause 23-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0130": GSRSafetyRule(
        rule_id="GSR_SEC23_0130",
        section_number="G&SR 23.11.5",
        title="Safety Protocol Compliance Clause 23-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0131": GSRSafetyRule(
        rule_id="GSR_SEC23_0131",
        section_number="G&SR 23.12.6",
        title="Safety Protocol Compliance Clause 23-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0132": GSRSafetyRule(
        rule_id="GSR_SEC23_0132",
        section_number="G&SR 23.13.7",
        title="Safety Protocol Compliance Clause 23-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0133": GSRSafetyRule(
        rule_id="GSR_SEC23_0133",
        section_number="G&SR 23.14.8",
        title="Safety Protocol Compliance Clause 23-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0134": GSRSafetyRule(
        rule_id="GSR_SEC23_0134",
        section_number="G&SR 23.15.9",
        title="Safety Protocol Compliance Clause 23-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0135": GSRSafetyRule(
        rule_id="GSR_SEC23_0135",
        section_number="G&SR 23.16.1",
        title="Safety Protocol Compliance Clause 23-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0136": GSRSafetyRule(
        rule_id="GSR_SEC23_0136",
        section_number="G&SR 23.17.2",
        title="Safety Protocol Compliance Clause 23-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0137": GSRSafetyRule(
        rule_id="GSR_SEC23_0137",
        section_number="G&SR 23.18.3",
        title="Safety Protocol Compliance Clause 23-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0138": GSRSafetyRule(
        rule_id="GSR_SEC23_0138",
        section_number="G&SR 23.19.4",
        title="Safety Protocol Compliance Clause 23-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0139": GSRSafetyRule(
        rule_id="GSR_SEC23_0139",
        section_number="G&SR 23.20.5",
        title="Safety Protocol Compliance Clause 23-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0140": GSRSafetyRule(
        rule_id="GSR_SEC23_0140",
        section_number="G&SR 23.1.6",
        title="Safety Protocol Compliance Clause 23-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0141": GSRSafetyRule(
        rule_id="GSR_SEC23_0141",
        section_number="G&SR 23.2.7",
        title="Safety Protocol Compliance Clause 23-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0142": GSRSafetyRule(
        rule_id="GSR_SEC23_0142",
        section_number="G&SR 23.3.8",
        title="Safety Protocol Compliance Clause 23-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0143": GSRSafetyRule(
        rule_id="GSR_SEC23_0143",
        section_number="G&SR 23.4.9",
        title="Safety Protocol Compliance Clause 23-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0144": GSRSafetyRule(
        rule_id="GSR_SEC23_0144",
        section_number="G&SR 23.5.1",
        title="Safety Protocol Compliance Clause 23-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0145": GSRSafetyRule(
        rule_id="GSR_SEC23_0145",
        section_number="G&SR 23.6.2",
        title="Safety Protocol Compliance Clause 23-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0146": GSRSafetyRule(
        rule_id="GSR_SEC23_0146",
        section_number="G&SR 23.7.3",
        title="Safety Protocol Compliance Clause 23-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0147": GSRSafetyRule(
        rule_id="GSR_SEC23_0147",
        section_number="G&SR 23.8.4",
        title="Safety Protocol Compliance Clause 23-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0148": GSRSafetyRule(
        rule_id="GSR_SEC23_0148",
        section_number="G&SR 23.9.5",
        title="Safety Protocol Compliance Clause 23-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0149": GSRSafetyRule(
        rule_id="GSR_SEC23_0149",
        section_number="G&SR 23.10.6",
        title="Safety Protocol Compliance Clause 23-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0150": GSRSafetyRule(
        rule_id="GSR_SEC23_0150",
        section_number="G&SR 23.11.7",
        title="Safety Protocol Compliance Clause 23-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0151": GSRSafetyRule(
        rule_id="GSR_SEC23_0151",
        section_number="G&SR 23.12.8",
        title="Safety Protocol Compliance Clause 23-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0152": GSRSafetyRule(
        rule_id="GSR_SEC23_0152",
        section_number="G&SR 23.13.9",
        title="Safety Protocol Compliance Clause 23-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0153": GSRSafetyRule(
        rule_id="GSR_SEC23_0153",
        section_number="G&SR 23.14.1",
        title="Safety Protocol Compliance Clause 23-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0154": GSRSafetyRule(
        rule_id="GSR_SEC23_0154",
        section_number="G&SR 23.15.2",
        title="Safety Protocol Compliance Clause 23-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0155": GSRSafetyRule(
        rule_id="GSR_SEC23_0155",
        section_number="G&SR 23.16.3",
        title="Safety Protocol Compliance Clause 23-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0156": GSRSafetyRule(
        rule_id="GSR_SEC23_0156",
        section_number="G&SR 23.17.4",
        title="Safety Protocol Compliance Clause 23-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0157": GSRSafetyRule(
        rule_id="GSR_SEC23_0157",
        section_number="G&SR 23.18.5",
        title="Safety Protocol Compliance Clause 23-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0158": GSRSafetyRule(
        rule_id="GSR_SEC23_0158",
        section_number="G&SR 23.19.6",
        title="Safety Protocol Compliance Clause 23-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0159": GSRSafetyRule(
        rule_id="GSR_SEC23_0159",
        section_number="G&SR 23.20.7",
        title="Safety Protocol Compliance Clause 23-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0160": GSRSafetyRule(
        rule_id="GSR_SEC23_0160",
        section_number="G&SR 23.1.8",
        title="Safety Protocol Compliance Clause 23-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0161": GSRSafetyRule(
        rule_id="GSR_SEC23_0161",
        section_number="G&SR 23.2.9",
        title="Safety Protocol Compliance Clause 23-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0162": GSRSafetyRule(
        rule_id="GSR_SEC23_0162",
        section_number="G&SR 23.3.1",
        title="Safety Protocol Compliance Clause 23-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0163": GSRSafetyRule(
        rule_id="GSR_SEC23_0163",
        section_number="G&SR 23.4.2",
        title="Safety Protocol Compliance Clause 23-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0164": GSRSafetyRule(
        rule_id="GSR_SEC23_0164",
        section_number="G&SR 23.5.3",
        title="Safety Protocol Compliance Clause 23-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0165": GSRSafetyRule(
        rule_id="GSR_SEC23_0165",
        section_number="G&SR 23.6.4",
        title="Safety Protocol Compliance Clause 23-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0166": GSRSafetyRule(
        rule_id="GSR_SEC23_0166",
        section_number="G&SR 23.7.5",
        title="Safety Protocol Compliance Clause 23-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0167": GSRSafetyRule(
        rule_id="GSR_SEC23_0167",
        section_number="G&SR 23.8.6",
        title="Safety Protocol Compliance Clause 23-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0168": GSRSafetyRule(
        rule_id="GSR_SEC23_0168",
        section_number="G&SR 23.9.7",
        title="Safety Protocol Compliance Clause 23-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0169": GSRSafetyRule(
        rule_id="GSR_SEC23_0169",
        section_number="G&SR 23.10.8",
        title="Safety Protocol Compliance Clause 23-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0170": GSRSafetyRule(
        rule_id="GSR_SEC23_0170",
        section_number="G&SR 23.11.9",
        title="Safety Protocol Compliance Clause 23-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0171": GSRSafetyRule(
        rule_id="GSR_SEC23_0171",
        section_number="G&SR 23.12.1",
        title="Safety Protocol Compliance Clause 23-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0172": GSRSafetyRule(
        rule_id="GSR_SEC23_0172",
        section_number="G&SR 23.13.2",
        title="Safety Protocol Compliance Clause 23-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0173": GSRSafetyRule(
        rule_id="GSR_SEC23_0173",
        section_number="G&SR 23.14.3",
        title="Safety Protocol Compliance Clause 23-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC23_0174": GSRSafetyRule(
        rule_id="GSR_SEC23_0174",
        section_number="G&SR 23.15.4",
        title="Safety Protocol Compliance Clause 23-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
