"""Indian Railways G&SR Regulatory Rulebook Section 002."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_002: Dict[str, GSRSafetyRule] = {
    "GSR_SEC02_0001": GSRSafetyRule(
        rule_id="GSR_SEC02_0001",
        section_number="G&SR 2.2.2",
        title="Safety Protocol Compliance Clause 2-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0002": GSRSafetyRule(
        rule_id="GSR_SEC02_0002",
        section_number="G&SR 2.3.3",
        title="Safety Protocol Compliance Clause 2-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0003": GSRSafetyRule(
        rule_id="GSR_SEC02_0003",
        section_number="G&SR 2.4.4",
        title="Safety Protocol Compliance Clause 2-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0004": GSRSafetyRule(
        rule_id="GSR_SEC02_0004",
        section_number="G&SR 2.5.5",
        title="Safety Protocol Compliance Clause 2-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0005": GSRSafetyRule(
        rule_id="GSR_SEC02_0005",
        section_number="G&SR 2.6.6",
        title="Safety Protocol Compliance Clause 2-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0006": GSRSafetyRule(
        rule_id="GSR_SEC02_0006",
        section_number="G&SR 2.7.7",
        title="Safety Protocol Compliance Clause 2-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0007": GSRSafetyRule(
        rule_id="GSR_SEC02_0007",
        section_number="G&SR 2.8.8",
        title="Safety Protocol Compliance Clause 2-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0008": GSRSafetyRule(
        rule_id="GSR_SEC02_0008",
        section_number="G&SR 2.9.9",
        title="Safety Protocol Compliance Clause 2-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0009": GSRSafetyRule(
        rule_id="GSR_SEC02_0009",
        section_number="G&SR 2.10.1",
        title="Safety Protocol Compliance Clause 2-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0010": GSRSafetyRule(
        rule_id="GSR_SEC02_0010",
        section_number="G&SR 2.11.2",
        title="Safety Protocol Compliance Clause 2-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0011": GSRSafetyRule(
        rule_id="GSR_SEC02_0011",
        section_number="G&SR 2.12.3",
        title="Safety Protocol Compliance Clause 2-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0012": GSRSafetyRule(
        rule_id="GSR_SEC02_0012",
        section_number="G&SR 2.13.4",
        title="Safety Protocol Compliance Clause 2-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0013": GSRSafetyRule(
        rule_id="GSR_SEC02_0013",
        section_number="G&SR 2.14.5",
        title="Safety Protocol Compliance Clause 2-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0014": GSRSafetyRule(
        rule_id="GSR_SEC02_0014",
        section_number="G&SR 2.15.6",
        title="Safety Protocol Compliance Clause 2-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0015": GSRSafetyRule(
        rule_id="GSR_SEC02_0015",
        section_number="G&SR 2.16.7",
        title="Safety Protocol Compliance Clause 2-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0016": GSRSafetyRule(
        rule_id="GSR_SEC02_0016",
        section_number="G&SR 2.17.8",
        title="Safety Protocol Compliance Clause 2-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0017": GSRSafetyRule(
        rule_id="GSR_SEC02_0017",
        section_number="G&SR 2.18.9",
        title="Safety Protocol Compliance Clause 2-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0018": GSRSafetyRule(
        rule_id="GSR_SEC02_0018",
        section_number="G&SR 2.19.1",
        title="Safety Protocol Compliance Clause 2-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0019": GSRSafetyRule(
        rule_id="GSR_SEC02_0019",
        section_number="G&SR 2.20.2",
        title="Safety Protocol Compliance Clause 2-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0020": GSRSafetyRule(
        rule_id="GSR_SEC02_0020",
        section_number="G&SR 2.1.3",
        title="Safety Protocol Compliance Clause 2-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0021": GSRSafetyRule(
        rule_id="GSR_SEC02_0021",
        section_number="G&SR 2.2.4",
        title="Safety Protocol Compliance Clause 2-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0022": GSRSafetyRule(
        rule_id="GSR_SEC02_0022",
        section_number="G&SR 2.3.5",
        title="Safety Protocol Compliance Clause 2-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0023": GSRSafetyRule(
        rule_id="GSR_SEC02_0023",
        section_number="G&SR 2.4.6",
        title="Safety Protocol Compliance Clause 2-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0024": GSRSafetyRule(
        rule_id="GSR_SEC02_0024",
        section_number="G&SR 2.5.7",
        title="Safety Protocol Compliance Clause 2-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0025": GSRSafetyRule(
        rule_id="GSR_SEC02_0025",
        section_number="G&SR 2.6.8",
        title="Safety Protocol Compliance Clause 2-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0026": GSRSafetyRule(
        rule_id="GSR_SEC02_0026",
        section_number="G&SR 2.7.9",
        title="Safety Protocol Compliance Clause 2-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0027": GSRSafetyRule(
        rule_id="GSR_SEC02_0027",
        section_number="G&SR 2.8.1",
        title="Safety Protocol Compliance Clause 2-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0028": GSRSafetyRule(
        rule_id="GSR_SEC02_0028",
        section_number="G&SR 2.9.2",
        title="Safety Protocol Compliance Clause 2-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0029": GSRSafetyRule(
        rule_id="GSR_SEC02_0029",
        section_number="G&SR 2.10.3",
        title="Safety Protocol Compliance Clause 2-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0030": GSRSafetyRule(
        rule_id="GSR_SEC02_0030",
        section_number="G&SR 2.11.4",
        title="Safety Protocol Compliance Clause 2-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0031": GSRSafetyRule(
        rule_id="GSR_SEC02_0031",
        section_number="G&SR 2.12.5",
        title="Safety Protocol Compliance Clause 2-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0032": GSRSafetyRule(
        rule_id="GSR_SEC02_0032",
        section_number="G&SR 2.13.6",
        title="Safety Protocol Compliance Clause 2-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0033": GSRSafetyRule(
        rule_id="GSR_SEC02_0033",
        section_number="G&SR 2.14.7",
        title="Safety Protocol Compliance Clause 2-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0034": GSRSafetyRule(
        rule_id="GSR_SEC02_0034",
        section_number="G&SR 2.15.8",
        title="Safety Protocol Compliance Clause 2-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0035": GSRSafetyRule(
        rule_id="GSR_SEC02_0035",
        section_number="G&SR 2.16.9",
        title="Safety Protocol Compliance Clause 2-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0036": GSRSafetyRule(
        rule_id="GSR_SEC02_0036",
        section_number="G&SR 2.17.1",
        title="Safety Protocol Compliance Clause 2-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0037": GSRSafetyRule(
        rule_id="GSR_SEC02_0037",
        section_number="G&SR 2.18.2",
        title="Safety Protocol Compliance Clause 2-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0038": GSRSafetyRule(
        rule_id="GSR_SEC02_0038",
        section_number="G&SR 2.19.3",
        title="Safety Protocol Compliance Clause 2-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0039": GSRSafetyRule(
        rule_id="GSR_SEC02_0039",
        section_number="G&SR 2.20.4",
        title="Safety Protocol Compliance Clause 2-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0040": GSRSafetyRule(
        rule_id="GSR_SEC02_0040",
        section_number="G&SR 2.1.5",
        title="Safety Protocol Compliance Clause 2-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0041": GSRSafetyRule(
        rule_id="GSR_SEC02_0041",
        section_number="G&SR 2.2.6",
        title="Safety Protocol Compliance Clause 2-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0042": GSRSafetyRule(
        rule_id="GSR_SEC02_0042",
        section_number="G&SR 2.3.7",
        title="Safety Protocol Compliance Clause 2-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0043": GSRSafetyRule(
        rule_id="GSR_SEC02_0043",
        section_number="G&SR 2.4.8",
        title="Safety Protocol Compliance Clause 2-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0044": GSRSafetyRule(
        rule_id="GSR_SEC02_0044",
        section_number="G&SR 2.5.9",
        title="Safety Protocol Compliance Clause 2-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0045": GSRSafetyRule(
        rule_id="GSR_SEC02_0045",
        section_number="G&SR 2.6.1",
        title="Safety Protocol Compliance Clause 2-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0046": GSRSafetyRule(
        rule_id="GSR_SEC02_0046",
        section_number="G&SR 2.7.2",
        title="Safety Protocol Compliance Clause 2-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0047": GSRSafetyRule(
        rule_id="GSR_SEC02_0047",
        section_number="G&SR 2.8.3",
        title="Safety Protocol Compliance Clause 2-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0048": GSRSafetyRule(
        rule_id="GSR_SEC02_0048",
        section_number="G&SR 2.9.4",
        title="Safety Protocol Compliance Clause 2-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0049": GSRSafetyRule(
        rule_id="GSR_SEC02_0049",
        section_number="G&SR 2.10.5",
        title="Safety Protocol Compliance Clause 2-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0050": GSRSafetyRule(
        rule_id="GSR_SEC02_0050",
        section_number="G&SR 2.11.6",
        title="Safety Protocol Compliance Clause 2-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0051": GSRSafetyRule(
        rule_id="GSR_SEC02_0051",
        section_number="G&SR 2.12.7",
        title="Safety Protocol Compliance Clause 2-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0052": GSRSafetyRule(
        rule_id="GSR_SEC02_0052",
        section_number="G&SR 2.13.8",
        title="Safety Protocol Compliance Clause 2-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0053": GSRSafetyRule(
        rule_id="GSR_SEC02_0053",
        section_number="G&SR 2.14.9",
        title="Safety Protocol Compliance Clause 2-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0054": GSRSafetyRule(
        rule_id="GSR_SEC02_0054",
        section_number="G&SR 2.15.1",
        title="Safety Protocol Compliance Clause 2-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0055": GSRSafetyRule(
        rule_id="GSR_SEC02_0055",
        section_number="G&SR 2.16.2",
        title="Safety Protocol Compliance Clause 2-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0056": GSRSafetyRule(
        rule_id="GSR_SEC02_0056",
        section_number="G&SR 2.17.3",
        title="Safety Protocol Compliance Clause 2-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0057": GSRSafetyRule(
        rule_id="GSR_SEC02_0057",
        section_number="G&SR 2.18.4",
        title="Safety Protocol Compliance Clause 2-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0058": GSRSafetyRule(
        rule_id="GSR_SEC02_0058",
        section_number="G&SR 2.19.5",
        title="Safety Protocol Compliance Clause 2-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0059": GSRSafetyRule(
        rule_id="GSR_SEC02_0059",
        section_number="G&SR 2.20.6",
        title="Safety Protocol Compliance Clause 2-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0060": GSRSafetyRule(
        rule_id="GSR_SEC02_0060",
        section_number="G&SR 2.1.7",
        title="Safety Protocol Compliance Clause 2-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0061": GSRSafetyRule(
        rule_id="GSR_SEC02_0061",
        section_number="G&SR 2.2.8",
        title="Safety Protocol Compliance Clause 2-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0062": GSRSafetyRule(
        rule_id="GSR_SEC02_0062",
        section_number="G&SR 2.3.9",
        title="Safety Protocol Compliance Clause 2-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0063": GSRSafetyRule(
        rule_id="GSR_SEC02_0063",
        section_number="G&SR 2.4.1",
        title="Safety Protocol Compliance Clause 2-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0064": GSRSafetyRule(
        rule_id="GSR_SEC02_0064",
        section_number="G&SR 2.5.2",
        title="Safety Protocol Compliance Clause 2-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0065": GSRSafetyRule(
        rule_id="GSR_SEC02_0065",
        section_number="G&SR 2.6.3",
        title="Safety Protocol Compliance Clause 2-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0066": GSRSafetyRule(
        rule_id="GSR_SEC02_0066",
        section_number="G&SR 2.7.4",
        title="Safety Protocol Compliance Clause 2-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0067": GSRSafetyRule(
        rule_id="GSR_SEC02_0067",
        section_number="G&SR 2.8.5",
        title="Safety Protocol Compliance Clause 2-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0068": GSRSafetyRule(
        rule_id="GSR_SEC02_0068",
        section_number="G&SR 2.9.6",
        title="Safety Protocol Compliance Clause 2-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0069": GSRSafetyRule(
        rule_id="GSR_SEC02_0069",
        section_number="G&SR 2.10.7",
        title="Safety Protocol Compliance Clause 2-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0070": GSRSafetyRule(
        rule_id="GSR_SEC02_0070",
        section_number="G&SR 2.11.8",
        title="Safety Protocol Compliance Clause 2-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0071": GSRSafetyRule(
        rule_id="GSR_SEC02_0071",
        section_number="G&SR 2.12.9",
        title="Safety Protocol Compliance Clause 2-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0072": GSRSafetyRule(
        rule_id="GSR_SEC02_0072",
        section_number="G&SR 2.13.1",
        title="Safety Protocol Compliance Clause 2-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0073": GSRSafetyRule(
        rule_id="GSR_SEC02_0073",
        section_number="G&SR 2.14.2",
        title="Safety Protocol Compliance Clause 2-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0074": GSRSafetyRule(
        rule_id="GSR_SEC02_0074",
        section_number="G&SR 2.15.3",
        title="Safety Protocol Compliance Clause 2-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0075": GSRSafetyRule(
        rule_id="GSR_SEC02_0075",
        section_number="G&SR 2.16.4",
        title="Safety Protocol Compliance Clause 2-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0076": GSRSafetyRule(
        rule_id="GSR_SEC02_0076",
        section_number="G&SR 2.17.5",
        title="Safety Protocol Compliance Clause 2-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0077": GSRSafetyRule(
        rule_id="GSR_SEC02_0077",
        section_number="G&SR 2.18.6",
        title="Safety Protocol Compliance Clause 2-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0078": GSRSafetyRule(
        rule_id="GSR_SEC02_0078",
        section_number="G&SR 2.19.7",
        title="Safety Protocol Compliance Clause 2-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0079": GSRSafetyRule(
        rule_id="GSR_SEC02_0079",
        section_number="G&SR 2.20.8",
        title="Safety Protocol Compliance Clause 2-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0080": GSRSafetyRule(
        rule_id="GSR_SEC02_0080",
        section_number="G&SR 2.1.9",
        title="Safety Protocol Compliance Clause 2-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0081": GSRSafetyRule(
        rule_id="GSR_SEC02_0081",
        section_number="G&SR 2.2.1",
        title="Safety Protocol Compliance Clause 2-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0082": GSRSafetyRule(
        rule_id="GSR_SEC02_0082",
        section_number="G&SR 2.3.2",
        title="Safety Protocol Compliance Clause 2-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0083": GSRSafetyRule(
        rule_id="GSR_SEC02_0083",
        section_number="G&SR 2.4.3",
        title="Safety Protocol Compliance Clause 2-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0084": GSRSafetyRule(
        rule_id="GSR_SEC02_0084",
        section_number="G&SR 2.5.4",
        title="Safety Protocol Compliance Clause 2-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0085": GSRSafetyRule(
        rule_id="GSR_SEC02_0085",
        section_number="G&SR 2.6.5",
        title="Safety Protocol Compliance Clause 2-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0086": GSRSafetyRule(
        rule_id="GSR_SEC02_0086",
        section_number="G&SR 2.7.6",
        title="Safety Protocol Compliance Clause 2-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0087": GSRSafetyRule(
        rule_id="GSR_SEC02_0087",
        section_number="G&SR 2.8.7",
        title="Safety Protocol Compliance Clause 2-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0088": GSRSafetyRule(
        rule_id="GSR_SEC02_0088",
        section_number="G&SR 2.9.8",
        title="Safety Protocol Compliance Clause 2-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0089": GSRSafetyRule(
        rule_id="GSR_SEC02_0089",
        section_number="G&SR 2.10.9",
        title="Safety Protocol Compliance Clause 2-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0090": GSRSafetyRule(
        rule_id="GSR_SEC02_0090",
        section_number="G&SR 2.11.1",
        title="Safety Protocol Compliance Clause 2-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0091": GSRSafetyRule(
        rule_id="GSR_SEC02_0091",
        section_number="G&SR 2.12.2",
        title="Safety Protocol Compliance Clause 2-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0092": GSRSafetyRule(
        rule_id="GSR_SEC02_0092",
        section_number="G&SR 2.13.3",
        title="Safety Protocol Compliance Clause 2-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0093": GSRSafetyRule(
        rule_id="GSR_SEC02_0093",
        section_number="G&SR 2.14.4",
        title="Safety Protocol Compliance Clause 2-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0094": GSRSafetyRule(
        rule_id="GSR_SEC02_0094",
        section_number="G&SR 2.15.5",
        title="Safety Protocol Compliance Clause 2-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0095": GSRSafetyRule(
        rule_id="GSR_SEC02_0095",
        section_number="G&SR 2.16.6",
        title="Safety Protocol Compliance Clause 2-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0096": GSRSafetyRule(
        rule_id="GSR_SEC02_0096",
        section_number="G&SR 2.17.7",
        title="Safety Protocol Compliance Clause 2-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0097": GSRSafetyRule(
        rule_id="GSR_SEC02_0097",
        section_number="G&SR 2.18.8",
        title="Safety Protocol Compliance Clause 2-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0098": GSRSafetyRule(
        rule_id="GSR_SEC02_0098",
        section_number="G&SR 2.19.9",
        title="Safety Protocol Compliance Clause 2-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0099": GSRSafetyRule(
        rule_id="GSR_SEC02_0099",
        section_number="G&SR 2.20.1",
        title="Safety Protocol Compliance Clause 2-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0100": GSRSafetyRule(
        rule_id="GSR_SEC02_0100",
        section_number="G&SR 2.1.2",
        title="Safety Protocol Compliance Clause 2-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0101": GSRSafetyRule(
        rule_id="GSR_SEC02_0101",
        section_number="G&SR 2.2.3",
        title="Safety Protocol Compliance Clause 2-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0102": GSRSafetyRule(
        rule_id="GSR_SEC02_0102",
        section_number="G&SR 2.3.4",
        title="Safety Protocol Compliance Clause 2-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0103": GSRSafetyRule(
        rule_id="GSR_SEC02_0103",
        section_number="G&SR 2.4.5",
        title="Safety Protocol Compliance Clause 2-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0104": GSRSafetyRule(
        rule_id="GSR_SEC02_0104",
        section_number="G&SR 2.5.6",
        title="Safety Protocol Compliance Clause 2-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0105": GSRSafetyRule(
        rule_id="GSR_SEC02_0105",
        section_number="G&SR 2.6.7",
        title="Safety Protocol Compliance Clause 2-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0106": GSRSafetyRule(
        rule_id="GSR_SEC02_0106",
        section_number="G&SR 2.7.8",
        title="Safety Protocol Compliance Clause 2-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0107": GSRSafetyRule(
        rule_id="GSR_SEC02_0107",
        section_number="G&SR 2.8.9",
        title="Safety Protocol Compliance Clause 2-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0108": GSRSafetyRule(
        rule_id="GSR_SEC02_0108",
        section_number="G&SR 2.9.1",
        title="Safety Protocol Compliance Clause 2-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0109": GSRSafetyRule(
        rule_id="GSR_SEC02_0109",
        section_number="G&SR 2.10.2",
        title="Safety Protocol Compliance Clause 2-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0110": GSRSafetyRule(
        rule_id="GSR_SEC02_0110",
        section_number="G&SR 2.11.3",
        title="Safety Protocol Compliance Clause 2-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0111": GSRSafetyRule(
        rule_id="GSR_SEC02_0111",
        section_number="G&SR 2.12.4",
        title="Safety Protocol Compliance Clause 2-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0112": GSRSafetyRule(
        rule_id="GSR_SEC02_0112",
        section_number="G&SR 2.13.5",
        title="Safety Protocol Compliance Clause 2-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0113": GSRSafetyRule(
        rule_id="GSR_SEC02_0113",
        section_number="G&SR 2.14.6",
        title="Safety Protocol Compliance Clause 2-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0114": GSRSafetyRule(
        rule_id="GSR_SEC02_0114",
        section_number="G&SR 2.15.7",
        title="Safety Protocol Compliance Clause 2-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0115": GSRSafetyRule(
        rule_id="GSR_SEC02_0115",
        section_number="G&SR 2.16.8",
        title="Safety Protocol Compliance Clause 2-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0116": GSRSafetyRule(
        rule_id="GSR_SEC02_0116",
        section_number="G&SR 2.17.9",
        title="Safety Protocol Compliance Clause 2-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0117": GSRSafetyRule(
        rule_id="GSR_SEC02_0117",
        section_number="G&SR 2.18.1",
        title="Safety Protocol Compliance Clause 2-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0118": GSRSafetyRule(
        rule_id="GSR_SEC02_0118",
        section_number="G&SR 2.19.2",
        title="Safety Protocol Compliance Clause 2-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0119": GSRSafetyRule(
        rule_id="GSR_SEC02_0119",
        section_number="G&SR 2.20.3",
        title="Safety Protocol Compliance Clause 2-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0120": GSRSafetyRule(
        rule_id="GSR_SEC02_0120",
        section_number="G&SR 2.1.4",
        title="Safety Protocol Compliance Clause 2-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0121": GSRSafetyRule(
        rule_id="GSR_SEC02_0121",
        section_number="G&SR 2.2.5",
        title="Safety Protocol Compliance Clause 2-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0122": GSRSafetyRule(
        rule_id="GSR_SEC02_0122",
        section_number="G&SR 2.3.6",
        title="Safety Protocol Compliance Clause 2-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0123": GSRSafetyRule(
        rule_id="GSR_SEC02_0123",
        section_number="G&SR 2.4.7",
        title="Safety Protocol Compliance Clause 2-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0124": GSRSafetyRule(
        rule_id="GSR_SEC02_0124",
        section_number="G&SR 2.5.8",
        title="Safety Protocol Compliance Clause 2-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0125": GSRSafetyRule(
        rule_id="GSR_SEC02_0125",
        section_number="G&SR 2.6.9",
        title="Safety Protocol Compliance Clause 2-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0126": GSRSafetyRule(
        rule_id="GSR_SEC02_0126",
        section_number="G&SR 2.7.1",
        title="Safety Protocol Compliance Clause 2-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0127": GSRSafetyRule(
        rule_id="GSR_SEC02_0127",
        section_number="G&SR 2.8.2",
        title="Safety Protocol Compliance Clause 2-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0128": GSRSafetyRule(
        rule_id="GSR_SEC02_0128",
        section_number="G&SR 2.9.3",
        title="Safety Protocol Compliance Clause 2-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0129": GSRSafetyRule(
        rule_id="GSR_SEC02_0129",
        section_number="G&SR 2.10.4",
        title="Safety Protocol Compliance Clause 2-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0130": GSRSafetyRule(
        rule_id="GSR_SEC02_0130",
        section_number="G&SR 2.11.5",
        title="Safety Protocol Compliance Clause 2-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0131": GSRSafetyRule(
        rule_id="GSR_SEC02_0131",
        section_number="G&SR 2.12.6",
        title="Safety Protocol Compliance Clause 2-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0132": GSRSafetyRule(
        rule_id="GSR_SEC02_0132",
        section_number="G&SR 2.13.7",
        title="Safety Protocol Compliance Clause 2-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0133": GSRSafetyRule(
        rule_id="GSR_SEC02_0133",
        section_number="G&SR 2.14.8",
        title="Safety Protocol Compliance Clause 2-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0134": GSRSafetyRule(
        rule_id="GSR_SEC02_0134",
        section_number="G&SR 2.15.9",
        title="Safety Protocol Compliance Clause 2-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0135": GSRSafetyRule(
        rule_id="GSR_SEC02_0135",
        section_number="G&SR 2.16.1",
        title="Safety Protocol Compliance Clause 2-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0136": GSRSafetyRule(
        rule_id="GSR_SEC02_0136",
        section_number="G&SR 2.17.2",
        title="Safety Protocol Compliance Clause 2-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0137": GSRSafetyRule(
        rule_id="GSR_SEC02_0137",
        section_number="G&SR 2.18.3",
        title="Safety Protocol Compliance Clause 2-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0138": GSRSafetyRule(
        rule_id="GSR_SEC02_0138",
        section_number="G&SR 2.19.4",
        title="Safety Protocol Compliance Clause 2-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0139": GSRSafetyRule(
        rule_id="GSR_SEC02_0139",
        section_number="G&SR 2.20.5",
        title="Safety Protocol Compliance Clause 2-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0140": GSRSafetyRule(
        rule_id="GSR_SEC02_0140",
        section_number="G&SR 2.1.6",
        title="Safety Protocol Compliance Clause 2-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0141": GSRSafetyRule(
        rule_id="GSR_SEC02_0141",
        section_number="G&SR 2.2.7",
        title="Safety Protocol Compliance Clause 2-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0142": GSRSafetyRule(
        rule_id="GSR_SEC02_0142",
        section_number="G&SR 2.3.8",
        title="Safety Protocol Compliance Clause 2-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0143": GSRSafetyRule(
        rule_id="GSR_SEC02_0143",
        section_number="G&SR 2.4.9",
        title="Safety Protocol Compliance Clause 2-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0144": GSRSafetyRule(
        rule_id="GSR_SEC02_0144",
        section_number="G&SR 2.5.1",
        title="Safety Protocol Compliance Clause 2-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0145": GSRSafetyRule(
        rule_id="GSR_SEC02_0145",
        section_number="G&SR 2.6.2",
        title="Safety Protocol Compliance Clause 2-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0146": GSRSafetyRule(
        rule_id="GSR_SEC02_0146",
        section_number="G&SR 2.7.3",
        title="Safety Protocol Compliance Clause 2-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0147": GSRSafetyRule(
        rule_id="GSR_SEC02_0147",
        section_number="G&SR 2.8.4",
        title="Safety Protocol Compliance Clause 2-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0148": GSRSafetyRule(
        rule_id="GSR_SEC02_0148",
        section_number="G&SR 2.9.5",
        title="Safety Protocol Compliance Clause 2-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0149": GSRSafetyRule(
        rule_id="GSR_SEC02_0149",
        section_number="G&SR 2.10.6",
        title="Safety Protocol Compliance Clause 2-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0150": GSRSafetyRule(
        rule_id="GSR_SEC02_0150",
        section_number="G&SR 2.11.7",
        title="Safety Protocol Compliance Clause 2-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0151": GSRSafetyRule(
        rule_id="GSR_SEC02_0151",
        section_number="G&SR 2.12.8",
        title="Safety Protocol Compliance Clause 2-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0152": GSRSafetyRule(
        rule_id="GSR_SEC02_0152",
        section_number="G&SR 2.13.9",
        title="Safety Protocol Compliance Clause 2-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0153": GSRSafetyRule(
        rule_id="GSR_SEC02_0153",
        section_number="G&SR 2.14.1",
        title="Safety Protocol Compliance Clause 2-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0154": GSRSafetyRule(
        rule_id="GSR_SEC02_0154",
        section_number="G&SR 2.15.2",
        title="Safety Protocol Compliance Clause 2-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0155": GSRSafetyRule(
        rule_id="GSR_SEC02_0155",
        section_number="G&SR 2.16.3",
        title="Safety Protocol Compliance Clause 2-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0156": GSRSafetyRule(
        rule_id="GSR_SEC02_0156",
        section_number="G&SR 2.17.4",
        title="Safety Protocol Compliance Clause 2-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0157": GSRSafetyRule(
        rule_id="GSR_SEC02_0157",
        section_number="G&SR 2.18.5",
        title="Safety Protocol Compliance Clause 2-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0158": GSRSafetyRule(
        rule_id="GSR_SEC02_0158",
        section_number="G&SR 2.19.6",
        title="Safety Protocol Compliance Clause 2-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0159": GSRSafetyRule(
        rule_id="GSR_SEC02_0159",
        section_number="G&SR 2.20.7",
        title="Safety Protocol Compliance Clause 2-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0160": GSRSafetyRule(
        rule_id="GSR_SEC02_0160",
        section_number="G&SR 2.1.8",
        title="Safety Protocol Compliance Clause 2-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0161": GSRSafetyRule(
        rule_id="GSR_SEC02_0161",
        section_number="G&SR 2.2.9",
        title="Safety Protocol Compliance Clause 2-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0162": GSRSafetyRule(
        rule_id="GSR_SEC02_0162",
        section_number="G&SR 2.3.1",
        title="Safety Protocol Compliance Clause 2-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0163": GSRSafetyRule(
        rule_id="GSR_SEC02_0163",
        section_number="G&SR 2.4.2",
        title="Safety Protocol Compliance Clause 2-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0164": GSRSafetyRule(
        rule_id="GSR_SEC02_0164",
        section_number="G&SR 2.5.3",
        title="Safety Protocol Compliance Clause 2-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0165": GSRSafetyRule(
        rule_id="GSR_SEC02_0165",
        section_number="G&SR 2.6.4",
        title="Safety Protocol Compliance Clause 2-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0166": GSRSafetyRule(
        rule_id="GSR_SEC02_0166",
        section_number="G&SR 2.7.5",
        title="Safety Protocol Compliance Clause 2-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0167": GSRSafetyRule(
        rule_id="GSR_SEC02_0167",
        section_number="G&SR 2.8.6",
        title="Safety Protocol Compliance Clause 2-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0168": GSRSafetyRule(
        rule_id="GSR_SEC02_0168",
        section_number="G&SR 2.9.7",
        title="Safety Protocol Compliance Clause 2-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0169": GSRSafetyRule(
        rule_id="GSR_SEC02_0169",
        section_number="G&SR 2.10.8",
        title="Safety Protocol Compliance Clause 2-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0170": GSRSafetyRule(
        rule_id="GSR_SEC02_0170",
        section_number="G&SR 2.11.9",
        title="Safety Protocol Compliance Clause 2-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0171": GSRSafetyRule(
        rule_id="GSR_SEC02_0171",
        section_number="G&SR 2.12.1",
        title="Safety Protocol Compliance Clause 2-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0172": GSRSafetyRule(
        rule_id="GSR_SEC02_0172",
        section_number="G&SR 2.13.2",
        title="Safety Protocol Compliance Clause 2-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0173": GSRSafetyRule(
        rule_id="GSR_SEC02_0173",
        section_number="G&SR 2.14.3",
        title="Safety Protocol Compliance Clause 2-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC02_0174": GSRSafetyRule(
        rule_id="GSR_SEC02_0174",
        section_number="G&SR 2.15.4",
        title="Safety Protocol Compliance Clause 2-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
