"""Indian Railways G&SR Regulatory Rulebook Section 011."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_011: Dict[str, GSRSafetyRule] = {
    "GSR_SEC11_0001": GSRSafetyRule(
        rule_id="GSR_SEC11_0001",
        section_number="G&SR 11.2.2",
        title="Safety Protocol Compliance Clause 11-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0002": GSRSafetyRule(
        rule_id="GSR_SEC11_0002",
        section_number="G&SR 11.3.3",
        title="Safety Protocol Compliance Clause 11-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0003": GSRSafetyRule(
        rule_id="GSR_SEC11_0003",
        section_number="G&SR 11.4.4",
        title="Safety Protocol Compliance Clause 11-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0004": GSRSafetyRule(
        rule_id="GSR_SEC11_0004",
        section_number="G&SR 11.5.5",
        title="Safety Protocol Compliance Clause 11-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0005": GSRSafetyRule(
        rule_id="GSR_SEC11_0005",
        section_number="G&SR 11.6.6",
        title="Safety Protocol Compliance Clause 11-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0006": GSRSafetyRule(
        rule_id="GSR_SEC11_0006",
        section_number="G&SR 11.7.7",
        title="Safety Protocol Compliance Clause 11-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0007": GSRSafetyRule(
        rule_id="GSR_SEC11_0007",
        section_number="G&SR 11.8.8",
        title="Safety Protocol Compliance Clause 11-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0008": GSRSafetyRule(
        rule_id="GSR_SEC11_0008",
        section_number="G&SR 11.9.9",
        title="Safety Protocol Compliance Clause 11-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0009": GSRSafetyRule(
        rule_id="GSR_SEC11_0009",
        section_number="G&SR 11.10.1",
        title="Safety Protocol Compliance Clause 11-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0010": GSRSafetyRule(
        rule_id="GSR_SEC11_0010",
        section_number="G&SR 11.11.2",
        title="Safety Protocol Compliance Clause 11-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0011": GSRSafetyRule(
        rule_id="GSR_SEC11_0011",
        section_number="G&SR 11.12.3",
        title="Safety Protocol Compliance Clause 11-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0012": GSRSafetyRule(
        rule_id="GSR_SEC11_0012",
        section_number="G&SR 11.13.4",
        title="Safety Protocol Compliance Clause 11-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0013": GSRSafetyRule(
        rule_id="GSR_SEC11_0013",
        section_number="G&SR 11.14.5",
        title="Safety Protocol Compliance Clause 11-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0014": GSRSafetyRule(
        rule_id="GSR_SEC11_0014",
        section_number="G&SR 11.15.6",
        title="Safety Protocol Compliance Clause 11-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0015": GSRSafetyRule(
        rule_id="GSR_SEC11_0015",
        section_number="G&SR 11.16.7",
        title="Safety Protocol Compliance Clause 11-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0016": GSRSafetyRule(
        rule_id="GSR_SEC11_0016",
        section_number="G&SR 11.17.8",
        title="Safety Protocol Compliance Clause 11-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0017": GSRSafetyRule(
        rule_id="GSR_SEC11_0017",
        section_number="G&SR 11.18.9",
        title="Safety Protocol Compliance Clause 11-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0018": GSRSafetyRule(
        rule_id="GSR_SEC11_0018",
        section_number="G&SR 11.19.1",
        title="Safety Protocol Compliance Clause 11-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0019": GSRSafetyRule(
        rule_id="GSR_SEC11_0019",
        section_number="G&SR 11.20.2",
        title="Safety Protocol Compliance Clause 11-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0020": GSRSafetyRule(
        rule_id="GSR_SEC11_0020",
        section_number="G&SR 11.1.3",
        title="Safety Protocol Compliance Clause 11-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0021": GSRSafetyRule(
        rule_id="GSR_SEC11_0021",
        section_number="G&SR 11.2.4",
        title="Safety Protocol Compliance Clause 11-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0022": GSRSafetyRule(
        rule_id="GSR_SEC11_0022",
        section_number="G&SR 11.3.5",
        title="Safety Protocol Compliance Clause 11-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0023": GSRSafetyRule(
        rule_id="GSR_SEC11_0023",
        section_number="G&SR 11.4.6",
        title="Safety Protocol Compliance Clause 11-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0024": GSRSafetyRule(
        rule_id="GSR_SEC11_0024",
        section_number="G&SR 11.5.7",
        title="Safety Protocol Compliance Clause 11-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0025": GSRSafetyRule(
        rule_id="GSR_SEC11_0025",
        section_number="G&SR 11.6.8",
        title="Safety Protocol Compliance Clause 11-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0026": GSRSafetyRule(
        rule_id="GSR_SEC11_0026",
        section_number="G&SR 11.7.9",
        title="Safety Protocol Compliance Clause 11-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0027": GSRSafetyRule(
        rule_id="GSR_SEC11_0027",
        section_number="G&SR 11.8.1",
        title="Safety Protocol Compliance Clause 11-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0028": GSRSafetyRule(
        rule_id="GSR_SEC11_0028",
        section_number="G&SR 11.9.2",
        title="Safety Protocol Compliance Clause 11-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0029": GSRSafetyRule(
        rule_id="GSR_SEC11_0029",
        section_number="G&SR 11.10.3",
        title="Safety Protocol Compliance Clause 11-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0030": GSRSafetyRule(
        rule_id="GSR_SEC11_0030",
        section_number="G&SR 11.11.4",
        title="Safety Protocol Compliance Clause 11-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0031": GSRSafetyRule(
        rule_id="GSR_SEC11_0031",
        section_number="G&SR 11.12.5",
        title="Safety Protocol Compliance Clause 11-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0032": GSRSafetyRule(
        rule_id="GSR_SEC11_0032",
        section_number="G&SR 11.13.6",
        title="Safety Protocol Compliance Clause 11-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0033": GSRSafetyRule(
        rule_id="GSR_SEC11_0033",
        section_number="G&SR 11.14.7",
        title="Safety Protocol Compliance Clause 11-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0034": GSRSafetyRule(
        rule_id="GSR_SEC11_0034",
        section_number="G&SR 11.15.8",
        title="Safety Protocol Compliance Clause 11-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0035": GSRSafetyRule(
        rule_id="GSR_SEC11_0035",
        section_number="G&SR 11.16.9",
        title="Safety Protocol Compliance Clause 11-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0036": GSRSafetyRule(
        rule_id="GSR_SEC11_0036",
        section_number="G&SR 11.17.1",
        title="Safety Protocol Compliance Clause 11-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0037": GSRSafetyRule(
        rule_id="GSR_SEC11_0037",
        section_number="G&SR 11.18.2",
        title="Safety Protocol Compliance Clause 11-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0038": GSRSafetyRule(
        rule_id="GSR_SEC11_0038",
        section_number="G&SR 11.19.3",
        title="Safety Protocol Compliance Clause 11-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0039": GSRSafetyRule(
        rule_id="GSR_SEC11_0039",
        section_number="G&SR 11.20.4",
        title="Safety Protocol Compliance Clause 11-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0040": GSRSafetyRule(
        rule_id="GSR_SEC11_0040",
        section_number="G&SR 11.1.5",
        title="Safety Protocol Compliance Clause 11-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0041": GSRSafetyRule(
        rule_id="GSR_SEC11_0041",
        section_number="G&SR 11.2.6",
        title="Safety Protocol Compliance Clause 11-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0042": GSRSafetyRule(
        rule_id="GSR_SEC11_0042",
        section_number="G&SR 11.3.7",
        title="Safety Protocol Compliance Clause 11-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0043": GSRSafetyRule(
        rule_id="GSR_SEC11_0043",
        section_number="G&SR 11.4.8",
        title="Safety Protocol Compliance Clause 11-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0044": GSRSafetyRule(
        rule_id="GSR_SEC11_0044",
        section_number="G&SR 11.5.9",
        title="Safety Protocol Compliance Clause 11-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0045": GSRSafetyRule(
        rule_id="GSR_SEC11_0045",
        section_number="G&SR 11.6.1",
        title="Safety Protocol Compliance Clause 11-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0046": GSRSafetyRule(
        rule_id="GSR_SEC11_0046",
        section_number="G&SR 11.7.2",
        title="Safety Protocol Compliance Clause 11-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0047": GSRSafetyRule(
        rule_id="GSR_SEC11_0047",
        section_number="G&SR 11.8.3",
        title="Safety Protocol Compliance Clause 11-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0048": GSRSafetyRule(
        rule_id="GSR_SEC11_0048",
        section_number="G&SR 11.9.4",
        title="Safety Protocol Compliance Clause 11-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0049": GSRSafetyRule(
        rule_id="GSR_SEC11_0049",
        section_number="G&SR 11.10.5",
        title="Safety Protocol Compliance Clause 11-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0050": GSRSafetyRule(
        rule_id="GSR_SEC11_0050",
        section_number="G&SR 11.11.6",
        title="Safety Protocol Compliance Clause 11-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0051": GSRSafetyRule(
        rule_id="GSR_SEC11_0051",
        section_number="G&SR 11.12.7",
        title="Safety Protocol Compliance Clause 11-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0052": GSRSafetyRule(
        rule_id="GSR_SEC11_0052",
        section_number="G&SR 11.13.8",
        title="Safety Protocol Compliance Clause 11-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0053": GSRSafetyRule(
        rule_id="GSR_SEC11_0053",
        section_number="G&SR 11.14.9",
        title="Safety Protocol Compliance Clause 11-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0054": GSRSafetyRule(
        rule_id="GSR_SEC11_0054",
        section_number="G&SR 11.15.1",
        title="Safety Protocol Compliance Clause 11-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0055": GSRSafetyRule(
        rule_id="GSR_SEC11_0055",
        section_number="G&SR 11.16.2",
        title="Safety Protocol Compliance Clause 11-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0056": GSRSafetyRule(
        rule_id="GSR_SEC11_0056",
        section_number="G&SR 11.17.3",
        title="Safety Protocol Compliance Clause 11-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0057": GSRSafetyRule(
        rule_id="GSR_SEC11_0057",
        section_number="G&SR 11.18.4",
        title="Safety Protocol Compliance Clause 11-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0058": GSRSafetyRule(
        rule_id="GSR_SEC11_0058",
        section_number="G&SR 11.19.5",
        title="Safety Protocol Compliance Clause 11-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0059": GSRSafetyRule(
        rule_id="GSR_SEC11_0059",
        section_number="G&SR 11.20.6",
        title="Safety Protocol Compliance Clause 11-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0060": GSRSafetyRule(
        rule_id="GSR_SEC11_0060",
        section_number="G&SR 11.1.7",
        title="Safety Protocol Compliance Clause 11-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0061": GSRSafetyRule(
        rule_id="GSR_SEC11_0061",
        section_number="G&SR 11.2.8",
        title="Safety Protocol Compliance Clause 11-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0062": GSRSafetyRule(
        rule_id="GSR_SEC11_0062",
        section_number="G&SR 11.3.9",
        title="Safety Protocol Compliance Clause 11-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0063": GSRSafetyRule(
        rule_id="GSR_SEC11_0063",
        section_number="G&SR 11.4.1",
        title="Safety Protocol Compliance Clause 11-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0064": GSRSafetyRule(
        rule_id="GSR_SEC11_0064",
        section_number="G&SR 11.5.2",
        title="Safety Protocol Compliance Clause 11-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0065": GSRSafetyRule(
        rule_id="GSR_SEC11_0065",
        section_number="G&SR 11.6.3",
        title="Safety Protocol Compliance Clause 11-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0066": GSRSafetyRule(
        rule_id="GSR_SEC11_0066",
        section_number="G&SR 11.7.4",
        title="Safety Protocol Compliance Clause 11-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0067": GSRSafetyRule(
        rule_id="GSR_SEC11_0067",
        section_number="G&SR 11.8.5",
        title="Safety Protocol Compliance Clause 11-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0068": GSRSafetyRule(
        rule_id="GSR_SEC11_0068",
        section_number="G&SR 11.9.6",
        title="Safety Protocol Compliance Clause 11-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0069": GSRSafetyRule(
        rule_id="GSR_SEC11_0069",
        section_number="G&SR 11.10.7",
        title="Safety Protocol Compliance Clause 11-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0070": GSRSafetyRule(
        rule_id="GSR_SEC11_0070",
        section_number="G&SR 11.11.8",
        title="Safety Protocol Compliance Clause 11-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0071": GSRSafetyRule(
        rule_id="GSR_SEC11_0071",
        section_number="G&SR 11.12.9",
        title="Safety Protocol Compliance Clause 11-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0072": GSRSafetyRule(
        rule_id="GSR_SEC11_0072",
        section_number="G&SR 11.13.1",
        title="Safety Protocol Compliance Clause 11-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0073": GSRSafetyRule(
        rule_id="GSR_SEC11_0073",
        section_number="G&SR 11.14.2",
        title="Safety Protocol Compliance Clause 11-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0074": GSRSafetyRule(
        rule_id="GSR_SEC11_0074",
        section_number="G&SR 11.15.3",
        title="Safety Protocol Compliance Clause 11-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0075": GSRSafetyRule(
        rule_id="GSR_SEC11_0075",
        section_number="G&SR 11.16.4",
        title="Safety Protocol Compliance Clause 11-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0076": GSRSafetyRule(
        rule_id="GSR_SEC11_0076",
        section_number="G&SR 11.17.5",
        title="Safety Protocol Compliance Clause 11-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0077": GSRSafetyRule(
        rule_id="GSR_SEC11_0077",
        section_number="G&SR 11.18.6",
        title="Safety Protocol Compliance Clause 11-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0078": GSRSafetyRule(
        rule_id="GSR_SEC11_0078",
        section_number="G&SR 11.19.7",
        title="Safety Protocol Compliance Clause 11-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0079": GSRSafetyRule(
        rule_id="GSR_SEC11_0079",
        section_number="G&SR 11.20.8",
        title="Safety Protocol Compliance Clause 11-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0080": GSRSafetyRule(
        rule_id="GSR_SEC11_0080",
        section_number="G&SR 11.1.9",
        title="Safety Protocol Compliance Clause 11-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0081": GSRSafetyRule(
        rule_id="GSR_SEC11_0081",
        section_number="G&SR 11.2.1",
        title="Safety Protocol Compliance Clause 11-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0082": GSRSafetyRule(
        rule_id="GSR_SEC11_0082",
        section_number="G&SR 11.3.2",
        title="Safety Protocol Compliance Clause 11-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0083": GSRSafetyRule(
        rule_id="GSR_SEC11_0083",
        section_number="G&SR 11.4.3",
        title="Safety Protocol Compliance Clause 11-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0084": GSRSafetyRule(
        rule_id="GSR_SEC11_0084",
        section_number="G&SR 11.5.4",
        title="Safety Protocol Compliance Clause 11-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0085": GSRSafetyRule(
        rule_id="GSR_SEC11_0085",
        section_number="G&SR 11.6.5",
        title="Safety Protocol Compliance Clause 11-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0086": GSRSafetyRule(
        rule_id="GSR_SEC11_0086",
        section_number="G&SR 11.7.6",
        title="Safety Protocol Compliance Clause 11-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0087": GSRSafetyRule(
        rule_id="GSR_SEC11_0087",
        section_number="G&SR 11.8.7",
        title="Safety Protocol Compliance Clause 11-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0088": GSRSafetyRule(
        rule_id="GSR_SEC11_0088",
        section_number="G&SR 11.9.8",
        title="Safety Protocol Compliance Clause 11-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0089": GSRSafetyRule(
        rule_id="GSR_SEC11_0089",
        section_number="G&SR 11.10.9",
        title="Safety Protocol Compliance Clause 11-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0090": GSRSafetyRule(
        rule_id="GSR_SEC11_0090",
        section_number="G&SR 11.11.1",
        title="Safety Protocol Compliance Clause 11-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0091": GSRSafetyRule(
        rule_id="GSR_SEC11_0091",
        section_number="G&SR 11.12.2",
        title="Safety Protocol Compliance Clause 11-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0092": GSRSafetyRule(
        rule_id="GSR_SEC11_0092",
        section_number="G&SR 11.13.3",
        title="Safety Protocol Compliance Clause 11-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0093": GSRSafetyRule(
        rule_id="GSR_SEC11_0093",
        section_number="G&SR 11.14.4",
        title="Safety Protocol Compliance Clause 11-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0094": GSRSafetyRule(
        rule_id="GSR_SEC11_0094",
        section_number="G&SR 11.15.5",
        title="Safety Protocol Compliance Clause 11-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0095": GSRSafetyRule(
        rule_id="GSR_SEC11_0095",
        section_number="G&SR 11.16.6",
        title="Safety Protocol Compliance Clause 11-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0096": GSRSafetyRule(
        rule_id="GSR_SEC11_0096",
        section_number="G&SR 11.17.7",
        title="Safety Protocol Compliance Clause 11-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0097": GSRSafetyRule(
        rule_id="GSR_SEC11_0097",
        section_number="G&SR 11.18.8",
        title="Safety Protocol Compliance Clause 11-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0098": GSRSafetyRule(
        rule_id="GSR_SEC11_0098",
        section_number="G&SR 11.19.9",
        title="Safety Protocol Compliance Clause 11-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0099": GSRSafetyRule(
        rule_id="GSR_SEC11_0099",
        section_number="G&SR 11.20.1",
        title="Safety Protocol Compliance Clause 11-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0100": GSRSafetyRule(
        rule_id="GSR_SEC11_0100",
        section_number="G&SR 11.1.2",
        title="Safety Protocol Compliance Clause 11-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0101": GSRSafetyRule(
        rule_id="GSR_SEC11_0101",
        section_number="G&SR 11.2.3",
        title="Safety Protocol Compliance Clause 11-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0102": GSRSafetyRule(
        rule_id="GSR_SEC11_0102",
        section_number="G&SR 11.3.4",
        title="Safety Protocol Compliance Clause 11-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0103": GSRSafetyRule(
        rule_id="GSR_SEC11_0103",
        section_number="G&SR 11.4.5",
        title="Safety Protocol Compliance Clause 11-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0104": GSRSafetyRule(
        rule_id="GSR_SEC11_0104",
        section_number="G&SR 11.5.6",
        title="Safety Protocol Compliance Clause 11-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0105": GSRSafetyRule(
        rule_id="GSR_SEC11_0105",
        section_number="G&SR 11.6.7",
        title="Safety Protocol Compliance Clause 11-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0106": GSRSafetyRule(
        rule_id="GSR_SEC11_0106",
        section_number="G&SR 11.7.8",
        title="Safety Protocol Compliance Clause 11-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0107": GSRSafetyRule(
        rule_id="GSR_SEC11_0107",
        section_number="G&SR 11.8.9",
        title="Safety Protocol Compliance Clause 11-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0108": GSRSafetyRule(
        rule_id="GSR_SEC11_0108",
        section_number="G&SR 11.9.1",
        title="Safety Protocol Compliance Clause 11-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0109": GSRSafetyRule(
        rule_id="GSR_SEC11_0109",
        section_number="G&SR 11.10.2",
        title="Safety Protocol Compliance Clause 11-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0110": GSRSafetyRule(
        rule_id="GSR_SEC11_0110",
        section_number="G&SR 11.11.3",
        title="Safety Protocol Compliance Clause 11-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0111": GSRSafetyRule(
        rule_id="GSR_SEC11_0111",
        section_number="G&SR 11.12.4",
        title="Safety Protocol Compliance Clause 11-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0112": GSRSafetyRule(
        rule_id="GSR_SEC11_0112",
        section_number="G&SR 11.13.5",
        title="Safety Protocol Compliance Clause 11-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0113": GSRSafetyRule(
        rule_id="GSR_SEC11_0113",
        section_number="G&SR 11.14.6",
        title="Safety Protocol Compliance Clause 11-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0114": GSRSafetyRule(
        rule_id="GSR_SEC11_0114",
        section_number="G&SR 11.15.7",
        title="Safety Protocol Compliance Clause 11-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0115": GSRSafetyRule(
        rule_id="GSR_SEC11_0115",
        section_number="G&SR 11.16.8",
        title="Safety Protocol Compliance Clause 11-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0116": GSRSafetyRule(
        rule_id="GSR_SEC11_0116",
        section_number="G&SR 11.17.9",
        title="Safety Protocol Compliance Clause 11-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0117": GSRSafetyRule(
        rule_id="GSR_SEC11_0117",
        section_number="G&SR 11.18.1",
        title="Safety Protocol Compliance Clause 11-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0118": GSRSafetyRule(
        rule_id="GSR_SEC11_0118",
        section_number="G&SR 11.19.2",
        title="Safety Protocol Compliance Clause 11-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0119": GSRSafetyRule(
        rule_id="GSR_SEC11_0119",
        section_number="G&SR 11.20.3",
        title="Safety Protocol Compliance Clause 11-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0120": GSRSafetyRule(
        rule_id="GSR_SEC11_0120",
        section_number="G&SR 11.1.4",
        title="Safety Protocol Compliance Clause 11-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0121": GSRSafetyRule(
        rule_id="GSR_SEC11_0121",
        section_number="G&SR 11.2.5",
        title="Safety Protocol Compliance Clause 11-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0122": GSRSafetyRule(
        rule_id="GSR_SEC11_0122",
        section_number="G&SR 11.3.6",
        title="Safety Protocol Compliance Clause 11-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0123": GSRSafetyRule(
        rule_id="GSR_SEC11_0123",
        section_number="G&SR 11.4.7",
        title="Safety Protocol Compliance Clause 11-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0124": GSRSafetyRule(
        rule_id="GSR_SEC11_0124",
        section_number="G&SR 11.5.8",
        title="Safety Protocol Compliance Clause 11-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0125": GSRSafetyRule(
        rule_id="GSR_SEC11_0125",
        section_number="G&SR 11.6.9",
        title="Safety Protocol Compliance Clause 11-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0126": GSRSafetyRule(
        rule_id="GSR_SEC11_0126",
        section_number="G&SR 11.7.1",
        title="Safety Protocol Compliance Clause 11-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0127": GSRSafetyRule(
        rule_id="GSR_SEC11_0127",
        section_number="G&SR 11.8.2",
        title="Safety Protocol Compliance Clause 11-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0128": GSRSafetyRule(
        rule_id="GSR_SEC11_0128",
        section_number="G&SR 11.9.3",
        title="Safety Protocol Compliance Clause 11-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0129": GSRSafetyRule(
        rule_id="GSR_SEC11_0129",
        section_number="G&SR 11.10.4",
        title="Safety Protocol Compliance Clause 11-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0130": GSRSafetyRule(
        rule_id="GSR_SEC11_0130",
        section_number="G&SR 11.11.5",
        title="Safety Protocol Compliance Clause 11-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0131": GSRSafetyRule(
        rule_id="GSR_SEC11_0131",
        section_number="G&SR 11.12.6",
        title="Safety Protocol Compliance Clause 11-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0132": GSRSafetyRule(
        rule_id="GSR_SEC11_0132",
        section_number="G&SR 11.13.7",
        title="Safety Protocol Compliance Clause 11-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0133": GSRSafetyRule(
        rule_id="GSR_SEC11_0133",
        section_number="G&SR 11.14.8",
        title="Safety Protocol Compliance Clause 11-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0134": GSRSafetyRule(
        rule_id="GSR_SEC11_0134",
        section_number="G&SR 11.15.9",
        title="Safety Protocol Compliance Clause 11-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0135": GSRSafetyRule(
        rule_id="GSR_SEC11_0135",
        section_number="G&SR 11.16.1",
        title="Safety Protocol Compliance Clause 11-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0136": GSRSafetyRule(
        rule_id="GSR_SEC11_0136",
        section_number="G&SR 11.17.2",
        title="Safety Protocol Compliance Clause 11-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0137": GSRSafetyRule(
        rule_id="GSR_SEC11_0137",
        section_number="G&SR 11.18.3",
        title="Safety Protocol Compliance Clause 11-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0138": GSRSafetyRule(
        rule_id="GSR_SEC11_0138",
        section_number="G&SR 11.19.4",
        title="Safety Protocol Compliance Clause 11-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0139": GSRSafetyRule(
        rule_id="GSR_SEC11_0139",
        section_number="G&SR 11.20.5",
        title="Safety Protocol Compliance Clause 11-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0140": GSRSafetyRule(
        rule_id="GSR_SEC11_0140",
        section_number="G&SR 11.1.6",
        title="Safety Protocol Compliance Clause 11-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0141": GSRSafetyRule(
        rule_id="GSR_SEC11_0141",
        section_number="G&SR 11.2.7",
        title="Safety Protocol Compliance Clause 11-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0142": GSRSafetyRule(
        rule_id="GSR_SEC11_0142",
        section_number="G&SR 11.3.8",
        title="Safety Protocol Compliance Clause 11-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0143": GSRSafetyRule(
        rule_id="GSR_SEC11_0143",
        section_number="G&SR 11.4.9",
        title="Safety Protocol Compliance Clause 11-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0144": GSRSafetyRule(
        rule_id="GSR_SEC11_0144",
        section_number="G&SR 11.5.1",
        title="Safety Protocol Compliance Clause 11-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0145": GSRSafetyRule(
        rule_id="GSR_SEC11_0145",
        section_number="G&SR 11.6.2",
        title="Safety Protocol Compliance Clause 11-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0146": GSRSafetyRule(
        rule_id="GSR_SEC11_0146",
        section_number="G&SR 11.7.3",
        title="Safety Protocol Compliance Clause 11-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0147": GSRSafetyRule(
        rule_id="GSR_SEC11_0147",
        section_number="G&SR 11.8.4",
        title="Safety Protocol Compliance Clause 11-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0148": GSRSafetyRule(
        rule_id="GSR_SEC11_0148",
        section_number="G&SR 11.9.5",
        title="Safety Protocol Compliance Clause 11-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0149": GSRSafetyRule(
        rule_id="GSR_SEC11_0149",
        section_number="G&SR 11.10.6",
        title="Safety Protocol Compliance Clause 11-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0150": GSRSafetyRule(
        rule_id="GSR_SEC11_0150",
        section_number="G&SR 11.11.7",
        title="Safety Protocol Compliance Clause 11-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0151": GSRSafetyRule(
        rule_id="GSR_SEC11_0151",
        section_number="G&SR 11.12.8",
        title="Safety Protocol Compliance Clause 11-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0152": GSRSafetyRule(
        rule_id="GSR_SEC11_0152",
        section_number="G&SR 11.13.9",
        title="Safety Protocol Compliance Clause 11-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0153": GSRSafetyRule(
        rule_id="GSR_SEC11_0153",
        section_number="G&SR 11.14.1",
        title="Safety Protocol Compliance Clause 11-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0154": GSRSafetyRule(
        rule_id="GSR_SEC11_0154",
        section_number="G&SR 11.15.2",
        title="Safety Protocol Compliance Clause 11-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0155": GSRSafetyRule(
        rule_id="GSR_SEC11_0155",
        section_number="G&SR 11.16.3",
        title="Safety Protocol Compliance Clause 11-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0156": GSRSafetyRule(
        rule_id="GSR_SEC11_0156",
        section_number="G&SR 11.17.4",
        title="Safety Protocol Compliance Clause 11-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0157": GSRSafetyRule(
        rule_id="GSR_SEC11_0157",
        section_number="G&SR 11.18.5",
        title="Safety Protocol Compliance Clause 11-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0158": GSRSafetyRule(
        rule_id="GSR_SEC11_0158",
        section_number="G&SR 11.19.6",
        title="Safety Protocol Compliance Clause 11-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0159": GSRSafetyRule(
        rule_id="GSR_SEC11_0159",
        section_number="G&SR 11.20.7",
        title="Safety Protocol Compliance Clause 11-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0160": GSRSafetyRule(
        rule_id="GSR_SEC11_0160",
        section_number="G&SR 11.1.8",
        title="Safety Protocol Compliance Clause 11-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0161": GSRSafetyRule(
        rule_id="GSR_SEC11_0161",
        section_number="G&SR 11.2.9",
        title="Safety Protocol Compliance Clause 11-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0162": GSRSafetyRule(
        rule_id="GSR_SEC11_0162",
        section_number="G&SR 11.3.1",
        title="Safety Protocol Compliance Clause 11-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0163": GSRSafetyRule(
        rule_id="GSR_SEC11_0163",
        section_number="G&SR 11.4.2",
        title="Safety Protocol Compliance Clause 11-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0164": GSRSafetyRule(
        rule_id="GSR_SEC11_0164",
        section_number="G&SR 11.5.3",
        title="Safety Protocol Compliance Clause 11-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0165": GSRSafetyRule(
        rule_id="GSR_SEC11_0165",
        section_number="G&SR 11.6.4",
        title="Safety Protocol Compliance Clause 11-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0166": GSRSafetyRule(
        rule_id="GSR_SEC11_0166",
        section_number="G&SR 11.7.5",
        title="Safety Protocol Compliance Clause 11-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0167": GSRSafetyRule(
        rule_id="GSR_SEC11_0167",
        section_number="G&SR 11.8.6",
        title="Safety Protocol Compliance Clause 11-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0168": GSRSafetyRule(
        rule_id="GSR_SEC11_0168",
        section_number="G&SR 11.9.7",
        title="Safety Protocol Compliance Clause 11-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0169": GSRSafetyRule(
        rule_id="GSR_SEC11_0169",
        section_number="G&SR 11.10.8",
        title="Safety Protocol Compliance Clause 11-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0170": GSRSafetyRule(
        rule_id="GSR_SEC11_0170",
        section_number="G&SR 11.11.9",
        title="Safety Protocol Compliance Clause 11-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0171": GSRSafetyRule(
        rule_id="GSR_SEC11_0171",
        section_number="G&SR 11.12.1",
        title="Safety Protocol Compliance Clause 11-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0172": GSRSafetyRule(
        rule_id="GSR_SEC11_0172",
        section_number="G&SR 11.13.2",
        title="Safety Protocol Compliance Clause 11-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0173": GSRSafetyRule(
        rule_id="GSR_SEC11_0173",
        section_number="G&SR 11.14.3",
        title="Safety Protocol Compliance Clause 11-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC11_0174": GSRSafetyRule(
        rule_id="GSR_SEC11_0174",
        section_number="G&SR 11.15.4",
        title="Safety Protocol Compliance Clause 11-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
