"""Indian Railways G&SR Regulatory Rulebook Section 029."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_029: Dict[str, GSRSafetyRule] = {
    "GSR_SEC29_0001": GSRSafetyRule(
        rule_id="GSR_SEC29_0001",
        section_number="G&SR 29.2.2",
        title="Safety Protocol Compliance Clause 29-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0002": GSRSafetyRule(
        rule_id="GSR_SEC29_0002",
        section_number="G&SR 29.3.3",
        title="Safety Protocol Compliance Clause 29-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0003": GSRSafetyRule(
        rule_id="GSR_SEC29_0003",
        section_number="G&SR 29.4.4",
        title="Safety Protocol Compliance Clause 29-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0004": GSRSafetyRule(
        rule_id="GSR_SEC29_0004",
        section_number="G&SR 29.5.5",
        title="Safety Protocol Compliance Clause 29-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0005": GSRSafetyRule(
        rule_id="GSR_SEC29_0005",
        section_number="G&SR 29.6.6",
        title="Safety Protocol Compliance Clause 29-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0006": GSRSafetyRule(
        rule_id="GSR_SEC29_0006",
        section_number="G&SR 29.7.7",
        title="Safety Protocol Compliance Clause 29-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0007": GSRSafetyRule(
        rule_id="GSR_SEC29_0007",
        section_number="G&SR 29.8.8",
        title="Safety Protocol Compliance Clause 29-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0008": GSRSafetyRule(
        rule_id="GSR_SEC29_0008",
        section_number="G&SR 29.9.9",
        title="Safety Protocol Compliance Clause 29-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0009": GSRSafetyRule(
        rule_id="GSR_SEC29_0009",
        section_number="G&SR 29.10.1",
        title="Safety Protocol Compliance Clause 29-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0010": GSRSafetyRule(
        rule_id="GSR_SEC29_0010",
        section_number="G&SR 29.11.2",
        title="Safety Protocol Compliance Clause 29-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0011": GSRSafetyRule(
        rule_id="GSR_SEC29_0011",
        section_number="G&SR 29.12.3",
        title="Safety Protocol Compliance Clause 29-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0012": GSRSafetyRule(
        rule_id="GSR_SEC29_0012",
        section_number="G&SR 29.13.4",
        title="Safety Protocol Compliance Clause 29-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0013": GSRSafetyRule(
        rule_id="GSR_SEC29_0013",
        section_number="G&SR 29.14.5",
        title="Safety Protocol Compliance Clause 29-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0014": GSRSafetyRule(
        rule_id="GSR_SEC29_0014",
        section_number="G&SR 29.15.6",
        title="Safety Protocol Compliance Clause 29-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0015": GSRSafetyRule(
        rule_id="GSR_SEC29_0015",
        section_number="G&SR 29.16.7",
        title="Safety Protocol Compliance Clause 29-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0016": GSRSafetyRule(
        rule_id="GSR_SEC29_0016",
        section_number="G&SR 29.17.8",
        title="Safety Protocol Compliance Clause 29-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0017": GSRSafetyRule(
        rule_id="GSR_SEC29_0017",
        section_number="G&SR 29.18.9",
        title="Safety Protocol Compliance Clause 29-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0018": GSRSafetyRule(
        rule_id="GSR_SEC29_0018",
        section_number="G&SR 29.19.1",
        title="Safety Protocol Compliance Clause 29-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0019": GSRSafetyRule(
        rule_id="GSR_SEC29_0019",
        section_number="G&SR 29.20.2",
        title="Safety Protocol Compliance Clause 29-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0020": GSRSafetyRule(
        rule_id="GSR_SEC29_0020",
        section_number="G&SR 29.1.3",
        title="Safety Protocol Compliance Clause 29-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0021": GSRSafetyRule(
        rule_id="GSR_SEC29_0021",
        section_number="G&SR 29.2.4",
        title="Safety Protocol Compliance Clause 29-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0022": GSRSafetyRule(
        rule_id="GSR_SEC29_0022",
        section_number="G&SR 29.3.5",
        title="Safety Protocol Compliance Clause 29-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0023": GSRSafetyRule(
        rule_id="GSR_SEC29_0023",
        section_number="G&SR 29.4.6",
        title="Safety Protocol Compliance Clause 29-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0024": GSRSafetyRule(
        rule_id="GSR_SEC29_0024",
        section_number="G&SR 29.5.7",
        title="Safety Protocol Compliance Clause 29-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0025": GSRSafetyRule(
        rule_id="GSR_SEC29_0025",
        section_number="G&SR 29.6.8",
        title="Safety Protocol Compliance Clause 29-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0026": GSRSafetyRule(
        rule_id="GSR_SEC29_0026",
        section_number="G&SR 29.7.9",
        title="Safety Protocol Compliance Clause 29-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0027": GSRSafetyRule(
        rule_id="GSR_SEC29_0027",
        section_number="G&SR 29.8.1",
        title="Safety Protocol Compliance Clause 29-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0028": GSRSafetyRule(
        rule_id="GSR_SEC29_0028",
        section_number="G&SR 29.9.2",
        title="Safety Protocol Compliance Clause 29-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0029": GSRSafetyRule(
        rule_id="GSR_SEC29_0029",
        section_number="G&SR 29.10.3",
        title="Safety Protocol Compliance Clause 29-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0030": GSRSafetyRule(
        rule_id="GSR_SEC29_0030",
        section_number="G&SR 29.11.4",
        title="Safety Protocol Compliance Clause 29-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0031": GSRSafetyRule(
        rule_id="GSR_SEC29_0031",
        section_number="G&SR 29.12.5",
        title="Safety Protocol Compliance Clause 29-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0032": GSRSafetyRule(
        rule_id="GSR_SEC29_0032",
        section_number="G&SR 29.13.6",
        title="Safety Protocol Compliance Clause 29-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0033": GSRSafetyRule(
        rule_id="GSR_SEC29_0033",
        section_number="G&SR 29.14.7",
        title="Safety Protocol Compliance Clause 29-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0034": GSRSafetyRule(
        rule_id="GSR_SEC29_0034",
        section_number="G&SR 29.15.8",
        title="Safety Protocol Compliance Clause 29-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0035": GSRSafetyRule(
        rule_id="GSR_SEC29_0035",
        section_number="G&SR 29.16.9",
        title="Safety Protocol Compliance Clause 29-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0036": GSRSafetyRule(
        rule_id="GSR_SEC29_0036",
        section_number="G&SR 29.17.1",
        title="Safety Protocol Compliance Clause 29-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0037": GSRSafetyRule(
        rule_id="GSR_SEC29_0037",
        section_number="G&SR 29.18.2",
        title="Safety Protocol Compliance Clause 29-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0038": GSRSafetyRule(
        rule_id="GSR_SEC29_0038",
        section_number="G&SR 29.19.3",
        title="Safety Protocol Compliance Clause 29-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0039": GSRSafetyRule(
        rule_id="GSR_SEC29_0039",
        section_number="G&SR 29.20.4",
        title="Safety Protocol Compliance Clause 29-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0040": GSRSafetyRule(
        rule_id="GSR_SEC29_0040",
        section_number="G&SR 29.1.5",
        title="Safety Protocol Compliance Clause 29-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0041": GSRSafetyRule(
        rule_id="GSR_SEC29_0041",
        section_number="G&SR 29.2.6",
        title="Safety Protocol Compliance Clause 29-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0042": GSRSafetyRule(
        rule_id="GSR_SEC29_0042",
        section_number="G&SR 29.3.7",
        title="Safety Protocol Compliance Clause 29-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0043": GSRSafetyRule(
        rule_id="GSR_SEC29_0043",
        section_number="G&SR 29.4.8",
        title="Safety Protocol Compliance Clause 29-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0044": GSRSafetyRule(
        rule_id="GSR_SEC29_0044",
        section_number="G&SR 29.5.9",
        title="Safety Protocol Compliance Clause 29-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0045": GSRSafetyRule(
        rule_id="GSR_SEC29_0045",
        section_number="G&SR 29.6.1",
        title="Safety Protocol Compliance Clause 29-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0046": GSRSafetyRule(
        rule_id="GSR_SEC29_0046",
        section_number="G&SR 29.7.2",
        title="Safety Protocol Compliance Clause 29-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0047": GSRSafetyRule(
        rule_id="GSR_SEC29_0047",
        section_number="G&SR 29.8.3",
        title="Safety Protocol Compliance Clause 29-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0048": GSRSafetyRule(
        rule_id="GSR_SEC29_0048",
        section_number="G&SR 29.9.4",
        title="Safety Protocol Compliance Clause 29-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0049": GSRSafetyRule(
        rule_id="GSR_SEC29_0049",
        section_number="G&SR 29.10.5",
        title="Safety Protocol Compliance Clause 29-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0050": GSRSafetyRule(
        rule_id="GSR_SEC29_0050",
        section_number="G&SR 29.11.6",
        title="Safety Protocol Compliance Clause 29-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0051": GSRSafetyRule(
        rule_id="GSR_SEC29_0051",
        section_number="G&SR 29.12.7",
        title="Safety Protocol Compliance Clause 29-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0052": GSRSafetyRule(
        rule_id="GSR_SEC29_0052",
        section_number="G&SR 29.13.8",
        title="Safety Protocol Compliance Clause 29-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0053": GSRSafetyRule(
        rule_id="GSR_SEC29_0053",
        section_number="G&SR 29.14.9",
        title="Safety Protocol Compliance Clause 29-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0054": GSRSafetyRule(
        rule_id="GSR_SEC29_0054",
        section_number="G&SR 29.15.1",
        title="Safety Protocol Compliance Clause 29-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0055": GSRSafetyRule(
        rule_id="GSR_SEC29_0055",
        section_number="G&SR 29.16.2",
        title="Safety Protocol Compliance Clause 29-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0056": GSRSafetyRule(
        rule_id="GSR_SEC29_0056",
        section_number="G&SR 29.17.3",
        title="Safety Protocol Compliance Clause 29-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0057": GSRSafetyRule(
        rule_id="GSR_SEC29_0057",
        section_number="G&SR 29.18.4",
        title="Safety Protocol Compliance Clause 29-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0058": GSRSafetyRule(
        rule_id="GSR_SEC29_0058",
        section_number="G&SR 29.19.5",
        title="Safety Protocol Compliance Clause 29-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0059": GSRSafetyRule(
        rule_id="GSR_SEC29_0059",
        section_number="G&SR 29.20.6",
        title="Safety Protocol Compliance Clause 29-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0060": GSRSafetyRule(
        rule_id="GSR_SEC29_0060",
        section_number="G&SR 29.1.7",
        title="Safety Protocol Compliance Clause 29-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0061": GSRSafetyRule(
        rule_id="GSR_SEC29_0061",
        section_number="G&SR 29.2.8",
        title="Safety Protocol Compliance Clause 29-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0062": GSRSafetyRule(
        rule_id="GSR_SEC29_0062",
        section_number="G&SR 29.3.9",
        title="Safety Protocol Compliance Clause 29-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0063": GSRSafetyRule(
        rule_id="GSR_SEC29_0063",
        section_number="G&SR 29.4.1",
        title="Safety Protocol Compliance Clause 29-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0064": GSRSafetyRule(
        rule_id="GSR_SEC29_0064",
        section_number="G&SR 29.5.2",
        title="Safety Protocol Compliance Clause 29-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0065": GSRSafetyRule(
        rule_id="GSR_SEC29_0065",
        section_number="G&SR 29.6.3",
        title="Safety Protocol Compliance Clause 29-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0066": GSRSafetyRule(
        rule_id="GSR_SEC29_0066",
        section_number="G&SR 29.7.4",
        title="Safety Protocol Compliance Clause 29-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0067": GSRSafetyRule(
        rule_id="GSR_SEC29_0067",
        section_number="G&SR 29.8.5",
        title="Safety Protocol Compliance Clause 29-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0068": GSRSafetyRule(
        rule_id="GSR_SEC29_0068",
        section_number="G&SR 29.9.6",
        title="Safety Protocol Compliance Clause 29-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0069": GSRSafetyRule(
        rule_id="GSR_SEC29_0069",
        section_number="G&SR 29.10.7",
        title="Safety Protocol Compliance Clause 29-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0070": GSRSafetyRule(
        rule_id="GSR_SEC29_0070",
        section_number="G&SR 29.11.8",
        title="Safety Protocol Compliance Clause 29-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0071": GSRSafetyRule(
        rule_id="GSR_SEC29_0071",
        section_number="G&SR 29.12.9",
        title="Safety Protocol Compliance Clause 29-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0072": GSRSafetyRule(
        rule_id="GSR_SEC29_0072",
        section_number="G&SR 29.13.1",
        title="Safety Protocol Compliance Clause 29-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0073": GSRSafetyRule(
        rule_id="GSR_SEC29_0073",
        section_number="G&SR 29.14.2",
        title="Safety Protocol Compliance Clause 29-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0074": GSRSafetyRule(
        rule_id="GSR_SEC29_0074",
        section_number="G&SR 29.15.3",
        title="Safety Protocol Compliance Clause 29-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0075": GSRSafetyRule(
        rule_id="GSR_SEC29_0075",
        section_number="G&SR 29.16.4",
        title="Safety Protocol Compliance Clause 29-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0076": GSRSafetyRule(
        rule_id="GSR_SEC29_0076",
        section_number="G&SR 29.17.5",
        title="Safety Protocol Compliance Clause 29-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0077": GSRSafetyRule(
        rule_id="GSR_SEC29_0077",
        section_number="G&SR 29.18.6",
        title="Safety Protocol Compliance Clause 29-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0078": GSRSafetyRule(
        rule_id="GSR_SEC29_0078",
        section_number="G&SR 29.19.7",
        title="Safety Protocol Compliance Clause 29-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0079": GSRSafetyRule(
        rule_id="GSR_SEC29_0079",
        section_number="G&SR 29.20.8",
        title="Safety Protocol Compliance Clause 29-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0080": GSRSafetyRule(
        rule_id="GSR_SEC29_0080",
        section_number="G&SR 29.1.9",
        title="Safety Protocol Compliance Clause 29-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0081": GSRSafetyRule(
        rule_id="GSR_SEC29_0081",
        section_number="G&SR 29.2.1",
        title="Safety Protocol Compliance Clause 29-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0082": GSRSafetyRule(
        rule_id="GSR_SEC29_0082",
        section_number="G&SR 29.3.2",
        title="Safety Protocol Compliance Clause 29-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0083": GSRSafetyRule(
        rule_id="GSR_SEC29_0083",
        section_number="G&SR 29.4.3",
        title="Safety Protocol Compliance Clause 29-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0084": GSRSafetyRule(
        rule_id="GSR_SEC29_0084",
        section_number="G&SR 29.5.4",
        title="Safety Protocol Compliance Clause 29-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0085": GSRSafetyRule(
        rule_id="GSR_SEC29_0085",
        section_number="G&SR 29.6.5",
        title="Safety Protocol Compliance Clause 29-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0086": GSRSafetyRule(
        rule_id="GSR_SEC29_0086",
        section_number="G&SR 29.7.6",
        title="Safety Protocol Compliance Clause 29-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0087": GSRSafetyRule(
        rule_id="GSR_SEC29_0087",
        section_number="G&SR 29.8.7",
        title="Safety Protocol Compliance Clause 29-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0088": GSRSafetyRule(
        rule_id="GSR_SEC29_0088",
        section_number="G&SR 29.9.8",
        title="Safety Protocol Compliance Clause 29-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0089": GSRSafetyRule(
        rule_id="GSR_SEC29_0089",
        section_number="G&SR 29.10.9",
        title="Safety Protocol Compliance Clause 29-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0090": GSRSafetyRule(
        rule_id="GSR_SEC29_0090",
        section_number="G&SR 29.11.1",
        title="Safety Protocol Compliance Clause 29-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0091": GSRSafetyRule(
        rule_id="GSR_SEC29_0091",
        section_number="G&SR 29.12.2",
        title="Safety Protocol Compliance Clause 29-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0092": GSRSafetyRule(
        rule_id="GSR_SEC29_0092",
        section_number="G&SR 29.13.3",
        title="Safety Protocol Compliance Clause 29-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0093": GSRSafetyRule(
        rule_id="GSR_SEC29_0093",
        section_number="G&SR 29.14.4",
        title="Safety Protocol Compliance Clause 29-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0094": GSRSafetyRule(
        rule_id="GSR_SEC29_0094",
        section_number="G&SR 29.15.5",
        title="Safety Protocol Compliance Clause 29-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0095": GSRSafetyRule(
        rule_id="GSR_SEC29_0095",
        section_number="G&SR 29.16.6",
        title="Safety Protocol Compliance Clause 29-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0096": GSRSafetyRule(
        rule_id="GSR_SEC29_0096",
        section_number="G&SR 29.17.7",
        title="Safety Protocol Compliance Clause 29-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0097": GSRSafetyRule(
        rule_id="GSR_SEC29_0097",
        section_number="G&SR 29.18.8",
        title="Safety Protocol Compliance Clause 29-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0098": GSRSafetyRule(
        rule_id="GSR_SEC29_0098",
        section_number="G&SR 29.19.9",
        title="Safety Protocol Compliance Clause 29-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0099": GSRSafetyRule(
        rule_id="GSR_SEC29_0099",
        section_number="G&SR 29.20.1",
        title="Safety Protocol Compliance Clause 29-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0100": GSRSafetyRule(
        rule_id="GSR_SEC29_0100",
        section_number="G&SR 29.1.2",
        title="Safety Protocol Compliance Clause 29-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0101": GSRSafetyRule(
        rule_id="GSR_SEC29_0101",
        section_number="G&SR 29.2.3",
        title="Safety Protocol Compliance Clause 29-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0102": GSRSafetyRule(
        rule_id="GSR_SEC29_0102",
        section_number="G&SR 29.3.4",
        title="Safety Protocol Compliance Clause 29-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0103": GSRSafetyRule(
        rule_id="GSR_SEC29_0103",
        section_number="G&SR 29.4.5",
        title="Safety Protocol Compliance Clause 29-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0104": GSRSafetyRule(
        rule_id="GSR_SEC29_0104",
        section_number="G&SR 29.5.6",
        title="Safety Protocol Compliance Clause 29-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0105": GSRSafetyRule(
        rule_id="GSR_SEC29_0105",
        section_number="G&SR 29.6.7",
        title="Safety Protocol Compliance Clause 29-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0106": GSRSafetyRule(
        rule_id="GSR_SEC29_0106",
        section_number="G&SR 29.7.8",
        title="Safety Protocol Compliance Clause 29-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0107": GSRSafetyRule(
        rule_id="GSR_SEC29_0107",
        section_number="G&SR 29.8.9",
        title="Safety Protocol Compliance Clause 29-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0108": GSRSafetyRule(
        rule_id="GSR_SEC29_0108",
        section_number="G&SR 29.9.1",
        title="Safety Protocol Compliance Clause 29-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0109": GSRSafetyRule(
        rule_id="GSR_SEC29_0109",
        section_number="G&SR 29.10.2",
        title="Safety Protocol Compliance Clause 29-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0110": GSRSafetyRule(
        rule_id="GSR_SEC29_0110",
        section_number="G&SR 29.11.3",
        title="Safety Protocol Compliance Clause 29-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0111": GSRSafetyRule(
        rule_id="GSR_SEC29_0111",
        section_number="G&SR 29.12.4",
        title="Safety Protocol Compliance Clause 29-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0112": GSRSafetyRule(
        rule_id="GSR_SEC29_0112",
        section_number="G&SR 29.13.5",
        title="Safety Protocol Compliance Clause 29-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0113": GSRSafetyRule(
        rule_id="GSR_SEC29_0113",
        section_number="G&SR 29.14.6",
        title="Safety Protocol Compliance Clause 29-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0114": GSRSafetyRule(
        rule_id="GSR_SEC29_0114",
        section_number="G&SR 29.15.7",
        title="Safety Protocol Compliance Clause 29-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0115": GSRSafetyRule(
        rule_id="GSR_SEC29_0115",
        section_number="G&SR 29.16.8",
        title="Safety Protocol Compliance Clause 29-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0116": GSRSafetyRule(
        rule_id="GSR_SEC29_0116",
        section_number="G&SR 29.17.9",
        title="Safety Protocol Compliance Clause 29-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0117": GSRSafetyRule(
        rule_id="GSR_SEC29_0117",
        section_number="G&SR 29.18.1",
        title="Safety Protocol Compliance Clause 29-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0118": GSRSafetyRule(
        rule_id="GSR_SEC29_0118",
        section_number="G&SR 29.19.2",
        title="Safety Protocol Compliance Clause 29-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0119": GSRSafetyRule(
        rule_id="GSR_SEC29_0119",
        section_number="G&SR 29.20.3",
        title="Safety Protocol Compliance Clause 29-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0120": GSRSafetyRule(
        rule_id="GSR_SEC29_0120",
        section_number="G&SR 29.1.4",
        title="Safety Protocol Compliance Clause 29-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0121": GSRSafetyRule(
        rule_id="GSR_SEC29_0121",
        section_number="G&SR 29.2.5",
        title="Safety Protocol Compliance Clause 29-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0122": GSRSafetyRule(
        rule_id="GSR_SEC29_0122",
        section_number="G&SR 29.3.6",
        title="Safety Protocol Compliance Clause 29-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0123": GSRSafetyRule(
        rule_id="GSR_SEC29_0123",
        section_number="G&SR 29.4.7",
        title="Safety Protocol Compliance Clause 29-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0124": GSRSafetyRule(
        rule_id="GSR_SEC29_0124",
        section_number="G&SR 29.5.8",
        title="Safety Protocol Compliance Clause 29-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0125": GSRSafetyRule(
        rule_id="GSR_SEC29_0125",
        section_number="G&SR 29.6.9",
        title="Safety Protocol Compliance Clause 29-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0126": GSRSafetyRule(
        rule_id="GSR_SEC29_0126",
        section_number="G&SR 29.7.1",
        title="Safety Protocol Compliance Clause 29-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0127": GSRSafetyRule(
        rule_id="GSR_SEC29_0127",
        section_number="G&SR 29.8.2",
        title="Safety Protocol Compliance Clause 29-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0128": GSRSafetyRule(
        rule_id="GSR_SEC29_0128",
        section_number="G&SR 29.9.3",
        title="Safety Protocol Compliance Clause 29-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0129": GSRSafetyRule(
        rule_id="GSR_SEC29_0129",
        section_number="G&SR 29.10.4",
        title="Safety Protocol Compliance Clause 29-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0130": GSRSafetyRule(
        rule_id="GSR_SEC29_0130",
        section_number="G&SR 29.11.5",
        title="Safety Protocol Compliance Clause 29-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0131": GSRSafetyRule(
        rule_id="GSR_SEC29_0131",
        section_number="G&SR 29.12.6",
        title="Safety Protocol Compliance Clause 29-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0132": GSRSafetyRule(
        rule_id="GSR_SEC29_0132",
        section_number="G&SR 29.13.7",
        title="Safety Protocol Compliance Clause 29-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0133": GSRSafetyRule(
        rule_id="GSR_SEC29_0133",
        section_number="G&SR 29.14.8",
        title="Safety Protocol Compliance Clause 29-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0134": GSRSafetyRule(
        rule_id="GSR_SEC29_0134",
        section_number="G&SR 29.15.9",
        title="Safety Protocol Compliance Clause 29-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0135": GSRSafetyRule(
        rule_id="GSR_SEC29_0135",
        section_number="G&SR 29.16.1",
        title="Safety Protocol Compliance Clause 29-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0136": GSRSafetyRule(
        rule_id="GSR_SEC29_0136",
        section_number="G&SR 29.17.2",
        title="Safety Protocol Compliance Clause 29-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0137": GSRSafetyRule(
        rule_id="GSR_SEC29_0137",
        section_number="G&SR 29.18.3",
        title="Safety Protocol Compliance Clause 29-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0138": GSRSafetyRule(
        rule_id="GSR_SEC29_0138",
        section_number="G&SR 29.19.4",
        title="Safety Protocol Compliance Clause 29-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0139": GSRSafetyRule(
        rule_id="GSR_SEC29_0139",
        section_number="G&SR 29.20.5",
        title="Safety Protocol Compliance Clause 29-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0140": GSRSafetyRule(
        rule_id="GSR_SEC29_0140",
        section_number="G&SR 29.1.6",
        title="Safety Protocol Compliance Clause 29-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0141": GSRSafetyRule(
        rule_id="GSR_SEC29_0141",
        section_number="G&SR 29.2.7",
        title="Safety Protocol Compliance Clause 29-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0142": GSRSafetyRule(
        rule_id="GSR_SEC29_0142",
        section_number="G&SR 29.3.8",
        title="Safety Protocol Compliance Clause 29-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0143": GSRSafetyRule(
        rule_id="GSR_SEC29_0143",
        section_number="G&SR 29.4.9",
        title="Safety Protocol Compliance Clause 29-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0144": GSRSafetyRule(
        rule_id="GSR_SEC29_0144",
        section_number="G&SR 29.5.1",
        title="Safety Protocol Compliance Clause 29-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0145": GSRSafetyRule(
        rule_id="GSR_SEC29_0145",
        section_number="G&SR 29.6.2",
        title="Safety Protocol Compliance Clause 29-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0146": GSRSafetyRule(
        rule_id="GSR_SEC29_0146",
        section_number="G&SR 29.7.3",
        title="Safety Protocol Compliance Clause 29-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0147": GSRSafetyRule(
        rule_id="GSR_SEC29_0147",
        section_number="G&SR 29.8.4",
        title="Safety Protocol Compliance Clause 29-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0148": GSRSafetyRule(
        rule_id="GSR_SEC29_0148",
        section_number="G&SR 29.9.5",
        title="Safety Protocol Compliance Clause 29-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0149": GSRSafetyRule(
        rule_id="GSR_SEC29_0149",
        section_number="G&SR 29.10.6",
        title="Safety Protocol Compliance Clause 29-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0150": GSRSafetyRule(
        rule_id="GSR_SEC29_0150",
        section_number="G&SR 29.11.7",
        title="Safety Protocol Compliance Clause 29-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0151": GSRSafetyRule(
        rule_id="GSR_SEC29_0151",
        section_number="G&SR 29.12.8",
        title="Safety Protocol Compliance Clause 29-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0152": GSRSafetyRule(
        rule_id="GSR_SEC29_0152",
        section_number="G&SR 29.13.9",
        title="Safety Protocol Compliance Clause 29-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0153": GSRSafetyRule(
        rule_id="GSR_SEC29_0153",
        section_number="G&SR 29.14.1",
        title="Safety Protocol Compliance Clause 29-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0154": GSRSafetyRule(
        rule_id="GSR_SEC29_0154",
        section_number="G&SR 29.15.2",
        title="Safety Protocol Compliance Clause 29-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0155": GSRSafetyRule(
        rule_id="GSR_SEC29_0155",
        section_number="G&SR 29.16.3",
        title="Safety Protocol Compliance Clause 29-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0156": GSRSafetyRule(
        rule_id="GSR_SEC29_0156",
        section_number="G&SR 29.17.4",
        title="Safety Protocol Compliance Clause 29-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0157": GSRSafetyRule(
        rule_id="GSR_SEC29_0157",
        section_number="G&SR 29.18.5",
        title="Safety Protocol Compliance Clause 29-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0158": GSRSafetyRule(
        rule_id="GSR_SEC29_0158",
        section_number="G&SR 29.19.6",
        title="Safety Protocol Compliance Clause 29-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0159": GSRSafetyRule(
        rule_id="GSR_SEC29_0159",
        section_number="G&SR 29.20.7",
        title="Safety Protocol Compliance Clause 29-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0160": GSRSafetyRule(
        rule_id="GSR_SEC29_0160",
        section_number="G&SR 29.1.8",
        title="Safety Protocol Compliance Clause 29-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0161": GSRSafetyRule(
        rule_id="GSR_SEC29_0161",
        section_number="G&SR 29.2.9",
        title="Safety Protocol Compliance Clause 29-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0162": GSRSafetyRule(
        rule_id="GSR_SEC29_0162",
        section_number="G&SR 29.3.1",
        title="Safety Protocol Compliance Clause 29-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0163": GSRSafetyRule(
        rule_id="GSR_SEC29_0163",
        section_number="G&SR 29.4.2",
        title="Safety Protocol Compliance Clause 29-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0164": GSRSafetyRule(
        rule_id="GSR_SEC29_0164",
        section_number="G&SR 29.5.3",
        title="Safety Protocol Compliance Clause 29-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0165": GSRSafetyRule(
        rule_id="GSR_SEC29_0165",
        section_number="G&SR 29.6.4",
        title="Safety Protocol Compliance Clause 29-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0166": GSRSafetyRule(
        rule_id="GSR_SEC29_0166",
        section_number="G&SR 29.7.5",
        title="Safety Protocol Compliance Clause 29-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0167": GSRSafetyRule(
        rule_id="GSR_SEC29_0167",
        section_number="G&SR 29.8.6",
        title="Safety Protocol Compliance Clause 29-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0168": GSRSafetyRule(
        rule_id="GSR_SEC29_0168",
        section_number="G&SR 29.9.7",
        title="Safety Protocol Compliance Clause 29-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0169": GSRSafetyRule(
        rule_id="GSR_SEC29_0169",
        section_number="G&SR 29.10.8",
        title="Safety Protocol Compliance Clause 29-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0170": GSRSafetyRule(
        rule_id="GSR_SEC29_0170",
        section_number="G&SR 29.11.9",
        title="Safety Protocol Compliance Clause 29-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0171": GSRSafetyRule(
        rule_id="GSR_SEC29_0171",
        section_number="G&SR 29.12.1",
        title="Safety Protocol Compliance Clause 29-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0172": GSRSafetyRule(
        rule_id="GSR_SEC29_0172",
        section_number="G&SR 29.13.2",
        title="Safety Protocol Compliance Clause 29-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0173": GSRSafetyRule(
        rule_id="GSR_SEC29_0173",
        section_number="G&SR 29.14.3",
        title="Safety Protocol Compliance Clause 29-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC29_0174": GSRSafetyRule(
        rule_id="GSR_SEC29_0174",
        section_number="G&SR 29.15.4",
        title="Safety Protocol Compliance Clause 29-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
