"""Indian Railways G&SR Regulatory Rulebook Section 007."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class GSRSafetyRule:
    rule_id: str
    section_number: str
    title: str
    category: str
    severity: str
    enforcement_action: str
    requires_pilot_guard: bool
    max_speed_override_kmh: float
    description: str

GSR_RULEBOOK_SECTION_007: Dict[str, GSRSafetyRule] = {
    "GSR_SEC07_0001": GSRSafetyRule(
        rule_id="GSR_SEC07_0001",
        section_number="G&SR 7.2.2",
        title="Safety Protocol Compliance Clause 7-1",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0002": GSRSafetyRule(
        rule_id="GSR_SEC07_0002",
        section_number="G&SR 7.3.3",
        title="Safety Protocol Compliance Clause 7-2",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0003": GSRSafetyRule(
        rule_id="GSR_SEC07_0003",
        section_number="G&SR 7.4.4",
        title="Safety Protocol Compliance Clause 7-3",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0004": GSRSafetyRule(
        rule_id="GSR_SEC07_0004",
        section_number="G&SR 7.5.5",
        title="Safety Protocol Compliance Clause 7-4",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0005": GSRSafetyRule(
        rule_id="GSR_SEC07_0005",
        section_number="G&SR 7.6.6",
        title="Safety Protocol Compliance Clause 7-5",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0006": GSRSafetyRule(
        rule_id="GSR_SEC07_0006",
        section_number="G&SR 7.7.7",
        title="Safety Protocol Compliance Clause 7-6",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0007": GSRSafetyRule(
        rule_id="GSR_SEC07_0007",
        section_number="G&SR 7.8.8",
        title="Safety Protocol Compliance Clause 7-7",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0008": GSRSafetyRule(
        rule_id="GSR_SEC07_0008",
        section_number="G&SR 7.9.9",
        title="Safety Protocol Compliance Clause 7-8",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0009": GSRSafetyRule(
        rule_id="GSR_SEC07_0009",
        section_number="G&SR 7.10.1",
        title="Safety Protocol Compliance Clause 7-9",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0010": GSRSafetyRule(
        rule_id="GSR_SEC07_0010",
        section_number="G&SR 7.11.2",
        title="Safety Protocol Compliance Clause 7-10",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0011": GSRSafetyRule(
        rule_id="GSR_SEC07_0011",
        section_number="G&SR 7.12.3",
        title="Safety Protocol Compliance Clause 7-11",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0012": GSRSafetyRule(
        rule_id="GSR_SEC07_0012",
        section_number="G&SR 7.13.4",
        title="Safety Protocol Compliance Clause 7-12",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0013": GSRSafetyRule(
        rule_id="GSR_SEC07_0013",
        section_number="G&SR 7.14.5",
        title="Safety Protocol Compliance Clause 7-13",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0014": GSRSafetyRule(
        rule_id="GSR_SEC07_0014",
        section_number="G&SR 7.15.6",
        title="Safety Protocol Compliance Clause 7-14",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0015": GSRSafetyRule(
        rule_id="GSR_SEC07_0015",
        section_number="G&SR 7.16.7",
        title="Safety Protocol Compliance Clause 7-15",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0016": GSRSafetyRule(
        rule_id="GSR_SEC07_0016",
        section_number="G&SR 7.17.8",
        title="Safety Protocol Compliance Clause 7-16",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0017": GSRSafetyRule(
        rule_id="GSR_SEC07_0017",
        section_number="G&SR 7.18.9",
        title="Safety Protocol Compliance Clause 7-17",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0018": GSRSafetyRule(
        rule_id="GSR_SEC07_0018",
        section_number="G&SR 7.19.1",
        title="Safety Protocol Compliance Clause 7-18",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0019": GSRSafetyRule(
        rule_id="GSR_SEC07_0019",
        section_number="G&SR 7.20.2",
        title="Safety Protocol Compliance Clause 7-19",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0020": GSRSafetyRule(
        rule_id="GSR_SEC07_0020",
        section_number="G&SR 7.1.3",
        title="Safety Protocol Compliance Clause 7-20",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0021": GSRSafetyRule(
        rule_id="GSR_SEC07_0021",
        section_number="G&SR 7.2.4",
        title="Safety Protocol Compliance Clause 7-21",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0022": GSRSafetyRule(
        rule_id="GSR_SEC07_0022",
        section_number="G&SR 7.3.5",
        title="Safety Protocol Compliance Clause 7-22",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0023": GSRSafetyRule(
        rule_id="GSR_SEC07_0023",
        section_number="G&SR 7.4.6",
        title="Safety Protocol Compliance Clause 7-23",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0024": GSRSafetyRule(
        rule_id="GSR_SEC07_0024",
        section_number="G&SR 7.5.7",
        title="Safety Protocol Compliance Clause 7-24",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0025": GSRSafetyRule(
        rule_id="GSR_SEC07_0025",
        section_number="G&SR 7.6.8",
        title="Safety Protocol Compliance Clause 7-25",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0026": GSRSafetyRule(
        rule_id="GSR_SEC07_0026",
        section_number="G&SR 7.7.9",
        title="Safety Protocol Compliance Clause 7-26",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0027": GSRSafetyRule(
        rule_id="GSR_SEC07_0027",
        section_number="G&SR 7.8.1",
        title="Safety Protocol Compliance Clause 7-27",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0028": GSRSafetyRule(
        rule_id="GSR_SEC07_0028",
        section_number="G&SR 7.9.2",
        title="Safety Protocol Compliance Clause 7-28",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0029": GSRSafetyRule(
        rule_id="GSR_SEC07_0029",
        section_number="G&SR 7.10.3",
        title="Safety Protocol Compliance Clause 7-29",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0030": GSRSafetyRule(
        rule_id="GSR_SEC07_0030",
        section_number="G&SR 7.11.4",
        title="Safety Protocol Compliance Clause 7-30",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0031": GSRSafetyRule(
        rule_id="GSR_SEC07_0031",
        section_number="G&SR 7.12.5",
        title="Safety Protocol Compliance Clause 7-31",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0032": GSRSafetyRule(
        rule_id="GSR_SEC07_0032",
        section_number="G&SR 7.13.6",
        title="Safety Protocol Compliance Clause 7-32",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0033": GSRSafetyRule(
        rule_id="GSR_SEC07_0033",
        section_number="G&SR 7.14.7",
        title="Safety Protocol Compliance Clause 7-33",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0034": GSRSafetyRule(
        rule_id="GSR_SEC07_0034",
        section_number="G&SR 7.15.8",
        title="Safety Protocol Compliance Clause 7-34",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0035": GSRSafetyRule(
        rule_id="GSR_SEC07_0035",
        section_number="G&SR 7.16.9",
        title="Safety Protocol Compliance Clause 7-35",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0036": GSRSafetyRule(
        rule_id="GSR_SEC07_0036",
        section_number="G&SR 7.17.1",
        title="Safety Protocol Compliance Clause 7-36",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0037": GSRSafetyRule(
        rule_id="GSR_SEC07_0037",
        section_number="G&SR 7.18.2",
        title="Safety Protocol Compliance Clause 7-37",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0038": GSRSafetyRule(
        rule_id="GSR_SEC07_0038",
        section_number="G&SR 7.19.3",
        title="Safety Protocol Compliance Clause 7-38",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0039": GSRSafetyRule(
        rule_id="GSR_SEC07_0039",
        section_number="G&SR 7.20.4",
        title="Safety Protocol Compliance Clause 7-39",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0040": GSRSafetyRule(
        rule_id="GSR_SEC07_0040",
        section_number="G&SR 7.1.5",
        title="Safety Protocol Compliance Clause 7-40",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0041": GSRSafetyRule(
        rule_id="GSR_SEC07_0041",
        section_number="G&SR 7.2.6",
        title="Safety Protocol Compliance Clause 7-41",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0042": GSRSafetyRule(
        rule_id="GSR_SEC07_0042",
        section_number="G&SR 7.3.7",
        title="Safety Protocol Compliance Clause 7-42",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0043": GSRSafetyRule(
        rule_id="GSR_SEC07_0043",
        section_number="G&SR 7.4.8",
        title="Safety Protocol Compliance Clause 7-43",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0044": GSRSafetyRule(
        rule_id="GSR_SEC07_0044",
        section_number="G&SR 7.5.9",
        title="Safety Protocol Compliance Clause 7-44",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0045": GSRSafetyRule(
        rule_id="GSR_SEC07_0045",
        section_number="G&SR 7.6.1",
        title="Safety Protocol Compliance Clause 7-45",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0046": GSRSafetyRule(
        rule_id="GSR_SEC07_0046",
        section_number="G&SR 7.7.2",
        title="Safety Protocol Compliance Clause 7-46",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0047": GSRSafetyRule(
        rule_id="GSR_SEC07_0047",
        section_number="G&SR 7.8.3",
        title="Safety Protocol Compliance Clause 7-47",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0048": GSRSafetyRule(
        rule_id="GSR_SEC07_0048",
        section_number="G&SR 7.9.4",
        title="Safety Protocol Compliance Clause 7-48",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0049": GSRSafetyRule(
        rule_id="GSR_SEC07_0049",
        section_number="G&SR 7.10.5",
        title="Safety Protocol Compliance Clause 7-49",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0050": GSRSafetyRule(
        rule_id="GSR_SEC07_0050",
        section_number="G&SR 7.11.6",
        title="Safety Protocol Compliance Clause 7-50",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0051": GSRSafetyRule(
        rule_id="GSR_SEC07_0051",
        section_number="G&SR 7.12.7",
        title="Safety Protocol Compliance Clause 7-51",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0052": GSRSafetyRule(
        rule_id="GSR_SEC07_0052",
        section_number="G&SR 7.13.8",
        title="Safety Protocol Compliance Clause 7-52",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0053": GSRSafetyRule(
        rule_id="GSR_SEC07_0053",
        section_number="G&SR 7.14.9",
        title="Safety Protocol Compliance Clause 7-53",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0054": GSRSafetyRule(
        rule_id="GSR_SEC07_0054",
        section_number="G&SR 7.15.1",
        title="Safety Protocol Compliance Clause 7-54",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0055": GSRSafetyRule(
        rule_id="GSR_SEC07_0055",
        section_number="G&SR 7.16.2",
        title="Safety Protocol Compliance Clause 7-55",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0056": GSRSafetyRule(
        rule_id="GSR_SEC07_0056",
        section_number="G&SR 7.17.3",
        title="Safety Protocol Compliance Clause 7-56",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0057": GSRSafetyRule(
        rule_id="GSR_SEC07_0057",
        section_number="G&SR 7.18.4",
        title="Safety Protocol Compliance Clause 7-57",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0058": GSRSafetyRule(
        rule_id="GSR_SEC07_0058",
        section_number="G&SR 7.19.5",
        title="Safety Protocol Compliance Clause 7-58",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0059": GSRSafetyRule(
        rule_id="GSR_SEC07_0059",
        section_number="G&SR 7.20.6",
        title="Safety Protocol Compliance Clause 7-59",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0060": GSRSafetyRule(
        rule_id="GSR_SEC07_0060",
        section_number="G&SR 7.1.7",
        title="Safety Protocol Compliance Clause 7-60",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0061": GSRSafetyRule(
        rule_id="GSR_SEC07_0061",
        section_number="G&SR 7.2.8",
        title="Safety Protocol Compliance Clause 7-61",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0062": GSRSafetyRule(
        rule_id="GSR_SEC07_0062",
        section_number="G&SR 7.3.9",
        title="Safety Protocol Compliance Clause 7-62",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0063": GSRSafetyRule(
        rule_id="GSR_SEC07_0063",
        section_number="G&SR 7.4.1",
        title="Safety Protocol Compliance Clause 7-63",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0064": GSRSafetyRule(
        rule_id="GSR_SEC07_0064",
        section_number="G&SR 7.5.2",
        title="Safety Protocol Compliance Clause 7-64",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0065": GSRSafetyRule(
        rule_id="GSR_SEC07_0065",
        section_number="G&SR 7.6.3",
        title="Safety Protocol Compliance Clause 7-65",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0066": GSRSafetyRule(
        rule_id="GSR_SEC07_0066",
        section_number="G&SR 7.7.4",
        title="Safety Protocol Compliance Clause 7-66",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0067": GSRSafetyRule(
        rule_id="GSR_SEC07_0067",
        section_number="G&SR 7.8.5",
        title="Safety Protocol Compliance Clause 7-67",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0068": GSRSafetyRule(
        rule_id="GSR_SEC07_0068",
        section_number="G&SR 7.9.6",
        title="Safety Protocol Compliance Clause 7-68",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0069": GSRSafetyRule(
        rule_id="GSR_SEC07_0069",
        section_number="G&SR 7.10.7",
        title="Safety Protocol Compliance Clause 7-69",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0070": GSRSafetyRule(
        rule_id="GSR_SEC07_0070",
        section_number="G&SR 7.11.8",
        title="Safety Protocol Compliance Clause 7-70",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0071": GSRSafetyRule(
        rule_id="GSR_SEC07_0071",
        section_number="G&SR 7.12.9",
        title="Safety Protocol Compliance Clause 7-71",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0072": GSRSafetyRule(
        rule_id="GSR_SEC07_0072",
        section_number="G&SR 7.13.1",
        title="Safety Protocol Compliance Clause 7-72",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0073": GSRSafetyRule(
        rule_id="GSR_SEC07_0073",
        section_number="G&SR 7.14.2",
        title="Safety Protocol Compliance Clause 7-73",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0074": GSRSafetyRule(
        rule_id="GSR_SEC07_0074",
        section_number="G&SR 7.15.3",
        title="Safety Protocol Compliance Clause 7-74",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0075": GSRSafetyRule(
        rule_id="GSR_SEC07_0075",
        section_number="G&SR 7.16.4",
        title="Safety Protocol Compliance Clause 7-75",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0076": GSRSafetyRule(
        rule_id="GSR_SEC07_0076",
        section_number="G&SR 7.17.5",
        title="Safety Protocol Compliance Clause 7-76",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0077": GSRSafetyRule(
        rule_id="GSR_SEC07_0077",
        section_number="G&SR 7.18.6",
        title="Safety Protocol Compliance Clause 7-77",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0078": GSRSafetyRule(
        rule_id="GSR_SEC07_0078",
        section_number="G&SR 7.19.7",
        title="Safety Protocol Compliance Clause 7-78",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0079": GSRSafetyRule(
        rule_id="GSR_SEC07_0079",
        section_number="G&SR 7.20.8",
        title="Safety Protocol Compliance Clause 7-79",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0080": GSRSafetyRule(
        rule_id="GSR_SEC07_0080",
        section_number="G&SR 7.1.9",
        title="Safety Protocol Compliance Clause 7-80",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0081": GSRSafetyRule(
        rule_id="GSR_SEC07_0081",
        section_number="G&SR 7.2.1",
        title="Safety Protocol Compliance Clause 7-81",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0082": GSRSafetyRule(
        rule_id="GSR_SEC07_0082",
        section_number="G&SR 7.3.2",
        title="Safety Protocol Compliance Clause 7-82",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0083": GSRSafetyRule(
        rule_id="GSR_SEC07_0083",
        section_number="G&SR 7.4.3",
        title="Safety Protocol Compliance Clause 7-83",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0084": GSRSafetyRule(
        rule_id="GSR_SEC07_0084",
        section_number="G&SR 7.5.4",
        title="Safety Protocol Compliance Clause 7-84",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0085": GSRSafetyRule(
        rule_id="GSR_SEC07_0085",
        section_number="G&SR 7.6.5",
        title="Safety Protocol Compliance Clause 7-85",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0086": GSRSafetyRule(
        rule_id="GSR_SEC07_0086",
        section_number="G&SR 7.7.6",
        title="Safety Protocol Compliance Clause 7-86",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0087": GSRSafetyRule(
        rule_id="GSR_SEC07_0087",
        section_number="G&SR 7.8.7",
        title="Safety Protocol Compliance Clause 7-87",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0088": GSRSafetyRule(
        rule_id="GSR_SEC07_0088",
        section_number="G&SR 7.9.8",
        title="Safety Protocol Compliance Clause 7-88",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0089": GSRSafetyRule(
        rule_id="GSR_SEC07_0089",
        section_number="G&SR 7.10.9",
        title="Safety Protocol Compliance Clause 7-89",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0090": GSRSafetyRule(
        rule_id="GSR_SEC07_0090",
        section_number="G&SR 7.11.1",
        title="Safety Protocol Compliance Clause 7-90",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0091": GSRSafetyRule(
        rule_id="GSR_SEC07_0091",
        section_number="G&SR 7.12.2",
        title="Safety Protocol Compliance Clause 7-91",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0092": GSRSafetyRule(
        rule_id="GSR_SEC07_0092",
        section_number="G&SR 7.13.3",
        title="Safety Protocol Compliance Clause 7-92",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0093": GSRSafetyRule(
        rule_id="GSR_SEC07_0093",
        section_number="G&SR 7.14.4",
        title="Safety Protocol Compliance Clause 7-93",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0094": GSRSafetyRule(
        rule_id="GSR_SEC07_0094",
        section_number="G&SR 7.15.5",
        title="Safety Protocol Compliance Clause 7-94",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0095": GSRSafetyRule(
        rule_id="GSR_SEC07_0095",
        section_number="G&SR 7.16.6",
        title="Safety Protocol Compliance Clause 7-95",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0096": GSRSafetyRule(
        rule_id="GSR_SEC07_0096",
        section_number="G&SR 7.17.7",
        title="Safety Protocol Compliance Clause 7-96",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0097": GSRSafetyRule(
        rule_id="GSR_SEC07_0097",
        section_number="G&SR 7.18.8",
        title="Safety Protocol Compliance Clause 7-97",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0098": GSRSafetyRule(
        rule_id="GSR_SEC07_0098",
        section_number="G&SR 7.19.9",
        title="Safety Protocol Compliance Clause 7-98",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0099": GSRSafetyRule(
        rule_id="GSR_SEC07_0099",
        section_number="G&SR 7.20.1",
        title="Safety Protocol Compliance Clause 7-99",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0100": GSRSafetyRule(
        rule_id="GSR_SEC07_0100",
        section_number="G&SR 7.1.2",
        title="Safety Protocol Compliance Clause 7-100",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0101": GSRSafetyRule(
        rule_id="GSR_SEC07_0101",
        section_number="G&SR 7.2.3",
        title="Safety Protocol Compliance Clause 7-101",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0102": GSRSafetyRule(
        rule_id="GSR_SEC07_0102",
        section_number="G&SR 7.3.4",
        title="Safety Protocol Compliance Clause 7-102",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0103": GSRSafetyRule(
        rule_id="GSR_SEC07_0103",
        section_number="G&SR 7.4.5",
        title="Safety Protocol Compliance Clause 7-103",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0104": GSRSafetyRule(
        rule_id="GSR_SEC07_0104",
        section_number="G&SR 7.5.6",
        title="Safety Protocol Compliance Clause 7-104",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0105": GSRSafetyRule(
        rule_id="GSR_SEC07_0105",
        section_number="G&SR 7.6.7",
        title="Safety Protocol Compliance Clause 7-105",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0106": GSRSafetyRule(
        rule_id="GSR_SEC07_0106",
        section_number="G&SR 7.7.8",
        title="Safety Protocol Compliance Clause 7-106",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0107": GSRSafetyRule(
        rule_id="GSR_SEC07_0107",
        section_number="G&SR 7.8.9",
        title="Safety Protocol Compliance Clause 7-107",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0108": GSRSafetyRule(
        rule_id="GSR_SEC07_0108",
        section_number="G&SR 7.9.1",
        title="Safety Protocol Compliance Clause 7-108",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0109": GSRSafetyRule(
        rule_id="GSR_SEC07_0109",
        section_number="G&SR 7.10.2",
        title="Safety Protocol Compliance Clause 7-109",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0110": GSRSafetyRule(
        rule_id="GSR_SEC07_0110",
        section_number="G&SR 7.11.3",
        title="Safety Protocol Compliance Clause 7-110",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0111": GSRSafetyRule(
        rule_id="GSR_SEC07_0111",
        section_number="G&SR 7.12.4",
        title="Safety Protocol Compliance Clause 7-111",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0112": GSRSafetyRule(
        rule_id="GSR_SEC07_0112",
        section_number="G&SR 7.13.5",
        title="Safety Protocol Compliance Clause 7-112",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0113": GSRSafetyRule(
        rule_id="GSR_SEC07_0113",
        section_number="G&SR 7.14.6",
        title="Safety Protocol Compliance Clause 7-113",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0114": GSRSafetyRule(
        rule_id="GSR_SEC07_0114",
        section_number="G&SR 7.15.7",
        title="Safety Protocol Compliance Clause 7-114",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0115": GSRSafetyRule(
        rule_id="GSR_SEC07_0115",
        section_number="G&SR 7.16.8",
        title="Safety Protocol Compliance Clause 7-115",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0116": GSRSafetyRule(
        rule_id="GSR_SEC07_0116",
        section_number="G&SR 7.17.9",
        title="Safety Protocol Compliance Clause 7-116",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0117": GSRSafetyRule(
        rule_id="GSR_SEC07_0117",
        section_number="G&SR 7.18.1",
        title="Safety Protocol Compliance Clause 7-117",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0118": GSRSafetyRule(
        rule_id="GSR_SEC07_0118",
        section_number="G&SR 7.19.2",
        title="Safety Protocol Compliance Clause 7-118",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0119": GSRSafetyRule(
        rule_id="GSR_SEC07_0119",
        section_number="G&SR 7.20.3",
        title="Safety Protocol Compliance Clause 7-119",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0120": GSRSafetyRule(
        rule_id="GSR_SEC07_0120",
        section_number="G&SR 7.1.4",
        title="Safety Protocol Compliance Clause 7-120",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0121": GSRSafetyRule(
        rule_id="GSR_SEC07_0121",
        section_number="G&SR 7.2.5",
        title="Safety Protocol Compliance Clause 7-121",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0122": GSRSafetyRule(
        rule_id="GSR_SEC07_0122",
        section_number="G&SR 7.3.6",
        title="Safety Protocol Compliance Clause 7-122",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0123": GSRSafetyRule(
        rule_id="GSR_SEC07_0123",
        section_number="G&SR 7.4.7",
        title="Safety Protocol Compliance Clause 7-123",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0124": GSRSafetyRule(
        rule_id="GSR_SEC07_0124",
        section_number="G&SR 7.5.8",
        title="Safety Protocol Compliance Clause 7-124",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0125": GSRSafetyRule(
        rule_id="GSR_SEC07_0125",
        section_number="G&SR 7.6.9",
        title="Safety Protocol Compliance Clause 7-125",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0126": GSRSafetyRule(
        rule_id="GSR_SEC07_0126",
        section_number="G&SR 7.7.1",
        title="Safety Protocol Compliance Clause 7-126",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0127": GSRSafetyRule(
        rule_id="GSR_SEC07_0127",
        section_number="G&SR 7.8.2",
        title="Safety Protocol Compliance Clause 7-127",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0128": GSRSafetyRule(
        rule_id="GSR_SEC07_0128",
        section_number="G&SR 7.9.3",
        title="Safety Protocol Compliance Clause 7-128",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0129": GSRSafetyRule(
        rule_id="GSR_SEC07_0129",
        section_number="G&SR 7.10.4",
        title="Safety Protocol Compliance Clause 7-129",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0130": GSRSafetyRule(
        rule_id="GSR_SEC07_0130",
        section_number="G&SR 7.11.5",
        title="Safety Protocol Compliance Clause 7-130",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0131": GSRSafetyRule(
        rule_id="GSR_SEC07_0131",
        section_number="G&SR 7.12.6",
        title="Safety Protocol Compliance Clause 7-131",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0132": GSRSafetyRule(
        rule_id="GSR_SEC07_0132",
        section_number="G&SR 7.13.7",
        title="Safety Protocol Compliance Clause 7-132",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0133": GSRSafetyRule(
        rule_id="GSR_SEC07_0133",
        section_number="G&SR 7.14.8",
        title="Safety Protocol Compliance Clause 7-133",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0134": GSRSafetyRule(
        rule_id="GSR_SEC07_0134",
        section_number="G&SR 7.15.9",
        title="Safety Protocol Compliance Clause 7-134",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0135": GSRSafetyRule(
        rule_id="GSR_SEC07_0135",
        section_number="G&SR 7.16.1",
        title="Safety Protocol Compliance Clause 7-135",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0136": GSRSafetyRule(
        rule_id="GSR_SEC07_0136",
        section_number="G&SR 7.17.2",
        title="Safety Protocol Compliance Clause 7-136",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0137": GSRSafetyRule(
        rule_id="GSR_SEC07_0137",
        section_number="G&SR 7.18.3",
        title="Safety Protocol Compliance Clause 7-137",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0138": GSRSafetyRule(
        rule_id="GSR_SEC07_0138",
        section_number="G&SR 7.19.4",
        title="Safety Protocol Compliance Clause 7-138",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0139": GSRSafetyRule(
        rule_id="GSR_SEC07_0139",
        section_number="G&SR 7.20.5",
        title="Safety Protocol Compliance Clause 7-139",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0140": GSRSafetyRule(
        rule_id="GSR_SEC07_0140",
        section_number="G&SR 7.1.6",
        title="Safety Protocol Compliance Clause 7-140",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0141": GSRSafetyRule(
        rule_id="GSR_SEC07_0141",
        section_number="G&SR 7.2.7",
        title="Safety Protocol Compliance Clause 7-141",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0142": GSRSafetyRule(
        rule_id="GSR_SEC07_0142",
        section_number="G&SR 7.3.8",
        title="Safety Protocol Compliance Clause 7-142",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0143": GSRSafetyRule(
        rule_id="GSR_SEC07_0143",
        section_number="G&SR 7.4.9",
        title="Safety Protocol Compliance Clause 7-143",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0144": GSRSafetyRule(
        rule_id="GSR_SEC07_0144",
        section_number="G&SR 7.5.1",
        title="Safety Protocol Compliance Clause 7-144",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0145": GSRSafetyRule(
        rule_id="GSR_SEC07_0145",
        section_number="G&SR 7.6.2",
        title="Safety Protocol Compliance Clause 7-145",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0146": GSRSafetyRule(
        rule_id="GSR_SEC07_0146",
        section_number="G&SR 7.7.3",
        title="Safety Protocol Compliance Clause 7-146",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0147": GSRSafetyRule(
        rule_id="GSR_SEC07_0147",
        section_number="G&SR 7.8.4",
        title="Safety Protocol Compliance Clause 7-147",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0148": GSRSafetyRule(
        rule_id="GSR_SEC07_0148",
        section_number="G&SR 7.9.5",
        title="Safety Protocol Compliance Clause 7-148",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0149": GSRSafetyRule(
        rule_id="GSR_SEC07_0149",
        section_number="G&SR 7.10.6",
        title="Safety Protocol Compliance Clause 7-149",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0150": GSRSafetyRule(
        rule_id="GSR_SEC07_0150",
        section_number="G&SR 7.11.7",
        title="Safety Protocol Compliance Clause 7-150",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0151": GSRSafetyRule(
        rule_id="GSR_SEC07_0151",
        section_number="G&SR 7.12.8",
        title="Safety Protocol Compliance Clause 7-151",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0152": GSRSafetyRule(
        rule_id="GSR_SEC07_0152",
        section_number="G&SR 7.13.9",
        title="Safety Protocol Compliance Clause 7-152",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0153": GSRSafetyRule(
        rule_id="GSR_SEC07_0153",
        section_number="G&SR 7.14.1",
        title="Safety Protocol Compliance Clause 7-153",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0154": GSRSafetyRule(
        rule_id="GSR_SEC07_0154",
        section_number="G&SR 7.15.2",
        title="Safety Protocol Compliance Clause 7-154",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0155": GSRSafetyRule(
        rule_id="GSR_SEC07_0155",
        section_number="G&SR 7.16.3",
        title="Safety Protocol Compliance Clause 7-155",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0156": GSRSafetyRule(
        rule_id="GSR_SEC07_0156",
        section_number="G&SR 7.17.4",
        title="Safety Protocol Compliance Clause 7-156",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0157": GSRSafetyRule(
        rule_id="GSR_SEC07_0157",
        section_number="G&SR 7.18.5",
        title="Safety Protocol Compliance Clause 7-157",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0158": GSRSafetyRule(
        rule_id="GSR_SEC07_0158",
        section_number="G&SR 7.19.6",
        title="Safety Protocol Compliance Clause 7-158",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0159": GSRSafetyRule(
        rule_id="GSR_SEC07_0159",
        section_number="G&SR 7.20.7",
        title="Safety Protocol Compliance Clause 7-159",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0160": GSRSafetyRule(
        rule_id="GSR_SEC07_0160",
        section_number="G&SR 7.1.8",
        title="Safety Protocol Compliance Clause 7-160",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0161": GSRSafetyRule(
        rule_id="GSR_SEC07_0161",
        section_number="G&SR 7.2.9",
        title="Safety Protocol Compliance Clause 7-161",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0162": GSRSafetyRule(
        rule_id="GSR_SEC07_0162",
        section_number="G&SR 7.3.1",
        title="Safety Protocol Compliance Clause 7-162",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0163": GSRSafetyRule(
        rule_id="GSR_SEC07_0163",
        section_number="G&SR 7.4.2",
        title="Safety Protocol Compliance Clause 7-163",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0164": GSRSafetyRule(
        rule_id="GSR_SEC07_0164",
        section_number="G&SR 7.5.3",
        title="Safety Protocol Compliance Clause 7-164",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0165": GSRSafetyRule(
        rule_id="GSR_SEC07_0165",
        section_number="G&SR 7.6.4",
        title="Safety Protocol Compliance Clause 7-165",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0166": GSRSafetyRule(
        rule_id="GSR_SEC07_0166",
        section_number="G&SR 7.7.5",
        title="Safety Protocol Compliance Clause 7-166",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0167": GSRSafetyRule(
        rule_id="GSR_SEC07_0167",
        section_number="G&SR 7.8.6",
        title="Safety Protocol Compliance Clause 7-167",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0168": GSRSafetyRule(
        rule_id="GSR_SEC07_0168",
        section_number="G&SR 7.9.7",
        title="Safety Protocol Compliance Clause 7-168",
        category="AUTOMATIC_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for AUTOMATIC_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0169": GSRSafetyRule(
        rule_id="GSR_SEC07_0169",
        section_number="G&SR 7.10.8",
        title="Safety Protocol Compliance Clause 7-169",
        category="ABSOLUTE_BLOCK",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ABSOLUTE_BLOCK under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0170": GSRSafetyRule(
        rule_id="GSR_SEC07_0170",
        section_number="G&SR 7.11.9",
        title="Safety Protocol Compliance Clause 7-170",
        category="SPEED_RESTRICTIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SPEED_RESTRICTIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0171": GSRSafetyRule(
        rule_id="GSR_SEC07_0171",
        section_number="G&SR 7.12.1",
        title="Safety Protocol Compliance Clause 7-171",
        category="ACCIDENT_RELIEF",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for ACCIDENT_RELIEF under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0172": GSRSafetyRule(
        rule_id="GSR_SEC07_0172",
        section_number="G&SR 7.13.2",
        title="Safety Protocol Compliance Clause 7-172",
        category="SHUNTING_OPERATIONS",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=True,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for SHUNTING_OPERATIONS under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0173": GSRSafetyRule(
        rule_id="GSR_SEC07_0173",
        section_number="G&SR 7.14.3",
        title="Safety Protocol Compliance Clause 7-173",
        category="LEVEL_CROSSING_GATES",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for LEVEL_CROSSING_GATES under Indian Railway standard specifications."
    ),
    "GSR_SEC07_0174": GSRSafetyRule(
        rule_id="GSR_SEC07_0174",
        section_number="G&SR 7.15.4",
        title="Safety Protocol Compliance Clause 7-174",
        category="FOG_SIGNALING",
        severity="CRITICAL",
        enforcement_action="DISPATCHER_OVERRIDE_REQUIRED",
        requires_pilot_guard=False,
        max_speed_override_kmh=15.0,
        description="Mandatory compliance clause for FOG_SIGNALING under Indian Railway standard specifications."
    ),
}
