"""Station Network Topology Cluster Partition 026."""

from dataclasses import dataclass
from typing import List, Dict

@dataclass
class StationRecord:
    code: str
    name: str
    zone: str
    division: str
    elevation_m: float
    platforms: int
    loop_lines: int
    electrified: bool
    station_type: str
    kavach_atp_level: str
    rfid_tags: List[str]
    catenary_voltage_kv: float
    max_permissible_speed_kmh: float
    has_crew_change: bool
    freight_siding_m: float

STATION_ZONE_CLUSTER_026: Dict[str, StationRecord] = {
    "IR_ZN26_0001": StationRecord(
        code="IR_ZN26_0001",
        name="Station_26_1",
        zone="SWR",
        division="Bengaluru",
        elevation_m=57.3,
        platforms=2,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0001_UP", "RFID_IR_ZN26_0001_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0002": StationRecord(
        code="IR_ZN26_0002",
        name="Station_26_2",
        zone="CR",
        division="Mumbai",
        elevation_m=64.6,
        platforms=3,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0002_UP", "RFID_IR_ZN26_0002_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0003": StationRecord(
        code="IR_ZN26_0003",
        name="Station_26_3",
        zone="WR",
        division="Ahmedabad",
        elevation_m=71.9,
        platforms=4,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0003_UP", "RFID_IR_ZN26_0003_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0004": StationRecord(
        code="IR_ZN26_0004",
        name="Station_26_4",
        zone="WCR",
        division="Delhi",
        elevation_m=79.2,
        platforms=5,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0004_UP", "RFID_IR_ZN26_0004_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0005": StationRecord(
        code="IR_ZN26_0005",
        name="Station_26_5",
        zone="KR",
        division="Lucknow",
        elevation_m=86.5,
        platforms=6,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0005_UP", "RFID_IR_ZN26_0005_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0006": StationRecord(
        code="IR_ZN26_0006",
        name="Station_26_6",
        zone="NR",
        division="Varanasi",
        elevation_m=93.8,
        platforms=7,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0006_UP", "RFID_IR_ZN26_0006_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0007": StationRecord(
        code="IR_ZN26_0007",
        name="Station_26_7",
        zone="NCR",
        division="Howrah",
        elevation_m=101.1,
        platforms=8,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0007_UP", "RFID_IR_ZN26_0007_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0008": StationRecord(
        code="IR_ZN26_0008",
        name="Station_26_8",
        zone="NER",
        division="Secunderabad",
        elevation_m=108.4,
        platforms=1,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0008_UP", "RFID_IR_ZN26_0008_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0009": StationRecord(
        code="IR_ZN26_0009",
        name="Station_26_9",
        zone="NFR",
        division="Vijayawada",
        elevation_m=115.7,
        platforms=2,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0009_UP", "RFID_IR_ZN26_0009_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0010": StationRecord(
        code="IR_ZN26_0010",
        name="Station_26_10",
        zone="ER",
        division="Chennai",
        elevation_m=123.0,
        platforms=3,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0010_UP", "RFID_IR_ZN26_0010_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0011": StationRecord(
        code="IR_ZN26_0011",
        name="Station_26_11",
        zone="ECR",
        division="Bengaluru",
        elevation_m=130.3,
        platforms=4,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0011_UP", "RFID_IR_ZN26_0011_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0012": StationRecord(
        code="IR_ZN26_0012",
        name="Station_26_12",
        zone="SER",
        division="Mumbai",
        elevation_m=137.6,
        platforms=5,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0012_UP", "RFID_IR_ZN26_0012_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0013": StationRecord(
        code="IR_ZN26_0013",
        name="Station_26_13",
        zone="SECR",
        division="Ahmedabad",
        elevation_m=144.9,
        platforms=6,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0013_UP", "RFID_IR_ZN26_0013_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0014": StationRecord(
        code="IR_ZN26_0014",
        name="Station_26_14",
        zone="ECoR",
        division="Delhi",
        elevation_m=152.2,
        platforms=7,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0014_UP", "RFID_IR_ZN26_0014_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0015": StationRecord(
        code="IR_ZN26_0015",
        name="Station_26_15",
        zone="SR",
        division="Lucknow",
        elevation_m=159.5,
        platforms=8,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0015_UP", "RFID_IR_ZN26_0015_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0016": StationRecord(
        code="IR_ZN26_0016",
        name="Station_26_16",
        zone="SCR",
        division="Varanasi",
        elevation_m=166.8,
        platforms=1,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0016_UP", "RFID_IR_ZN26_0016_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0017": StationRecord(
        code="IR_ZN26_0017",
        name="Station_26_17",
        zone="SWR",
        division="Howrah",
        elevation_m=174.1,
        platforms=2,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0017_UP", "RFID_IR_ZN26_0017_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0018": StationRecord(
        code="IR_ZN26_0018",
        name="Station_26_18",
        zone="CR",
        division="Secunderabad",
        elevation_m=181.4,
        platforms=3,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0018_UP", "RFID_IR_ZN26_0018_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0019": StationRecord(
        code="IR_ZN26_0019",
        name="Station_26_19",
        zone="WR",
        division="Vijayawada",
        elevation_m=188.7,
        platforms=4,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0019_UP", "RFID_IR_ZN26_0019_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0020": StationRecord(
        code="IR_ZN26_0020",
        name="Station_26_20",
        zone="WCR",
        division="Chennai",
        elevation_m=196.0,
        platforms=5,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0020_UP", "RFID_IR_ZN26_0020_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0021": StationRecord(
        code="IR_ZN26_0021",
        name="Station_26_21",
        zone="KR",
        division="Bengaluru",
        elevation_m=203.3,
        platforms=6,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0021_UP", "RFID_IR_ZN26_0021_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0022": StationRecord(
        code="IR_ZN26_0022",
        name="Station_26_22",
        zone="NR",
        division="Mumbai",
        elevation_m=210.6,
        platforms=7,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0022_UP", "RFID_IR_ZN26_0022_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0023": StationRecord(
        code="IR_ZN26_0023",
        name="Station_26_23",
        zone="NCR",
        division="Ahmedabad",
        elevation_m=217.9,
        platforms=8,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0023_UP", "RFID_IR_ZN26_0023_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0024": StationRecord(
        code="IR_ZN26_0024",
        name="Station_26_24",
        zone="NER",
        division="Delhi",
        elevation_m=225.2,
        platforms=1,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0024_UP", "RFID_IR_ZN26_0024_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0025": StationRecord(
        code="IR_ZN26_0025",
        name="Station_26_25",
        zone="NFR",
        division="Lucknow",
        elevation_m=232.5,
        platforms=2,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0025_UP", "RFID_IR_ZN26_0025_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0026": StationRecord(
        code="IR_ZN26_0026",
        name="Station_26_26",
        zone="ER",
        division="Varanasi",
        elevation_m=239.8,
        platforms=3,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0026_UP", "RFID_IR_ZN26_0026_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0027": StationRecord(
        code="IR_ZN26_0027",
        name="Station_26_27",
        zone="ECR",
        division="Howrah",
        elevation_m=247.1,
        platforms=4,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0027_UP", "RFID_IR_ZN26_0027_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0028": StationRecord(
        code="IR_ZN26_0028",
        name="Station_26_28",
        zone="SER",
        division="Secunderabad",
        elevation_m=254.4,
        platforms=5,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0028_UP", "RFID_IR_ZN26_0028_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0029": StationRecord(
        code="IR_ZN26_0029",
        name="Station_26_29",
        zone="SECR",
        division="Vijayawada",
        elevation_m=261.7,
        platforms=6,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0029_UP", "RFID_IR_ZN26_0029_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0030": StationRecord(
        code="IR_ZN26_0030",
        name="Station_26_30",
        zone="ECoR",
        division="Chennai",
        elevation_m=269.0,
        platforms=7,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0030_UP", "RFID_IR_ZN26_0030_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0031": StationRecord(
        code="IR_ZN26_0031",
        name="Station_26_31",
        zone="SR",
        division="Bengaluru",
        elevation_m=276.3,
        platforms=8,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0031_UP", "RFID_IR_ZN26_0031_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0032": StationRecord(
        code="IR_ZN26_0032",
        name="Station_26_32",
        zone="SCR",
        division="Mumbai",
        elevation_m=283.6,
        platforms=1,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0032_UP", "RFID_IR_ZN26_0032_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0033": StationRecord(
        code="IR_ZN26_0033",
        name="Station_26_33",
        zone="SWR",
        division="Ahmedabad",
        elevation_m=290.9,
        platforms=2,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0033_UP", "RFID_IR_ZN26_0033_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0034": StationRecord(
        code="IR_ZN26_0034",
        name="Station_26_34",
        zone="CR",
        division="Delhi",
        elevation_m=298.2,
        platforms=3,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0034_UP", "RFID_IR_ZN26_0034_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0035": StationRecord(
        code="IR_ZN26_0035",
        name="Station_26_35",
        zone="WR",
        division="Lucknow",
        elevation_m=305.5,
        platforms=4,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0035_UP", "RFID_IR_ZN26_0035_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0036": StationRecord(
        code="IR_ZN26_0036",
        name="Station_26_36",
        zone="WCR",
        division="Varanasi",
        elevation_m=312.8,
        platforms=5,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0036_UP", "RFID_IR_ZN26_0036_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0037": StationRecord(
        code="IR_ZN26_0037",
        name="Station_26_37",
        zone="KR",
        division="Howrah",
        elevation_m=320.1,
        platforms=6,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0037_UP", "RFID_IR_ZN26_0037_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0038": StationRecord(
        code="IR_ZN26_0038",
        name="Station_26_38",
        zone="NR",
        division="Secunderabad",
        elevation_m=327.4,
        platforms=7,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0038_UP", "RFID_IR_ZN26_0038_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0039": StationRecord(
        code="IR_ZN26_0039",
        name="Station_26_39",
        zone="NCR",
        division="Vijayawada",
        elevation_m=334.7,
        platforms=8,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0039_UP", "RFID_IR_ZN26_0039_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0040": StationRecord(
        code="IR_ZN26_0040",
        name="Station_26_40",
        zone="NER",
        division="Chennai",
        elevation_m=342.0,
        platforms=1,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0040_UP", "RFID_IR_ZN26_0040_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0041": StationRecord(
        code="IR_ZN26_0041",
        name="Station_26_41",
        zone="NFR",
        division="Bengaluru",
        elevation_m=349.3,
        platforms=2,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0041_UP", "RFID_IR_ZN26_0041_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0042": StationRecord(
        code="IR_ZN26_0042",
        name="Station_26_42",
        zone="ER",
        division="Mumbai",
        elevation_m=356.6,
        platforms=3,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0042_UP", "RFID_IR_ZN26_0042_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0043": StationRecord(
        code="IR_ZN26_0043",
        name="Station_26_43",
        zone="ECR",
        division="Ahmedabad",
        elevation_m=363.9,
        platforms=4,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0043_UP", "RFID_IR_ZN26_0043_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0044": StationRecord(
        code="IR_ZN26_0044",
        name="Station_26_44",
        zone="SER",
        division="Delhi",
        elevation_m=371.2,
        platforms=5,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0044_UP", "RFID_IR_ZN26_0044_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0045": StationRecord(
        code="IR_ZN26_0045",
        name="Station_26_45",
        zone="SECR",
        division="Lucknow",
        elevation_m=378.5,
        platforms=6,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0045_UP", "RFID_IR_ZN26_0045_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0046": StationRecord(
        code="IR_ZN26_0046",
        name="Station_26_46",
        zone="ECoR",
        division="Varanasi",
        elevation_m=385.8,
        platforms=7,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0046_UP", "RFID_IR_ZN26_0046_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0047": StationRecord(
        code="IR_ZN26_0047",
        name="Station_26_47",
        zone="SR",
        division="Howrah",
        elevation_m=393.1,
        platforms=8,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0047_UP", "RFID_IR_ZN26_0047_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0048": StationRecord(
        code="IR_ZN26_0048",
        name="Station_26_48",
        zone="SCR",
        division="Secunderabad",
        elevation_m=400.4,
        platforms=1,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0048_UP", "RFID_IR_ZN26_0048_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0049": StationRecord(
        code="IR_ZN26_0049",
        name="Station_26_49",
        zone="SWR",
        division="Vijayawada",
        elevation_m=407.7,
        platforms=2,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0049_UP", "RFID_IR_ZN26_0049_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0050": StationRecord(
        code="IR_ZN26_0050",
        name="Station_26_50",
        zone="CR",
        division="Chennai",
        elevation_m=415.0,
        platforms=3,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0050_UP", "RFID_IR_ZN26_0050_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0051": StationRecord(
        code="IR_ZN26_0051",
        name="Station_26_51",
        zone="WR",
        division="Bengaluru",
        elevation_m=422.3,
        platforms=4,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0051_UP", "RFID_IR_ZN26_0051_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0052": StationRecord(
        code="IR_ZN26_0052",
        name="Station_26_52",
        zone="WCR",
        division="Mumbai",
        elevation_m=429.6,
        platforms=5,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0052_UP", "RFID_IR_ZN26_0052_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0053": StationRecord(
        code="IR_ZN26_0053",
        name="Station_26_53",
        zone="KR",
        division="Ahmedabad",
        elevation_m=436.9,
        platforms=6,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0053_UP", "RFID_IR_ZN26_0053_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0054": StationRecord(
        code="IR_ZN26_0054",
        name="Station_26_54",
        zone="NR",
        division="Delhi",
        elevation_m=444.2,
        platforms=7,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0054_UP", "RFID_IR_ZN26_0054_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0055": StationRecord(
        code="IR_ZN26_0055",
        name="Station_26_55",
        zone="NCR",
        division="Lucknow",
        elevation_m=51.5,
        platforms=8,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0055_UP", "RFID_IR_ZN26_0055_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0056": StationRecord(
        code="IR_ZN26_0056",
        name="Station_26_56",
        zone="NER",
        division="Varanasi",
        elevation_m=58.8,
        platforms=1,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0056_UP", "RFID_IR_ZN26_0056_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0057": StationRecord(
        code="IR_ZN26_0057",
        name="Station_26_57",
        zone="NFR",
        division="Howrah",
        elevation_m=66.1,
        platforms=2,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0057_UP", "RFID_IR_ZN26_0057_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0058": StationRecord(
        code="IR_ZN26_0058",
        name="Station_26_58",
        zone="ER",
        division="Secunderabad",
        elevation_m=73.4,
        platforms=3,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0058_UP", "RFID_IR_ZN26_0058_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0059": StationRecord(
        code="IR_ZN26_0059",
        name="Station_26_59",
        zone="ECR",
        division="Vijayawada",
        elevation_m=80.7,
        platforms=4,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0059_UP", "RFID_IR_ZN26_0059_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0060": StationRecord(
        code="IR_ZN26_0060",
        name="Station_26_60",
        zone="SER",
        division="Chennai",
        elevation_m=88.0,
        platforms=5,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0060_UP", "RFID_IR_ZN26_0060_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0061": StationRecord(
        code="IR_ZN26_0061",
        name="Station_26_61",
        zone="SECR",
        division="Bengaluru",
        elevation_m=95.3,
        platforms=6,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0061_UP", "RFID_IR_ZN26_0061_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0062": StationRecord(
        code="IR_ZN26_0062",
        name="Station_26_62",
        zone="ECoR",
        division="Mumbai",
        elevation_m=102.6,
        platforms=7,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0062_UP", "RFID_IR_ZN26_0062_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0063": StationRecord(
        code="IR_ZN26_0063",
        name="Station_26_63",
        zone="SR",
        division="Ahmedabad",
        elevation_m=109.9,
        platforms=8,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0063_UP", "RFID_IR_ZN26_0063_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0064": StationRecord(
        code="IR_ZN26_0064",
        name="Station_26_64",
        zone="SCR",
        division="Delhi",
        elevation_m=117.2,
        platforms=1,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0064_UP", "RFID_IR_ZN26_0064_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0065": StationRecord(
        code="IR_ZN26_0065",
        name="Station_26_65",
        zone="SWR",
        division="Lucknow",
        elevation_m=124.5,
        platforms=2,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0065_UP", "RFID_IR_ZN26_0065_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0066": StationRecord(
        code="IR_ZN26_0066",
        name="Station_26_66",
        zone="CR",
        division="Varanasi",
        elevation_m=131.8,
        platforms=3,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0066_UP", "RFID_IR_ZN26_0066_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0067": StationRecord(
        code="IR_ZN26_0067",
        name="Station_26_67",
        zone="WR",
        division="Howrah",
        elevation_m=139.1,
        platforms=4,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0067_UP", "RFID_IR_ZN26_0067_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0068": StationRecord(
        code="IR_ZN26_0068",
        name="Station_26_68",
        zone="WCR",
        division="Secunderabad",
        elevation_m=146.4,
        platforms=5,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0068_UP", "RFID_IR_ZN26_0068_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0069": StationRecord(
        code="IR_ZN26_0069",
        name="Station_26_69",
        zone="KR",
        division="Vijayawada",
        elevation_m=153.7,
        platforms=6,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0069_UP", "RFID_IR_ZN26_0069_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0070": StationRecord(
        code="IR_ZN26_0070",
        name="Station_26_70",
        zone="NR",
        division="Chennai",
        elevation_m=161.0,
        platforms=7,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0070_UP", "RFID_IR_ZN26_0070_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0071": StationRecord(
        code="IR_ZN26_0071",
        name="Station_26_71",
        zone="NCR",
        division="Bengaluru",
        elevation_m=168.3,
        platforms=8,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0071_UP", "RFID_IR_ZN26_0071_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0072": StationRecord(
        code="IR_ZN26_0072",
        name="Station_26_72",
        zone="NER",
        division="Mumbai",
        elevation_m=175.6,
        platforms=1,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0072_UP", "RFID_IR_ZN26_0072_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0073": StationRecord(
        code="IR_ZN26_0073",
        name="Station_26_73",
        zone="NFR",
        division="Ahmedabad",
        elevation_m=182.9,
        platforms=2,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0073_UP", "RFID_IR_ZN26_0073_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0074": StationRecord(
        code="IR_ZN26_0074",
        name="Station_26_74",
        zone="ER",
        division="Delhi",
        elevation_m=190.2,
        platforms=3,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0074_UP", "RFID_IR_ZN26_0074_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0075": StationRecord(
        code="IR_ZN26_0075",
        name="Station_26_75",
        zone="ECR",
        division="Lucknow",
        elevation_m=197.5,
        platforms=4,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0075_UP", "RFID_IR_ZN26_0075_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0076": StationRecord(
        code="IR_ZN26_0076",
        name="Station_26_76",
        zone="SER",
        division="Varanasi",
        elevation_m=204.8,
        platforms=5,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0076_UP", "RFID_IR_ZN26_0076_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0077": StationRecord(
        code="IR_ZN26_0077",
        name="Station_26_77",
        zone="SECR",
        division="Howrah",
        elevation_m=212.1,
        platforms=6,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0077_UP", "RFID_IR_ZN26_0077_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0078": StationRecord(
        code="IR_ZN26_0078",
        name="Station_26_78",
        zone="ECoR",
        division="Secunderabad",
        elevation_m=219.4,
        platforms=7,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0078_UP", "RFID_IR_ZN26_0078_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0079": StationRecord(
        code="IR_ZN26_0079",
        name="Station_26_79",
        zone="SR",
        division="Vijayawada",
        elevation_m=226.7,
        platforms=8,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0079_UP", "RFID_IR_ZN26_0079_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0080": StationRecord(
        code="IR_ZN26_0080",
        name="Station_26_80",
        zone="SCR",
        division="Chennai",
        elevation_m=234.0,
        platforms=1,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0080_UP", "RFID_IR_ZN26_0080_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0081": StationRecord(
        code="IR_ZN26_0081",
        name="Station_26_81",
        zone="SWR",
        division="Bengaluru",
        elevation_m=241.3,
        platforms=2,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0081_UP", "RFID_IR_ZN26_0081_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0082": StationRecord(
        code="IR_ZN26_0082",
        name="Station_26_82",
        zone="CR",
        division="Mumbai",
        elevation_m=248.6,
        platforms=3,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0082_UP", "RFID_IR_ZN26_0082_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0083": StationRecord(
        code="IR_ZN26_0083",
        name="Station_26_83",
        zone="WR",
        division="Ahmedabad",
        elevation_m=255.9,
        platforms=4,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0083_UP", "RFID_IR_ZN26_0083_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0084": StationRecord(
        code="IR_ZN26_0084",
        name="Station_26_84",
        zone="WCR",
        division="Delhi",
        elevation_m=263.2,
        platforms=5,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0084_UP", "RFID_IR_ZN26_0084_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0085": StationRecord(
        code="IR_ZN26_0085",
        name="Station_26_85",
        zone="KR",
        division="Lucknow",
        elevation_m=270.5,
        platforms=6,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0085_UP", "RFID_IR_ZN26_0085_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0086": StationRecord(
        code="IR_ZN26_0086",
        name="Station_26_86",
        zone="NR",
        division="Varanasi",
        elevation_m=277.8,
        platforms=7,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0086_UP", "RFID_IR_ZN26_0086_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0087": StationRecord(
        code="IR_ZN26_0087",
        name="Station_26_87",
        zone="NCR",
        division="Howrah",
        elevation_m=285.1,
        platforms=8,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0087_UP", "RFID_IR_ZN26_0087_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0088": StationRecord(
        code="IR_ZN26_0088",
        name="Station_26_88",
        zone="NER",
        division="Secunderabad",
        elevation_m=292.4,
        platforms=1,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0088_UP", "RFID_IR_ZN26_0088_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0089": StationRecord(
        code="IR_ZN26_0089",
        name="Station_26_89",
        zone="NFR",
        division="Vijayawada",
        elevation_m=299.7,
        platforms=2,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0089_UP", "RFID_IR_ZN26_0089_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0090": StationRecord(
        code="IR_ZN26_0090",
        name="Station_26_90",
        zone="ER",
        division="Chennai",
        elevation_m=307.0,
        platforms=3,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0090_UP", "RFID_IR_ZN26_0090_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0091": StationRecord(
        code="IR_ZN26_0091",
        name="Station_26_91",
        zone="ECR",
        division="Bengaluru",
        elevation_m=314.3,
        platforms=4,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0091_UP", "RFID_IR_ZN26_0091_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0092": StationRecord(
        code="IR_ZN26_0092",
        name="Station_26_92",
        zone="SER",
        division="Mumbai",
        elevation_m=321.6,
        platforms=5,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0092_UP", "RFID_IR_ZN26_0092_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0093": StationRecord(
        code="IR_ZN26_0093",
        name="Station_26_93",
        zone="SECR",
        division="Ahmedabad",
        elevation_m=328.9,
        platforms=6,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0093_UP", "RFID_IR_ZN26_0093_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0094": StationRecord(
        code="IR_ZN26_0094",
        name="Station_26_94",
        zone="ECoR",
        division="Delhi",
        elevation_m=336.2,
        platforms=7,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0094_UP", "RFID_IR_ZN26_0094_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0095": StationRecord(
        code="IR_ZN26_0095",
        name="Station_26_95",
        zone="SR",
        division="Lucknow",
        elevation_m=343.5,
        platforms=8,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0095_UP", "RFID_IR_ZN26_0095_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0096": StationRecord(
        code="IR_ZN26_0096",
        name="Station_26_96",
        zone="SCR",
        division="Varanasi",
        elevation_m=350.8,
        platforms=1,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0096_UP", "RFID_IR_ZN26_0096_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0097": StationRecord(
        code="IR_ZN26_0097",
        name="Station_26_97",
        zone="SWR",
        division="Howrah",
        elevation_m=358.1,
        platforms=2,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0097_UP", "RFID_IR_ZN26_0097_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0098": StationRecord(
        code="IR_ZN26_0098",
        name="Station_26_98",
        zone="CR",
        division="Secunderabad",
        elevation_m=365.4,
        platforms=3,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0098_UP", "RFID_IR_ZN26_0098_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0099": StationRecord(
        code="IR_ZN26_0099",
        name="Station_26_99",
        zone="WR",
        division="Vijayawada",
        elevation_m=372.7,
        platforms=4,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0099_UP", "RFID_IR_ZN26_0099_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0100": StationRecord(
        code="IR_ZN26_0100",
        name="Station_26_100",
        zone="WCR",
        division="Chennai",
        elevation_m=380.0,
        platforms=5,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0100_UP", "RFID_IR_ZN26_0100_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0101": StationRecord(
        code="IR_ZN26_0101",
        name="Station_26_101",
        zone="KR",
        division="Bengaluru",
        elevation_m=387.3,
        platforms=6,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0101_UP", "RFID_IR_ZN26_0101_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0102": StationRecord(
        code="IR_ZN26_0102",
        name="Station_26_102",
        zone="NR",
        division="Mumbai",
        elevation_m=394.6,
        platforms=7,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0102_UP", "RFID_IR_ZN26_0102_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0103": StationRecord(
        code="IR_ZN26_0103",
        name="Station_26_103",
        zone="NCR",
        division="Ahmedabad",
        elevation_m=401.9,
        platforms=8,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0103_UP", "RFID_IR_ZN26_0103_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0104": StationRecord(
        code="IR_ZN26_0104",
        name="Station_26_104",
        zone="NER",
        division="Delhi",
        elevation_m=409.2,
        platforms=1,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0104_UP", "RFID_IR_ZN26_0104_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0105": StationRecord(
        code="IR_ZN26_0105",
        name="Station_26_105",
        zone="NFR",
        division="Lucknow",
        elevation_m=416.5,
        platforms=2,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0105_UP", "RFID_IR_ZN26_0105_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0106": StationRecord(
        code="IR_ZN26_0106",
        name="Station_26_106",
        zone="ER",
        division="Varanasi",
        elevation_m=423.8,
        platforms=3,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0106_UP", "RFID_IR_ZN26_0106_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0107": StationRecord(
        code="IR_ZN26_0107",
        name="Station_26_107",
        zone="ECR",
        division="Howrah",
        elevation_m=431.1,
        platforms=4,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0107_UP", "RFID_IR_ZN26_0107_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0108": StationRecord(
        code="IR_ZN26_0108",
        name="Station_26_108",
        zone="SER",
        division="Secunderabad",
        elevation_m=438.4,
        platforms=5,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0108_UP", "RFID_IR_ZN26_0108_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0109": StationRecord(
        code="IR_ZN26_0109",
        name="Station_26_109",
        zone="SECR",
        division="Vijayawada",
        elevation_m=445.7,
        platforms=6,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0109_UP", "RFID_IR_ZN26_0109_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0110": StationRecord(
        code="IR_ZN26_0110",
        name="Station_26_110",
        zone="ECoR",
        division="Chennai",
        elevation_m=53.0,
        platforms=7,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0110_UP", "RFID_IR_ZN26_0110_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0111": StationRecord(
        code="IR_ZN26_0111",
        name="Station_26_111",
        zone="SR",
        division="Bengaluru",
        elevation_m=60.3,
        platforms=8,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0111_UP", "RFID_IR_ZN26_0111_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0112": StationRecord(
        code="IR_ZN26_0112",
        name="Station_26_112",
        zone="SCR",
        division="Mumbai",
        elevation_m=67.6,
        platforms=1,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0112_UP", "RFID_IR_ZN26_0112_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0113": StationRecord(
        code="IR_ZN26_0113",
        name="Station_26_113",
        zone="SWR",
        division="Ahmedabad",
        elevation_m=74.9,
        platforms=2,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0113_UP", "RFID_IR_ZN26_0113_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0114": StationRecord(
        code="IR_ZN26_0114",
        name="Station_26_114",
        zone="CR",
        division="Delhi",
        elevation_m=82.2,
        platforms=3,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0114_UP", "RFID_IR_ZN26_0114_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0115": StationRecord(
        code="IR_ZN26_0115",
        name="Station_26_115",
        zone="WR",
        division="Lucknow",
        elevation_m=89.5,
        platforms=4,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0115_UP", "RFID_IR_ZN26_0115_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0116": StationRecord(
        code="IR_ZN26_0116",
        name="Station_26_116",
        zone="WCR",
        division="Varanasi",
        elevation_m=96.8,
        platforms=5,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0116_UP", "RFID_IR_ZN26_0116_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0117": StationRecord(
        code="IR_ZN26_0117",
        name="Station_26_117",
        zone="KR",
        division="Howrah",
        elevation_m=104.1,
        platforms=6,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0117_UP", "RFID_IR_ZN26_0117_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0118": StationRecord(
        code="IR_ZN26_0118",
        name="Station_26_118",
        zone="NR",
        division="Secunderabad",
        elevation_m=111.4,
        platforms=7,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0118_UP", "RFID_IR_ZN26_0118_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0119": StationRecord(
        code="IR_ZN26_0119",
        name="Station_26_119",
        zone="NCR",
        division="Vijayawada",
        elevation_m=118.7,
        platforms=8,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0119_UP", "RFID_IR_ZN26_0119_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0120": StationRecord(
        code="IR_ZN26_0120",
        name="Station_26_120",
        zone="NER",
        division="Chennai",
        elevation_m=126.0,
        platforms=1,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0120_UP", "RFID_IR_ZN26_0120_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN26_0121": StationRecord(
        code="IR_ZN26_0121",
        name="Station_26_121",
        zone="NFR",
        division="Bengaluru",
        elevation_m=133.3,
        platforms=2,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0121_UP", "RFID_IR_ZN26_0121_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN26_0122": StationRecord(
        code="IR_ZN26_0122",
        name="Station_26_122",
        zone="ER",
        division="Mumbai",
        elevation_m=140.6,
        platforms=3,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0122_UP", "RFID_IR_ZN26_0122_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN26_0123": StationRecord(
        code="IR_ZN26_0123",
        name="Station_26_123",
        zone="ECR",
        division="Ahmedabad",
        elevation_m=147.9,
        platforms=4,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0123_UP", "RFID_IR_ZN26_0123_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN26_0124": StationRecord(
        code="IR_ZN26_0124",
        name="Station_26_124",
        zone="SER",
        division="Delhi",
        elevation_m=155.2,
        platforms=5,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN26_0124_UP", "RFID_IR_ZN26_0124_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
}
