"""Station Network Topology Cluster Partition 043."""

from dataclasses import dataclass
from typing import List, Dict

@dataclass
class StationRecord:
    code: str
    name: str
    zone: str
    division: str
    elevation_m: float
    platforms: int
    loop_lines: int
    electrified: bool
    station_type: str
    kavach_atp_level: str
    rfid_tags: List[str]
    catenary_voltage_kv: float
    max_permissible_speed_kmh: float
    has_crew_change: bool
    freight_siding_m: float

STATION_ZONE_CLUSTER_043: Dict[str, StationRecord] = {
    "IR_ZN43_0001": StationRecord(
        code="IR_ZN43_0001",
        name="Station_43_1",
        zone="CR",
        division="Secunderabad",
        elevation_m=57.3,
        platforms=2,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0001_UP", "RFID_IR_ZN43_0001_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0002": StationRecord(
        code="IR_ZN43_0002",
        name="Station_43_2",
        zone="WR",
        division="Vijayawada",
        elevation_m=64.6,
        platforms=3,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0002_UP", "RFID_IR_ZN43_0002_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0003": StationRecord(
        code="IR_ZN43_0003",
        name="Station_43_3",
        zone="WCR",
        division="Chennai",
        elevation_m=71.9,
        platforms=4,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0003_UP", "RFID_IR_ZN43_0003_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0004": StationRecord(
        code="IR_ZN43_0004",
        name="Station_43_4",
        zone="KR",
        division="Bengaluru",
        elevation_m=79.2,
        platforms=5,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0004_UP", "RFID_IR_ZN43_0004_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0005": StationRecord(
        code="IR_ZN43_0005",
        name="Station_43_5",
        zone="NR",
        division="Mumbai",
        elevation_m=86.5,
        platforms=6,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0005_UP", "RFID_IR_ZN43_0005_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0006": StationRecord(
        code="IR_ZN43_0006",
        name="Station_43_6",
        zone="NCR",
        division="Ahmedabad",
        elevation_m=93.8,
        platforms=7,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0006_UP", "RFID_IR_ZN43_0006_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0007": StationRecord(
        code="IR_ZN43_0007",
        name="Station_43_7",
        zone="NER",
        division="Delhi",
        elevation_m=101.1,
        platforms=8,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0007_UP", "RFID_IR_ZN43_0007_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0008": StationRecord(
        code="IR_ZN43_0008",
        name="Station_43_8",
        zone="NFR",
        division="Lucknow",
        elevation_m=108.4,
        platforms=1,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0008_UP", "RFID_IR_ZN43_0008_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0009": StationRecord(
        code="IR_ZN43_0009",
        name="Station_43_9",
        zone="ER",
        division="Varanasi",
        elevation_m=115.7,
        platforms=2,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0009_UP", "RFID_IR_ZN43_0009_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0010": StationRecord(
        code="IR_ZN43_0010",
        name="Station_43_10",
        zone="ECR",
        division="Howrah",
        elevation_m=123.0,
        platforms=3,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0010_UP", "RFID_IR_ZN43_0010_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0011": StationRecord(
        code="IR_ZN43_0011",
        name="Station_43_11",
        zone="SER",
        division="Secunderabad",
        elevation_m=130.3,
        platforms=4,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0011_UP", "RFID_IR_ZN43_0011_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0012": StationRecord(
        code="IR_ZN43_0012",
        name="Station_43_12",
        zone="SECR",
        division="Vijayawada",
        elevation_m=137.6,
        platforms=5,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0012_UP", "RFID_IR_ZN43_0012_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0013": StationRecord(
        code="IR_ZN43_0013",
        name="Station_43_13",
        zone="ECoR",
        division="Chennai",
        elevation_m=144.9,
        platforms=6,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0013_UP", "RFID_IR_ZN43_0013_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0014": StationRecord(
        code="IR_ZN43_0014",
        name="Station_43_14",
        zone="SR",
        division="Bengaluru",
        elevation_m=152.2,
        platforms=7,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0014_UP", "RFID_IR_ZN43_0014_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0015": StationRecord(
        code="IR_ZN43_0015",
        name="Station_43_15",
        zone="SCR",
        division="Mumbai",
        elevation_m=159.5,
        platforms=8,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0015_UP", "RFID_IR_ZN43_0015_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0016": StationRecord(
        code="IR_ZN43_0016",
        name="Station_43_16",
        zone="SWR",
        division="Ahmedabad",
        elevation_m=166.8,
        platforms=1,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0016_UP", "RFID_IR_ZN43_0016_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0017": StationRecord(
        code="IR_ZN43_0017",
        name="Station_43_17",
        zone="CR",
        division="Delhi",
        elevation_m=174.1,
        platforms=2,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0017_UP", "RFID_IR_ZN43_0017_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0018": StationRecord(
        code="IR_ZN43_0018",
        name="Station_43_18",
        zone="WR",
        division="Lucknow",
        elevation_m=181.4,
        platforms=3,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0018_UP", "RFID_IR_ZN43_0018_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0019": StationRecord(
        code="IR_ZN43_0019",
        name="Station_43_19",
        zone="WCR",
        division="Varanasi",
        elevation_m=188.7,
        platforms=4,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0019_UP", "RFID_IR_ZN43_0019_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0020": StationRecord(
        code="IR_ZN43_0020",
        name="Station_43_20",
        zone="KR",
        division="Howrah",
        elevation_m=196.0,
        platforms=5,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0020_UP", "RFID_IR_ZN43_0020_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0021": StationRecord(
        code="IR_ZN43_0021",
        name="Station_43_21",
        zone="NR",
        division="Secunderabad",
        elevation_m=203.3,
        platforms=6,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0021_UP", "RFID_IR_ZN43_0021_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0022": StationRecord(
        code="IR_ZN43_0022",
        name="Station_43_22",
        zone="NCR",
        division="Vijayawada",
        elevation_m=210.6,
        platforms=7,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0022_UP", "RFID_IR_ZN43_0022_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0023": StationRecord(
        code="IR_ZN43_0023",
        name="Station_43_23",
        zone="NER",
        division="Chennai",
        elevation_m=217.9,
        platforms=8,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0023_UP", "RFID_IR_ZN43_0023_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0024": StationRecord(
        code="IR_ZN43_0024",
        name="Station_43_24",
        zone="NFR",
        division="Bengaluru",
        elevation_m=225.2,
        platforms=1,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0024_UP", "RFID_IR_ZN43_0024_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0025": StationRecord(
        code="IR_ZN43_0025",
        name="Station_43_25",
        zone="ER",
        division="Mumbai",
        elevation_m=232.5,
        platforms=2,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0025_UP", "RFID_IR_ZN43_0025_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0026": StationRecord(
        code="IR_ZN43_0026",
        name="Station_43_26",
        zone="ECR",
        division="Ahmedabad",
        elevation_m=239.8,
        platforms=3,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0026_UP", "RFID_IR_ZN43_0026_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0027": StationRecord(
        code="IR_ZN43_0027",
        name="Station_43_27",
        zone="SER",
        division="Delhi",
        elevation_m=247.1,
        platforms=4,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0027_UP", "RFID_IR_ZN43_0027_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0028": StationRecord(
        code="IR_ZN43_0028",
        name="Station_43_28",
        zone="SECR",
        division="Lucknow",
        elevation_m=254.4,
        platforms=5,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0028_UP", "RFID_IR_ZN43_0028_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0029": StationRecord(
        code="IR_ZN43_0029",
        name="Station_43_29",
        zone="ECoR",
        division="Varanasi",
        elevation_m=261.7,
        platforms=6,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0029_UP", "RFID_IR_ZN43_0029_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0030": StationRecord(
        code="IR_ZN43_0030",
        name="Station_43_30",
        zone="SR",
        division="Howrah",
        elevation_m=269.0,
        platforms=7,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0030_UP", "RFID_IR_ZN43_0030_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0031": StationRecord(
        code="IR_ZN43_0031",
        name="Station_43_31",
        zone="SCR",
        division="Secunderabad",
        elevation_m=276.3,
        platforms=8,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0031_UP", "RFID_IR_ZN43_0031_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0032": StationRecord(
        code="IR_ZN43_0032",
        name="Station_43_32",
        zone="SWR",
        division="Vijayawada",
        elevation_m=283.6,
        platforms=1,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0032_UP", "RFID_IR_ZN43_0032_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0033": StationRecord(
        code="IR_ZN43_0033",
        name="Station_43_33",
        zone="CR",
        division="Chennai",
        elevation_m=290.9,
        platforms=2,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0033_UP", "RFID_IR_ZN43_0033_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0034": StationRecord(
        code="IR_ZN43_0034",
        name="Station_43_34",
        zone="WR",
        division="Bengaluru",
        elevation_m=298.2,
        platforms=3,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0034_UP", "RFID_IR_ZN43_0034_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0035": StationRecord(
        code="IR_ZN43_0035",
        name="Station_43_35",
        zone="WCR",
        division="Mumbai",
        elevation_m=305.5,
        platforms=4,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0035_UP", "RFID_IR_ZN43_0035_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0036": StationRecord(
        code="IR_ZN43_0036",
        name="Station_43_36",
        zone="KR",
        division="Ahmedabad",
        elevation_m=312.8,
        platforms=5,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0036_UP", "RFID_IR_ZN43_0036_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0037": StationRecord(
        code="IR_ZN43_0037",
        name="Station_43_37",
        zone="NR",
        division="Delhi",
        elevation_m=320.1,
        platforms=6,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0037_UP", "RFID_IR_ZN43_0037_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0038": StationRecord(
        code="IR_ZN43_0038",
        name="Station_43_38",
        zone="NCR",
        division="Lucknow",
        elevation_m=327.4,
        platforms=7,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0038_UP", "RFID_IR_ZN43_0038_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0039": StationRecord(
        code="IR_ZN43_0039",
        name="Station_43_39",
        zone="NER",
        division="Varanasi",
        elevation_m=334.7,
        platforms=8,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0039_UP", "RFID_IR_ZN43_0039_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0040": StationRecord(
        code="IR_ZN43_0040",
        name="Station_43_40",
        zone="NFR",
        division="Howrah",
        elevation_m=342.0,
        platforms=1,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0040_UP", "RFID_IR_ZN43_0040_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0041": StationRecord(
        code="IR_ZN43_0041",
        name="Station_43_41",
        zone="ER",
        division="Secunderabad",
        elevation_m=349.3,
        platforms=2,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0041_UP", "RFID_IR_ZN43_0041_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0042": StationRecord(
        code="IR_ZN43_0042",
        name="Station_43_42",
        zone="ECR",
        division="Vijayawada",
        elevation_m=356.6,
        platforms=3,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0042_UP", "RFID_IR_ZN43_0042_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0043": StationRecord(
        code="IR_ZN43_0043",
        name="Station_43_43",
        zone="SER",
        division="Chennai",
        elevation_m=363.9,
        platforms=4,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0043_UP", "RFID_IR_ZN43_0043_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0044": StationRecord(
        code="IR_ZN43_0044",
        name="Station_43_44",
        zone="SECR",
        division="Bengaluru",
        elevation_m=371.2,
        platforms=5,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0044_UP", "RFID_IR_ZN43_0044_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0045": StationRecord(
        code="IR_ZN43_0045",
        name="Station_43_45",
        zone="ECoR",
        division="Mumbai",
        elevation_m=378.5,
        platforms=6,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0045_UP", "RFID_IR_ZN43_0045_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0046": StationRecord(
        code="IR_ZN43_0046",
        name="Station_43_46",
        zone="SR",
        division="Ahmedabad",
        elevation_m=385.8,
        platforms=7,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0046_UP", "RFID_IR_ZN43_0046_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0047": StationRecord(
        code="IR_ZN43_0047",
        name="Station_43_47",
        zone="SCR",
        division="Delhi",
        elevation_m=393.1,
        platforms=8,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0047_UP", "RFID_IR_ZN43_0047_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0048": StationRecord(
        code="IR_ZN43_0048",
        name="Station_43_48",
        zone="SWR",
        division="Lucknow",
        elevation_m=400.4,
        platforms=1,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0048_UP", "RFID_IR_ZN43_0048_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0049": StationRecord(
        code="IR_ZN43_0049",
        name="Station_43_49",
        zone="CR",
        division="Varanasi",
        elevation_m=407.7,
        platforms=2,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0049_UP", "RFID_IR_ZN43_0049_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0050": StationRecord(
        code="IR_ZN43_0050",
        name="Station_43_50",
        zone="WR",
        division="Howrah",
        elevation_m=415.0,
        platforms=3,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0050_UP", "RFID_IR_ZN43_0050_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0051": StationRecord(
        code="IR_ZN43_0051",
        name="Station_43_51",
        zone="WCR",
        division="Secunderabad",
        elevation_m=422.3,
        platforms=4,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0051_UP", "RFID_IR_ZN43_0051_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0052": StationRecord(
        code="IR_ZN43_0052",
        name="Station_43_52",
        zone="KR",
        division="Vijayawada",
        elevation_m=429.6,
        platforms=5,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0052_UP", "RFID_IR_ZN43_0052_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0053": StationRecord(
        code="IR_ZN43_0053",
        name="Station_43_53",
        zone="NR",
        division="Chennai",
        elevation_m=436.9,
        platforms=6,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0053_UP", "RFID_IR_ZN43_0053_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0054": StationRecord(
        code="IR_ZN43_0054",
        name="Station_43_54",
        zone="NCR",
        division="Bengaluru",
        elevation_m=444.2,
        platforms=7,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0054_UP", "RFID_IR_ZN43_0054_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0055": StationRecord(
        code="IR_ZN43_0055",
        name="Station_43_55",
        zone="NER",
        division="Mumbai",
        elevation_m=51.5,
        platforms=8,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0055_UP", "RFID_IR_ZN43_0055_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0056": StationRecord(
        code="IR_ZN43_0056",
        name="Station_43_56",
        zone="NFR",
        division="Ahmedabad",
        elevation_m=58.8,
        platforms=1,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0056_UP", "RFID_IR_ZN43_0056_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0057": StationRecord(
        code="IR_ZN43_0057",
        name="Station_43_57",
        zone="ER",
        division="Delhi",
        elevation_m=66.1,
        platforms=2,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0057_UP", "RFID_IR_ZN43_0057_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0058": StationRecord(
        code="IR_ZN43_0058",
        name="Station_43_58",
        zone="ECR",
        division="Lucknow",
        elevation_m=73.4,
        platforms=3,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0058_UP", "RFID_IR_ZN43_0058_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0059": StationRecord(
        code="IR_ZN43_0059",
        name="Station_43_59",
        zone="SER",
        division="Varanasi",
        elevation_m=80.7,
        platforms=4,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0059_UP", "RFID_IR_ZN43_0059_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0060": StationRecord(
        code="IR_ZN43_0060",
        name="Station_43_60",
        zone="SECR",
        division="Howrah",
        elevation_m=88.0,
        platforms=5,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0060_UP", "RFID_IR_ZN43_0060_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0061": StationRecord(
        code="IR_ZN43_0061",
        name="Station_43_61",
        zone="ECoR",
        division="Secunderabad",
        elevation_m=95.3,
        platforms=6,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0061_UP", "RFID_IR_ZN43_0061_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0062": StationRecord(
        code="IR_ZN43_0062",
        name="Station_43_62",
        zone="SR",
        division="Vijayawada",
        elevation_m=102.6,
        platforms=7,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0062_UP", "RFID_IR_ZN43_0062_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0063": StationRecord(
        code="IR_ZN43_0063",
        name="Station_43_63",
        zone="SCR",
        division="Chennai",
        elevation_m=109.9,
        platforms=8,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0063_UP", "RFID_IR_ZN43_0063_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0064": StationRecord(
        code="IR_ZN43_0064",
        name="Station_43_64",
        zone="SWR",
        division="Bengaluru",
        elevation_m=117.2,
        platforms=1,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0064_UP", "RFID_IR_ZN43_0064_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0065": StationRecord(
        code="IR_ZN43_0065",
        name="Station_43_65",
        zone="CR",
        division="Mumbai",
        elevation_m=124.5,
        platforms=2,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0065_UP", "RFID_IR_ZN43_0065_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0066": StationRecord(
        code="IR_ZN43_0066",
        name="Station_43_66",
        zone="WR",
        division="Ahmedabad",
        elevation_m=131.8,
        platforms=3,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0066_UP", "RFID_IR_ZN43_0066_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0067": StationRecord(
        code="IR_ZN43_0067",
        name="Station_43_67",
        zone="WCR",
        division="Delhi",
        elevation_m=139.1,
        platforms=4,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0067_UP", "RFID_IR_ZN43_0067_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0068": StationRecord(
        code="IR_ZN43_0068",
        name="Station_43_68",
        zone="KR",
        division="Lucknow",
        elevation_m=146.4,
        platforms=5,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0068_UP", "RFID_IR_ZN43_0068_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0069": StationRecord(
        code="IR_ZN43_0069",
        name="Station_43_69",
        zone="NR",
        division="Varanasi",
        elevation_m=153.7,
        platforms=6,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0069_UP", "RFID_IR_ZN43_0069_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0070": StationRecord(
        code="IR_ZN43_0070",
        name="Station_43_70",
        zone="NCR",
        division="Howrah",
        elevation_m=161.0,
        platforms=7,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0070_UP", "RFID_IR_ZN43_0070_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0071": StationRecord(
        code="IR_ZN43_0071",
        name="Station_43_71",
        zone="NER",
        division="Secunderabad",
        elevation_m=168.3,
        platforms=8,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0071_UP", "RFID_IR_ZN43_0071_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0072": StationRecord(
        code="IR_ZN43_0072",
        name="Station_43_72",
        zone="NFR",
        division="Vijayawada",
        elevation_m=175.6,
        platforms=1,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0072_UP", "RFID_IR_ZN43_0072_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0073": StationRecord(
        code="IR_ZN43_0073",
        name="Station_43_73",
        zone="ER",
        division="Chennai",
        elevation_m=182.9,
        platforms=2,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0073_UP", "RFID_IR_ZN43_0073_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0074": StationRecord(
        code="IR_ZN43_0074",
        name="Station_43_74",
        zone="ECR",
        division="Bengaluru",
        elevation_m=190.2,
        platforms=3,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0074_UP", "RFID_IR_ZN43_0074_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0075": StationRecord(
        code="IR_ZN43_0075",
        name="Station_43_75",
        zone="SER",
        division="Mumbai",
        elevation_m=197.5,
        platforms=4,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0075_UP", "RFID_IR_ZN43_0075_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0076": StationRecord(
        code="IR_ZN43_0076",
        name="Station_43_76",
        zone="SECR",
        division="Ahmedabad",
        elevation_m=204.8,
        platforms=5,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0076_UP", "RFID_IR_ZN43_0076_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0077": StationRecord(
        code="IR_ZN43_0077",
        name="Station_43_77",
        zone="ECoR",
        division="Delhi",
        elevation_m=212.1,
        platforms=6,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0077_UP", "RFID_IR_ZN43_0077_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0078": StationRecord(
        code="IR_ZN43_0078",
        name="Station_43_78",
        zone="SR",
        division="Lucknow",
        elevation_m=219.4,
        platforms=7,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0078_UP", "RFID_IR_ZN43_0078_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0079": StationRecord(
        code="IR_ZN43_0079",
        name="Station_43_79",
        zone="SCR",
        division="Varanasi",
        elevation_m=226.7,
        platforms=8,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0079_UP", "RFID_IR_ZN43_0079_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0080": StationRecord(
        code="IR_ZN43_0080",
        name="Station_43_80",
        zone="SWR",
        division="Howrah",
        elevation_m=234.0,
        platforms=1,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0080_UP", "RFID_IR_ZN43_0080_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0081": StationRecord(
        code="IR_ZN43_0081",
        name="Station_43_81",
        zone="CR",
        division="Secunderabad",
        elevation_m=241.3,
        platforms=2,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0081_UP", "RFID_IR_ZN43_0081_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0082": StationRecord(
        code="IR_ZN43_0082",
        name="Station_43_82",
        zone="WR",
        division="Vijayawada",
        elevation_m=248.6,
        platforms=3,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0082_UP", "RFID_IR_ZN43_0082_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0083": StationRecord(
        code="IR_ZN43_0083",
        name="Station_43_83",
        zone="WCR",
        division="Chennai",
        elevation_m=255.9,
        platforms=4,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0083_UP", "RFID_IR_ZN43_0083_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0084": StationRecord(
        code="IR_ZN43_0084",
        name="Station_43_84",
        zone="KR",
        division="Bengaluru",
        elevation_m=263.2,
        platforms=5,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0084_UP", "RFID_IR_ZN43_0084_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0085": StationRecord(
        code="IR_ZN43_0085",
        name="Station_43_85",
        zone="NR",
        division="Mumbai",
        elevation_m=270.5,
        platforms=6,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0085_UP", "RFID_IR_ZN43_0085_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0086": StationRecord(
        code="IR_ZN43_0086",
        name="Station_43_86",
        zone="NCR",
        division="Ahmedabad",
        elevation_m=277.8,
        platforms=7,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0086_UP", "RFID_IR_ZN43_0086_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0087": StationRecord(
        code="IR_ZN43_0087",
        name="Station_43_87",
        zone="NER",
        division="Delhi",
        elevation_m=285.1,
        platforms=8,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0087_UP", "RFID_IR_ZN43_0087_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0088": StationRecord(
        code="IR_ZN43_0088",
        name="Station_43_88",
        zone="NFR",
        division="Lucknow",
        elevation_m=292.4,
        platforms=1,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0088_UP", "RFID_IR_ZN43_0088_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0089": StationRecord(
        code="IR_ZN43_0089",
        name="Station_43_89",
        zone="ER",
        division="Varanasi",
        elevation_m=299.7,
        platforms=2,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0089_UP", "RFID_IR_ZN43_0089_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0090": StationRecord(
        code="IR_ZN43_0090",
        name="Station_43_90",
        zone="ECR",
        division="Howrah",
        elevation_m=307.0,
        platforms=3,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0090_UP", "RFID_IR_ZN43_0090_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0091": StationRecord(
        code="IR_ZN43_0091",
        name="Station_43_91",
        zone="SER",
        division="Secunderabad",
        elevation_m=314.3,
        platforms=4,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0091_UP", "RFID_IR_ZN43_0091_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0092": StationRecord(
        code="IR_ZN43_0092",
        name="Station_43_92",
        zone="SECR",
        division="Vijayawada",
        elevation_m=321.6,
        platforms=5,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0092_UP", "RFID_IR_ZN43_0092_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0093": StationRecord(
        code="IR_ZN43_0093",
        name="Station_43_93",
        zone="ECoR",
        division="Chennai",
        elevation_m=328.9,
        platforms=6,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0093_UP", "RFID_IR_ZN43_0093_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0094": StationRecord(
        code="IR_ZN43_0094",
        name="Station_43_94",
        zone="SR",
        division="Bengaluru",
        elevation_m=336.2,
        platforms=7,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0094_UP", "RFID_IR_ZN43_0094_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0095": StationRecord(
        code="IR_ZN43_0095",
        name="Station_43_95",
        zone="SCR",
        division="Mumbai",
        elevation_m=343.5,
        platforms=8,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0095_UP", "RFID_IR_ZN43_0095_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0096": StationRecord(
        code="IR_ZN43_0096",
        name="Station_43_96",
        zone="SWR",
        division="Ahmedabad",
        elevation_m=350.8,
        platforms=1,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0096_UP", "RFID_IR_ZN43_0096_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0097": StationRecord(
        code="IR_ZN43_0097",
        name="Station_43_97",
        zone="CR",
        division="Delhi",
        elevation_m=358.1,
        platforms=2,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0097_UP", "RFID_IR_ZN43_0097_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0098": StationRecord(
        code="IR_ZN43_0098",
        name="Station_43_98",
        zone="WR",
        division="Lucknow",
        elevation_m=365.4,
        platforms=3,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0098_UP", "RFID_IR_ZN43_0098_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0099": StationRecord(
        code="IR_ZN43_0099",
        name="Station_43_99",
        zone="WCR",
        division="Varanasi",
        elevation_m=372.7,
        platforms=4,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0099_UP", "RFID_IR_ZN43_0099_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0100": StationRecord(
        code="IR_ZN43_0100",
        name="Station_43_100",
        zone="KR",
        division="Howrah",
        elevation_m=380.0,
        platforms=5,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0100_UP", "RFID_IR_ZN43_0100_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0101": StationRecord(
        code="IR_ZN43_0101",
        name="Station_43_101",
        zone="NR",
        division="Secunderabad",
        elevation_m=387.3,
        platforms=6,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0101_UP", "RFID_IR_ZN43_0101_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0102": StationRecord(
        code="IR_ZN43_0102",
        name="Station_43_102",
        zone="NCR",
        division="Vijayawada",
        elevation_m=394.6,
        platforms=7,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0102_UP", "RFID_IR_ZN43_0102_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0103": StationRecord(
        code="IR_ZN43_0103",
        name="Station_43_103",
        zone="NER",
        division="Chennai",
        elevation_m=401.9,
        platforms=8,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0103_UP", "RFID_IR_ZN43_0103_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0104": StationRecord(
        code="IR_ZN43_0104",
        name="Station_43_104",
        zone="NFR",
        division="Bengaluru",
        elevation_m=409.2,
        platforms=1,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0104_UP", "RFID_IR_ZN43_0104_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0105": StationRecord(
        code="IR_ZN43_0105",
        name="Station_43_105",
        zone="ER",
        division="Mumbai",
        elevation_m=416.5,
        platforms=2,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0105_UP", "RFID_IR_ZN43_0105_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0106": StationRecord(
        code="IR_ZN43_0106",
        name="Station_43_106",
        zone="ECR",
        division="Ahmedabad",
        elevation_m=423.8,
        platforms=3,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0106_UP", "RFID_IR_ZN43_0106_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0107": StationRecord(
        code="IR_ZN43_0107",
        name="Station_43_107",
        zone="SER",
        division="Delhi",
        elevation_m=431.1,
        platforms=4,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0107_UP", "RFID_IR_ZN43_0107_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0108": StationRecord(
        code="IR_ZN43_0108",
        name="Station_43_108",
        zone="SECR",
        division="Lucknow",
        elevation_m=438.4,
        platforms=5,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0108_UP", "RFID_IR_ZN43_0108_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0109": StationRecord(
        code="IR_ZN43_0109",
        name="Station_43_109",
        zone="ECoR",
        division="Varanasi",
        elevation_m=445.7,
        platforms=6,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0109_UP", "RFID_IR_ZN43_0109_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0110": StationRecord(
        code="IR_ZN43_0110",
        name="Station_43_110",
        zone="SR",
        division="Howrah",
        elevation_m=53.0,
        platforms=7,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0110_UP", "RFID_IR_ZN43_0110_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0111": StationRecord(
        code="IR_ZN43_0111",
        name="Station_43_111",
        zone="SCR",
        division="Secunderabad",
        elevation_m=60.3,
        platforms=8,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0111_UP", "RFID_IR_ZN43_0111_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0112": StationRecord(
        code="IR_ZN43_0112",
        name="Station_43_112",
        zone="SWR",
        division="Vijayawada",
        elevation_m=67.6,
        platforms=1,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0112_UP", "RFID_IR_ZN43_0112_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0113": StationRecord(
        code="IR_ZN43_0113",
        name="Station_43_113",
        zone="CR",
        division="Chennai",
        elevation_m=74.9,
        platforms=2,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0113_UP", "RFID_IR_ZN43_0113_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0114": StationRecord(
        code="IR_ZN43_0114",
        name="Station_43_114",
        zone="WR",
        division="Bengaluru",
        elevation_m=82.2,
        platforms=3,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0114_UP", "RFID_IR_ZN43_0114_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=True,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0115": StationRecord(
        code="IR_ZN43_0115",
        name="Station_43_115",
        zone="WCR",
        division="Mumbai",
        elevation_m=89.5,
        platforms=4,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0115_UP", "RFID_IR_ZN43_0115_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0116": StationRecord(
        code="IR_ZN43_0116",
        name="Station_43_116",
        zone="KR",
        division="Ahmedabad",
        elevation_m=96.8,
        platforms=5,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0116_UP", "RFID_IR_ZN43_0116_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0117": StationRecord(
        code="IR_ZN43_0117",
        name="Station_43_117",
        zone="NR",
        division="Delhi",
        elevation_m=104.1,
        platforms=6,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0117_UP", "RFID_IR_ZN43_0117_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=True,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0118": StationRecord(
        code="IR_ZN43_0118",
        name="Station_43_118",
        zone="NCR",
        division="Lucknow",
        elevation_m=111.4,
        platforms=7,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0118_UP", "RFID_IR_ZN43_0118_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=160.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0119": StationRecord(
        code="IR_ZN43_0119",
        name="Station_43_119",
        zone="NER",
        division="Varanasi",
        elevation_m=118.7,
        platforms=8,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0119_UP", "RFID_IR_ZN43_0119_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=100.0,
        has_crew_change=False,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0120": StationRecord(
        code="IR_ZN43_0120",
        name="Station_43_120",
        zone="NFR",
        division="Howrah",
        elevation_m=126.0,
        platforms=1,
        loop_lines=1,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0120_UP", "RFID_IR_ZN43_0120_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=110.0,
        has_crew_change=True,
        freight_siding_m=650.0
    ),
    "IR_ZN43_0121": StationRecord(
        code="IR_ZN43_0121",
        name="Station_43_121",
        zone="ER",
        division="Secunderabad",
        elevation_m=133.3,
        platforms=2,
        loop_lines=2,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0121_UP", "RFID_IR_ZN43_0121_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=120.0,
        has_crew_change=False,
        freight_siding_m=700.0
    ),
    "IR_ZN43_0122": StationRecord(
        code="IR_ZN43_0122",
        name="Station_43_122",
        zone="ECR",
        division="Vijayawada",
        elevation_m=140.6,
        platforms=3,
        loop_lines=3,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0122_UP", "RFID_IR_ZN43_0122_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=130.0,
        has_crew_change=False,
        freight_siding_m=750.0
    ),
    "IR_ZN43_0123": StationRecord(
        code="IR_ZN43_0123",
        name="Station_43_123",
        zone="SER",
        division="Chennai",
        elevation_m=147.9,
        platforms=4,
        loop_lines=4,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0123_UP", "RFID_IR_ZN43_0123_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=140.0,
        has_crew_change=True,
        freight_siding_m=800.0
    ),
    "IR_ZN43_0124": StationRecord(
        code="IR_ZN43_0124",
        name="Station_43_124",
        zone="SECR",
        division="Bengaluru",
        elevation_m=155.2,
        platforms=5,
        loop_lines=5,
        electrified=True,
        station_type="JUNCTION",
        kavach_atp_level="SIL4_REV3.2",
        rfid_tags=["RFID_IR_ZN43_0124_UP", "RFID_IR_ZN43_0124_DN"],
        catenary_voltage_kv=25.0,
        max_permissible_speed_kmh=150.0,
        has_crew_change=False,
        freight_siding_m=650.0
    ),
}
