"""Railway Incident Contingency Action Plans Part 022."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class IncidentContingencyPlan:
    plan_id: str
    title: str
    incident_type: str
    affected_block_id: str
    time_of_occurrence_min: int
    expected_clearance_min: int
    severity_score: int
    primary_dispatch_action: str
    contingency_corridor_id: str

INCIDENT_CONTINGENCY_PLANS_022: Dict[str, IncidentContingencyPlan] = {
    "PLAN_P22_0001": IncidentContingencyPlan(
        plan_id="PLAN_P22_0001",
        title="Operational Action Plan 22-1",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_001",
        time_of_occurrence_min=601,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0002": IncidentContingencyPlan(
        plan_id="PLAN_P22_0002",
        title="Operational Action Plan 22-2",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_002",
        time_of_occurrence_min=602,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0003": IncidentContingencyPlan(
        plan_id="PLAN_P22_0003",
        title="Operational Action Plan 22-3",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_003",
        time_of_occurrence_min=603,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0004": IncidentContingencyPlan(
        plan_id="PLAN_P22_0004",
        title="Operational Action Plan 22-4",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_004",
        time_of_occurrence_min=604,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0005": IncidentContingencyPlan(
        plan_id="PLAN_P22_0005",
        title="Operational Action Plan 22-5",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_005",
        time_of_occurrence_min=605,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0006": IncidentContingencyPlan(
        plan_id="PLAN_P22_0006",
        title="Operational Action Plan 22-6",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_006",
        time_of_occurrence_min=606,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0007": IncidentContingencyPlan(
        plan_id="PLAN_P22_0007",
        title="Operational Action Plan 22-7",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_007",
        time_of_occurrence_min=607,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0008": IncidentContingencyPlan(
        plan_id="PLAN_P22_0008",
        title="Operational Action Plan 22-8",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_008",
        time_of_occurrence_min=608,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0009": IncidentContingencyPlan(
        plan_id="PLAN_P22_0009",
        title="Operational Action Plan 22-9",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_009",
        time_of_occurrence_min=609,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0010": IncidentContingencyPlan(
        plan_id="PLAN_P22_0010",
        title="Operational Action Plan 22-10",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_010",
        time_of_occurrence_min=610,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0011": IncidentContingencyPlan(
        plan_id="PLAN_P22_0011",
        title="Operational Action Plan 22-11",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_011",
        time_of_occurrence_min=611,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0012": IncidentContingencyPlan(
        plan_id="PLAN_P22_0012",
        title="Operational Action Plan 22-12",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_012",
        time_of_occurrence_min=612,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0013": IncidentContingencyPlan(
        plan_id="PLAN_P22_0013",
        title="Operational Action Plan 22-13",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_013",
        time_of_occurrence_min=613,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0014": IncidentContingencyPlan(
        plan_id="PLAN_P22_0014",
        title="Operational Action Plan 22-14",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_014",
        time_of_occurrence_min=614,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0015": IncidentContingencyPlan(
        plan_id="PLAN_P22_0015",
        title="Operational Action Plan 22-15",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_015",
        time_of_occurrence_min=615,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0016": IncidentContingencyPlan(
        plan_id="PLAN_P22_0016",
        title="Operational Action Plan 22-16",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_016",
        time_of_occurrence_min=616,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0017": IncidentContingencyPlan(
        plan_id="PLAN_P22_0017",
        title="Operational Action Plan 22-17",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_017",
        time_of_occurrence_min=617,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0018": IncidentContingencyPlan(
        plan_id="PLAN_P22_0018",
        title="Operational Action Plan 22-18",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_018",
        time_of_occurrence_min=618,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0019": IncidentContingencyPlan(
        plan_id="PLAN_P22_0019",
        title="Operational Action Plan 22-19",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_019",
        time_of_occurrence_min=619,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0020": IncidentContingencyPlan(
        plan_id="PLAN_P22_0020",
        title="Operational Action Plan 22-20",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_020",
        time_of_occurrence_min=620,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0021": IncidentContingencyPlan(
        plan_id="PLAN_P22_0021",
        title="Operational Action Plan 22-21",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_021",
        time_of_occurrence_min=621,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0022": IncidentContingencyPlan(
        plan_id="PLAN_P22_0022",
        title="Operational Action Plan 22-22",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_022",
        time_of_occurrence_min=622,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0023": IncidentContingencyPlan(
        plan_id="PLAN_P22_0023",
        title="Operational Action Plan 22-23",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_023",
        time_of_occurrence_min=623,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0024": IncidentContingencyPlan(
        plan_id="PLAN_P22_0024",
        title="Operational Action Plan 22-24",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_024",
        time_of_occurrence_min=624,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0025": IncidentContingencyPlan(
        plan_id="PLAN_P22_0025",
        title="Operational Action Plan 22-25",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_025",
        time_of_occurrence_min=625,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0026": IncidentContingencyPlan(
        plan_id="PLAN_P22_0026",
        title="Operational Action Plan 22-26",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_026",
        time_of_occurrence_min=626,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0027": IncidentContingencyPlan(
        plan_id="PLAN_P22_0027",
        title="Operational Action Plan 22-27",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_027",
        time_of_occurrence_min=627,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0028": IncidentContingencyPlan(
        plan_id="PLAN_P22_0028",
        title="Operational Action Plan 22-28",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_028",
        time_of_occurrence_min=628,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0029": IncidentContingencyPlan(
        plan_id="PLAN_P22_0029",
        title="Operational Action Plan 22-29",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_029",
        time_of_occurrence_min=629,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0030": IncidentContingencyPlan(
        plan_id="PLAN_P22_0030",
        title="Operational Action Plan 22-30",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_030",
        time_of_occurrence_min=630,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0031": IncidentContingencyPlan(
        plan_id="PLAN_P22_0031",
        title="Operational Action Plan 22-31",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_031",
        time_of_occurrence_min=631,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0032": IncidentContingencyPlan(
        plan_id="PLAN_P22_0032",
        title="Operational Action Plan 22-32",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_032",
        time_of_occurrence_min=632,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0033": IncidentContingencyPlan(
        plan_id="PLAN_P22_0033",
        title="Operational Action Plan 22-33",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_033",
        time_of_occurrence_min=633,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0034": IncidentContingencyPlan(
        plan_id="PLAN_P22_0034",
        title="Operational Action Plan 22-34",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_034",
        time_of_occurrence_min=634,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0035": IncidentContingencyPlan(
        plan_id="PLAN_P22_0035",
        title="Operational Action Plan 22-35",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_035",
        time_of_occurrence_min=635,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0036": IncidentContingencyPlan(
        plan_id="PLAN_P22_0036",
        title="Operational Action Plan 22-36",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_036",
        time_of_occurrence_min=636,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0037": IncidentContingencyPlan(
        plan_id="PLAN_P22_0037",
        title="Operational Action Plan 22-37",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_037",
        time_of_occurrence_min=637,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0038": IncidentContingencyPlan(
        plan_id="PLAN_P22_0038",
        title="Operational Action Plan 22-38",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_038",
        time_of_occurrence_min=638,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0039": IncidentContingencyPlan(
        plan_id="PLAN_P22_0039",
        title="Operational Action Plan 22-39",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_039",
        time_of_occurrence_min=639,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0040": IncidentContingencyPlan(
        plan_id="PLAN_P22_0040",
        title="Operational Action Plan 22-40",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_040",
        time_of_occurrence_min=640,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0041": IncidentContingencyPlan(
        plan_id="PLAN_P22_0041",
        title="Operational Action Plan 22-41",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_041",
        time_of_occurrence_min=641,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0042": IncidentContingencyPlan(
        plan_id="PLAN_P22_0042",
        title="Operational Action Plan 22-42",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_042",
        time_of_occurrence_min=642,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0043": IncidentContingencyPlan(
        plan_id="PLAN_P22_0043",
        title="Operational Action Plan 22-43",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_043",
        time_of_occurrence_min=643,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0044": IncidentContingencyPlan(
        plan_id="PLAN_P22_0044",
        title="Operational Action Plan 22-44",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_044",
        time_of_occurrence_min=644,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0045": IncidentContingencyPlan(
        plan_id="PLAN_P22_0045",
        title="Operational Action Plan 22-45",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_045",
        time_of_occurrence_min=645,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0046": IncidentContingencyPlan(
        plan_id="PLAN_P22_0046",
        title="Operational Action Plan 22-46",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_046",
        time_of_occurrence_min=646,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0047": IncidentContingencyPlan(
        plan_id="PLAN_P22_0047",
        title="Operational Action Plan 22-47",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_047",
        time_of_occurrence_min=647,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0048": IncidentContingencyPlan(
        plan_id="PLAN_P22_0048",
        title="Operational Action Plan 22-48",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_048",
        time_of_occurrence_min=648,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0049": IncidentContingencyPlan(
        plan_id="PLAN_P22_0049",
        title="Operational Action Plan 22-49",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_049",
        time_of_occurrence_min=649,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0050": IncidentContingencyPlan(
        plan_id="PLAN_P22_0050",
        title="Operational Action Plan 22-50",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_050",
        time_of_occurrence_min=650,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0051": IncidentContingencyPlan(
        plan_id="PLAN_P22_0051",
        title="Operational Action Plan 22-51",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_051",
        time_of_occurrence_min=651,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0052": IncidentContingencyPlan(
        plan_id="PLAN_P22_0052",
        title="Operational Action Plan 22-52",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_052",
        time_of_occurrence_min=652,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0053": IncidentContingencyPlan(
        plan_id="PLAN_P22_0053",
        title="Operational Action Plan 22-53",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_053",
        time_of_occurrence_min=653,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0054": IncidentContingencyPlan(
        plan_id="PLAN_P22_0054",
        title="Operational Action Plan 22-54",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_054",
        time_of_occurrence_min=654,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0055": IncidentContingencyPlan(
        plan_id="PLAN_P22_0055",
        title="Operational Action Plan 22-55",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_055",
        time_of_occurrence_min=655,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0056": IncidentContingencyPlan(
        plan_id="PLAN_P22_0056",
        title="Operational Action Plan 22-56",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_056",
        time_of_occurrence_min=656,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0057": IncidentContingencyPlan(
        plan_id="PLAN_P22_0057",
        title="Operational Action Plan 22-57",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_057",
        time_of_occurrence_min=657,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0058": IncidentContingencyPlan(
        plan_id="PLAN_P22_0058",
        title="Operational Action Plan 22-58",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_058",
        time_of_occurrence_min=658,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0059": IncidentContingencyPlan(
        plan_id="PLAN_P22_0059",
        title="Operational Action Plan 22-59",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_059",
        time_of_occurrence_min=659,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0060": IncidentContingencyPlan(
        plan_id="PLAN_P22_0060",
        title="Operational Action Plan 22-60",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_060",
        time_of_occurrence_min=660,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0061": IncidentContingencyPlan(
        plan_id="PLAN_P22_0061",
        title="Operational Action Plan 22-61",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_061",
        time_of_occurrence_min=661,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0062": IncidentContingencyPlan(
        plan_id="PLAN_P22_0062",
        title="Operational Action Plan 22-62",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_062",
        time_of_occurrence_min=662,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0063": IncidentContingencyPlan(
        plan_id="PLAN_P22_0063",
        title="Operational Action Plan 22-63",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_063",
        time_of_occurrence_min=663,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0064": IncidentContingencyPlan(
        plan_id="PLAN_P22_0064",
        title="Operational Action Plan 22-64",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_064",
        time_of_occurrence_min=664,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0065": IncidentContingencyPlan(
        plan_id="PLAN_P22_0065",
        title="Operational Action Plan 22-65",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_065",
        time_of_occurrence_min=665,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0066": IncidentContingencyPlan(
        plan_id="PLAN_P22_0066",
        title="Operational Action Plan 22-66",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_066",
        time_of_occurrence_min=666,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0067": IncidentContingencyPlan(
        plan_id="PLAN_P22_0067",
        title="Operational Action Plan 22-67",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_067",
        time_of_occurrence_min=667,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0068": IncidentContingencyPlan(
        plan_id="PLAN_P22_0068",
        title="Operational Action Plan 22-68",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_068",
        time_of_occurrence_min=668,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0069": IncidentContingencyPlan(
        plan_id="PLAN_P22_0069",
        title="Operational Action Plan 22-69",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_069",
        time_of_occurrence_min=669,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0070": IncidentContingencyPlan(
        plan_id="PLAN_P22_0070",
        title="Operational Action Plan 22-70",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_070",
        time_of_occurrence_min=670,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0071": IncidentContingencyPlan(
        plan_id="PLAN_P22_0071",
        title="Operational Action Plan 22-71",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_071",
        time_of_occurrence_min=671,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0072": IncidentContingencyPlan(
        plan_id="PLAN_P22_0072",
        title="Operational Action Plan 22-72",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_072",
        time_of_occurrence_min=672,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0073": IncidentContingencyPlan(
        plan_id="PLAN_P22_0073",
        title="Operational Action Plan 22-73",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_073",
        time_of_occurrence_min=673,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0074": IncidentContingencyPlan(
        plan_id="PLAN_P22_0074",
        title="Operational Action Plan 22-74",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_074",
        time_of_occurrence_min=674,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0075": IncidentContingencyPlan(
        plan_id="PLAN_P22_0075",
        title="Operational Action Plan 22-75",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_075",
        time_of_occurrence_min=675,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0076": IncidentContingencyPlan(
        plan_id="PLAN_P22_0076",
        title="Operational Action Plan 22-76",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_076",
        time_of_occurrence_min=676,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0077": IncidentContingencyPlan(
        plan_id="PLAN_P22_0077",
        title="Operational Action Plan 22-77",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_077",
        time_of_occurrence_min=677,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0078": IncidentContingencyPlan(
        plan_id="PLAN_P22_0078",
        title="Operational Action Plan 22-78",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_078",
        time_of_occurrence_min=678,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0079": IncidentContingencyPlan(
        plan_id="PLAN_P22_0079",
        title="Operational Action Plan 22-79",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_079",
        time_of_occurrence_min=679,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0080": IncidentContingencyPlan(
        plan_id="PLAN_P22_0080",
        title="Operational Action Plan 22-80",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_080",
        time_of_occurrence_min=680,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0081": IncidentContingencyPlan(
        plan_id="PLAN_P22_0081",
        title="Operational Action Plan 22-81",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_081",
        time_of_occurrence_min=681,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0082": IncidentContingencyPlan(
        plan_id="PLAN_P22_0082",
        title="Operational Action Plan 22-82",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_082",
        time_of_occurrence_min=682,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0083": IncidentContingencyPlan(
        plan_id="PLAN_P22_0083",
        title="Operational Action Plan 22-83",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_083",
        time_of_occurrence_min=683,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0084": IncidentContingencyPlan(
        plan_id="PLAN_P22_0084",
        title="Operational Action Plan 22-84",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_084",
        time_of_occurrence_min=684,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0085": IncidentContingencyPlan(
        plan_id="PLAN_P22_0085",
        title="Operational Action Plan 22-85",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_085",
        time_of_occurrence_min=685,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0086": IncidentContingencyPlan(
        plan_id="PLAN_P22_0086",
        title="Operational Action Plan 22-86",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_086",
        time_of_occurrence_min=686,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0087": IncidentContingencyPlan(
        plan_id="PLAN_P22_0087",
        title="Operational Action Plan 22-87",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_087",
        time_of_occurrence_min=687,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0088": IncidentContingencyPlan(
        plan_id="PLAN_P22_0088",
        title="Operational Action Plan 22-88",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_088",
        time_of_occurrence_min=688,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0089": IncidentContingencyPlan(
        plan_id="PLAN_P22_0089",
        title="Operational Action Plan 22-89",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_089",
        time_of_occurrence_min=689,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0090": IncidentContingencyPlan(
        plan_id="PLAN_P22_0090",
        title="Operational Action Plan 22-90",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_090",
        time_of_occurrence_min=690,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0091": IncidentContingencyPlan(
        plan_id="PLAN_P22_0091",
        title="Operational Action Plan 22-91",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_091",
        time_of_occurrence_min=691,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0092": IncidentContingencyPlan(
        plan_id="PLAN_P22_0092",
        title="Operational Action Plan 22-92",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_092",
        time_of_occurrence_min=692,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0093": IncidentContingencyPlan(
        plan_id="PLAN_P22_0093",
        title="Operational Action Plan 22-93",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_093",
        time_of_occurrence_min=693,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0094": IncidentContingencyPlan(
        plan_id="PLAN_P22_0094",
        title="Operational Action Plan 22-94",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_094",
        time_of_occurrence_min=694,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0095": IncidentContingencyPlan(
        plan_id="PLAN_P22_0095",
        title="Operational Action Plan 22-95",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_095",
        time_of_occurrence_min=695,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0096": IncidentContingencyPlan(
        plan_id="PLAN_P22_0096",
        title="Operational Action Plan 22-96",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_096",
        time_of_occurrence_min=696,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0097": IncidentContingencyPlan(
        plan_id="PLAN_P22_0097",
        title="Operational Action Plan 22-97",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_097",
        time_of_occurrence_min=697,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0098": IncidentContingencyPlan(
        plan_id="PLAN_P22_0098",
        title="Operational Action Plan 22-98",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_098",
        time_of_occurrence_min=698,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0099": IncidentContingencyPlan(
        plan_id="PLAN_P22_0099",
        title="Operational Action Plan 22-99",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_099",
        time_of_occurrence_min=699,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0100": IncidentContingencyPlan(
        plan_id="PLAN_P22_0100",
        title="Operational Action Plan 22-100",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_100",
        time_of_occurrence_min=700,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0101": IncidentContingencyPlan(
        plan_id="PLAN_P22_0101",
        title="Operational Action Plan 22-101",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_101",
        time_of_occurrence_min=701,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0102": IncidentContingencyPlan(
        plan_id="PLAN_P22_0102",
        title="Operational Action Plan 22-102",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_102",
        time_of_occurrence_min=702,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0103": IncidentContingencyPlan(
        plan_id="PLAN_P22_0103",
        title="Operational Action Plan 22-103",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_103",
        time_of_occurrence_min=703,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0104": IncidentContingencyPlan(
        plan_id="PLAN_P22_0104",
        title="Operational Action Plan 22-104",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_104",
        time_of_occurrence_min=704,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0105": IncidentContingencyPlan(
        plan_id="PLAN_P22_0105",
        title="Operational Action Plan 22-105",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_105",
        time_of_occurrence_min=705,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0106": IncidentContingencyPlan(
        plan_id="PLAN_P22_0106",
        title="Operational Action Plan 22-106",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_106",
        time_of_occurrence_min=706,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0107": IncidentContingencyPlan(
        plan_id="PLAN_P22_0107",
        title="Operational Action Plan 22-107",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_107",
        time_of_occurrence_min=707,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0108": IncidentContingencyPlan(
        plan_id="PLAN_P22_0108",
        title="Operational Action Plan 22-108",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_108",
        time_of_occurrence_min=708,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0109": IncidentContingencyPlan(
        plan_id="PLAN_P22_0109",
        title="Operational Action Plan 22-109",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_109",
        time_of_occurrence_min=709,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0110": IncidentContingencyPlan(
        plan_id="PLAN_P22_0110",
        title="Operational Action Plan 22-110",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_110",
        time_of_occurrence_min=710,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0111": IncidentContingencyPlan(
        plan_id="PLAN_P22_0111",
        title="Operational Action Plan 22-111",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_111",
        time_of_occurrence_min=711,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0112": IncidentContingencyPlan(
        plan_id="PLAN_P22_0112",
        title="Operational Action Plan 22-112",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_112",
        time_of_occurrence_min=712,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0113": IncidentContingencyPlan(
        plan_id="PLAN_P22_0113",
        title="Operational Action Plan 22-113",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_113",
        time_of_occurrence_min=713,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0114": IncidentContingencyPlan(
        plan_id="PLAN_P22_0114",
        title="Operational Action Plan 22-114",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_114",
        time_of_occurrence_min=714,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0115": IncidentContingencyPlan(
        plan_id="PLAN_P22_0115",
        title="Operational Action Plan 22-115",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_115",
        time_of_occurrence_min=715,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0116": IncidentContingencyPlan(
        plan_id="PLAN_P22_0116",
        title="Operational Action Plan 22-116",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_116",
        time_of_occurrence_min=716,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0117": IncidentContingencyPlan(
        plan_id="PLAN_P22_0117",
        title="Operational Action Plan 22-117",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_117",
        time_of_occurrence_min=717,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0118": IncidentContingencyPlan(
        plan_id="PLAN_P22_0118",
        title="Operational Action Plan 22-118",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_118",
        time_of_occurrence_min=718,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0119": IncidentContingencyPlan(
        plan_id="PLAN_P22_0119",
        title="Operational Action Plan 22-119",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_119",
        time_of_occurrence_min=719,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0120": IncidentContingencyPlan(
        plan_id="PLAN_P22_0120",
        title="Operational Action Plan 22-120",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_120",
        time_of_occurrence_min=720,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0121": IncidentContingencyPlan(
        plan_id="PLAN_P22_0121",
        title="Operational Action Plan 22-121",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_121",
        time_of_occurrence_min=721,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0122": IncidentContingencyPlan(
        plan_id="PLAN_P22_0122",
        title="Operational Action Plan 22-122",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_122",
        time_of_occurrence_min=722,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0123": IncidentContingencyPlan(
        plan_id="PLAN_P22_0123",
        title="Operational Action Plan 22-123",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_123",
        time_of_occurrence_min=723,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0124": IncidentContingencyPlan(
        plan_id="PLAN_P22_0124",
        title="Operational Action Plan 22-124",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_124",
        time_of_occurrence_min=724,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0125": IncidentContingencyPlan(
        plan_id="PLAN_P22_0125",
        title="Operational Action Plan 22-125",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_125",
        time_of_occurrence_min=725,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0126": IncidentContingencyPlan(
        plan_id="PLAN_P22_0126",
        title="Operational Action Plan 22-126",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_126",
        time_of_occurrence_min=726,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0127": IncidentContingencyPlan(
        plan_id="PLAN_P22_0127",
        title="Operational Action Plan 22-127",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_127",
        time_of_occurrence_min=727,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0128": IncidentContingencyPlan(
        plan_id="PLAN_P22_0128",
        title="Operational Action Plan 22-128",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_128",
        time_of_occurrence_min=728,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0129": IncidentContingencyPlan(
        plan_id="PLAN_P22_0129",
        title="Operational Action Plan 22-129",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_129",
        time_of_occurrence_min=729,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0130": IncidentContingencyPlan(
        plan_id="PLAN_P22_0130",
        title="Operational Action Plan 22-130",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_130",
        time_of_occurrence_min=730,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0131": IncidentContingencyPlan(
        plan_id="PLAN_P22_0131",
        title="Operational Action Plan 22-131",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_131",
        time_of_occurrence_min=731,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0132": IncidentContingencyPlan(
        plan_id="PLAN_P22_0132",
        title="Operational Action Plan 22-132",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_132",
        time_of_occurrence_min=732,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0133": IncidentContingencyPlan(
        plan_id="PLAN_P22_0133",
        title="Operational Action Plan 22-133",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_133",
        time_of_occurrence_min=733,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0134": IncidentContingencyPlan(
        plan_id="PLAN_P22_0134",
        title="Operational Action Plan 22-134",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_134",
        time_of_occurrence_min=734,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0135": IncidentContingencyPlan(
        plan_id="PLAN_P22_0135",
        title="Operational Action Plan 22-135",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_135",
        time_of_occurrence_min=735,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0136": IncidentContingencyPlan(
        plan_id="PLAN_P22_0136",
        title="Operational Action Plan 22-136",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_136",
        time_of_occurrence_min=736,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0137": IncidentContingencyPlan(
        plan_id="PLAN_P22_0137",
        title="Operational Action Plan 22-137",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_137",
        time_of_occurrence_min=737,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0138": IncidentContingencyPlan(
        plan_id="PLAN_P22_0138",
        title="Operational Action Plan 22-138",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_138",
        time_of_occurrence_min=738,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0139": IncidentContingencyPlan(
        plan_id="PLAN_P22_0139",
        title="Operational Action Plan 22-139",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_139",
        time_of_occurrence_min=739,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0140": IncidentContingencyPlan(
        plan_id="PLAN_P22_0140",
        title="Operational Action Plan 22-140",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_140",
        time_of_occurrence_min=740,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0141": IncidentContingencyPlan(
        plan_id="PLAN_P22_0141",
        title="Operational Action Plan 22-141",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_141",
        time_of_occurrence_min=741,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0142": IncidentContingencyPlan(
        plan_id="PLAN_P22_0142",
        title="Operational Action Plan 22-142",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_142",
        time_of_occurrence_min=742,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0143": IncidentContingencyPlan(
        plan_id="PLAN_P22_0143",
        title="Operational Action Plan 22-143",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_143",
        time_of_occurrence_min=743,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0144": IncidentContingencyPlan(
        plan_id="PLAN_P22_0144",
        title="Operational Action Plan 22-144",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_144",
        time_of_occurrence_min=744,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0145": IncidentContingencyPlan(
        plan_id="PLAN_P22_0145",
        title="Operational Action Plan 22-145",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_145",
        time_of_occurrence_min=745,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0146": IncidentContingencyPlan(
        plan_id="PLAN_P22_0146",
        title="Operational Action Plan 22-146",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_146",
        time_of_occurrence_min=746,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0147": IncidentContingencyPlan(
        plan_id="PLAN_P22_0147",
        title="Operational Action Plan 22-147",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_147",
        time_of_occurrence_min=747,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0148": IncidentContingencyPlan(
        plan_id="PLAN_P22_0148",
        title="Operational Action Plan 22-148",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_148",
        time_of_occurrence_min=748,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0149": IncidentContingencyPlan(
        plan_id="PLAN_P22_0149",
        title="Operational Action Plan 22-149",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_149",
        time_of_occurrence_min=749,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0150": IncidentContingencyPlan(
        plan_id="PLAN_P22_0150",
        title="Operational Action Plan 22-150",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_150",
        time_of_occurrence_min=750,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0151": IncidentContingencyPlan(
        plan_id="PLAN_P22_0151",
        title="Operational Action Plan 22-151",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_151",
        time_of_occurrence_min=751,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0152": IncidentContingencyPlan(
        plan_id="PLAN_P22_0152",
        title="Operational Action Plan 22-152",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_152",
        time_of_occurrence_min=752,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0153": IncidentContingencyPlan(
        plan_id="PLAN_P22_0153",
        title="Operational Action Plan 22-153",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_153",
        time_of_occurrence_min=753,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0154": IncidentContingencyPlan(
        plan_id="PLAN_P22_0154",
        title="Operational Action Plan 22-154",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_154",
        time_of_occurrence_min=754,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0155": IncidentContingencyPlan(
        plan_id="PLAN_P22_0155",
        title="Operational Action Plan 22-155",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_155",
        time_of_occurrence_min=755,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0156": IncidentContingencyPlan(
        plan_id="PLAN_P22_0156",
        title="Operational Action Plan 22-156",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_156",
        time_of_occurrence_min=756,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0157": IncidentContingencyPlan(
        plan_id="PLAN_P22_0157",
        title="Operational Action Plan 22-157",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_157",
        time_of_occurrence_min=757,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0158": IncidentContingencyPlan(
        plan_id="PLAN_P22_0158",
        title="Operational Action Plan 22-158",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_158",
        time_of_occurrence_min=758,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0159": IncidentContingencyPlan(
        plan_id="PLAN_P22_0159",
        title="Operational Action Plan 22-159",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_159",
        time_of_occurrence_min=759,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0160": IncidentContingencyPlan(
        plan_id="PLAN_P22_0160",
        title="Operational Action Plan 22-160",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_160",
        time_of_occurrence_min=760,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0161": IncidentContingencyPlan(
        plan_id="PLAN_P22_0161",
        title="Operational Action Plan 22-161",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_161",
        time_of_occurrence_min=761,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0162": IncidentContingencyPlan(
        plan_id="PLAN_P22_0162",
        title="Operational Action Plan 22-162",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_162",
        time_of_occurrence_min=762,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0163": IncidentContingencyPlan(
        plan_id="PLAN_P22_0163",
        title="Operational Action Plan 22-163",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_163",
        time_of_occurrence_min=763,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0164": IncidentContingencyPlan(
        plan_id="PLAN_P22_0164",
        title="Operational Action Plan 22-164",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_164",
        time_of_occurrence_min=764,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
    "PLAN_P22_0165": IncidentContingencyPlan(
        plan_id="PLAN_P22_0165",
        title="Operational Action Plan 22-165",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_165",
        time_of_occurrence_min=765,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_05"
    ),
    "PLAN_P22_0166": IncidentContingencyPlan(
        plan_id="PLAN_P22_0166",
        title="Operational Action Plan 22-166",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_166",
        time_of_occurrence_min=766,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_06"
    ),
    "PLAN_P22_0167": IncidentContingencyPlan(
        plan_id="PLAN_P22_0167",
        title="Operational Action Plan 22-167",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_167",
        time_of_occurrence_min=767,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_07"
    ),
    "PLAN_P22_0168": IncidentContingencyPlan(
        plan_id="PLAN_P22_0168",
        title="Operational Action Plan 22-168",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_168",
        time_of_occurrence_min=768,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_08"
    ),
    "PLAN_P22_0169": IncidentContingencyPlan(
        plan_id="PLAN_P22_0169",
        title="Operational Action Plan 22-169",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P22_169",
        time_of_occurrence_min=769,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_09"
    ),
    "PLAN_P22_0170": IncidentContingencyPlan(
        plan_id="PLAN_P22_0170",
        title="Operational Action Plan 22-170",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P22_170",
        time_of_occurrence_min=770,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_00"
    ),
    "PLAN_P22_0171": IncidentContingencyPlan(
        plan_id="PLAN_P22_0171",
        title="Operational Action Plan 22-171",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P22_171",
        time_of_occurrence_min=771,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_01"
    ),
    "PLAN_P22_0172": IncidentContingencyPlan(
        plan_id="PLAN_P22_0172",
        title="Operational Action Plan 22-172",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P22_172",
        time_of_occurrence_min=772,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_02"
    ),
    "PLAN_P22_0173": IncidentContingencyPlan(
        plan_id="PLAN_P22_0173",
        title="Operational Action Plan 22-173",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P22_173",
        time_of_occurrence_min=773,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_03"
    ),
    "PLAN_P22_0174": IncidentContingencyPlan(
        plan_id="PLAN_P22_0174",
        title="Operational Action Plan 22-174",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P22_174",
        time_of_occurrence_min=774,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_22_04"
    ),
}
