"""Railway Incident Contingency Action Plans Part 024."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class IncidentContingencyPlan:
    plan_id: str
    title: str
    incident_type: str
    affected_block_id: str
    time_of_occurrence_min: int
    expected_clearance_min: int
    severity_score: int
    primary_dispatch_action: str
    contingency_corridor_id: str

INCIDENT_CONTINGENCY_PLANS_024: Dict[str, IncidentContingencyPlan] = {
    "PLAN_P24_0001": IncidentContingencyPlan(
        plan_id="PLAN_P24_0001",
        title="Operational Action Plan 24-1",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_001",
        time_of_occurrence_min=601,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0002": IncidentContingencyPlan(
        plan_id="PLAN_P24_0002",
        title="Operational Action Plan 24-2",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_002",
        time_of_occurrence_min=602,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0003": IncidentContingencyPlan(
        plan_id="PLAN_P24_0003",
        title="Operational Action Plan 24-3",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_003",
        time_of_occurrence_min=603,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0004": IncidentContingencyPlan(
        plan_id="PLAN_P24_0004",
        title="Operational Action Plan 24-4",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_004",
        time_of_occurrence_min=604,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0005": IncidentContingencyPlan(
        plan_id="PLAN_P24_0005",
        title="Operational Action Plan 24-5",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_005",
        time_of_occurrence_min=605,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0006": IncidentContingencyPlan(
        plan_id="PLAN_P24_0006",
        title="Operational Action Plan 24-6",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_006",
        time_of_occurrence_min=606,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0007": IncidentContingencyPlan(
        plan_id="PLAN_P24_0007",
        title="Operational Action Plan 24-7",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_007",
        time_of_occurrence_min=607,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0008": IncidentContingencyPlan(
        plan_id="PLAN_P24_0008",
        title="Operational Action Plan 24-8",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_008",
        time_of_occurrence_min=608,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0009": IncidentContingencyPlan(
        plan_id="PLAN_P24_0009",
        title="Operational Action Plan 24-9",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_009",
        time_of_occurrence_min=609,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0010": IncidentContingencyPlan(
        plan_id="PLAN_P24_0010",
        title="Operational Action Plan 24-10",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_010",
        time_of_occurrence_min=610,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0011": IncidentContingencyPlan(
        plan_id="PLAN_P24_0011",
        title="Operational Action Plan 24-11",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_011",
        time_of_occurrence_min=611,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0012": IncidentContingencyPlan(
        plan_id="PLAN_P24_0012",
        title="Operational Action Plan 24-12",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_012",
        time_of_occurrence_min=612,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0013": IncidentContingencyPlan(
        plan_id="PLAN_P24_0013",
        title="Operational Action Plan 24-13",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_013",
        time_of_occurrence_min=613,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0014": IncidentContingencyPlan(
        plan_id="PLAN_P24_0014",
        title="Operational Action Plan 24-14",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_014",
        time_of_occurrence_min=614,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0015": IncidentContingencyPlan(
        plan_id="PLAN_P24_0015",
        title="Operational Action Plan 24-15",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_015",
        time_of_occurrence_min=615,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0016": IncidentContingencyPlan(
        plan_id="PLAN_P24_0016",
        title="Operational Action Plan 24-16",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_016",
        time_of_occurrence_min=616,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0017": IncidentContingencyPlan(
        plan_id="PLAN_P24_0017",
        title="Operational Action Plan 24-17",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_017",
        time_of_occurrence_min=617,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0018": IncidentContingencyPlan(
        plan_id="PLAN_P24_0018",
        title="Operational Action Plan 24-18",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_018",
        time_of_occurrence_min=618,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0019": IncidentContingencyPlan(
        plan_id="PLAN_P24_0019",
        title="Operational Action Plan 24-19",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_019",
        time_of_occurrence_min=619,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0020": IncidentContingencyPlan(
        plan_id="PLAN_P24_0020",
        title="Operational Action Plan 24-20",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_020",
        time_of_occurrence_min=620,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0021": IncidentContingencyPlan(
        plan_id="PLAN_P24_0021",
        title="Operational Action Plan 24-21",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_021",
        time_of_occurrence_min=621,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0022": IncidentContingencyPlan(
        plan_id="PLAN_P24_0022",
        title="Operational Action Plan 24-22",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_022",
        time_of_occurrence_min=622,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0023": IncidentContingencyPlan(
        plan_id="PLAN_P24_0023",
        title="Operational Action Plan 24-23",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_023",
        time_of_occurrence_min=623,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0024": IncidentContingencyPlan(
        plan_id="PLAN_P24_0024",
        title="Operational Action Plan 24-24",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_024",
        time_of_occurrence_min=624,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0025": IncidentContingencyPlan(
        plan_id="PLAN_P24_0025",
        title="Operational Action Plan 24-25",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_025",
        time_of_occurrence_min=625,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0026": IncidentContingencyPlan(
        plan_id="PLAN_P24_0026",
        title="Operational Action Plan 24-26",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_026",
        time_of_occurrence_min=626,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0027": IncidentContingencyPlan(
        plan_id="PLAN_P24_0027",
        title="Operational Action Plan 24-27",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_027",
        time_of_occurrence_min=627,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0028": IncidentContingencyPlan(
        plan_id="PLAN_P24_0028",
        title="Operational Action Plan 24-28",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_028",
        time_of_occurrence_min=628,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0029": IncidentContingencyPlan(
        plan_id="PLAN_P24_0029",
        title="Operational Action Plan 24-29",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_029",
        time_of_occurrence_min=629,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0030": IncidentContingencyPlan(
        plan_id="PLAN_P24_0030",
        title="Operational Action Plan 24-30",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_030",
        time_of_occurrence_min=630,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0031": IncidentContingencyPlan(
        plan_id="PLAN_P24_0031",
        title="Operational Action Plan 24-31",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_031",
        time_of_occurrence_min=631,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0032": IncidentContingencyPlan(
        plan_id="PLAN_P24_0032",
        title="Operational Action Plan 24-32",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_032",
        time_of_occurrence_min=632,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0033": IncidentContingencyPlan(
        plan_id="PLAN_P24_0033",
        title="Operational Action Plan 24-33",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_033",
        time_of_occurrence_min=633,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0034": IncidentContingencyPlan(
        plan_id="PLAN_P24_0034",
        title="Operational Action Plan 24-34",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_034",
        time_of_occurrence_min=634,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0035": IncidentContingencyPlan(
        plan_id="PLAN_P24_0035",
        title="Operational Action Plan 24-35",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_035",
        time_of_occurrence_min=635,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0036": IncidentContingencyPlan(
        plan_id="PLAN_P24_0036",
        title="Operational Action Plan 24-36",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_036",
        time_of_occurrence_min=636,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0037": IncidentContingencyPlan(
        plan_id="PLAN_P24_0037",
        title="Operational Action Plan 24-37",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_037",
        time_of_occurrence_min=637,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0038": IncidentContingencyPlan(
        plan_id="PLAN_P24_0038",
        title="Operational Action Plan 24-38",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_038",
        time_of_occurrence_min=638,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0039": IncidentContingencyPlan(
        plan_id="PLAN_P24_0039",
        title="Operational Action Plan 24-39",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_039",
        time_of_occurrence_min=639,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0040": IncidentContingencyPlan(
        plan_id="PLAN_P24_0040",
        title="Operational Action Plan 24-40",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_040",
        time_of_occurrence_min=640,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0041": IncidentContingencyPlan(
        plan_id="PLAN_P24_0041",
        title="Operational Action Plan 24-41",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_041",
        time_of_occurrence_min=641,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0042": IncidentContingencyPlan(
        plan_id="PLAN_P24_0042",
        title="Operational Action Plan 24-42",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_042",
        time_of_occurrence_min=642,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0043": IncidentContingencyPlan(
        plan_id="PLAN_P24_0043",
        title="Operational Action Plan 24-43",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_043",
        time_of_occurrence_min=643,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0044": IncidentContingencyPlan(
        plan_id="PLAN_P24_0044",
        title="Operational Action Plan 24-44",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_044",
        time_of_occurrence_min=644,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0045": IncidentContingencyPlan(
        plan_id="PLAN_P24_0045",
        title="Operational Action Plan 24-45",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_045",
        time_of_occurrence_min=645,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0046": IncidentContingencyPlan(
        plan_id="PLAN_P24_0046",
        title="Operational Action Plan 24-46",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_046",
        time_of_occurrence_min=646,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0047": IncidentContingencyPlan(
        plan_id="PLAN_P24_0047",
        title="Operational Action Plan 24-47",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_047",
        time_of_occurrence_min=647,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0048": IncidentContingencyPlan(
        plan_id="PLAN_P24_0048",
        title="Operational Action Plan 24-48",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_048",
        time_of_occurrence_min=648,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0049": IncidentContingencyPlan(
        plan_id="PLAN_P24_0049",
        title="Operational Action Plan 24-49",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_049",
        time_of_occurrence_min=649,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0050": IncidentContingencyPlan(
        plan_id="PLAN_P24_0050",
        title="Operational Action Plan 24-50",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_050",
        time_of_occurrence_min=650,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0051": IncidentContingencyPlan(
        plan_id="PLAN_P24_0051",
        title="Operational Action Plan 24-51",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_051",
        time_of_occurrence_min=651,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0052": IncidentContingencyPlan(
        plan_id="PLAN_P24_0052",
        title="Operational Action Plan 24-52",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_052",
        time_of_occurrence_min=652,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0053": IncidentContingencyPlan(
        plan_id="PLAN_P24_0053",
        title="Operational Action Plan 24-53",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_053",
        time_of_occurrence_min=653,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0054": IncidentContingencyPlan(
        plan_id="PLAN_P24_0054",
        title="Operational Action Plan 24-54",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_054",
        time_of_occurrence_min=654,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0055": IncidentContingencyPlan(
        plan_id="PLAN_P24_0055",
        title="Operational Action Plan 24-55",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_055",
        time_of_occurrence_min=655,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0056": IncidentContingencyPlan(
        plan_id="PLAN_P24_0056",
        title="Operational Action Plan 24-56",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_056",
        time_of_occurrence_min=656,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0057": IncidentContingencyPlan(
        plan_id="PLAN_P24_0057",
        title="Operational Action Plan 24-57",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_057",
        time_of_occurrence_min=657,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0058": IncidentContingencyPlan(
        plan_id="PLAN_P24_0058",
        title="Operational Action Plan 24-58",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_058",
        time_of_occurrence_min=658,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0059": IncidentContingencyPlan(
        plan_id="PLAN_P24_0059",
        title="Operational Action Plan 24-59",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_059",
        time_of_occurrence_min=659,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0060": IncidentContingencyPlan(
        plan_id="PLAN_P24_0060",
        title="Operational Action Plan 24-60",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_060",
        time_of_occurrence_min=660,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0061": IncidentContingencyPlan(
        plan_id="PLAN_P24_0061",
        title="Operational Action Plan 24-61",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_061",
        time_of_occurrence_min=661,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0062": IncidentContingencyPlan(
        plan_id="PLAN_P24_0062",
        title="Operational Action Plan 24-62",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_062",
        time_of_occurrence_min=662,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0063": IncidentContingencyPlan(
        plan_id="PLAN_P24_0063",
        title="Operational Action Plan 24-63",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_063",
        time_of_occurrence_min=663,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0064": IncidentContingencyPlan(
        plan_id="PLAN_P24_0064",
        title="Operational Action Plan 24-64",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_064",
        time_of_occurrence_min=664,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0065": IncidentContingencyPlan(
        plan_id="PLAN_P24_0065",
        title="Operational Action Plan 24-65",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_065",
        time_of_occurrence_min=665,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0066": IncidentContingencyPlan(
        plan_id="PLAN_P24_0066",
        title="Operational Action Plan 24-66",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_066",
        time_of_occurrence_min=666,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0067": IncidentContingencyPlan(
        plan_id="PLAN_P24_0067",
        title="Operational Action Plan 24-67",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_067",
        time_of_occurrence_min=667,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0068": IncidentContingencyPlan(
        plan_id="PLAN_P24_0068",
        title="Operational Action Plan 24-68",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_068",
        time_of_occurrence_min=668,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0069": IncidentContingencyPlan(
        plan_id="PLAN_P24_0069",
        title="Operational Action Plan 24-69",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_069",
        time_of_occurrence_min=669,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0070": IncidentContingencyPlan(
        plan_id="PLAN_P24_0070",
        title="Operational Action Plan 24-70",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_070",
        time_of_occurrence_min=670,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0071": IncidentContingencyPlan(
        plan_id="PLAN_P24_0071",
        title="Operational Action Plan 24-71",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_071",
        time_of_occurrence_min=671,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0072": IncidentContingencyPlan(
        plan_id="PLAN_P24_0072",
        title="Operational Action Plan 24-72",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_072",
        time_of_occurrence_min=672,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0073": IncidentContingencyPlan(
        plan_id="PLAN_P24_0073",
        title="Operational Action Plan 24-73",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_073",
        time_of_occurrence_min=673,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0074": IncidentContingencyPlan(
        plan_id="PLAN_P24_0074",
        title="Operational Action Plan 24-74",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_074",
        time_of_occurrence_min=674,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0075": IncidentContingencyPlan(
        plan_id="PLAN_P24_0075",
        title="Operational Action Plan 24-75",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_075",
        time_of_occurrence_min=675,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0076": IncidentContingencyPlan(
        plan_id="PLAN_P24_0076",
        title="Operational Action Plan 24-76",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_076",
        time_of_occurrence_min=676,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0077": IncidentContingencyPlan(
        plan_id="PLAN_P24_0077",
        title="Operational Action Plan 24-77",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_077",
        time_of_occurrence_min=677,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0078": IncidentContingencyPlan(
        plan_id="PLAN_P24_0078",
        title="Operational Action Plan 24-78",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_078",
        time_of_occurrence_min=678,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0079": IncidentContingencyPlan(
        plan_id="PLAN_P24_0079",
        title="Operational Action Plan 24-79",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_079",
        time_of_occurrence_min=679,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0080": IncidentContingencyPlan(
        plan_id="PLAN_P24_0080",
        title="Operational Action Plan 24-80",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_080",
        time_of_occurrence_min=680,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0081": IncidentContingencyPlan(
        plan_id="PLAN_P24_0081",
        title="Operational Action Plan 24-81",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_081",
        time_of_occurrence_min=681,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0082": IncidentContingencyPlan(
        plan_id="PLAN_P24_0082",
        title="Operational Action Plan 24-82",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_082",
        time_of_occurrence_min=682,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0083": IncidentContingencyPlan(
        plan_id="PLAN_P24_0083",
        title="Operational Action Plan 24-83",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_083",
        time_of_occurrence_min=683,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0084": IncidentContingencyPlan(
        plan_id="PLAN_P24_0084",
        title="Operational Action Plan 24-84",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_084",
        time_of_occurrence_min=684,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0085": IncidentContingencyPlan(
        plan_id="PLAN_P24_0085",
        title="Operational Action Plan 24-85",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_085",
        time_of_occurrence_min=685,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0086": IncidentContingencyPlan(
        plan_id="PLAN_P24_0086",
        title="Operational Action Plan 24-86",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_086",
        time_of_occurrence_min=686,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0087": IncidentContingencyPlan(
        plan_id="PLAN_P24_0087",
        title="Operational Action Plan 24-87",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_087",
        time_of_occurrence_min=687,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0088": IncidentContingencyPlan(
        plan_id="PLAN_P24_0088",
        title="Operational Action Plan 24-88",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_088",
        time_of_occurrence_min=688,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0089": IncidentContingencyPlan(
        plan_id="PLAN_P24_0089",
        title="Operational Action Plan 24-89",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_089",
        time_of_occurrence_min=689,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0090": IncidentContingencyPlan(
        plan_id="PLAN_P24_0090",
        title="Operational Action Plan 24-90",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_090",
        time_of_occurrence_min=690,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0091": IncidentContingencyPlan(
        plan_id="PLAN_P24_0091",
        title="Operational Action Plan 24-91",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_091",
        time_of_occurrence_min=691,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0092": IncidentContingencyPlan(
        plan_id="PLAN_P24_0092",
        title="Operational Action Plan 24-92",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_092",
        time_of_occurrence_min=692,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0093": IncidentContingencyPlan(
        plan_id="PLAN_P24_0093",
        title="Operational Action Plan 24-93",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_093",
        time_of_occurrence_min=693,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0094": IncidentContingencyPlan(
        plan_id="PLAN_P24_0094",
        title="Operational Action Plan 24-94",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_094",
        time_of_occurrence_min=694,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0095": IncidentContingencyPlan(
        plan_id="PLAN_P24_0095",
        title="Operational Action Plan 24-95",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_095",
        time_of_occurrence_min=695,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0096": IncidentContingencyPlan(
        plan_id="PLAN_P24_0096",
        title="Operational Action Plan 24-96",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_096",
        time_of_occurrence_min=696,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0097": IncidentContingencyPlan(
        plan_id="PLAN_P24_0097",
        title="Operational Action Plan 24-97",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_097",
        time_of_occurrence_min=697,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0098": IncidentContingencyPlan(
        plan_id="PLAN_P24_0098",
        title="Operational Action Plan 24-98",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_098",
        time_of_occurrence_min=698,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0099": IncidentContingencyPlan(
        plan_id="PLAN_P24_0099",
        title="Operational Action Plan 24-99",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_099",
        time_of_occurrence_min=699,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0100": IncidentContingencyPlan(
        plan_id="PLAN_P24_0100",
        title="Operational Action Plan 24-100",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_100",
        time_of_occurrence_min=700,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0101": IncidentContingencyPlan(
        plan_id="PLAN_P24_0101",
        title="Operational Action Plan 24-101",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_101",
        time_of_occurrence_min=701,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0102": IncidentContingencyPlan(
        plan_id="PLAN_P24_0102",
        title="Operational Action Plan 24-102",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_102",
        time_of_occurrence_min=702,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0103": IncidentContingencyPlan(
        plan_id="PLAN_P24_0103",
        title="Operational Action Plan 24-103",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_103",
        time_of_occurrence_min=703,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0104": IncidentContingencyPlan(
        plan_id="PLAN_P24_0104",
        title="Operational Action Plan 24-104",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_104",
        time_of_occurrence_min=704,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0105": IncidentContingencyPlan(
        plan_id="PLAN_P24_0105",
        title="Operational Action Plan 24-105",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_105",
        time_of_occurrence_min=705,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0106": IncidentContingencyPlan(
        plan_id="PLAN_P24_0106",
        title="Operational Action Plan 24-106",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_106",
        time_of_occurrence_min=706,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0107": IncidentContingencyPlan(
        plan_id="PLAN_P24_0107",
        title="Operational Action Plan 24-107",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_107",
        time_of_occurrence_min=707,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0108": IncidentContingencyPlan(
        plan_id="PLAN_P24_0108",
        title="Operational Action Plan 24-108",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_108",
        time_of_occurrence_min=708,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0109": IncidentContingencyPlan(
        plan_id="PLAN_P24_0109",
        title="Operational Action Plan 24-109",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_109",
        time_of_occurrence_min=709,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0110": IncidentContingencyPlan(
        plan_id="PLAN_P24_0110",
        title="Operational Action Plan 24-110",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_110",
        time_of_occurrence_min=710,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0111": IncidentContingencyPlan(
        plan_id="PLAN_P24_0111",
        title="Operational Action Plan 24-111",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_111",
        time_of_occurrence_min=711,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0112": IncidentContingencyPlan(
        plan_id="PLAN_P24_0112",
        title="Operational Action Plan 24-112",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_112",
        time_of_occurrence_min=712,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0113": IncidentContingencyPlan(
        plan_id="PLAN_P24_0113",
        title="Operational Action Plan 24-113",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_113",
        time_of_occurrence_min=713,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0114": IncidentContingencyPlan(
        plan_id="PLAN_P24_0114",
        title="Operational Action Plan 24-114",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_114",
        time_of_occurrence_min=714,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0115": IncidentContingencyPlan(
        plan_id="PLAN_P24_0115",
        title="Operational Action Plan 24-115",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_115",
        time_of_occurrence_min=715,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0116": IncidentContingencyPlan(
        plan_id="PLAN_P24_0116",
        title="Operational Action Plan 24-116",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_116",
        time_of_occurrence_min=716,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0117": IncidentContingencyPlan(
        plan_id="PLAN_P24_0117",
        title="Operational Action Plan 24-117",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_117",
        time_of_occurrence_min=717,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0118": IncidentContingencyPlan(
        plan_id="PLAN_P24_0118",
        title="Operational Action Plan 24-118",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_118",
        time_of_occurrence_min=718,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0119": IncidentContingencyPlan(
        plan_id="PLAN_P24_0119",
        title="Operational Action Plan 24-119",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_119",
        time_of_occurrence_min=719,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0120": IncidentContingencyPlan(
        plan_id="PLAN_P24_0120",
        title="Operational Action Plan 24-120",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_120",
        time_of_occurrence_min=720,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0121": IncidentContingencyPlan(
        plan_id="PLAN_P24_0121",
        title="Operational Action Plan 24-121",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_121",
        time_of_occurrence_min=721,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0122": IncidentContingencyPlan(
        plan_id="PLAN_P24_0122",
        title="Operational Action Plan 24-122",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_122",
        time_of_occurrence_min=722,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0123": IncidentContingencyPlan(
        plan_id="PLAN_P24_0123",
        title="Operational Action Plan 24-123",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_123",
        time_of_occurrence_min=723,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0124": IncidentContingencyPlan(
        plan_id="PLAN_P24_0124",
        title="Operational Action Plan 24-124",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_124",
        time_of_occurrence_min=724,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0125": IncidentContingencyPlan(
        plan_id="PLAN_P24_0125",
        title="Operational Action Plan 24-125",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_125",
        time_of_occurrence_min=725,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0126": IncidentContingencyPlan(
        plan_id="PLAN_P24_0126",
        title="Operational Action Plan 24-126",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_126",
        time_of_occurrence_min=726,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0127": IncidentContingencyPlan(
        plan_id="PLAN_P24_0127",
        title="Operational Action Plan 24-127",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_127",
        time_of_occurrence_min=727,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0128": IncidentContingencyPlan(
        plan_id="PLAN_P24_0128",
        title="Operational Action Plan 24-128",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_128",
        time_of_occurrence_min=728,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0129": IncidentContingencyPlan(
        plan_id="PLAN_P24_0129",
        title="Operational Action Plan 24-129",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_129",
        time_of_occurrence_min=729,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0130": IncidentContingencyPlan(
        plan_id="PLAN_P24_0130",
        title="Operational Action Plan 24-130",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_130",
        time_of_occurrence_min=730,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0131": IncidentContingencyPlan(
        plan_id="PLAN_P24_0131",
        title="Operational Action Plan 24-131",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_131",
        time_of_occurrence_min=731,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0132": IncidentContingencyPlan(
        plan_id="PLAN_P24_0132",
        title="Operational Action Plan 24-132",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_132",
        time_of_occurrence_min=732,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0133": IncidentContingencyPlan(
        plan_id="PLAN_P24_0133",
        title="Operational Action Plan 24-133",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_133",
        time_of_occurrence_min=733,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0134": IncidentContingencyPlan(
        plan_id="PLAN_P24_0134",
        title="Operational Action Plan 24-134",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_134",
        time_of_occurrence_min=734,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0135": IncidentContingencyPlan(
        plan_id="PLAN_P24_0135",
        title="Operational Action Plan 24-135",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_135",
        time_of_occurrence_min=735,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0136": IncidentContingencyPlan(
        plan_id="PLAN_P24_0136",
        title="Operational Action Plan 24-136",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_136",
        time_of_occurrence_min=736,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0137": IncidentContingencyPlan(
        plan_id="PLAN_P24_0137",
        title="Operational Action Plan 24-137",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_137",
        time_of_occurrence_min=737,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0138": IncidentContingencyPlan(
        plan_id="PLAN_P24_0138",
        title="Operational Action Plan 24-138",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_138",
        time_of_occurrence_min=738,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0139": IncidentContingencyPlan(
        plan_id="PLAN_P24_0139",
        title="Operational Action Plan 24-139",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_139",
        time_of_occurrence_min=739,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0140": IncidentContingencyPlan(
        plan_id="PLAN_P24_0140",
        title="Operational Action Plan 24-140",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_140",
        time_of_occurrence_min=740,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0141": IncidentContingencyPlan(
        plan_id="PLAN_P24_0141",
        title="Operational Action Plan 24-141",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_141",
        time_of_occurrence_min=741,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0142": IncidentContingencyPlan(
        plan_id="PLAN_P24_0142",
        title="Operational Action Plan 24-142",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_142",
        time_of_occurrence_min=742,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0143": IncidentContingencyPlan(
        plan_id="PLAN_P24_0143",
        title="Operational Action Plan 24-143",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_143",
        time_of_occurrence_min=743,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0144": IncidentContingencyPlan(
        plan_id="PLAN_P24_0144",
        title="Operational Action Plan 24-144",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_144",
        time_of_occurrence_min=744,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0145": IncidentContingencyPlan(
        plan_id="PLAN_P24_0145",
        title="Operational Action Plan 24-145",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_145",
        time_of_occurrence_min=745,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0146": IncidentContingencyPlan(
        plan_id="PLAN_P24_0146",
        title="Operational Action Plan 24-146",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_146",
        time_of_occurrence_min=746,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0147": IncidentContingencyPlan(
        plan_id="PLAN_P24_0147",
        title="Operational Action Plan 24-147",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_147",
        time_of_occurrence_min=747,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0148": IncidentContingencyPlan(
        plan_id="PLAN_P24_0148",
        title="Operational Action Plan 24-148",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_148",
        time_of_occurrence_min=748,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0149": IncidentContingencyPlan(
        plan_id="PLAN_P24_0149",
        title="Operational Action Plan 24-149",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_149",
        time_of_occurrence_min=749,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0150": IncidentContingencyPlan(
        plan_id="PLAN_P24_0150",
        title="Operational Action Plan 24-150",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_150",
        time_of_occurrence_min=750,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0151": IncidentContingencyPlan(
        plan_id="PLAN_P24_0151",
        title="Operational Action Plan 24-151",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_151",
        time_of_occurrence_min=751,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0152": IncidentContingencyPlan(
        plan_id="PLAN_P24_0152",
        title="Operational Action Plan 24-152",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_152",
        time_of_occurrence_min=752,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0153": IncidentContingencyPlan(
        plan_id="PLAN_P24_0153",
        title="Operational Action Plan 24-153",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_153",
        time_of_occurrence_min=753,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0154": IncidentContingencyPlan(
        plan_id="PLAN_P24_0154",
        title="Operational Action Plan 24-154",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_154",
        time_of_occurrence_min=754,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0155": IncidentContingencyPlan(
        plan_id="PLAN_P24_0155",
        title="Operational Action Plan 24-155",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_155",
        time_of_occurrence_min=755,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0156": IncidentContingencyPlan(
        plan_id="PLAN_P24_0156",
        title="Operational Action Plan 24-156",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_156",
        time_of_occurrence_min=756,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0157": IncidentContingencyPlan(
        plan_id="PLAN_P24_0157",
        title="Operational Action Plan 24-157",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_157",
        time_of_occurrence_min=757,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0158": IncidentContingencyPlan(
        plan_id="PLAN_P24_0158",
        title="Operational Action Plan 24-158",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_158",
        time_of_occurrence_min=758,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0159": IncidentContingencyPlan(
        plan_id="PLAN_P24_0159",
        title="Operational Action Plan 24-159",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_159",
        time_of_occurrence_min=759,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0160": IncidentContingencyPlan(
        plan_id="PLAN_P24_0160",
        title="Operational Action Plan 24-160",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_160",
        time_of_occurrence_min=760,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0161": IncidentContingencyPlan(
        plan_id="PLAN_P24_0161",
        title="Operational Action Plan 24-161",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_161",
        time_of_occurrence_min=761,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0162": IncidentContingencyPlan(
        plan_id="PLAN_P24_0162",
        title="Operational Action Plan 24-162",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_162",
        time_of_occurrence_min=762,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0163": IncidentContingencyPlan(
        plan_id="PLAN_P24_0163",
        title="Operational Action Plan 24-163",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_163",
        time_of_occurrence_min=763,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0164": IncidentContingencyPlan(
        plan_id="PLAN_P24_0164",
        title="Operational Action Plan 24-164",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_164",
        time_of_occurrence_min=764,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
    "PLAN_P24_0165": IncidentContingencyPlan(
        plan_id="PLAN_P24_0165",
        title="Operational Action Plan 24-165",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_165",
        time_of_occurrence_min=765,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_05"
    ),
    "PLAN_P24_0166": IncidentContingencyPlan(
        plan_id="PLAN_P24_0166",
        title="Operational Action Plan 24-166",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_166",
        time_of_occurrence_min=766,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_06"
    ),
    "PLAN_P24_0167": IncidentContingencyPlan(
        plan_id="PLAN_P24_0167",
        title="Operational Action Plan 24-167",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_167",
        time_of_occurrence_min=767,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_07"
    ),
    "PLAN_P24_0168": IncidentContingencyPlan(
        plan_id="PLAN_P24_0168",
        title="Operational Action Plan 24-168",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_168",
        time_of_occurrence_min=768,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_08"
    ),
    "PLAN_P24_0169": IncidentContingencyPlan(
        plan_id="PLAN_P24_0169",
        title="Operational Action Plan 24-169",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P24_169",
        time_of_occurrence_min=769,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_09"
    ),
    "PLAN_P24_0170": IncidentContingencyPlan(
        plan_id="PLAN_P24_0170",
        title="Operational Action Plan 24-170",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P24_170",
        time_of_occurrence_min=770,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_00"
    ),
    "PLAN_P24_0171": IncidentContingencyPlan(
        plan_id="PLAN_P24_0171",
        title="Operational Action Plan 24-171",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P24_171",
        time_of_occurrence_min=771,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_01"
    ),
    "PLAN_P24_0172": IncidentContingencyPlan(
        plan_id="PLAN_P24_0172",
        title="Operational Action Plan 24-172",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P24_172",
        time_of_occurrence_min=772,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_02"
    ),
    "PLAN_P24_0173": IncidentContingencyPlan(
        plan_id="PLAN_P24_0173",
        title="Operational Action Plan 24-173",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P24_173",
        time_of_occurrence_min=773,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_03"
    ),
    "PLAN_P24_0174": IncidentContingencyPlan(
        plan_id="PLAN_P24_0174",
        title="Operational Action Plan 24-174",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P24_174",
        time_of_occurrence_min=774,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_24_04"
    ),
}
