"""Railway Incident Contingency Action Plans Part 001."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class IncidentContingencyPlan:
    plan_id: str
    title: str
    incident_type: str
    affected_block_id: str
    time_of_occurrence_min: int
    expected_clearance_min: int
    severity_score: int
    primary_dispatch_action: str
    contingency_corridor_id: str

INCIDENT_CONTINGENCY_PLANS_001: Dict[str, IncidentContingencyPlan] = {
    "PLAN_P01_0001": IncidentContingencyPlan(
        plan_id="PLAN_P01_0001",
        title="Operational Action Plan 1-1",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_001",
        time_of_occurrence_min=601,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0002": IncidentContingencyPlan(
        plan_id="PLAN_P01_0002",
        title="Operational Action Plan 1-2",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_002",
        time_of_occurrence_min=602,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0003": IncidentContingencyPlan(
        plan_id="PLAN_P01_0003",
        title="Operational Action Plan 1-3",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_003",
        time_of_occurrence_min=603,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0004": IncidentContingencyPlan(
        plan_id="PLAN_P01_0004",
        title="Operational Action Plan 1-4",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_004",
        time_of_occurrence_min=604,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0005": IncidentContingencyPlan(
        plan_id="PLAN_P01_0005",
        title="Operational Action Plan 1-5",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_005",
        time_of_occurrence_min=605,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0006": IncidentContingencyPlan(
        plan_id="PLAN_P01_0006",
        title="Operational Action Plan 1-6",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_006",
        time_of_occurrence_min=606,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0007": IncidentContingencyPlan(
        plan_id="PLAN_P01_0007",
        title="Operational Action Plan 1-7",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_007",
        time_of_occurrence_min=607,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0008": IncidentContingencyPlan(
        plan_id="PLAN_P01_0008",
        title="Operational Action Plan 1-8",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_008",
        time_of_occurrence_min=608,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0009": IncidentContingencyPlan(
        plan_id="PLAN_P01_0009",
        title="Operational Action Plan 1-9",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_009",
        time_of_occurrence_min=609,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0010": IncidentContingencyPlan(
        plan_id="PLAN_P01_0010",
        title="Operational Action Plan 1-10",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_010",
        time_of_occurrence_min=610,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0011": IncidentContingencyPlan(
        plan_id="PLAN_P01_0011",
        title="Operational Action Plan 1-11",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_011",
        time_of_occurrence_min=611,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0012": IncidentContingencyPlan(
        plan_id="PLAN_P01_0012",
        title="Operational Action Plan 1-12",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_012",
        time_of_occurrence_min=612,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0013": IncidentContingencyPlan(
        plan_id="PLAN_P01_0013",
        title="Operational Action Plan 1-13",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_013",
        time_of_occurrence_min=613,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0014": IncidentContingencyPlan(
        plan_id="PLAN_P01_0014",
        title="Operational Action Plan 1-14",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_014",
        time_of_occurrence_min=614,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0015": IncidentContingencyPlan(
        plan_id="PLAN_P01_0015",
        title="Operational Action Plan 1-15",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_015",
        time_of_occurrence_min=615,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0016": IncidentContingencyPlan(
        plan_id="PLAN_P01_0016",
        title="Operational Action Plan 1-16",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_016",
        time_of_occurrence_min=616,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0017": IncidentContingencyPlan(
        plan_id="PLAN_P01_0017",
        title="Operational Action Plan 1-17",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_017",
        time_of_occurrence_min=617,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0018": IncidentContingencyPlan(
        plan_id="PLAN_P01_0018",
        title="Operational Action Plan 1-18",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_018",
        time_of_occurrence_min=618,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0019": IncidentContingencyPlan(
        plan_id="PLAN_P01_0019",
        title="Operational Action Plan 1-19",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_019",
        time_of_occurrence_min=619,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0020": IncidentContingencyPlan(
        plan_id="PLAN_P01_0020",
        title="Operational Action Plan 1-20",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_020",
        time_of_occurrence_min=620,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0021": IncidentContingencyPlan(
        plan_id="PLAN_P01_0021",
        title="Operational Action Plan 1-21",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_021",
        time_of_occurrence_min=621,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0022": IncidentContingencyPlan(
        plan_id="PLAN_P01_0022",
        title="Operational Action Plan 1-22",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_022",
        time_of_occurrence_min=622,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0023": IncidentContingencyPlan(
        plan_id="PLAN_P01_0023",
        title="Operational Action Plan 1-23",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_023",
        time_of_occurrence_min=623,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0024": IncidentContingencyPlan(
        plan_id="PLAN_P01_0024",
        title="Operational Action Plan 1-24",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_024",
        time_of_occurrence_min=624,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0025": IncidentContingencyPlan(
        plan_id="PLAN_P01_0025",
        title="Operational Action Plan 1-25",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_025",
        time_of_occurrence_min=625,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0026": IncidentContingencyPlan(
        plan_id="PLAN_P01_0026",
        title="Operational Action Plan 1-26",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_026",
        time_of_occurrence_min=626,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0027": IncidentContingencyPlan(
        plan_id="PLAN_P01_0027",
        title="Operational Action Plan 1-27",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_027",
        time_of_occurrence_min=627,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0028": IncidentContingencyPlan(
        plan_id="PLAN_P01_0028",
        title="Operational Action Plan 1-28",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_028",
        time_of_occurrence_min=628,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0029": IncidentContingencyPlan(
        plan_id="PLAN_P01_0029",
        title="Operational Action Plan 1-29",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_029",
        time_of_occurrence_min=629,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0030": IncidentContingencyPlan(
        plan_id="PLAN_P01_0030",
        title="Operational Action Plan 1-30",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_030",
        time_of_occurrence_min=630,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0031": IncidentContingencyPlan(
        plan_id="PLAN_P01_0031",
        title="Operational Action Plan 1-31",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_031",
        time_of_occurrence_min=631,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0032": IncidentContingencyPlan(
        plan_id="PLAN_P01_0032",
        title="Operational Action Plan 1-32",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_032",
        time_of_occurrence_min=632,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0033": IncidentContingencyPlan(
        plan_id="PLAN_P01_0033",
        title="Operational Action Plan 1-33",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_033",
        time_of_occurrence_min=633,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0034": IncidentContingencyPlan(
        plan_id="PLAN_P01_0034",
        title="Operational Action Plan 1-34",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_034",
        time_of_occurrence_min=634,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0035": IncidentContingencyPlan(
        plan_id="PLAN_P01_0035",
        title="Operational Action Plan 1-35",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_035",
        time_of_occurrence_min=635,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0036": IncidentContingencyPlan(
        plan_id="PLAN_P01_0036",
        title="Operational Action Plan 1-36",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_036",
        time_of_occurrence_min=636,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0037": IncidentContingencyPlan(
        plan_id="PLAN_P01_0037",
        title="Operational Action Plan 1-37",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_037",
        time_of_occurrence_min=637,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0038": IncidentContingencyPlan(
        plan_id="PLAN_P01_0038",
        title="Operational Action Plan 1-38",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_038",
        time_of_occurrence_min=638,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0039": IncidentContingencyPlan(
        plan_id="PLAN_P01_0039",
        title="Operational Action Plan 1-39",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_039",
        time_of_occurrence_min=639,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0040": IncidentContingencyPlan(
        plan_id="PLAN_P01_0040",
        title="Operational Action Plan 1-40",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_040",
        time_of_occurrence_min=640,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0041": IncidentContingencyPlan(
        plan_id="PLAN_P01_0041",
        title="Operational Action Plan 1-41",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_041",
        time_of_occurrence_min=641,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0042": IncidentContingencyPlan(
        plan_id="PLAN_P01_0042",
        title="Operational Action Plan 1-42",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_042",
        time_of_occurrence_min=642,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0043": IncidentContingencyPlan(
        plan_id="PLAN_P01_0043",
        title="Operational Action Plan 1-43",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_043",
        time_of_occurrence_min=643,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0044": IncidentContingencyPlan(
        plan_id="PLAN_P01_0044",
        title="Operational Action Plan 1-44",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_044",
        time_of_occurrence_min=644,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0045": IncidentContingencyPlan(
        plan_id="PLAN_P01_0045",
        title="Operational Action Plan 1-45",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_045",
        time_of_occurrence_min=645,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0046": IncidentContingencyPlan(
        plan_id="PLAN_P01_0046",
        title="Operational Action Plan 1-46",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_046",
        time_of_occurrence_min=646,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0047": IncidentContingencyPlan(
        plan_id="PLAN_P01_0047",
        title="Operational Action Plan 1-47",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_047",
        time_of_occurrence_min=647,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0048": IncidentContingencyPlan(
        plan_id="PLAN_P01_0048",
        title="Operational Action Plan 1-48",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_048",
        time_of_occurrence_min=648,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0049": IncidentContingencyPlan(
        plan_id="PLAN_P01_0049",
        title="Operational Action Plan 1-49",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_049",
        time_of_occurrence_min=649,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0050": IncidentContingencyPlan(
        plan_id="PLAN_P01_0050",
        title="Operational Action Plan 1-50",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_050",
        time_of_occurrence_min=650,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0051": IncidentContingencyPlan(
        plan_id="PLAN_P01_0051",
        title="Operational Action Plan 1-51",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_051",
        time_of_occurrence_min=651,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0052": IncidentContingencyPlan(
        plan_id="PLAN_P01_0052",
        title="Operational Action Plan 1-52",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_052",
        time_of_occurrence_min=652,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0053": IncidentContingencyPlan(
        plan_id="PLAN_P01_0053",
        title="Operational Action Plan 1-53",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_053",
        time_of_occurrence_min=653,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0054": IncidentContingencyPlan(
        plan_id="PLAN_P01_0054",
        title="Operational Action Plan 1-54",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_054",
        time_of_occurrence_min=654,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0055": IncidentContingencyPlan(
        plan_id="PLAN_P01_0055",
        title="Operational Action Plan 1-55",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_055",
        time_of_occurrence_min=655,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0056": IncidentContingencyPlan(
        plan_id="PLAN_P01_0056",
        title="Operational Action Plan 1-56",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_056",
        time_of_occurrence_min=656,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0057": IncidentContingencyPlan(
        plan_id="PLAN_P01_0057",
        title="Operational Action Plan 1-57",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_057",
        time_of_occurrence_min=657,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0058": IncidentContingencyPlan(
        plan_id="PLAN_P01_0058",
        title="Operational Action Plan 1-58",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_058",
        time_of_occurrence_min=658,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0059": IncidentContingencyPlan(
        plan_id="PLAN_P01_0059",
        title="Operational Action Plan 1-59",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_059",
        time_of_occurrence_min=659,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0060": IncidentContingencyPlan(
        plan_id="PLAN_P01_0060",
        title="Operational Action Plan 1-60",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_060",
        time_of_occurrence_min=660,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0061": IncidentContingencyPlan(
        plan_id="PLAN_P01_0061",
        title="Operational Action Plan 1-61",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_061",
        time_of_occurrence_min=661,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0062": IncidentContingencyPlan(
        plan_id="PLAN_P01_0062",
        title="Operational Action Plan 1-62",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_062",
        time_of_occurrence_min=662,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0063": IncidentContingencyPlan(
        plan_id="PLAN_P01_0063",
        title="Operational Action Plan 1-63",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_063",
        time_of_occurrence_min=663,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0064": IncidentContingencyPlan(
        plan_id="PLAN_P01_0064",
        title="Operational Action Plan 1-64",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_064",
        time_of_occurrence_min=664,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0065": IncidentContingencyPlan(
        plan_id="PLAN_P01_0065",
        title="Operational Action Plan 1-65",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_065",
        time_of_occurrence_min=665,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0066": IncidentContingencyPlan(
        plan_id="PLAN_P01_0066",
        title="Operational Action Plan 1-66",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_066",
        time_of_occurrence_min=666,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0067": IncidentContingencyPlan(
        plan_id="PLAN_P01_0067",
        title="Operational Action Plan 1-67",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_067",
        time_of_occurrence_min=667,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0068": IncidentContingencyPlan(
        plan_id="PLAN_P01_0068",
        title="Operational Action Plan 1-68",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_068",
        time_of_occurrence_min=668,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0069": IncidentContingencyPlan(
        plan_id="PLAN_P01_0069",
        title="Operational Action Plan 1-69",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_069",
        time_of_occurrence_min=669,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0070": IncidentContingencyPlan(
        plan_id="PLAN_P01_0070",
        title="Operational Action Plan 1-70",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_070",
        time_of_occurrence_min=670,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0071": IncidentContingencyPlan(
        plan_id="PLAN_P01_0071",
        title="Operational Action Plan 1-71",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_071",
        time_of_occurrence_min=671,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0072": IncidentContingencyPlan(
        plan_id="PLAN_P01_0072",
        title="Operational Action Plan 1-72",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_072",
        time_of_occurrence_min=672,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0073": IncidentContingencyPlan(
        plan_id="PLAN_P01_0073",
        title="Operational Action Plan 1-73",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_073",
        time_of_occurrence_min=673,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0074": IncidentContingencyPlan(
        plan_id="PLAN_P01_0074",
        title="Operational Action Plan 1-74",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_074",
        time_of_occurrence_min=674,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0075": IncidentContingencyPlan(
        plan_id="PLAN_P01_0075",
        title="Operational Action Plan 1-75",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_075",
        time_of_occurrence_min=675,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0076": IncidentContingencyPlan(
        plan_id="PLAN_P01_0076",
        title="Operational Action Plan 1-76",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_076",
        time_of_occurrence_min=676,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0077": IncidentContingencyPlan(
        plan_id="PLAN_P01_0077",
        title="Operational Action Plan 1-77",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_077",
        time_of_occurrence_min=677,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0078": IncidentContingencyPlan(
        plan_id="PLAN_P01_0078",
        title="Operational Action Plan 1-78",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_078",
        time_of_occurrence_min=678,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0079": IncidentContingencyPlan(
        plan_id="PLAN_P01_0079",
        title="Operational Action Plan 1-79",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_079",
        time_of_occurrence_min=679,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0080": IncidentContingencyPlan(
        plan_id="PLAN_P01_0080",
        title="Operational Action Plan 1-80",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_080",
        time_of_occurrence_min=680,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0081": IncidentContingencyPlan(
        plan_id="PLAN_P01_0081",
        title="Operational Action Plan 1-81",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_081",
        time_of_occurrence_min=681,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0082": IncidentContingencyPlan(
        plan_id="PLAN_P01_0082",
        title="Operational Action Plan 1-82",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_082",
        time_of_occurrence_min=682,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0083": IncidentContingencyPlan(
        plan_id="PLAN_P01_0083",
        title="Operational Action Plan 1-83",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_083",
        time_of_occurrence_min=683,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0084": IncidentContingencyPlan(
        plan_id="PLAN_P01_0084",
        title="Operational Action Plan 1-84",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_084",
        time_of_occurrence_min=684,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0085": IncidentContingencyPlan(
        plan_id="PLAN_P01_0085",
        title="Operational Action Plan 1-85",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_085",
        time_of_occurrence_min=685,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0086": IncidentContingencyPlan(
        plan_id="PLAN_P01_0086",
        title="Operational Action Plan 1-86",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_086",
        time_of_occurrence_min=686,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0087": IncidentContingencyPlan(
        plan_id="PLAN_P01_0087",
        title="Operational Action Plan 1-87",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_087",
        time_of_occurrence_min=687,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0088": IncidentContingencyPlan(
        plan_id="PLAN_P01_0088",
        title="Operational Action Plan 1-88",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_088",
        time_of_occurrence_min=688,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0089": IncidentContingencyPlan(
        plan_id="PLAN_P01_0089",
        title="Operational Action Plan 1-89",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_089",
        time_of_occurrence_min=689,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0090": IncidentContingencyPlan(
        plan_id="PLAN_P01_0090",
        title="Operational Action Plan 1-90",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_090",
        time_of_occurrence_min=690,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0091": IncidentContingencyPlan(
        plan_id="PLAN_P01_0091",
        title="Operational Action Plan 1-91",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_091",
        time_of_occurrence_min=691,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0092": IncidentContingencyPlan(
        plan_id="PLAN_P01_0092",
        title="Operational Action Plan 1-92",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_092",
        time_of_occurrence_min=692,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0093": IncidentContingencyPlan(
        plan_id="PLAN_P01_0093",
        title="Operational Action Plan 1-93",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_093",
        time_of_occurrence_min=693,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0094": IncidentContingencyPlan(
        plan_id="PLAN_P01_0094",
        title="Operational Action Plan 1-94",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_094",
        time_of_occurrence_min=694,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0095": IncidentContingencyPlan(
        plan_id="PLAN_P01_0095",
        title="Operational Action Plan 1-95",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_095",
        time_of_occurrence_min=695,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0096": IncidentContingencyPlan(
        plan_id="PLAN_P01_0096",
        title="Operational Action Plan 1-96",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_096",
        time_of_occurrence_min=696,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0097": IncidentContingencyPlan(
        plan_id="PLAN_P01_0097",
        title="Operational Action Plan 1-97",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_097",
        time_of_occurrence_min=697,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0098": IncidentContingencyPlan(
        plan_id="PLAN_P01_0098",
        title="Operational Action Plan 1-98",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_098",
        time_of_occurrence_min=698,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0099": IncidentContingencyPlan(
        plan_id="PLAN_P01_0099",
        title="Operational Action Plan 1-99",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_099",
        time_of_occurrence_min=699,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0100": IncidentContingencyPlan(
        plan_id="PLAN_P01_0100",
        title="Operational Action Plan 1-100",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_100",
        time_of_occurrence_min=700,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0101": IncidentContingencyPlan(
        plan_id="PLAN_P01_0101",
        title="Operational Action Plan 1-101",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_101",
        time_of_occurrence_min=701,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0102": IncidentContingencyPlan(
        plan_id="PLAN_P01_0102",
        title="Operational Action Plan 1-102",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_102",
        time_of_occurrence_min=702,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0103": IncidentContingencyPlan(
        plan_id="PLAN_P01_0103",
        title="Operational Action Plan 1-103",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_103",
        time_of_occurrence_min=703,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0104": IncidentContingencyPlan(
        plan_id="PLAN_P01_0104",
        title="Operational Action Plan 1-104",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_104",
        time_of_occurrence_min=704,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0105": IncidentContingencyPlan(
        plan_id="PLAN_P01_0105",
        title="Operational Action Plan 1-105",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_105",
        time_of_occurrence_min=705,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0106": IncidentContingencyPlan(
        plan_id="PLAN_P01_0106",
        title="Operational Action Plan 1-106",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_106",
        time_of_occurrence_min=706,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0107": IncidentContingencyPlan(
        plan_id="PLAN_P01_0107",
        title="Operational Action Plan 1-107",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_107",
        time_of_occurrence_min=707,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0108": IncidentContingencyPlan(
        plan_id="PLAN_P01_0108",
        title="Operational Action Plan 1-108",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_108",
        time_of_occurrence_min=708,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0109": IncidentContingencyPlan(
        plan_id="PLAN_P01_0109",
        title="Operational Action Plan 1-109",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_109",
        time_of_occurrence_min=709,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0110": IncidentContingencyPlan(
        plan_id="PLAN_P01_0110",
        title="Operational Action Plan 1-110",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_110",
        time_of_occurrence_min=710,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0111": IncidentContingencyPlan(
        plan_id="PLAN_P01_0111",
        title="Operational Action Plan 1-111",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_111",
        time_of_occurrence_min=711,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0112": IncidentContingencyPlan(
        plan_id="PLAN_P01_0112",
        title="Operational Action Plan 1-112",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_112",
        time_of_occurrence_min=712,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0113": IncidentContingencyPlan(
        plan_id="PLAN_P01_0113",
        title="Operational Action Plan 1-113",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_113",
        time_of_occurrence_min=713,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0114": IncidentContingencyPlan(
        plan_id="PLAN_P01_0114",
        title="Operational Action Plan 1-114",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_114",
        time_of_occurrence_min=714,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0115": IncidentContingencyPlan(
        plan_id="PLAN_P01_0115",
        title="Operational Action Plan 1-115",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_115",
        time_of_occurrence_min=715,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0116": IncidentContingencyPlan(
        plan_id="PLAN_P01_0116",
        title="Operational Action Plan 1-116",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_116",
        time_of_occurrence_min=716,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0117": IncidentContingencyPlan(
        plan_id="PLAN_P01_0117",
        title="Operational Action Plan 1-117",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_117",
        time_of_occurrence_min=717,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0118": IncidentContingencyPlan(
        plan_id="PLAN_P01_0118",
        title="Operational Action Plan 1-118",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_118",
        time_of_occurrence_min=718,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0119": IncidentContingencyPlan(
        plan_id="PLAN_P01_0119",
        title="Operational Action Plan 1-119",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_119",
        time_of_occurrence_min=719,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0120": IncidentContingencyPlan(
        plan_id="PLAN_P01_0120",
        title="Operational Action Plan 1-120",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_120",
        time_of_occurrence_min=720,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0121": IncidentContingencyPlan(
        plan_id="PLAN_P01_0121",
        title="Operational Action Plan 1-121",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_121",
        time_of_occurrence_min=721,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0122": IncidentContingencyPlan(
        plan_id="PLAN_P01_0122",
        title="Operational Action Plan 1-122",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_122",
        time_of_occurrence_min=722,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0123": IncidentContingencyPlan(
        plan_id="PLAN_P01_0123",
        title="Operational Action Plan 1-123",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_123",
        time_of_occurrence_min=723,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0124": IncidentContingencyPlan(
        plan_id="PLAN_P01_0124",
        title="Operational Action Plan 1-124",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_124",
        time_of_occurrence_min=724,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0125": IncidentContingencyPlan(
        plan_id="PLAN_P01_0125",
        title="Operational Action Plan 1-125",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_125",
        time_of_occurrence_min=725,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0126": IncidentContingencyPlan(
        plan_id="PLAN_P01_0126",
        title="Operational Action Plan 1-126",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_126",
        time_of_occurrence_min=726,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0127": IncidentContingencyPlan(
        plan_id="PLAN_P01_0127",
        title="Operational Action Plan 1-127",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_127",
        time_of_occurrence_min=727,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0128": IncidentContingencyPlan(
        plan_id="PLAN_P01_0128",
        title="Operational Action Plan 1-128",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_128",
        time_of_occurrence_min=728,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0129": IncidentContingencyPlan(
        plan_id="PLAN_P01_0129",
        title="Operational Action Plan 1-129",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_129",
        time_of_occurrence_min=729,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0130": IncidentContingencyPlan(
        plan_id="PLAN_P01_0130",
        title="Operational Action Plan 1-130",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_130",
        time_of_occurrence_min=730,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0131": IncidentContingencyPlan(
        plan_id="PLAN_P01_0131",
        title="Operational Action Plan 1-131",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_131",
        time_of_occurrence_min=731,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0132": IncidentContingencyPlan(
        plan_id="PLAN_P01_0132",
        title="Operational Action Plan 1-132",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_132",
        time_of_occurrence_min=732,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0133": IncidentContingencyPlan(
        plan_id="PLAN_P01_0133",
        title="Operational Action Plan 1-133",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_133",
        time_of_occurrence_min=733,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0134": IncidentContingencyPlan(
        plan_id="PLAN_P01_0134",
        title="Operational Action Plan 1-134",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_134",
        time_of_occurrence_min=734,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0135": IncidentContingencyPlan(
        plan_id="PLAN_P01_0135",
        title="Operational Action Plan 1-135",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_135",
        time_of_occurrence_min=735,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0136": IncidentContingencyPlan(
        plan_id="PLAN_P01_0136",
        title="Operational Action Plan 1-136",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_136",
        time_of_occurrence_min=736,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0137": IncidentContingencyPlan(
        plan_id="PLAN_P01_0137",
        title="Operational Action Plan 1-137",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_137",
        time_of_occurrence_min=737,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0138": IncidentContingencyPlan(
        plan_id="PLAN_P01_0138",
        title="Operational Action Plan 1-138",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_138",
        time_of_occurrence_min=738,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0139": IncidentContingencyPlan(
        plan_id="PLAN_P01_0139",
        title="Operational Action Plan 1-139",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_139",
        time_of_occurrence_min=739,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0140": IncidentContingencyPlan(
        plan_id="PLAN_P01_0140",
        title="Operational Action Plan 1-140",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_140",
        time_of_occurrence_min=740,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0141": IncidentContingencyPlan(
        plan_id="PLAN_P01_0141",
        title="Operational Action Plan 1-141",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_141",
        time_of_occurrence_min=741,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0142": IncidentContingencyPlan(
        plan_id="PLAN_P01_0142",
        title="Operational Action Plan 1-142",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_142",
        time_of_occurrence_min=742,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0143": IncidentContingencyPlan(
        plan_id="PLAN_P01_0143",
        title="Operational Action Plan 1-143",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_143",
        time_of_occurrence_min=743,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0144": IncidentContingencyPlan(
        plan_id="PLAN_P01_0144",
        title="Operational Action Plan 1-144",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_144",
        time_of_occurrence_min=744,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0145": IncidentContingencyPlan(
        plan_id="PLAN_P01_0145",
        title="Operational Action Plan 1-145",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_145",
        time_of_occurrence_min=745,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0146": IncidentContingencyPlan(
        plan_id="PLAN_P01_0146",
        title="Operational Action Plan 1-146",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_146",
        time_of_occurrence_min=746,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0147": IncidentContingencyPlan(
        plan_id="PLAN_P01_0147",
        title="Operational Action Plan 1-147",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_147",
        time_of_occurrence_min=747,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0148": IncidentContingencyPlan(
        plan_id="PLAN_P01_0148",
        title="Operational Action Plan 1-148",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_148",
        time_of_occurrence_min=748,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0149": IncidentContingencyPlan(
        plan_id="PLAN_P01_0149",
        title="Operational Action Plan 1-149",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_149",
        time_of_occurrence_min=749,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0150": IncidentContingencyPlan(
        plan_id="PLAN_P01_0150",
        title="Operational Action Plan 1-150",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_150",
        time_of_occurrence_min=750,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0151": IncidentContingencyPlan(
        plan_id="PLAN_P01_0151",
        title="Operational Action Plan 1-151",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_151",
        time_of_occurrence_min=751,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0152": IncidentContingencyPlan(
        plan_id="PLAN_P01_0152",
        title="Operational Action Plan 1-152",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_152",
        time_of_occurrence_min=752,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0153": IncidentContingencyPlan(
        plan_id="PLAN_P01_0153",
        title="Operational Action Plan 1-153",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_153",
        time_of_occurrence_min=753,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0154": IncidentContingencyPlan(
        plan_id="PLAN_P01_0154",
        title="Operational Action Plan 1-154",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_154",
        time_of_occurrence_min=754,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0155": IncidentContingencyPlan(
        plan_id="PLAN_P01_0155",
        title="Operational Action Plan 1-155",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_155",
        time_of_occurrence_min=755,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0156": IncidentContingencyPlan(
        plan_id="PLAN_P01_0156",
        title="Operational Action Plan 1-156",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_156",
        time_of_occurrence_min=756,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0157": IncidentContingencyPlan(
        plan_id="PLAN_P01_0157",
        title="Operational Action Plan 1-157",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_157",
        time_of_occurrence_min=757,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0158": IncidentContingencyPlan(
        plan_id="PLAN_P01_0158",
        title="Operational Action Plan 1-158",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_158",
        time_of_occurrence_min=758,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0159": IncidentContingencyPlan(
        plan_id="PLAN_P01_0159",
        title="Operational Action Plan 1-159",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_159",
        time_of_occurrence_min=759,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0160": IncidentContingencyPlan(
        plan_id="PLAN_P01_0160",
        title="Operational Action Plan 1-160",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_160",
        time_of_occurrence_min=760,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0161": IncidentContingencyPlan(
        plan_id="PLAN_P01_0161",
        title="Operational Action Plan 1-161",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_161",
        time_of_occurrence_min=761,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0162": IncidentContingencyPlan(
        plan_id="PLAN_P01_0162",
        title="Operational Action Plan 1-162",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_162",
        time_of_occurrence_min=762,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0163": IncidentContingencyPlan(
        plan_id="PLAN_P01_0163",
        title="Operational Action Plan 1-163",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_163",
        time_of_occurrence_min=763,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0164": IncidentContingencyPlan(
        plan_id="PLAN_P01_0164",
        title="Operational Action Plan 1-164",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_164",
        time_of_occurrence_min=764,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
    "PLAN_P01_0165": IncidentContingencyPlan(
        plan_id="PLAN_P01_0165",
        title="Operational Action Plan 1-165",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_165",
        time_of_occurrence_min=765,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_05"
    ),
    "PLAN_P01_0166": IncidentContingencyPlan(
        plan_id="PLAN_P01_0166",
        title="Operational Action Plan 1-166",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_166",
        time_of_occurrence_min=766,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_06"
    ),
    "PLAN_P01_0167": IncidentContingencyPlan(
        plan_id="PLAN_P01_0167",
        title="Operational Action Plan 1-167",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_167",
        time_of_occurrence_min=767,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_07"
    ),
    "PLAN_P01_0168": IncidentContingencyPlan(
        plan_id="PLAN_P01_0168",
        title="Operational Action Plan 1-168",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_168",
        time_of_occurrence_min=768,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_08"
    ),
    "PLAN_P01_0169": IncidentContingencyPlan(
        plan_id="PLAN_P01_0169",
        title="Operational Action Plan 1-169",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P1_169",
        time_of_occurrence_min=769,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_09"
    ),
    "PLAN_P01_0170": IncidentContingencyPlan(
        plan_id="PLAN_P01_0170",
        title="Operational Action Plan 1-170",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P1_170",
        time_of_occurrence_min=770,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_00"
    ),
    "PLAN_P01_0171": IncidentContingencyPlan(
        plan_id="PLAN_P01_0171",
        title="Operational Action Plan 1-171",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P1_171",
        time_of_occurrence_min=771,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_01"
    ),
    "PLAN_P01_0172": IncidentContingencyPlan(
        plan_id="PLAN_P01_0172",
        title="Operational Action Plan 1-172",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P1_172",
        time_of_occurrence_min=772,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_02"
    ),
    "PLAN_P01_0173": IncidentContingencyPlan(
        plan_id="PLAN_P01_0173",
        title="Operational Action Plan 1-173",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P1_173",
        time_of_occurrence_min=773,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_03"
    ),
    "PLAN_P01_0174": IncidentContingencyPlan(
        plan_id="PLAN_P01_0174",
        title="Operational Action Plan 1-174",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P1_174",
        time_of_occurrence_min=774,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_01_04"
    ),
}
