"""Railway Incident Contingency Action Plans Part 012."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class IncidentContingencyPlan:
    plan_id: str
    title: str
    incident_type: str
    affected_block_id: str
    time_of_occurrence_min: int
    expected_clearance_min: int
    severity_score: int
    primary_dispatch_action: str
    contingency_corridor_id: str

INCIDENT_CONTINGENCY_PLANS_012: Dict[str, IncidentContingencyPlan] = {
    "PLAN_P12_0001": IncidentContingencyPlan(
        plan_id="PLAN_P12_0001",
        title="Operational Action Plan 12-1",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_001",
        time_of_occurrence_min=601,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0002": IncidentContingencyPlan(
        plan_id="PLAN_P12_0002",
        title="Operational Action Plan 12-2",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_002",
        time_of_occurrence_min=602,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0003": IncidentContingencyPlan(
        plan_id="PLAN_P12_0003",
        title="Operational Action Plan 12-3",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_003",
        time_of_occurrence_min=603,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0004": IncidentContingencyPlan(
        plan_id="PLAN_P12_0004",
        title="Operational Action Plan 12-4",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_004",
        time_of_occurrence_min=604,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0005": IncidentContingencyPlan(
        plan_id="PLAN_P12_0005",
        title="Operational Action Plan 12-5",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_005",
        time_of_occurrence_min=605,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0006": IncidentContingencyPlan(
        plan_id="PLAN_P12_0006",
        title="Operational Action Plan 12-6",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_006",
        time_of_occurrence_min=606,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0007": IncidentContingencyPlan(
        plan_id="PLAN_P12_0007",
        title="Operational Action Plan 12-7",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_007",
        time_of_occurrence_min=607,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0008": IncidentContingencyPlan(
        plan_id="PLAN_P12_0008",
        title="Operational Action Plan 12-8",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_008",
        time_of_occurrence_min=608,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0009": IncidentContingencyPlan(
        plan_id="PLAN_P12_0009",
        title="Operational Action Plan 12-9",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_009",
        time_of_occurrence_min=609,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0010": IncidentContingencyPlan(
        plan_id="PLAN_P12_0010",
        title="Operational Action Plan 12-10",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_010",
        time_of_occurrence_min=610,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0011": IncidentContingencyPlan(
        plan_id="PLAN_P12_0011",
        title="Operational Action Plan 12-11",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_011",
        time_of_occurrence_min=611,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0012": IncidentContingencyPlan(
        plan_id="PLAN_P12_0012",
        title="Operational Action Plan 12-12",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_012",
        time_of_occurrence_min=612,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0013": IncidentContingencyPlan(
        plan_id="PLAN_P12_0013",
        title="Operational Action Plan 12-13",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_013",
        time_of_occurrence_min=613,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0014": IncidentContingencyPlan(
        plan_id="PLAN_P12_0014",
        title="Operational Action Plan 12-14",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_014",
        time_of_occurrence_min=614,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0015": IncidentContingencyPlan(
        plan_id="PLAN_P12_0015",
        title="Operational Action Plan 12-15",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_015",
        time_of_occurrence_min=615,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0016": IncidentContingencyPlan(
        plan_id="PLAN_P12_0016",
        title="Operational Action Plan 12-16",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_016",
        time_of_occurrence_min=616,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0017": IncidentContingencyPlan(
        plan_id="PLAN_P12_0017",
        title="Operational Action Plan 12-17",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_017",
        time_of_occurrence_min=617,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0018": IncidentContingencyPlan(
        plan_id="PLAN_P12_0018",
        title="Operational Action Plan 12-18",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_018",
        time_of_occurrence_min=618,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0019": IncidentContingencyPlan(
        plan_id="PLAN_P12_0019",
        title="Operational Action Plan 12-19",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_019",
        time_of_occurrence_min=619,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0020": IncidentContingencyPlan(
        plan_id="PLAN_P12_0020",
        title="Operational Action Plan 12-20",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_020",
        time_of_occurrence_min=620,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0021": IncidentContingencyPlan(
        plan_id="PLAN_P12_0021",
        title="Operational Action Plan 12-21",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_021",
        time_of_occurrence_min=621,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0022": IncidentContingencyPlan(
        plan_id="PLAN_P12_0022",
        title="Operational Action Plan 12-22",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_022",
        time_of_occurrence_min=622,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0023": IncidentContingencyPlan(
        plan_id="PLAN_P12_0023",
        title="Operational Action Plan 12-23",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_023",
        time_of_occurrence_min=623,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0024": IncidentContingencyPlan(
        plan_id="PLAN_P12_0024",
        title="Operational Action Plan 12-24",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_024",
        time_of_occurrence_min=624,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0025": IncidentContingencyPlan(
        plan_id="PLAN_P12_0025",
        title="Operational Action Plan 12-25",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_025",
        time_of_occurrence_min=625,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0026": IncidentContingencyPlan(
        plan_id="PLAN_P12_0026",
        title="Operational Action Plan 12-26",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_026",
        time_of_occurrence_min=626,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0027": IncidentContingencyPlan(
        plan_id="PLAN_P12_0027",
        title="Operational Action Plan 12-27",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_027",
        time_of_occurrence_min=627,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0028": IncidentContingencyPlan(
        plan_id="PLAN_P12_0028",
        title="Operational Action Plan 12-28",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_028",
        time_of_occurrence_min=628,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0029": IncidentContingencyPlan(
        plan_id="PLAN_P12_0029",
        title="Operational Action Plan 12-29",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_029",
        time_of_occurrence_min=629,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0030": IncidentContingencyPlan(
        plan_id="PLAN_P12_0030",
        title="Operational Action Plan 12-30",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_030",
        time_of_occurrence_min=630,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0031": IncidentContingencyPlan(
        plan_id="PLAN_P12_0031",
        title="Operational Action Plan 12-31",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_031",
        time_of_occurrence_min=631,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0032": IncidentContingencyPlan(
        plan_id="PLAN_P12_0032",
        title="Operational Action Plan 12-32",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_032",
        time_of_occurrence_min=632,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0033": IncidentContingencyPlan(
        plan_id="PLAN_P12_0033",
        title="Operational Action Plan 12-33",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_033",
        time_of_occurrence_min=633,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0034": IncidentContingencyPlan(
        plan_id="PLAN_P12_0034",
        title="Operational Action Plan 12-34",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_034",
        time_of_occurrence_min=634,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0035": IncidentContingencyPlan(
        plan_id="PLAN_P12_0035",
        title="Operational Action Plan 12-35",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_035",
        time_of_occurrence_min=635,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0036": IncidentContingencyPlan(
        plan_id="PLAN_P12_0036",
        title="Operational Action Plan 12-36",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_036",
        time_of_occurrence_min=636,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0037": IncidentContingencyPlan(
        plan_id="PLAN_P12_0037",
        title="Operational Action Plan 12-37",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_037",
        time_of_occurrence_min=637,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0038": IncidentContingencyPlan(
        plan_id="PLAN_P12_0038",
        title="Operational Action Plan 12-38",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_038",
        time_of_occurrence_min=638,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0039": IncidentContingencyPlan(
        plan_id="PLAN_P12_0039",
        title="Operational Action Plan 12-39",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_039",
        time_of_occurrence_min=639,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0040": IncidentContingencyPlan(
        plan_id="PLAN_P12_0040",
        title="Operational Action Plan 12-40",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_040",
        time_of_occurrence_min=640,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0041": IncidentContingencyPlan(
        plan_id="PLAN_P12_0041",
        title="Operational Action Plan 12-41",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_041",
        time_of_occurrence_min=641,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0042": IncidentContingencyPlan(
        plan_id="PLAN_P12_0042",
        title="Operational Action Plan 12-42",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_042",
        time_of_occurrence_min=642,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0043": IncidentContingencyPlan(
        plan_id="PLAN_P12_0043",
        title="Operational Action Plan 12-43",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_043",
        time_of_occurrence_min=643,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0044": IncidentContingencyPlan(
        plan_id="PLAN_P12_0044",
        title="Operational Action Plan 12-44",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_044",
        time_of_occurrence_min=644,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0045": IncidentContingencyPlan(
        plan_id="PLAN_P12_0045",
        title="Operational Action Plan 12-45",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_045",
        time_of_occurrence_min=645,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0046": IncidentContingencyPlan(
        plan_id="PLAN_P12_0046",
        title="Operational Action Plan 12-46",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_046",
        time_of_occurrence_min=646,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0047": IncidentContingencyPlan(
        plan_id="PLAN_P12_0047",
        title="Operational Action Plan 12-47",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_047",
        time_of_occurrence_min=647,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0048": IncidentContingencyPlan(
        plan_id="PLAN_P12_0048",
        title="Operational Action Plan 12-48",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_048",
        time_of_occurrence_min=648,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0049": IncidentContingencyPlan(
        plan_id="PLAN_P12_0049",
        title="Operational Action Plan 12-49",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_049",
        time_of_occurrence_min=649,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0050": IncidentContingencyPlan(
        plan_id="PLAN_P12_0050",
        title="Operational Action Plan 12-50",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_050",
        time_of_occurrence_min=650,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0051": IncidentContingencyPlan(
        plan_id="PLAN_P12_0051",
        title="Operational Action Plan 12-51",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_051",
        time_of_occurrence_min=651,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0052": IncidentContingencyPlan(
        plan_id="PLAN_P12_0052",
        title="Operational Action Plan 12-52",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_052",
        time_of_occurrence_min=652,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0053": IncidentContingencyPlan(
        plan_id="PLAN_P12_0053",
        title="Operational Action Plan 12-53",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_053",
        time_of_occurrence_min=653,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0054": IncidentContingencyPlan(
        plan_id="PLAN_P12_0054",
        title="Operational Action Plan 12-54",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_054",
        time_of_occurrence_min=654,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0055": IncidentContingencyPlan(
        plan_id="PLAN_P12_0055",
        title="Operational Action Plan 12-55",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_055",
        time_of_occurrence_min=655,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0056": IncidentContingencyPlan(
        plan_id="PLAN_P12_0056",
        title="Operational Action Plan 12-56",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_056",
        time_of_occurrence_min=656,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0057": IncidentContingencyPlan(
        plan_id="PLAN_P12_0057",
        title="Operational Action Plan 12-57",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_057",
        time_of_occurrence_min=657,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0058": IncidentContingencyPlan(
        plan_id="PLAN_P12_0058",
        title="Operational Action Plan 12-58",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_058",
        time_of_occurrence_min=658,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0059": IncidentContingencyPlan(
        plan_id="PLAN_P12_0059",
        title="Operational Action Plan 12-59",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_059",
        time_of_occurrence_min=659,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0060": IncidentContingencyPlan(
        plan_id="PLAN_P12_0060",
        title="Operational Action Plan 12-60",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_060",
        time_of_occurrence_min=660,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0061": IncidentContingencyPlan(
        plan_id="PLAN_P12_0061",
        title="Operational Action Plan 12-61",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_061",
        time_of_occurrence_min=661,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0062": IncidentContingencyPlan(
        plan_id="PLAN_P12_0062",
        title="Operational Action Plan 12-62",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_062",
        time_of_occurrence_min=662,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0063": IncidentContingencyPlan(
        plan_id="PLAN_P12_0063",
        title="Operational Action Plan 12-63",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_063",
        time_of_occurrence_min=663,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0064": IncidentContingencyPlan(
        plan_id="PLAN_P12_0064",
        title="Operational Action Plan 12-64",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_064",
        time_of_occurrence_min=664,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0065": IncidentContingencyPlan(
        plan_id="PLAN_P12_0065",
        title="Operational Action Plan 12-65",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_065",
        time_of_occurrence_min=665,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0066": IncidentContingencyPlan(
        plan_id="PLAN_P12_0066",
        title="Operational Action Plan 12-66",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_066",
        time_of_occurrence_min=666,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0067": IncidentContingencyPlan(
        plan_id="PLAN_P12_0067",
        title="Operational Action Plan 12-67",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_067",
        time_of_occurrence_min=667,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0068": IncidentContingencyPlan(
        plan_id="PLAN_P12_0068",
        title="Operational Action Plan 12-68",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_068",
        time_of_occurrence_min=668,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0069": IncidentContingencyPlan(
        plan_id="PLAN_P12_0069",
        title="Operational Action Plan 12-69",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_069",
        time_of_occurrence_min=669,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0070": IncidentContingencyPlan(
        plan_id="PLAN_P12_0070",
        title="Operational Action Plan 12-70",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_070",
        time_of_occurrence_min=670,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0071": IncidentContingencyPlan(
        plan_id="PLAN_P12_0071",
        title="Operational Action Plan 12-71",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_071",
        time_of_occurrence_min=671,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0072": IncidentContingencyPlan(
        plan_id="PLAN_P12_0072",
        title="Operational Action Plan 12-72",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_072",
        time_of_occurrence_min=672,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0073": IncidentContingencyPlan(
        plan_id="PLAN_P12_0073",
        title="Operational Action Plan 12-73",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_073",
        time_of_occurrence_min=673,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0074": IncidentContingencyPlan(
        plan_id="PLAN_P12_0074",
        title="Operational Action Plan 12-74",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_074",
        time_of_occurrence_min=674,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0075": IncidentContingencyPlan(
        plan_id="PLAN_P12_0075",
        title="Operational Action Plan 12-75",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_075",
        time_of_occurrence_min=675,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0076": IncidentContingencyPlan(
        plan_id="PLAN_P12_0076",
        title="Operational Action Plan 12-76",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_076",
        time_of_occurrence_min=676,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0077": IncidentContingencyPlan(
        plan_id="PLAN_P12_0077",
        title="Operational Action Plan 12-77",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_077",
        time_of_occurrence_min=677,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0078": IncidentContingencyPlan(
        plan_id="PLAN_P12_0078",
        title="Operational Action Plan 12-78",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_078",
        time_of_occurrence_min=678,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0079": IncidentContingencyPlan(
        plan_id="PLAN_P12_0079",
        title="Operational Action Plan 12-79",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_079",
        time_of_occurrence_min=679,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0080": IncidentContingencyPlan(
        plan_id="PLAN_P12_0080",
        title="Operational Action Plan 12-80",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_080",
        time_of_occurrence_min=680,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0081": IncidentContingencyPlan(
        plan_id="PLAN_P12_0081",
        title="Operational Action Plan 12-81",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_081",
        time_of_occurrence_min=681,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0082": IncidentContingencyPlan(
        plan_id="PLAN_P12_0082",
        title="Operational Action Plan 12-82",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_082",
        time_of_occurrence_min=682,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0083": IncidentContingencyPlan(
        plan_id="PLAN_P12_0083",
        title="Operational Action Plan 12-83",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_083",
        time_of_occurrence_min=683,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0084": IncidentContingencyPlan(
        plan_id="PLAN_P12_0084",
        title="Operational Action Plan 12-84",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_084",
        time_of_occurrence_min=684,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0085": IncidentContingencyPlan(
        plan_id="PLAN_P12_0085",
        title="Operational Action Plan 12-85",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_085",
        time_of_occurrence_min=685,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0086": IncidentContingencyPlan(
        plan_id="PLAN_P12_0086",
        title="Operational Action Plan 12-86",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_086",
        time_of_occurrence_min=686,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0087": IncidentContingencyPlan(
        plan_id="PLAN_P12_0087",
        title="Operational Action Plan 12-87",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_087",
        time_of_occurrence_min=687,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0088": IncidentContingencyPlan(
        plan_id="PLAN_P12_0088",
        title="Operational Action Plan 12-88",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_088",
        time_of_occurrence_min=688,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0089": IncidentContingencyPlan(
        plan_id="PLAN_P12_0089",
        title="Operational Action Plan 12-89",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_089",
        time_of_occurrence_min=689,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0090": IncidentContingencyPlan(
        plan_id="PLAN_P12_0090",
        title="Operational Action Plan 12-90",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_090",
        time_of_occurrence_min=690,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0091": IncidentContingencyPlan(
        plan_id="PLAN_P12_0091",
        title="Operational Action Plan 12-91",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_091",
        time_of_occurrence_min=691,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0092": IncidentContingencyPlan(
        plan_id="PLAN_P12_0092",
        title="Operational Action Plan 12-92",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_092",
        time_of_occurrence_min=692,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0093": IncidentContingencyPlan(
        plan_id="PLAN_P12_0093",
        title="Operational Action Plan 12-93",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_093",
        time_of_occurrence_min=693,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0094": IncidentContingencyPlan(
        plan_id="PLAN_P12_0094",
        title="Operational Action Plan 12-94",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_094",
        time_of_occurrence_min=694,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0095": IncidentContingencyPlan(
        plan_id="PLAN_P12_0095",
        title="Operational Action Plan 12-95",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_095",
        time_of_occurrence_min=695,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0096": IncidentContingencyPlan(
        plan_id="PLAN_P12_0096",
        title="Operational Action Plan 12-96",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_096",
        time_of_occurrence_min=696,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0097": IncidentContingencyPlan(
        plan_id="PLAN_P12_0097",
        title="Operational Action Plan 12-97",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_097",
        time_of_occurrence_min=697,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0098": IncidentContingencyPlan(
        plan_id="PLAN_P12_0098",
        title="Operational Action Plan 12-98",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_098",
        time_of_occurrence_min=698,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0099": IncidentContingencyPlan(
        plan_id="PLAN_P12_0099",
        title="Operational Action Plan 12-99",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_099",
        time_of_occurrence_min=699,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0100": IncidentContingencyPlan(
        plan_id="PLAN_P12_0100",
        title="Operational Action Plan 12-100",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_100",
        time_of_occurrence_min=700,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0101": IncidentContingencyPlan(
        plan_id="PLAN_P12_0101",
        title="Operational Action Plan 12-101",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_101",
        time_of_occurrence_min=701,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0102": IncidentContingencyPlan(
        plan_id="PLAN_P12_0102",
        title="Operational Action Plan 12-102",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_102",
        time_of_occurrence_min=702,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0103": IncidentContingencyPlan(
        plan_id="PLAN_P12_0103",
        title="Operational Action Plan 12-103",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_103",
        time_of_occurrence_min=703,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0104": IncidentContingencyPlan(
        plan_id="PLAN_P12_0104",
        title="Operational Action Plan 12-104",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_104",
        time_of_occurrence_min=704,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0105": IncidentContingencyPlan(
        plan_id="PLAN_P12_0105",
        title="Operational Action Plan 12-105",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_105",
        time_of_occurrence_min=705,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0106": IncidentContingencyPlan(
        plan_id="PLAN_P12_0106",
        title="Operational Action Plan 12-106",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_106",
        time_of_occurrence_min=706,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0107": IncidentContingencyPlan(
        plan_id="PLAN_P12_0107",
        title="Operational Action Plan 12-107",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_107",
        time_of_occurrence_min=707,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0108": IncidentContingencyPlan(
        plan_id="PLAN_P12_0108",
        title="Operational Action Plan 12-108",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_108",
        time_of_occurrence_min=708,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0109": IncidentContingencyPlan(
        plan_id="PLAN_P12_0109",
        title="Operational Action Plan 12-109",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_109",
        time_of_occurrence_min=709,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0110": IncidentContingencyPlan(
        plan_id="PLAN_P12_0110",
        title="Operational Action Plan 12-110",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_110",
        time_of_occurrence_min=710,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0111": IncidentContingencyPlan(
        plan_id="PLAN_P12_0111",
        title="Operational Action Plan 12-111",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_111",
        time_of_occurrence_min=711,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0112": IncidentContingencyPlan(
        plan_id="PLAN_P12_0112",
        title="Operational Action Plan 12-112",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_112",
        time_of_occurrence_min=712,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0113": IncidentContingencyPlan(
        plan_id="PLAN_P12_0113",
        title="Operational Action Plan 12-113",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_113",
        time_of_occurrence_min=713,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0114": IncidentContingencyPlan(
        plan_id="PLAN_P12_0114",
        title="Operational Action Plan 12-114",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_114",
        time_of_occurrence_min=714,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0115": IncidentContingencyPlan(
        plan_id="PLAN_P12_0115",
        title="Operational Action Plan 12-115",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_115",
        time_of_occurrence_min=715,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0116": IncidentContingencyPlan(
        plan_id="PLAN_P12_0116",
        title="Operational Action Plan 12-116",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_116",
        time_of_occurrence_min=716,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0117": IncidentContingencyPlan(
        plan_id="PLAN_P12_0117",
        title="Operational Action Plan 12-117",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_117",
        time_of_occurrence_min=717,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0118": IncidentContingencyPlan(
        plan_id="PLAN_P12_0118",
        title="Operational Action Plan 12-118",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_118",
        time_of_occurrence_min=718,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0119": IncidentContingencyPlan(
        plan_id="PLAN_P12_0119",
        title="Operational Action Plan 12-119",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_119",
        time_of_occurrence_min=719,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0120": IncidentContingencyPlan(
        plan_id="PLAN_P12_0120",
        title="Operational Action Plan 12-120",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_120",
        time_of_occurrence_min=720,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0121": IncidentContingencyPlan(
        plan_id="PLAN_P12_0121",
        title="Operational Action Plan 12-121",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_121",
        time_of_occurrence_min=721,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0122": IncidentContingencyPlan(
        plan_id="PLAN_P12_0122",
        title="Operational Action Plan 12-122",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_122",
        time_of_occurrence_min=722,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0123": IncidentContingencyPlan(
        plan_id="PLAN_P12_0123",
        title="Operational Action Plan 12-123",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_123",
        time_of_occurrence_min=723,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0124": IncidentContingencyPlan(
        plan_id="PLAN_P12_0124",
        title="Operational Action Plan 12-124",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_124",
        time_of_occurrence_min=724,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0125": IncidentContingencyPlan(
        plan_id="PLAN_P12_0125",
        title="Operational Action Plan 12-125",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_125",
        time_of_occurrence_min=725,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0126": IncidentContingencyPlan(
        plan_id="PLAN_P12_0126",
        title="Operational Action Plan 12-126",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_126",
        time_of_occurrence_min=726,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0127": IncidentContingencyPlan(
        plan_id="PLAN_P12_0127",
        title="Operational Action Plan 12-127",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_127",
        time_of_occurrence_min=727,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0128": IncidentContingencyPlan(
        plan_id="PLAN_P12_0128",
        title="Operational Action Plan 12-128",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_128",
        time_of_occurrence_min=728,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0129": IncidentContingencyPlan(
        plan_id="PLAN_P12_0129",
        title="Operational Action Plan 12-129",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_129",
        time_of_occurrence_min=729,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0130": IncidentContingencyPlan(
        plan_id="PLAN_P12_0130",
        title="Operational Action Plan 12-130",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_130",
        time_of_occurrence_min=730,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0131": IncidentContingencyPlan(
        plan_id="PLAN_P12_0131",
        title="Operational Action Plan 12-131",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_131",
        time_of_occurrence_min=731,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0132": IncidentContingencyPlan(
        plan_id="PLAN_P12_0132",
        title="Operational Action Plan 12-132",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_132",
        time_of_occurrence_min=732,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0133": IncidentContingencyPlan(
        plan_id="PLAN_P12_0133",
        title="Operational Action Plan 12-133",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_133",
        time_of_occurrence_min=733,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0134": IncidentContingencyPlan(
        plan_id="PLAN_P12_0134",
        title="Operational Action Plan 12-134",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_134",
        time_of_occurrence_min=734,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0135": IncidentContingencyPlan(
        plan_id="PLAN_P12_0135",
        title="Operational Action Plan 12-135",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_135",
        time_of_occurrence_min=735,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0136": IncidentContingencyPlan(
        plan_id="PLAN_P12_0136",
        title="Operational Action Plan 12-136",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_136",
        time_of_occurrence_min=736,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0137": IncidentContingencyPlan(
        plan_id="PLAN_P12_0137",
        title="Operational Action Plan 12-137",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_137",
        time_of_occurrence_min=737,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0138": IncidentContingencyPlan(
        plan_id="PLAN_P12_0138",
        title="Operational Action Plan 12-138",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_138",
        time_of_occurrence_min=738,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0139": IncidentContingencyPlan(
        plan_id="PLAN_P12_0139",
        title="Operational Action Plan 12-139",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_139",
        time_of_occurrence_min=739,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0140": IncidentContingencyPlan(
        plan_id="PLAN_P12_0140",
        title="Operational Action Plan 12-140",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_140",
        time_of_occurrence_min=740,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0141": IncidentContingencyPlan(
        plan_id="PLAN_P12_0141",
        title="Operational Action Plan 12-141",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_141",
        time_of_occurrence_min=741,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0142": IncidentContingencyPlan(
        plan_id="PLAN_P12_0142",
        title="Operational Action Plan 12-142",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_142",
        time_of_occurrence_min=742,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0143": IncidentContingencyPlan(
        plan_id="PLAN_P12_0143",
        title="Operational Action Plan 12-143",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_143",
        time_of_occurrence_min=743,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0144": IncidentContingencyPlan(
        plan_id="PLAN_P12_0144",
        title="Operational Action Plan 12-144",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_144",
        time_of_occurrence_min=744,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0145": IncidentContingencyPlan(
        plan_id="PLAN_P12_0145",
        title="Operational Action Plan 12-145",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_145",
        time_of_occurrence_min=745,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0146": IncidentContingencyPlan(
        plan_id="PLAN_P12_0146",
        title="Operational Action Plan 12-146",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_146",
        time_of_occurrence_min=746,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0147": IncidentContingencyPlan(
        plan_id="PLAN_P12_0147",
        title="Operational Action Plan 12-147",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_147",
        time_of_occurrence_min=747,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0148": IncidentContingencyPlan(
        plan_id="PLAN_P12_0148",
        title="Operational Action Plan 12-148",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_148",
        time_of_occurrence_min=748,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0149": IncidentContingencyPlan(
        plan_id="PLAN_P12_0149",
        title="Operational Action Plan 12-149",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_149",
        time_of_occurrence_min=749,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0150": IncidentContingencyPlan(
        plan_id="PLAN_P12_0150",
        title="Operational Action Plan 12-150",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_150",
        time_of_occurrence_min=750,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0151": IncidentContingencyPlan(
        plan_id="PLAN_P12_0151",
        title="Operational Action Plan 12-151",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_151",
        time_of_occurrence_min=751,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0152": IncidentContingencyPlan(
        plan_id="PLAN_P12_0152",
        title="Operational Action Plan 12-152",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_152",
        time_of_occurrence_min=752,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0153": IncidentContingencyPlan(
        plan_id="PLAN_P12_0153",
        title="Operational Action Plan 12-153",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_153",
        time_of_occurrence_min=753,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0154": IncidentContingencyPlan(
        plan_id="PLAN_P12_0154",
        title="Operational Action Plan 12-154",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_154",
        time_of_occurrence_min=754,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0155": IncidentContingencyPlan(
        plan_id="PLAN_P12_0155",
        title="Operational Action Plan 12-155",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_155",
        time_of_occurrence_min=755,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0156": IncidentContingencyPlan(
        plan_id="PLAN_P12_0156",
        title="Operational Action Plan 12-156",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_156",
        time_of_occurrence_min=756,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0157": IncidentContingencyPlan(
        plan_id="PLAN_P12_0157",
        title="Operational Action Plan 12-157",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_157",
        time_of_occurrence_min=757,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0158": IncidentContingencyPlan(
        plan_id="PLAN_P12_0158",
        title="Operational Action Plan 12-158",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_158",
        time_of_occurrence_min=758,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0159": IncidentContingencyPlan(
        plan_id="PLAN_P12_0159",
        title="Operational Action Plan 12-159",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_159",
        time_of_occurrence_min=759,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0160": IncidentContingencyPlan(
        plan_id="PLAN_P12_0160",
        title="Operational Action Plan 12-160",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_160",
        time_of_occurrence_min=760,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0161": IncidentContingencyPlan(
        plan_id="PLAN_P12_0161",
        title="Operational Action Plan 12-161",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_161",
        time_of_occurrence_min=761,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0162": IncidentContingencyPlan(
        plan_id="PLAN_P12_0162",
        title="Operational Action Plan 12-162",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_162",
        time_of_occurrence_min=762,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0163": IncidentContingencyPlan(
        plan_id="PLAN_P12_0163",
        title="Operational Action Plan 12-163",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_163",
        time_of_occurrence_min=763,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0164": IncidentContingencyPlan(
        plan_id="PLAN_P12_0164",
        title="Operational Action Plan 12-164",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_164",
        time_of_occurrence_min=764,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
    "PLAN_P12_0165": IncidentContingencyPlan(
        plan_id="PLAN_P12_0165",
        title="Operational Action Plan 12-165",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_165",
        time_of_occurrence_min=765,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_05"
    ),
    "PLAN_P12_0166": IncidentContingencyPlan(
        plan_id="PLAN_P12_0166",
        title="Operational Action Plan 12-166",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_166",
        time_of_occurrence_min=766,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_06"
    ),
    "PLAN_P12_0167": IncidentContingencyPlan(
        plan_id="PLAN_P12_0167",
        title="Operational Action Plan 12-167",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_167",
        time_of_occurrence_min=767,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_07"
    ),
    "PLAN_P12_0168": IncidentContingencyPlan(
        plan_id="PLAN_P12_0168",
        title="Operational Action Plan 12-168",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_168",
        time_of_occurrence_min=768,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_08"
    ),
    "PLAN_P12_0169": IncidentContingencyPlan(
        plan_id="PLAN_P12_0169",
        title="Operational Action Plan 12-169",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P12_169",
        time_of_occurrence_min=769,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_09"
    ),
    "PLAN_P12_0170": IncidentContingencyPlan(
        plan_id="PLAN_P12_0170",
        title="Operational Action Plan 12-170",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P12_170",
        time_of_occurrence_min=770,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_00"
    ),
    "PLAN_P12_0171": IncidentContingencyPlan(
        plan_id="PLAN_P12_0171",
        title="Operational Action Plan 12-171",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P12_171",
        time_of_occurrence_min=771,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_01"
    ),
    "PLAN_P12_0172": IncidentContingencyPlan(
        plan_id="PLAN_P12_0172",
        title="Operational Action Plan 12-172",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P12_172",
        time_of_occurrence_min=772,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_02"
    ),
    "PLAN_P12_0173": IncidentContingencyPlan(
        plan_id="PLAN_P12_0173",
        title="Operational Action Plan 12-173",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P12_173",
        time_of_occurrence_min=773,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_03"
    ),
    "PLAN_P12_0174": IncidentContingencyPlan(
        plan_id="PLAN_P12_0174",
        title="Operational Action Plan 12-174",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P12_174",
        time_of_occurrence_min=774,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_12_04"
    ),
}
