"""Railway Incident Contingency Action Plans Part 025."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class IncidentContingencyPlan:
    plan_id: str
    title: str
    incident_type: str
    affected_block_id: str
    time_of_occurrence_min: int
    expected_clearance_min: int
    severity_score: int
    primary_dispatch_action: str
    contingency_corridor_id: str

INCIDENT_CONTINGENCY_PLANS_025: Dict[str, IncidentContingencyPlan] = {
    "PLAN_P25_0001": IncidentContingencyPlan(
        plan_id="PLAN_P25_0001",
        title="Operational Action Plan 25-1",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_001",
        time_of_occurrence_min=601,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0002": IncidentContingencyPlan(
        plan_id="PLAN_P25_0002",
        title="Operational Action Plan 25-2",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_002",
        time_of_occurrence_min=602,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0003": IncidentContingencyPlan(
        plan_id="PLAN_P25_0003",
        title="Operational Action Plan 25-3",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_003",
        time_of_occurrence_min=603,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0004": IncidentContingencyPlan(
        plan_id="PLAN_P25_0004",
        title="Operational Action Plan 25-4",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_004",
        time_of_occurrence_min=604,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0005": IncidentContingencyPlan(
        plan_id="PLAN_P25_0005",
        title="Operational Action Plan 25-5",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_005",
        time_of_occurrence_min=605,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0006": IncidentContingencyPlan(
        plan_id="PLAN_P25_0006",
        title="Operational Action Plan 25-6",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_006",
        time_of_occurrence_min=606,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0007": IncidentContingencyPlan(
        plan_id="PLAN_P25_0007",
        title="Operational Action Plan 25-7",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_007",
        time_of_occurrence_min=607,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0008": IncidentContingencyPlan(
        plan_id="PLAN_P25_0008",
        title="Operational Action Plan 25-8",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_008",
        time_of_occurrence_min=608,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0009": IncidentContingencyPlan(
        plan_id="PLAN_P25_0009",
        title="Operational Action Plan 25-9",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_009",
        time_of_occurrence_min=609,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0010": IncidentContingencyPlan(
        plan_id="PLAN_P25_0010",
        title="Operational Action Plan 25-10",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_010",
        time_of_occurrence_min=610,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0011": IncidentContingencyPlan(
        plan_id="PLAN_P25_0011",
        title="Operational Action Plan 25-11",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_011",
        time_of_occurrence_min=611,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0012": IncidentContingencyPlan(
        plan_id="PLAN_P25_0012",
        title="Operational Action Plan 25-12",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_012",
        time_of_occurrence_min=612,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0013": IncidentContingencyPlan(
        plan_id="PLAN_P25_0013",
        title="Operational Action Plan 25-13",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_013",
        time_of_occurrence_min=613,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0014": IncidentContingencyPlan(
        plan_id="PLAN_P25_0014",
        title="Operational Action Plan 25-14",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_014",
        time_of_occurrence_min=614,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0015": IncidentContingencyPlan(
        plan_id="PLAN_P25_0015",
        title="Operational Action Plan 25-15",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_015",
        time_of_occurrence_min=615,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0016": IncidentContingencyPlan(
        plan_id="PLAN_P25_0016",
        title="Operational Action Plan 25-16",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_016",
        time_of_occurrence_min=616,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0017": IncidentContingencyPlan(
        plan_id="PLAN_P25_0017",
        title="Operational Action Plan 25-17",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_017",
        time_of_occurrence_min=617,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0018": IncidentContingencyPlan(
        plan_id="PLAN_P25_0018",
        title="Operational Action Plan 25-18",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_018",
        time_of_occurrence_min=618,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0019": IncidentContingencyPlan(
        plan_id="PLAN_P25_0019",
        title="Operational Action Plan 25-19",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_019",
        time_of_occurrence_min=619,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0020": IncidentContingencyPlan(
        plan_id="PLAN_P25_0020",
        title="Operational Action Plan 25-20",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_020",
        time_of_occurrence_min=620,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0021": IncidentContingencyPlan(
        plan_id="PLAN_P25_0021",
        title="Operational Action Plan 25-21",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_021",
        time_of_occurrence_min=621,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0022": IncidentContingencyPlan(
        plan_id="PLAN_P25_0022",
        title="Operational Action Plan 25-22",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_022",
        time_of_occurrence_min=622,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0023": IncidentContingencyPlan(
        plan_id="PLAN_P25_0023",
        title="Operational Action Plan 25-23",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_023",
        time_of_occurrence_min=623,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0024": IncidentContingencyPlan(
        plan_id="PLAN_P25_0024",
        title="Operational Action Plan 25-24",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_024",
        time_of_occurrence_min=624,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0025": IncidentContingencyPlan(
        plan_id="PLAN_P25_0025",
        title="Operational Action Plan 25-25",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_025",
        time_of_occurrence_min=625,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0026": IncidentContingencyPlan(
        plan_id="PLAN_P25_0026",
        title="Operational Action Plan 25-26",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_026",
        time_of_occurrence_min=626,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0027": IncidentContingencyPlan(
        plan_id="PLAN_P25_0027",
        title="Operational Action Plan 25-27",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_027",
        time_of_occurrence_min=627,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0028": IncidentContingencyPlan(
        plan_id="PLAN_P25_0028",
        title="Operational Action Plan 25-28",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_028",
        time_of_occurrence_min=628,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0029": IncidentContingencyPlan(
        plan_id="PLAN_P25_0029",
        title="Operational Action Plan 25-29",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_029",
        time_of_occurrence_min=629,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0030": IncidentContingencyPlan(
        plan_id="PLAN_P25_0030",
        title="Operational Action Plan 25-30",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_030",
        time_of_occurrence_min=630,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0031": IncidentContingencyPlan(
        plan_id="PLAN_P25_0031",
        title="Operational Action Plan 25-31",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_031",
        time_of_occurrence_min=631,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0032": IncidentContingencyPlan(
        plan_id="PLAN_P25_0032",
        title="Operational Action Plan 25-32",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_032",
        time_of_occurrence_min=632,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0033": IncidentContingencyPlan(
        plan_id="PLAN_P25_0033",
        title="Operational Action Plan 25-33",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_033",
        time_of_occurrence_min=633,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0034": IncidentContingencyPlan(
        plan_id="PLAN_P25_0034",
        title="Operational Action Plan 25-34",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_034",
        time_of_occurrence_min=634,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0035": IncidentContingencyPlan(
        plan_id="PLAN_P25_0035",
        title="Operational Action Plan 25-35",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_035",
        time_of_occurrence_min=635,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0036": IncidentContingencyPlan(
        plan_id="PLAN_P25_0036",
        title="Operational Action Plan 25-36",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_036",
        time_of_occurrence_min=636,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0037": IncidentContingencyPlan(
        plan_id="PLAN_P25_0037",
        title="Operational Action Plan 25-37",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_037",
        time_of_occurrence_min=637,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0038": IncidentContingencyPlan(
        plan_id="PLAN_P25_0038",
        title="Operational Action Plan 25-38",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_038",
        time_of_occurrence_min=638,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0039": IncidentContingencyPlan(
        plan_id="PLAN_P25_0039",
        title="Operational Action Plan 25-39",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_039",
        time_of_occurrence_min=639,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0040": IncidentContingencyPlan(
        plan_id="PLAN_P25_0040",
        title="Operational Action Plan 25-40",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_040",
        time_of_occurrence_min=640,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0041": IncidentContingencyPlan(
        plan_id="PLAN_P25_0041",
        title="Operational Action Plan 25-41",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_041",
        time_of_occurrence_min=641,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0042": IncidentContingencyPlan(
        plan_id="PLAN_P25_0042",
        title="Operational Action Plan 25-42",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_042",
        time_of_occurrence_min=642,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0043": IncidentContingencyPlan(
        plan_id="PLAN_P25_0043",
        title="Operational Action Plan 25-43",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_043",
        time_of_occurrence_min=643,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0044": IncidentContingencyPlan(
        plan_id="PLAN_P25_0044",
        title="Operational Action Plan 25-44",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_044",
        time_of_occurrence_min=644,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0045": IncidentContingencyPlan(
        plan_id="PLAN_P25_0045",
        title="Operational Action Plan 25-45",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_045",
        time_of_occurrence_min=645,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0046": IncidentContingencyPlan(
        plan_id="PLAN_P25_0046",
        title="Operational Action Plan 25-46",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_046",
        time_of_occurrence_min=646,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0047": IncidentContingencyPlan(
        plan_id="PLAN_P25_0047",
        title="Operational Action Plan 25-47",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_047",
        time_of_occurrence_min=647,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0048": IncidentContingencyPlan(
        plan_id="PLAN_P25_0048",
        title="Operational Action Plan 25-48",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_048",
        time_of_occurrence_min=648,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0049": IncidentContingencyPlan(
        plan_id="PLAN_P25_0049",
        title="Operational Action Plan 25-49",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_049",
        time_of_occurrence_min=649,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0050": IncidentContingencyPlan(
        plan_id="PLAN_P25_0050",
        title="Operational Action Plan 25-50",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_050",
        time_of_occurrence_min=650,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0051": IncidentContingencyPlan(
        plan_id="PLAN_P25_0051",
        title="Operational Action Plan 25-51",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_051",
        time_of_occurrence_min=651,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0052": IncidentContingencyPlan(
        plan_id="PLAN_P25_0052",
        title="Operational Action Plan 25-52",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_052",
        time_of_occurrence_min=652,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0053": IncidentContingencyPlan(
        plan_id="PLAN_P25_0053",
        title="Operational Action Plan 25-53",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_053",
        time_of_occurrence_min=653,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0054": IncidentContingencyPlan(
        plan_id="PLAN_P25_0054",
        title="Operational Action Plan 25-54",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_054",
        time_of_occurrence_min=654,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0055": IncidentContingencyPlan(
        plan_id="PLAN_P25_0055",
        title="Operational Action Plan 25-55",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_055",
        time_of_occurrence_min=655,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0056": IncidentContingencyPlan(
        plan_id="PLAN_P25_0056",
        title="Operational Action Plan 25-56",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_056",
        time_of_occurrence_min=656,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0057": IncidentContingencyPlan(
        plan_id="PLAN_P25_0057",
        title="Operational Action Plan 25-57",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_057",
        time_of_occurrence_min=657,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0058": IncidentContingencyPlan(
        plan_id="PLAN_P25_0058",
        title="Operational Action Plan 25-58",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_058",
        time_of_occurrence_min=658,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0059": IncidentContingencyPlan(
        plan_id="PLAN_P25_0059",
        title="Operational Action Plan 25-59",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_059",
        time_of_occurrence_min=659,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0060": IncidentContingencyPlan(
        plan_id="PLAN_P25_0060",
        title="Operational Action Plan 25-60",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_060",
        time_of_occurrence_min=660,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0061": IncidentContingencyPlan(
        plan_id="PLAN_P25_0061",
        title="Operational Action Plan 25-61",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_061",
        time_of_occurrence_min=661,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0062": IncidentContingencyPlan(
        plan_id="PLAN_P25_0062",
        title="Operational Action Plan 25-62",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_062",
        time_of_occurrence_min=662,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0063": IncidentContingencyPlan(
        plan_id="PLAN_P25_0063",
        title="Operational Action Plan 25-63",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_063",
        time_of_occurrence_min=663,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0064": IncidentContingencyPlan(
        plan_id="PLAN_P25_0064",
        title="Operational Action Plan 25-64",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_064",
        time_of_occurrence_min=664,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0065": IncidentContingencyPlan(
        plan_id="PLAN_P25_0065",
        title="Operational Action Plan 25-65",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_065",
        time_of_occurrence_min=665,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0066": IncidentContingencyPlan(
        plan_id="PLAN_P25_0066",
        title="Operational Action Plan 25-66",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_066",
        time_of_occurrence_min=666,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0067": IncidentContingencyPlan(
        plan_id="PLAN_P25_0067",
        title="Operational Action Plan 25-67",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_067",
        time_of_occurrence_min=667,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0068": IncidentContingencyPlan(
        plan_id="PLAN_P25_0068",
        title="Operational Action Plan 25-68",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_068",
        time_of_occurrence_min=668,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0069": IncidentContingencyPlan(
        plan_id="PLAN_P25_0069",
        title="Operational Action Plan 25-69",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_069",
        time_of_occurrence_min=669,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0070": IncidentContingencyPlan(
        plan_id="PLAN_P25_0070",
        title="Operational Action Plan 25-70",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_070",
        time_of_occurrence_min=670,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0071": IncidentContingencyPlan(
        plan_id="PLAN_P25_0071",
        title="Operational Action Plan 25-71",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_071",
        time_of_occurrence_min=671,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0072": IncidentContingencyPlan(
        plan_id="PLAN_P25_0072",
        title="Operational Action Plan 25-72",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_072",
        time_of_occurrence_min=672,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0073": IncidentContingencyPlan(
        plan_id="PLAN_P25_0073",
        title="Operational Action Plan 25-73",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_073",
        time_of_occurrence_min=673,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0074": IncidentContingencyPlan(
        plan_id="PLAN_P25_0074",
        title="Operational Action Plan 25-74",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_074",
        time_of_occurrence_min=674,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0075": IncidentContingencyPlan(
        plan_id="PLAN_P25_0075",
        title="Operational Action Plan 25-75",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_075",
        time_of_occurrence_min=675,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0076": IncidentContingencyPlan(
        plan_id="PLAN_P25_0076",
        title="Operational Action Plan 25-76",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_076",
        time_of_occurrence_min=676,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0077": IncidentContingencyPlan(
        plan_id="PLAN_P25_0077",
        title="Operational Action Plan 25-77",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_077",
        time_of_occurrence_min=677,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0078": IncidentContingencyPlan(
        plan_id="PLAN_P25_0078",
        title="Operational Action Plan 25-78",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_078",
        time_of_occurrence_min=678,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0079": IncidentContingencyPlan(
        plan_id="PLAN_P25_0079",
        title="Operational Action Plan 25-79",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_079",
        time_of_occurrence_min=679,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0080": IncidentContingencyPlan(
        plan_id="PLAN_P25_0080",
        title="Operational Action Plan 25-80",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_080",
        time_of_occurrence_min=680,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0081": IncidentContingencyPlan(
        plan_id="PLAN_P25_0081",
        title="Operational Action Plan 25-81",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_081",
        time_of_occurrence_min=681,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0082": IncidentContingencyPlan(
        plan_id="PLAN_P25_0082",
        title="Operational Action Plan 25-82",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_082",
        time_of_occurrence_min=682,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0083": IncidentContingencyPlan(
        plan_id="PLAN_P25_0083",
        title="Operational Action Plan 25-83",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_083",
        time_of_occurrence_min=683,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0084": IncidentContingencyPlan(
        plan_id="PLAN_P25_0084",
        title="Operational Action Plan 25-84",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_084",
        time_of_occurrence_min=684,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0085": IncidentContingencyPlan(
        plan_id="PLAN_P25_0085",
        title="Operational Action Plan 25-85",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_085",
        time_of_occurrence_min=685,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0086": IncidentContingencyPlan(
        plan_id="PLAN_P25_0086",
        title="Operational Action Plan 25-86",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_086",
        time_of_occurrence_min=686,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0087": IncidentContingencyPlan(
        plan_id="PLAN_P25_0087",
        title="Operational Action Plan 25-87",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_087",
        time_of_occurrence_min=687,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0088": IncidentContingencyPlan(
        plan_id="PLAN_P25_0088",
        title="Operational Action Plan 25-88",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_088",
        time_of_occurrence_min=688,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0089": IncidentContingencyPlan(
        plan_id="PLAN_P25_0089",
        title="Operational Action Plan 25-89",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_089",
        time_of_occurrence_min=689,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0090": IncidentContingencyPlan(
        plan_id="PLAN_P25_0090",
        title="Operational Action Plan 25-90",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_090",
        time_of_occurrence_min=690,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0091": IncidentContingencyPlan(
        plan_id="PLAN_P25_0091",
        title="Operational Action Plan 25-91",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_091",
        time_of_occurrence_min=691,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0092": IncidentContingencyPlan(
        plan_id="PLAN_P25_0092",
        title="Operational Action Plan 25-92",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_092",
        time_of_occurrence_min=692,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0093": IncidentContingencyPlan(
        plan_id="PLAN_P25_0093",
        title="Operational Action Plan 25-93",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_093",
        time_of_occurrence_min=693,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0094": IncidentContingencyPlan(
        plan_id="PLAN_P25_0094",
        title="Operational Action Plan 25-94",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_094",
        time_of_occurrence_min=694,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0095": IncidentContingencyPlan(
        plan_id="PLAN_P25_0095",
        title="Operational Action Plan 25-95",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_095",
        time_of_occurrence_min=695,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0096": IncidentContingencyPlan(
        plan_id="PLAN_P25_0096",
        title="Operational Action Plan 25-96",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_096",
        time_of_occurrence_min=696,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0097": IncidentContingencyPlan(
        plan_id="PLAN_P25_0097",
        title="Operational Action Plan 25-97",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_097",
        time_of_occurrence_min=697,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0098": IncidentContingencyPlan(
        plan_id="PLAN_P25_0098",
        title="Operational Action Plan 25-98",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_098",
        time_of_occurrence_min=698,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0099": IncidentContingencyPlan(
        plan_id="PLAN_P25_0099",
        title="Operational Action Plan 25-99",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_099",
        time_of_occurrence_min=699,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0100": IncidentContingencyPlan(
        plan_id="PLAN_P25_0100",
        title="Operational Action Plan 25-100",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_100",
        time_of_occurrence_min=700,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0101": IncidentContingencyPlan(
        plan_id="PLAN_P25_0101",
        title="Operational Action Plan 25-101",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_101",
        time_of_occurrence_min=701,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0102": IncidentContingencyPlan(
        plan_id="PLAN_P25_0102",
        title="Operational Action Plan 25-102",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_102",
        time_of_occurrence_min=702,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0103": IncidentContingencyPlan(
        plan_id="PLAN_P25_0103",
        title="Operational Action Plan 25-103",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_103",
        time_of_occurrence_min=703,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0104": IncidentContingencyPlan(
        plan_id="PLAN_P25_0104",
        title="Operational Action Plan 25-104",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_104",
        time_of_occurrence_min=704,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0105": IncidentContingencyPlan(
        plan_id="PLAN_P25_0105",
        title="Operational Action Plan 25-105",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_105",
        time_of_occurrence_min=705,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0106": IncidentContingencyPlan(
        plan_id="PLAN_P25_0106",
        title="Operational Action Plan 25-106",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_106",
        time_of_occurrence_min=706,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0107": IncidentContingencyPlan(
        plan_id="PLAN_P25_0107",
        title="Operational Action Plan 25-107",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_107",
        time_of_occurrence_min=707,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0108": IncidentContingencyPlan(
        plan_id="PLAN_P25_0108",
        title="Operational Action Plan 25-108",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_108",
        time_of_occurrence_min=708,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0109": IncidentContingencyPlan(
        plan_id="PLAN_P25_0109",
        title="Operational Action Plan 25-109",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_109",
        time_of_occurrence_min=709,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0110": IncidentContingencyPlan(
        plan_id="PLAN_P25_0110",
        title="Operational Action Plan 25-110",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_110",
        time_of_occurrence_min=710,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0111": IncidentContingencyPlan(
        plan_id="PLAN_P25_0111",
        title="Operational Action Plan 25-111",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_111",
        time_of_occurrence_min=711,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0112": IncidentContingencyPlan(
        plan_id="PLAN_P25_0112",
        title="Operational Action Plan 25-112",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_112",
        time_of_occurrence_min=712,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0113": IncidentContingencyPlan(
        plan_id="PLAN_P25_0113",
        title="Operational Action Plan 25-113",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_113",
        time_of_occurrence_min=713,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0114": IncidentContingencyPlan(
        plan_id="PLAN_P25_0114",
        title="Operational Action Plan 25-114",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_114",
        time_of_occurrence_min=714,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0115": IncidentContingencyPlan(
        plan_id="PLAN_P25_0115",
        title="Operational Action Plan 25-115",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_115",
        time_of_occurrence_min=715,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0116": IncidentContingencyPlan(
        plan_id="PLAN_P25_0116",
        title="Operational Action Plan 25-116",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_116",
        time_of_occurrence_min=716,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0117": IncidentContingencyPlan(
        plan_id="PLAN_P25_0117",
        title="Operational Action Plan 25-117",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_117",
        time_of_occurrence_min=717,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0118": IncidentContingencyPlan(
        plan_id="PLAN_P25_0118",
        title="Operational Action Plan 25-118",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_118",
        time_of_occurrence_min=718,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0119": IncidentContingencyPlan(
        plan_id="PLAN_P25_0119",
        title="Operational Action Plan 25-119",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_119",
        time_of_occurrence_min=719,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0120": IncidentContingencyPlan(
        plan_id="PLAN_P25_0120",
        title="Operational Action Plan 25-120",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_120",
        time_of_occurrence_min=720,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0121": IncidentContingencyPlan(
        plan_id="PLAN_P25_0121",
        title="Operational Action Plan 25-121",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_121",
        time_of_occurrence_min=721,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0122": IncidentContingencyPlan(
        plan_id="PLAN_P25_0122",
        title="Operational Action Plan 25-122",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_122",
        time_of_occurrence_min=722,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0123": IncidentContingencyPlan(
        plan_id="PLAN_P25_0123",
        title="Operational Action Plan 25-123",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_123",
        time_of_occurrence_min=723,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0124": IncidentContingencyPlan(
        plan_id="PLAN_P25_0124",
        title="Operational Action Plan 25-124",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_124",
        time_of_occurrence_min=724,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0125": IncidentContingencyPlan(
        plan_id="PLAN_P25_0125",
        title="Operational Action Plan 25-125",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_125",
        time_of_occurrence_min=725,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0126": IncidentContingencyPlan(
        plan_id="PLAN_P25_0126",
        title="Operational Action Plan 25-126",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_126",
        time_of_occurrence_min=726,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0127": IncidentContingencyPlan(
        plan_id="PLAN_P25_0127",
        title="Operational Action Plan 25-127",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_127",
        time_of_occurrence_min=727,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0128": IncidentContingencyPlan(
        plan_id="PLAN_P25_0128",
        title="Operational Action Plan 25-128",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_128",
        time_of_occurrence_min=728,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0129": IncidentContingencyPlan(
        plan_id="PLAN_P25_0129",
        title="Operational Action Plan 25-129",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_129",
        time_of_occurrence_min=729,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0130": IncidentContingencyPlan(
        plan_id="PLAN_P25_0130",
        title="Operational Action Plan 25-130",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_130",
        time_of_occurrence_min=730,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0131": IncidentContingencyPlan(
        plan_id="PLAN_P25_0131",
        title="Operational Action Plan 25-131",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_131",
        time_of_occurrence_min=731,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0132": IncidentContingencyPlan(
        plan_id="PLAN_P25_0132",
        title="Operational Action Plan 25-132",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_132",
        time_of_occurrence_min=732,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0133": IncidentContingencyPlan(
        plan_id="PLAN_P25_0133",
        title="Operational Action Plan 25-133",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_133",
        time_of_occurrence_min=733,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0134": IncidentContingencyPlan(
        plan_id="PLAN_P25_0134",
        title="Operational Action Plan 25-134",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_134",
        time_of_occurrence_min=734,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0135": IncidentContingencyPlan(
        plan_id="PLAN_P25_0135",
        title="Operational Action Plan 25-135",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_135",
        time_of_occurrence_min=735,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0136": IncidentContingencyPlan(
        plan_id="PLAN_P25_0136",
        title="Operational Action Plan 25-136",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_136",
        time_of_occurrence_min=736,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0137": IncidentContingencyPlan(
        plan_id="PLAN_P25_0137",
        title="Operational Action Plan 25-137",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_137",
        time_of_occurrence_min=737,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0138": IncidentContingencyPlan(
        plan_id="PLAN_P25_0138",
        title="Operational Action Plan 25-138",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_138",
        time_of_occurrence_min=738,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0139": IncidentContingencyPlan(
        plan_id="PLAN_P25_0139",
        title="Operational Action Plan 25-139",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_139",
        time_of_occurrence_min=739,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0140": IncidentContingencyPlan(
        plan_id="PLAN_P25_0140",
        title="Operational Action Plan 25-140",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_140",
        time_of_occurrence_min=740,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0141": IncidentContingencyPlan(
        plan_id="PLAN_P25_0141",
        title="Operational Action Plan 25-141",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_141",
        time_of_occurrence_min=741,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0142": IncidentContingencyPlan(
        plan_id="PLAN_P25_0142",
        title="Operational Action Plan 25-142",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_142",
        time_of_occurrence_min=742,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0143": IncidentContingencyPlan(
        plan_id="PLAN_P25_0143",
        title="Operational Action Plan 25-143",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_143",
        time_of_occurrence_min=743,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0144": IncidentContingencyPlan(
        plan_id="PLAN_P25_0144",
        title="Operational Action Plan 25-144",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_144",
        time_of_occurrence_min=744,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0145": IncidentContingencyPlan(
        plan_id="PLAN_P25_0145",
        title="Operational Action Plan 25-145",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_145",
        time_of_occurrence_min=745,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0146": IncidentContingencyPlan(
        plan_id="PLAN_P25_0146",
        title="Operational Action Plan 25-146",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_146",
        time_of_occurrence_min=746,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0147": IncidentContingencyPlan(
        plan_id="PLAN_P25_0147",
        title="Operational Action Plan 25-147",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_147",
        time_of_occurrence_min=747,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0148": IncidentContingencyPlan(
        plan_id="PLAN_P25_0148",
        title="Operational Action Plan 25-148",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_148",
        time_of_occurrence_min=748,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0149": IncidentContingencyPlan(
        plan_id="PLAN_P25_0149",
        title="Operational Action Plan 25-149",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_149",
        time_of_occurrence_min=749,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0150": IncidentContingencyPlan(
        plan_id="PLAN_P25_0150",
        title="Operational Action Plan 25-150",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_150",
        time_of_occurrence_min=750,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0151": IncidentContingencyPlan(
        plan_id="PLAN_P25_0151",
        title="Operational Action Plan 25-151",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_151",
        time_of_occurrence_min=751,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0152": IncidentContingencyPlan(
        plan_id="PLAN_P25_0152",
        title="Operational Action Plan 25-152",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_152",
        time_of_occurrence_min=752,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0153": IncidentContingencyPlan(
        plan_id="PLAN_P25_0153",
        title="Operational Action Plan 25-153",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_153",
        time_of_occurrence_min=753,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0154": IncidentContingencyPlan(
        plan_id="PLAN_P25_0154",
        title="Operational Action Plan 25-154",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_154",
        time_of_occurrence_min=754,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0155": IncidentContingencyPlan(
        plan_id="PLAN_P25_0155",
        title="Operational Action Plan 25-155",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_155",
        time_of_occurrence_min=755,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0156": IncidentContingencyPlan(
        plan_id="PLAN_P25_0156",
        title="Operational Action Plan 25-156",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_156",
        time_of_occurrence_min=756,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0157": IncidentContingencyPlan(
        plan_id="PLAN_P25_0157",
        title="Operational Action Plan 25-157",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_157",
        time_of_occurrence_min=757,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0158": IncidentContingencyPlan(
        plan_id="PLAN_P25_0158",
        title="Operational Action Plan 25-158",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_158",
        time_of_occurrence_min=758,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0159": IncidentContingencyPlan(
        plan_id="PLAN_P25_0159",
        title="Operational Action Plan 25-159",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_159",
        time_of_occurrence_min=759,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0160": IncidentContingencyPlan(
        plan_id="PLAN_P25_0160",
        title="Operational Action Plan 25-160",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_160",
        time_of_occurrence_min=760,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0161": IncidentContingencyPlan(
        plan_id="PLAN_P25_0161",
        title="Operational Action Plan 25-161",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_161",
        time_of_occurrence_min=761,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0162": IncidentContingencyPlan(
        plan_id="PLAN_P25_0162",
        title="Operational Action Plan 25-162",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_162",
        time_of_occurrence_min=762,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0163": IncidentContingencyPlan(
        plan_id="PLAN_P25_0163",
        title="Operational Action Plan 25-163",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_163",
        time_of_occurrence_min=763,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0164": IncidentContingencyPlan(
        plan_id="PLAN_P25_0164",
        title="Operational Action Plan 25-164",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_164",
        time_of_occurrence_min=764,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
    "PLAN_P25_0165": IncidentContingencyPlan(
        plan_id="PLAN_P25_0165",
        title="Operational Action Plan 25-165",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_165",
        time_of_occurrence_min=765,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_05"
    ),
    "PLAN_P25_0166": IncidentContingencyPlan(
        plan_id="PLAN_P25_0166",
        title="Operational Action Plan 25-166",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_166",
        time_of_occurrence_min=766,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_06"
    ),
    "PLAN_P25_0167": IncidentContingencyPlan(
        plan_id="PLAN_P25_0167",
        title="Operational Action Plan 25-167",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_167",
        time_of_occurrence_min=767,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_07"
    ),
    "PLAN_P25_0168": IncidentContingencyPlan(
        plan_id="PLAN_P25_0168",
        title="Operational Action Plan 25-168",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_168",
        time_of_occurrence_min=768,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_08"
    ),
    "PLAN_P25_0169": IncidentContingencyPlan(
        plan_id="PLAN_P25_0169",
        title="Operational Action Plan 25-169",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P25_169",
        time_of_occurrence_min=769,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_09"
    ),
    "PLAN_P25_0170": IncidentContingencyPlan(
        plan_id="PLAN_P25_0170",
        title="Operational Action Plan 25-170",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P25_170",
        time_of_occurrence_min=770,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_00"
    ),
    "PLAN_P25_0171": IncidentContingencyPlan(
        plan_id="PLAN_P25_0171",
        title="Operational Action Plan 25-171",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P25_171",
        time_of_occurrence_min=771,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_01"
    ),
    "PLAN_P25_0172": IncidentContingencyPlan(
        plan_id="PLAN_P25_0172",
        title="Operational Action Plan 25-172",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P25_172",
        time_of_occurrence_min=772,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_02"
    ),
    "PLAN_P25_0173": IncidentContingencyPlan(
        plan_id="PLAN_P25_0173",
        title="Operational Action Plan 25-173",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P25_173",
        time_of_occurrence_min=773,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_03"
    ),
    "PLAN_P25_0174": IncidentContingencyPlan(
        plan_id="PLAN_P25_0174",
        title="Operational Action Plan 25-174",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P25_174",
        time_of_occurrence_min=774,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_25_04"
    ),
}
