"""Railway Incident Contingency Action Plans Part 015."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class IncidentContingencyPlan:
    plan_id: str
    title: str
    incident_type: str
    affected_block_id: str
    time_of_occurrence_min: int
    expected_clearance_min: int
    severity_score: int
    primary_dispatch_action: str
    contingency_corridor_id: str

INCIDENT_CONTINGENCY_PLANS_015: Dict[str, IncidentContingencyPlan] = {
    "PLAN_P15_0001": IncidentContingencyPlan(
        plan_id="PLAN_P15_0001",
        title="Operational Action Plan 15-1",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_001",
        time_of_occurrence_min=601,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0002": IncidentContingencyPlan(
        plan_id="PLAN_P15_0002",
        title="Operational Action Plan 15-2",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_002",
        time_of_occurrence_min=602,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0003": IncidentContingencyPlan(
        plan_id="PLAN_P15_0003",
        title="Operational Action Plan 15-3",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_003",
        time_of_occurrence_min=603,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0004": IncidentContingencyPlan(
        plan_id="PLAN_P15_0004",
        title="Operational Action Plan 15-4",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_004",
        time_of_occurrence_min=604,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0005": IncidentContingencyPlan(
        plan_id="PLAN_P15_0005",
        title="Operational Action Plan 15-5",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_005",
        time_of_occurrence_min=605,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0006": IncidentContingencyPlan(
        plan_id="PLAN_P15_0006",
        title="Operational Action Plan 15-6",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_006",
        time_of_occurrence_min=606,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0007": IncidentContingencyPlan(
        plan_id="PLAN_P15_0007",
        title="Operational Action Plan 15-7",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_007",
        time_of_occurrence_min=607,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0008": IncidentContingencyPlan(
        plan_id="PLAN_P15_0008",
        title="Operational Action Plan 15-8",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_008",
        time_of_occurrence_min=608,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0009": IncidentContingencyPlan(
        plan_id="PLAN_P15_0009",
        title="Operational Action Plan 15-9",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_009",
        time_of_occurrence_min=609,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0010": IncidentContingencyPlan(
        plan_id="PLAN_P15_0010",
        title="Operational Action Plan 15-10",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_010",
        time_of_occurrence_min=610,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0011": IncidentContingencyPlan(
        plan_id="PLAN_P15_0011",
        title="Operational Action Plan 15-11",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_011",
        time_of_occurrence_min=611,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0012": IncidentContingencyPlan(
        plan_id="PLAN_P15_0012",
        title="Operational Action Plan 15-12",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_012",
        time_of_occurrence_min=612,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0013": IncidentContingencyPlan(
        plan_id="PLAN_P15_0013",
        title="Operational Action Plan 15-13",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_013",
        time_of_occurrence_min=613,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0014": IncidentContingencyPlan(
        plan_id="PLAN_P15_0014",
        title="Operational Action Plan 15-14",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_014",
        time_of_occurrence_min=614,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0015": IncidentContingencyPlan(
        plan_id="PLAN_P15_0015",
        title="Operational Action Plan 15-15",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_015",
        time_of_occurrence_min=615,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0016": IncidentContingencyPlan(
        plan_id="PLAN_P15_0016",
        title="Operational Action Plan 15-16",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_016",
        time_of_occurrence_min=616,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0017": IncidentContingencyPlan(
        plan_id="PLAN_P15_0017",
        title="Operational Action Plan 15-17",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_017",
        time_of_occurrence_min=617,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0018": IncidentContingencyPlan(
        plan_id="PLAN_P15_0018",
        title="Operational Action Plan 15-18",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_018",
        time_of_occurrence_min=618,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0019": IncidentContingencyPlan(
        plan_id="PLAN_P15_0019",
        title="Operational Action Plan 15-19",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_019",
        time_of_occurrence_min=619,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0020": IncidentContingencyPlan(
        plan_id="PLAN_P15_0020",
        title="Operational Action Plan 15-20",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_020",
        time_of_occurrence_min=620,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0021": IncidentContingencyPlan(
        plan_id="PLAN_P15_0021",
        title="Operational Action Plan 15-21",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_021",
        time_of_occurrence_min=621,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0022": IncidentContingencyPlan(
        plan_id="PLAN_P15_0022",
        title="Operational Action Plan 15-22",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_022",
        time_of_occurrence_min=622,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0023": IncidentContingencyPlan(
        plan_id="PLAN_P15_0023",
        title="Operational Action Plan 15-23",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_023",
        time_of_occurrence_min=623,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0024": IncidentContingencyPlan(
        plan_id="PLAN_P15_0024",
        title="Operational Action Plan 15-24",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_024",
        time_of_occurrence_min=624,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0025": IncidentContingencyPlan(
        plan_id="PLAN_P15_0025",
        title="Operational Action Plan 15-25",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_025",
        time_of_occurrence_min=625,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0026": IncidentContingencyPlan(
        plan_id="PLAN_P15_0026",
        title="Operational Action Plan 15-26",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_026",
        time_of_occurrence_min=626,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0027": IncidentContingencyPlan(
        plan_id="PLAN_P15_0027",
        title="Operational Action Plan 15-27",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_027",
        time_of_occurrence_min=627,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0028": IncidentContingencyPlan(
        plan_id="PLAN_P15_0028",
        title="Operational Action Plan 15-28",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_028",
        time_of_occurrence_min=628,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0029": IncidentContingencyPlan(
        plan_id="PLAN_P15_0029",
        title="Operational Action Plan 15-29",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_029",
        time_of_occurrence_min=629,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0030": IncidentContingencyPlan(
        plan_id="PLAN_P15_0030",
        title="Operational Action Plan 15-30",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_030",
        time_of_occurrence_min=630,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0031": IncidentContingencyPlan(
        plan_id="PLAN_P15_0031",
        title="Operational Action Plan 15-31",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_031",
        time_of_occurrence_min=631,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0032": IncidentContingencyPlan(
        plan_id="PLAN_P15_0032",
        title="Operational Action Plan 15-32",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_032",
        time_of_occurrence_min=632,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0033": IncidentContingencyPlan(
        plan_id="PLAN_P15_0033",
        title="Operational Action Plan 15-33",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_033",
        time_of_occurrence_min=633,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0034": IncidentContingencyPlan(
        plan_id="PLAN_P15_0034",
        title="Operational Action Plan 15-34",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_034",
        time_of_occurrence_min=634,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0035": IncidentContingencyPlan(
        plan_id="PLAN_P15_0035",
        title="Operational Action Plan 15-35",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_035",
        time_of_occurrence_min=635,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0036": IncidentContingencyPlan(
        plan_id="PLAN_P15_0036",
        title="Operational Action Plan 15-36",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_036",
        time_of_occurrence_min=636,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0037": IncidentContingencyPlan(
        plan_id="PLAN_P15_0037",
        title="Operational Action Plan 15-37",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_037",
        time_of_occurrence_min=637,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0038": IncidentContingencyPlan(
        plan_id="PLAN_P15_0038",
        title="Operational Action Plan 15-38",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_038",
        time_of_occurrence_min=638,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0039": IncidentContingencyPlan(
        plan_id="PLAN_P15_0039",
        title="Operational Action Plan 15-39",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_039",
        time_of_occurrence_min=639,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0040": IncidentContingencyPlan(
        plan_id="PLAN_P15_0040",
        title="Operational Action Plan 15-40",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_040",
        time_of_occurrence_min=640,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0041": IncidentContingencyPlan(
        plan_id="PLAN_P15_0041",
        title="Operational Action Plan 15-41",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_041",
        time_of_occurrence_min=641,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0042": IncidentContingencyPlan(
        plan_id="PLAN_P15_0042",
        title="Operational Action Plan 15-42",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_042",
        time_of_occurrence_min=642,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0043": IncidentContingencyPlan(
        plan_id="PLAN_P15_0043",
        title="Operational Action Plan 15-43",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_043",
        time_of_occurrence_min=643,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0044": IncidentContingencyPlan(
        plan_id="PLAN_P15_0044",
        title="Operational Action Plan 15-44",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_044",
        time_of_occurrence_min=644,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0045": IncidentContingencyPlan(
        plan_id="PLAN_P15_0045",
        title="Operational Action Plan 15-45",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_045",
        time_of_occurrence_min=645,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0046": IncidentContingencyPlan(
        plan_id="PLAN_P15_0046",
        title="Operational Action Plan 15-46",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_046",
        time_of_occurrence_min=646,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0047": IncidentContingencyPlan(
        plan_id="PLAN_P15_0047",
        title="Operational Action Plan 15-47",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_047",
        time_of_occurrence_min=647,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0048": IncidentContingencyPlan(
        plan_id="PLAN_P15_0048",
        title="Operational Action Plan 15-48",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_048",
        time_of_occurrence_min=648,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0049": IncidentContingencyPlan(
        plan_id="PLAN_P15_0049",
        title="Operational Action Plan 15-49",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_049",
        time_of_occurrence_min=649,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0050": IncidentContingencyPlan(
        plan_id="PLAN_P15_0050",
        title="Operational Action Plan 15-50",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_050",
        time_of_occurrence_min=650,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0051": IncidentContingencyPlan(
        plan_id="PLAN_P15_0051",
        title="Operational Action Plan 15-51",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_051",
        time_of_occurrence_min=651,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0052": IncidentContingencyPlan(
        plan_id="PLAN_P15_0052",
        title="Operational Action Plan 15-52",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_052",
        time_of_occurrence_min=652,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0053": IncidentContingencyPlan(
        plan_id="PLAN_P15_0053",
        title="Operational Action Plan 15-53",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_053",
        time_of_occurrence_min=653,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0054": IncidentContingencyPlan(
        plan_id="PLAN_P15_0054",
        title="Operational Action Plan 15-54",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_054",
        time_of_occurrence_min=654,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0055": IncidentContingencyPlan(
        plan_id="PLAN_P15_0055",
        title="Operational Action Plan 15-55",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_055",
        time_of_occurrence_min=655,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0056": IncidentContingencyPlan(
        plan_id="PLAN_P15_0056",
        title="Operational Action Plan 15-56",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_056",
        time_of_occurrence_min=656,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0057": IncidentContingencyPlan(
        plan_id="PLAN_P15_0057",
        title="Operational Action Plan 15-57",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_057",
        time_of_occurrence_min=657,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0058": IncidentContingencyPlan(
        plan_id="PLAN_P15_0058",
        title="Operational Action Plan 15-58",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_058",
        time_of_occurrence_min=658,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0059": IncidentContingencyPlan(
        plan_id="PLAN_P15_0059",
        title="Operational Action Plan 15-59",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_059",
        time_of_occurrence_min=659,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0060": IncidentContingencyPlan(
        plan_id="PLAN_P15_0060",
        title="Operational Action Plan 15-60",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_060",
        time_of_occurrence_min=660,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0061": IncidentContingencyPlan(
        plan_id="PLAN_P15_0061",
        title="Operational Action Plan 15-61",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_061",
        time_of_occurrence_min=661,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0062": IncidentContingencyPlan(
        plan_id="PLAN_P15_0062",
        title="Operational Action Plan 15-62",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_062",
        time_of_occurrence_min=662,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0063": IncidentContingencyPlan(
        plan_id="PLAN_P15_0063",
        title="Operational Action Plan 15-63",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_063",
        time_of_occurrence_min=663,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0064": IncidentContingencyPlan(
        plan_id="PLAN_P15_0064",
        title="Operational Action Plan 15-64",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_064",
        time_of_occurrence_min=664,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0065": IncidentContingencyPlan(
        plan_id="PLAN_P15_0065",
        title="Operational Action Plan 15-65",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_065",
        time_of_occurrence_min=665,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0066": IncidentContingencyPlan(
        plan_id="PLAN_P15_0066",
        title="Operational Action Plan 15-66",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_066",
        time_of_occurrence_min=666,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0067": IncidentContingencyPlan(
        plan_id="PLAN_P15_0067",
        title="Operational Action Plan 15-67",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_067",
        time_of_occurrence_min=667,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0068": IncidentContingencyPlan(
        plan_id="PLAN_P15_0068",
        title="Operational Action Plan 15-68",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_068",
        time_of_occurrence_min=668,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0069": IncidentContingencyPlan(
        plan_id="PLAN_P15_0069",
        title="Operational Action Plan 15-69",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_069",
        time_of_occurrence_min=669,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0070": IncidentContingencyPlan(
        plan_id="PLAN_P15_0070",
        title="Operational Action Plan 15-70",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_070",
        time_of_occurrence_min=670,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0071": IncidentContingencyPlan(
        plan_id="PLAN_P15_0071",
        title="Operational Action Plan 15-71",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_071",
        time_of_occurrence_min=671,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0072": IncidentContingencyPlan(
        plan_id="PLAN_P15_0072",
        title="Operational Action Plan 15-72",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_072",
        time_of_occurrence_min=672,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0073": IncidentContingencyPlan(
        plan_id="PLAN_P15_0073",
        title="Operational Action Plan 15-73",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_073",
        time_of_occurrence_min=673,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0074": IncidentContingencyPlan(
        plan_id="PLAN_P15_0074",
        title="Operational Action Plan 15-74",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_074",
        time_of_occurrence_min=674,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0075": IncidentContingencyPlan(
        plan_id="PLAN_P15_0075",
        title="Operational Action Plan 15-75",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_075",
        time_of_occurrence_min=675,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0076": IncidentContingencyPlan(
        plan_id="PLAN_P15_0076",
        title="Operational Action Plan 15-76",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_076",
        time_of_occurrence_min=676,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0077": IncidentContingencyPlan(
        plan_id="PLAN_P15_0077",
        title="Operational Action Plan 15-77",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_077",
        time_of_occurrence_min=677,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0078": IncidentContingencyPlan(
        plan_id="PLAN_P15_0078",
        title="Operational Action Plan 15-78",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_078",
        time_of_occurrence_min=678,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0079": IncidentContingencyPlan(
        plan_id="PLAN_P15_0079",
        title="Operational Action Plan 15-79",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_079",
        time_of_occurrence_min=679,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0080": IncidentContingencyPlan(
        plan_id="PLAN_P15_0080",
        title="Operational Action Plan 15-80",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_080",
        time_of_occurrence_min=680,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0081": IncidentContingencyPlan(
        plan_id="PLAN_P15_0081",
        title="Operational Action Plan 15-81",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_081",
        time_of_occurrence_min=681,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0082": IncidentContingencyPlan(
        plan_id="PLAN_P15_0082",
        title="Operational Action Plan 15-82",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_082",
        time_of_occurrence_min=682,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0083": IncidentContingencyPlan(
        plan_id="PLAN_P15_0083",
        title="Operational Action Plan 15-83",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_083",
        time_of_occurrence_min=683,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0084": IncidentContingencyPlan(
        plan_id="PLAN_P15_0084",
        title="Operational Action Plan 15-84",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_084",
        time_of_occurrence_min=684,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0085": IncidentContingencyPlan(
        plan_id="PLAN_P15_0085",
        title="Operational Action Plan 15-85",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_085",
        time_of_occurrence_min=685,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0086": IncidentContingencyPlan(
        plan_id="PLAN_P15_0086",
        title="Operational Action Plan 15-86",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_086",
        time_of_occurrence_min=686,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0087": IncidentContingencyPlan(
        plan_id="PLAN_P15_0087",
        title="Operational Action Plan 15-87",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_087",
        time_of_occurrence_min=687,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0088": IncidentContingencyPlan(
        plan_id="PLAN_P15_0088",
        title="Operational Action Plan 15-88",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_088",
        time_of_occurrence_min=688,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0089": IncidentContingencyPlan(
        plan_id="PLAN_P15_0089",
        title="Operational Action Plan 15-89",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_089",
        time_of_occurrence_min=689,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0090": IncidentContingencyPlan(
        plan_id="PLAN_P15_0090",
        title="Operational Action Plan 15-90",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_090",
        time_of_occurrence_min=690,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0091": IncidentContingencyPlan(
        plan_id="PLAN_P15_0091",
        title="Operational Action Plan 15-91",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_091",
        time_of_occurrence_min=691,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0092": IncidentContingencyPlan(
        plan_id="PLAN_P15_0092",
        title="Operational Action Plan 15-92",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_092",
        time_of_occurrence_min=692,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0093": IncidentContingencyPlan(
        plan_id="PLAN_P15_0093",
        title="Operational Action Plan 15-93",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_093",
        time_of_occurrence_min=693,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0094": IncidentContingencyPlan(
        plan_id="PLAN_P15_0094",
        title="Operational Action Plan 15-94",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_094",
        time_of_occurrence_min=694,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0095": IncidentContingencyPlan(
        plan_id="PLAN_P15_0095",
        title="Operational Action Plan 15-95",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_095",
        time_of_occurrence_min=695,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0096": IncidentContingencyPlan(
        plan_id="PLAN_P15_0096",
        title="Operational Action Plan 15-96",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_096",
        time_of_occurrence_min=696,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0097": IncidentContingencyPlan(
        plan_id="PLAN_P15_0097",
        title="Operational Action Plan 15-97",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_097",
        time_of_occurrence_min=697,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0098": IncidentContingencyPlan(
        plan_id="PLAN_P15_0098",
        title="Operational Action Plan 15-98",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_098",
        time_of_occurrence_min=698,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0099": IncidentContingencyPlan(
        plan_id="PLAN_P15_0099",
        title="Operational Action Plan 15-99",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_099",
        time_of_occurrence_min=699,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0100": IncidentContingencyPlan(
        plan_id="PLAN_P15_0100",
        title="Operational Action Plan 15-100",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_100",
        time_of_occurrence_min=700,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0101": IncidentContingencyPlan(
        plan_id="PLAN_P15_0101",
        title="Operational Action Plan 15-101",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_101",
        time_of_occurrence_min=701,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0102": IncidentContingencyPlan(
        plan_id="PLAN_P15_0102",
        title="Operational Action Plan 15-102",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_102",
        time_of_occurrence_min=702,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0103": IncidentContingencyPlan(
        plan_id="PLAN_P15_0103",
        title="Operational Action Plan 15-103",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_103",
        time_of_occurrence_min=703,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0104": IncidentContingencyPlan(
        plan_id="PLAN_P15_0104",
        title="Operational Action Plan 15-104",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_104",
        time_of_occurrence_min=704,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0105": IncidentContingencyPlan(
        plan_id="PLAN_P15_0105",
        title="Operational Action Plan 15-105",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_105",
        time_of_occurrence_min=705,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0106": IncidentContingencyPlan(
        plan_id="PLAN_P15_0106",
        title="Operational Action Plan 15-106",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_106",
        time_of_occurrence_min=706,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0107": IncidentContingencyPlan(
        plan_id="PLAN_P15_0107",
        title="Operational Action Plan 15-107",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_107",
        time_of_occurrence_min=707,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0108": IncidentContingencyPlan(
        plan_id="PLAN_P15_0108",
        title="Operational Action Plan 15-108",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_108",
        time_of_occurrence_min=708,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0109": IncidentContingencyPlan(
        plan_id="PLAN_P15_0109",
        title="Operational Action Plan 15-109",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_109",
        time_of_occurrence_min=709,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0110": IncidentContingencyPlan(
        plan_id="PLAN_P15_0110",
        title="Operational Action Plan 15-110",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_110",
        time_of_occurrence_min=710,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0111": IncidentContingencyPlan(
        plan_id="PLAN_P15_0111",
        title="Operational Action Plan 15-111",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_111",
        time_of_occurrence_min=711,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0112": IncidentContingencyPlan(
        plan_id="PLAN_P15_0112",
        title="Operational Action Plan 15-112",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_112",
        time_of_occurrence_min=712,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0113": IncidentContingencyPlan(
        plan_id="PLAN_P15_0113",
        title="Operational Action Plan 15-113",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_113",
        time_of_occurrence_min=713,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0114": IncidentContingencyPlan(
        plan_id="PLAN_P15_0114",
        title="Operational Action Plan 15-114",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_114",
        time_of_occurrence_min=714,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0115": IncidentContingencyPlan(
        plan_id="PLAN_P15_0115",
        title="Operational Action Plan 15-115",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_115",
        time_of_occurrence_min=715,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0116": IncidentContingencyPlan(
        plan_id="PLAN_P15_0116",
        title="Operational Action Plan 15-116",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_116",
        time_of_occurrence_min=716,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0117": IncidentContingencyPlan(
        plan_id="PLAN_P15_0117",
        title="Operational Action Plan 15-117",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_117",
        time_of_occurrence_min=717,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0118": IncidentContingencyPlan(
        plan_id="PLAN_P15_0118",
        title="Operational Action Plan 15-118",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_118",
        time_of_occurrence_min=718,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0119": IncidentContingencyPlan(
        plan_id="PLAN_P15_0119",
        title="Operational Action Plan 15-119",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_119",
        time_of_occurrence_min=719,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0120": IncidentContingencyPlan(
        plan_id="PLAN_P15_0120",
        title="Operational Action Plan 15-120",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_120",
        time_of_occurrence_min=720,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0121": IncidentContingencyPlan(
        plan_id="PLAN_P15_0121",
        title="Operational Action Plan 15-121",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_121",
        time_of_occurrence_min=721,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0122": IncidentContingencyPlan(
        plan_id="PLAN_P15_0122",
        title="Operational Action Plan 15-122",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_122",
        time_of_occurrence_min=722,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0123": IncidentContingencyPlan(
        plan_id="PLAN_P15_0123",
        title="Operational Action Plan 15-123",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_123",
        time_of_occurrence_min=723,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0124": IncidentContingencyPlan(
        plan_id="PLAN_P15_0124",
        title="Operational Action Plan 15-124",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_124",
        time_of_occurrence_min=724,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0125": IncidentContingencyPlan(
        plan_id="PLAN_P15_0125",
        title="Operational Action Plan 15-125",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_125",
        time_of_occurrence_min=725,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0126": IncidentContingencyPlan(
        plan_id="PLAN_P15_0126",
        title="Operational Action Plan 15-126",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_126",
        time_of_occurrence_min=726,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0127": IncidentContingencyPlan(
        plan_id="PLAN_P15_0127",
        title="Operational Action Plan 15-127",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_127",
        time_of_occurrence_min=727,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0128": IncidentContingencyPlan(
        plan_id="PLAN_P15_0128",
        title="Operational Action Plan 15-128",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_128",
        time_of_occurrence_min=728,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0129": IncidentContingencyPlan(
        plan_id="PLAN_P15_0129",
        title="Operational Action Plan 15-129",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_129",
        time_of_occurrence_min=729,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0130": IncidentContingencyPlan(
        plan_id="PLAN_P15_0130",
        title="Operational Action Plan 15-130",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_130",
        time_of_occurrence_min=730,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0131": IncidentContingencyPlan(
        plan_id="PLAN_P15_0131",
        title="Operational Action Plan 15-131",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_131",
        time_of_occurrence_min=731,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0132": IncidentContingencyPlan(
        plan_id="PLAN_P15_0132",
        title="Operational Action Plan 15-132",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_132",
        time_of_occurrence_min=732,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0133": IncidentContingencyPlan(
        plan_id="PLAN_P15_0133",
        title="Operational Action Plan 15-133",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_133",
        time_of_occurrence_min=733,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0134": IncidentContingencyPlan(
        plan_id="PLAN_P15_0134",
        title="Operational Action Plan 15-134",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_134",
        time_of_occurrence_min=734,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0135": IncidentContingencyPlan(
        plan_id="PLAN_P15_0135",
        title="Operational Action Plan 15-135",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_135",
        time_of_occurrence_min=735,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0136": IncidentContingencyPlan(
        plan_id="PLAN_P15_0136",
        title="Operational Action Plan 15-136",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_136",
        time_of_occurrence_min=736,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0137": IncidentContingencyPlan(
        plan_id="PLAN_P15_0137",
        title="Operational Action Plan 15-137",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_137",
        time_of_occurrence_min=737,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0138": IncidentContingencyPlan(
        plan_id="PLAN_P15_0138",
        title="Operational Action Plan 15-138",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_138",
        time_of_occurrence_min=738,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0139": IncidentContingencyPlan(
        plan_id="PLAN_P15_0139",
        title="Operational Action Plan 15-139",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_139",
        time_of_occurrence_min=739,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0140": IncidentContingencyPlan(
        plan_id="PLAN_P15_0140",
        title="Operational Action Plan 15-140",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_140",
        time_of_occurrence_min=740,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0141": IncidentContingencyPlan(
        plan_id="PLAN_P15_0141",
        title="Operational Action Plan 15-141",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_141",
        time_of_occurrence_min=741,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0142": IncidentContingencyPlan(
        plan_id="PLAN_P15_0142",
        title="Operational Action Plan 15-142",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_142",
        time_of_occurrence_min=742,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0143": IncidentContingencyPlan(
        plan_id="PLAN_P15_0143",
        title="Operational Action Plan 15-143",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_143",
        time_of_occurrence_min=743,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0144": IncidentContingencyPlan(
        plan_id="PLAN_P15_0144",
        title="Operational Action Plan 15-144",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_144",
        time_of_occurrence_min=744,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0145": IncidentContingencyPlan(
        plan_id="PLAN_P15_0145",
        title="Operational Action Plan 15-145",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_145",
        time_of_occurrence_min=745,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0146": IncidentContingencyPlan(
        plan_id="PLAN_P15_0146",
        title="Operational Action Plan 15-146",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_146",
        time_of_occurrence_min=746,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0147": IncidentContingencyPlan(
        plan_id="PLAN_P15_0147",
        title="Operational Action Plan 15-147",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_147",
        time_of_occurrence_min=747,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0148": IncidentContingencyPlan(
        plan_id="PLAN_P15_0148",
        title="Operational Action Plan 15-148",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_148",
        time_of_occurrence_min=748,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0149": IncidentContingencyPlan(
        plan_id="PLAN_P15_0149",
        title="Operational Action Plan 15-149",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_149",
        time_of_occurrence_min=749,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0150": IncidentContingencyPlan(
        plan_id="PLAN_P15_0150",
        title="Operational Action Plan 15-150",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_150",
        time_of_occurrence_min=750,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0151": IncidentContingencyPlan(
        plan_id="PLAN_P15_0151",
        title="Operational Action Plan 15-151",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_151",
        time_of_occurrence_min=751,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0152": IncidentContingencyPlan(
        plan_id="PLAN_P15_0152",
        title="Operational Action Plan 15-152",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_152",
        time_of_occurrence_min=752,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0153": IncidentContingencyPlan(
        plan_id="PLAN_P15_0153",
        title="Operational Action Plan 15-153",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_153",
        time_of_occurrence_min=753,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0154": IncidentContingencyPlan(
        plan_id="PLAN_P15_0154",
        title="Operational Action Plan 15-154",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_154",
        time_of_occurrence_min=754,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0155": IncidentContingencyPlan(
        plan_id="PLAN_P15_0155",
        title="Operational Action Plan 15-155",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_155",
        time_of_occurrence_min=755,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0156": IncidentContingencyPlan(
        plan_id="PLAN_P15_0156",
        title="Operational Action Plan 15-156",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_156",
        time_of_occurrence_min=756,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0157": IncidentContingencyPlan(
        plan_id="PLAN_P15_0157",
        title="Operational Action Plan 15-157",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_157",
        time_of_occurrence_min=757,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0158": IncidentContingencyPlan(
        plan_id="PLAN_P15_0158",
        title="Operational Action Plan 15-158",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_158",
        time_of_occurrence_min=758,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0159": IncidentContingencyPlan(
        plan_id="PLAN_P15_0159",
        title="Operational Action Plan 15-159",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_159",
        time_of_occurrence_min=759,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0160": IncidentContingencyPlan(
        plan_id="PLAN_P15_0160",
        title="Operational Action Plan 15-160",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_160",
        time_of_occurrence_min=760,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0161": IncidentContingencyPlan(
        plan_id="PLAN_P15_0161",
        title="Operational Action Plan 15-161",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_161",
        time_of_occurrence_min=761,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0162": IncidentContingencyPlan(
        plan_id="PLAN_P15_0162",
        title="Operational Action Plan 15-162",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_162",
        time_of_occurrence_min=762,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0163": IncidentContingencyPlan(
        plan_id="PLAN_P15_0163",
        title="Operational Action Plan 15-163",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_163",
        time_of_occurrence_min=763,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0164": IncidentContingencyPlan(
        plan_id="PLAN_P15_0164",
        title="Operational Action Plan 15-164",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_164",
        time_of_occurrence_min=764,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
    "PLAN_P15_0165": IncidentContingencyPlan(
        plan_id="PLAN_P15_0165",
        title="Operational Action Plan 15-165",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_165",
        time_of_occurrence_min=765,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_05"
    ),
    "PLAN_P15_0166": IncidentContingencyPlan(
        plan_id="PLAN_P15_0166",
        title="Operational Action Plan 15-166",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_166",
        time_of_occurrence_min=766,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_06"
    ),
    "PLAN_P15_0167": IncidentContingencyPlan(
        plan_id="PLAN_P15_0167",
        title="Operational Action Plan 15-167",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_167",
        time_of_occurrence_min=767,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_07"
    ),
    "PLAN_P15_0168": IncidentContingencyPlan(
        plan_id="PLAN_P15_0168",
        title="Operational Action Plan 15-168",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_168",
        time_of_occurrence_min=768,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_08"
    ),
    "PLAN_P15_0169": IncidentContingencyPlan(
        plan_id="PLAN_P15_0169",
        title="Operational Action Plan 15-169",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P15_169",
        time_of_occurrence_min=769,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_09"
    ),
    "PLAN_P15_0170": IncidentContingencyPlan(
        plan_id="PLAN_P15_0170",
        title="Operational Action Plan 15-170",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P15_170",
        time_of_occurrence_min=770,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_00"
    ),
    "PLAN_P15_0171": IncidentContingencyPlan(
        plan_id="PLAN_P15_0171",
        title="Operational Action Plan 15-171",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P15_171",
        time_of_occurrence_min=771,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_01"
    ),
    "PLAN_P15_0172": IncidentContingencyPlan(
        plan_id="PLAN_P15_0172",
        title="Operational Action Plan 15-172",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P15_172",
        time_of_occurrence_min=772,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_02"
    ),
    "PLAN_P15_0173": IncidentContingencyPlan(
        plan_id="PLAN_P15_0173",
        title="Operational Action Plan 15-173",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P15_173",
        time_of_occurrence_min=773,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_03"
    ),
    "PLAN_P15_0174": IncidentContingencyPlan(
        plan_id="PLAN_P15_0174",
        title="Operational Action Plan 15-174",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P15_174",
        time_of_occurrence_min=774,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_15_04"
    ),
}
