"""Railway Incident Contingency Action Plans Part 013."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class IncidentContingencyPlan:
    plan_id: str
    title: str
    incident_type: str
    affected_block_id: str
    time_of_occurrence_min: int
    expected_clearance_min: int
    severity_score: int
    primary_dispatch_action: str
    contingency_corridor_id: str

INCIDENT_CONTINGENCY_PLANS_013: Dict[str, IncidentContingencyPlan] = {
    "PLAN_P13_0001": IncidentContingencyPlan(
        plan_id="PLAN_P13_0001",
        title="Operational Action Plan 13-1",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_001",
        time_of_occurrence_min=601,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0002": IncidentContingencyPlan(
        plan_id="PLAN_P13_0002",
        title="Operational Action Plan 13-2",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_002",
        time_of_occurrence_min=602,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0003": IncidentContingencyPlan(
        plan_id="PLAN_P13_0003",
        title="Operational Action Plan 13-3",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_003",
        time_of_occurrence_min=603,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0004": IncidentContingencyPlan(
        plan_id="PLAN_P13_0004",
        title="Operational Action Plan 13-4",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_004",
        time_of_occurrence_min=604,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0005": IncidentContingencyPlan(
        plan_id="PLAN_P13_0005",
        title="Operational Action Plan 13-5",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_005",
        time_of_occurrence_min=605,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0006": IncidentContingencyPlan(
        plan_id="PLAN_P13_0006",
        title="Operational Action Plan 13-6",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_006",
        time_of_occurrence_min=606,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0007": IncidentContingencyPlan(
        plan_id="PLAN_P13_0007",
        title="Operational Action Plan 13-7",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_007",
        time_of_occurrence_min=607,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0008": IncidentContingencyPlan(
        plan_id="PLAN_P13_0008",
        title="Operational Action Plan 13-8",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_008",
        time_of_occurrence_min=608,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0009": IncidentContingencyPlan(
        plan_id="PLAN_P13_0009",
        title="Operational Action Plan 13-9",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_009",
        time_of_occurrence_min=609,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0010": IncidentContingencyPlan(
        plan_id="PLAN_P13_0010",
        title="Operational Action Plan 13-10",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_010",
        time_of_occurrence_min=610,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0011": IncidentContingencyPlan(
        plan_id="PLAN_P13_0011",
        title="Operational Action Plan 13-11",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_011",
        time_of_occurrence_min=611,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0012": IncidentContingencyPlan(
        plan_id="PLAN_P13_0012",
        title="Operational Action Plan 13-12",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_012",
        time_of_occurrence_min=612,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0013": IncidentContingencyPlan(
        plan_id="PLAN_P13_0013",
        title="Operational Action Plan 13-13",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_013",
        time_of_occurrence_min=613,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0014": IncidentContingencyPlan(
        plan_id="PLAN_P13_0014",
        title="Operational Action Plan 13-14",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_014",
        time_of_occurrence_min=614,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0015": IncidentContingencyPlan(
        plan_id="PLAN_P13_0015",
        title="Operational Action Plan 13-15",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_015",
        time_of_occurrence_min=615,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0016": IncidentContingencyPlan(
        plan_id="PLAN_P13_0016",
        title="Operational Action Plan 13-16",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_016",
        time_of_occurrence_min=616,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0017": IncidentContingencyPlan(
        plan_id="PLAN_P13_0017",
        title="Operational Action Plan 13-17",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_017",
        time_of_occurrence_min=617,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0018": IncidentContingencyPlan(
        plan_id="PLAN_P13_0018",
        title="Operational Action Plan 13-18",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_018",
        time_of_occurrence_min=618,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0019": IncidentContingencyPlan(
        plan_id="PLAN_P13_0019",
        title="Operational Action Plan 13-19",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_019",
        time_of_occurrence_min=619,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0020": IncidentContingencyPlan(
        plan_id="PLAN_P13_0020",
        title="Operational Action Plan 13-20",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_020",
        time_of_occurrence_min=620,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0021": IncidentContingencyPlan(
        plan_id="PLAN_P13_0021",
        title="Operational Action Plan 13-21",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_021",
        time_of_occurrence_min=621,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0022": IncidentContingencyPlan(
        plan_id="PLAN_P13_0022",
        title="Operational Action Plan 13-22",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_022",
        time_of_occurrence_min=622,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0023": IncidentContingencyPlan(
        plan_id="PLAN_P13_0023",
        title="Operational Action Plan 13-23",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_023",
        time_of_occurrence_min=623,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0024": IncidentContingencyPlan(
        plan_id="PLAN_P13_0024",
        title="Operational Action Plan 13-24",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_024",
        time_of_occurrence_min=624,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0025": IncidentContingencyPlan(
        plan_id="PLAN_P13_0025",
        title="Operational Action Plan 13-25",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_025",
        time_of_occurrence_min=625,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0026": IncidentContingencyPlan(
        plan_id="PLAN_P13_0026",
        title="Operational Action Plan 13-26",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_026",
        time_of_occurrence_min=626,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0027": IncidentContingencyPlan(
        plan_id="PLAN_P13_0027",
        title="Operational Action Plan 13-27",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_027",
        time_of_occurrence_min=627,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0028": IncidentContingencyPlan(
        plan_id="PLAN_P13_0028",
        title="Operational Action Plan 13-28",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_028",
        time_of_occurrence_min=628,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0029": IncidentContingencyPlan(
        plan_id="PLAN_P13_0029",
        title="Operational Action Plan 13-29",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_029",
        time_of_occurrence_min=629,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0030": IncidentContingencyPlan(
        plan_id="PLAN_P13_0030",
        title="Operational Action Plan 13-30",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_030",
        time_of_occurrence_min=630,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0031": IncidentContingencyPlan(
        plan_id="PLAN_P13_0031",
        title="Operational Action Plan 13-31",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_031",
        time_of_occurrence_min=631,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0032": IncidentContingencyPlan(
        plan_id="PLAN_P13_0032",
        title="Operational Action Plan 13-32",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_032",
        time_of_occurrence_min=632,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0033": IncidentContingencyPlan(
        plan_id="PLAN_P13_0033",
        title="Operational Action Plan 13-33",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_033",
        time_of_occurrence_min=633,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0034": IncidentContingencyPlan(
        plan_id="PLAN_P13_0034",
        title="Operational Action Plan 13-34",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_034",
        time_of_occurrence_min=634,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0035": IncidentContingencyPlan(
        plan_id="PLAN_P13_0035",
        title="Operational Action Plan 13-35",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_035",
        time_of_occurrence_min=635,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0036": IncidentContingencyPlan(
        plan_id="PLAN_P13_0036",
        title="Operational Action Plan 13-36",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_036",
        time_of_occurrence_min=636,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0037": IncidentContingencyPlan(
        plan_id="PLAN_P13_0037",
        title="Operational Action Plan 13-37",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_037",
        time_of_occurrence_min=637,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0038": IncidentContingencyPlan(
        plan_id="PLAN_P13_0038",
        title="Operational Action Plan 13-38",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_038",
        time_of_occurrence_min=638,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0039": IncidentContingencyPlan(
        plan_id="PLAN_P13_0039",
        title="Operational Action Plan 13-39",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_039",
        time_of_occurrence_min=639,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0040": IncidentContingencyPlan(
        plan_id="PLAN_P13_0040",
        title="Operational Action Plan 13-40",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_040",
        time_of_occurrence_min=640,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0041": IncidentContingencyPlan(
        plan_id="PLAN_P13_0041",
        title="Operational Action Plan 13-41",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_041",
        time_of_occurrence_min=641,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0042": IncidentContingencyPlan(
        plan_id="PLAN_P13_0042",
        title="Operational Action Plan 13-42",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_042",
        time_of_occurrence_min=642,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0043": IncidentContingencyPlan(
        plan_id="PLAN_P13_0043",
        title="Operational Action Plan 13-43",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_043",
        time_of_occurrence_min=643,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0044": IncidentContingencyPlan(
        plan_id="PLAN_P13_0044",
        title="Operational Action Plan 13-44",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_044",
        time_of_occurrence_min=644,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0045": IncidentContingencyPlan(
        plan_id="PLAN_P13_0045",
        title="Operational Action Plan 13-45",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_045",
        time_of_occurrence_min=645,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0046": IncidentContingencyPlan(
        plan_id="PLAN_P13_0046",
        title="Operational Action Plan 13-46",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_046",
        time_of_occurrence_min=646,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0047": IncidentContingencyPlan(
        plan_id="PLAN_P13_0047",
        title="Operational Action Plan 13-47",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_047",
        time_of_occurrence_min=647,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0048": IncidentContingencyPlan(
        plan_id="PLAN_P13_0048",
        title="Operational Action Plan 13-48",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_048",
        time_of_occurrence_min=648,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0049": IncidentContingencyPlan(
        plan_id="PLAN_P13_0049",
        title="Operational Action Plan 13-49",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_049",
        time_of_occurrence_min=649,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0050": IncidentContingencyPlan(
        plan_id="PLAN_P13_0050",
        title="Operational Action Plan 13-50",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_050",
        time_of_occurrence_min=650,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0051": IncidentContingencyPlan(
        plan_id="PLAN_P13_0051",
        title="Operational Action Plan 13-51",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_051",
        time_of_occurrence_min=651,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0052": IncidentContingencyPlan(
        plan_id="PLAN_P13_0052",
        title="Operational Action Plan 13-52",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_052",
        time_of_occurrence_min=652,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0053": IncidentContingencyPlan(
        plan_id="PLAN_P13_0053",
        title="Operational Action Plan 13-53",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_053",
        time_of_occurrence_min=653,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0054": IncidentContingencyPlan(
        plan_id="PLAN_P13_0054",
        title="Operational Action Plan 13-54",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_054",
        time_of_occurrence_min=654,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0055": IncidentContingencyPlan(
        plan_id="PLAN_P13_0055",
        title="Operational Action Plan 13-55",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_055",
        time_of_occurrence_min=655,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0056": IncidentContingencyPlan(
        plan_id="PLAN_P13_0056",
        title="Operational Action Plan 13-56",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_056",
        time_of_occurrence_min=656,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0057": IncidentContingencyPlan(
        plan_id="PLAN_P13_0057",
        title="Operational Action Plan 13-57",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_057",
        time_of_occurrence_min=657,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0058": IncidentContingencyPlan(
        plan_id="PLAN_P13_0058",
        title="Operational Action Plan 13-58",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_058",
        time_of_occurrence_min=658,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0059": IncidentContingencyPlan(
        plan_id="PLAN_P13_0059",
        title="Operational Action Plan 13-59",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_059",
        time_of_occurrence_min=659,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0060": IncidentContingencyPlan(
        plan_id="PLAN_P13_0060",
        title="Operational Action Plan 13-60",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_060",
        time_of_occurrence_min=660,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0061": IncidentContingencyPlan(
        plan_id="PLAN_P13_0061",
        title="Operational Action Plan 13-61",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_061",
        time_of_occurrence_min=661,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0062": IncidentContingencyPlan(
        plan_id="PLAN_P13_0062",
        title="Operational Action Plan 13-62",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_062",
        time_of_occurrence_min=662,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0063": IncidentContingencyPlan(
        plan_id="PLAN_P13_0063",
        title="Operational Action Plan 13-63",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_063",
        time_of_occurrence_min=663,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0064": IncidentContingencyPlan(
        plan_id="PLAN_P13_0064",
        title="Operational Action Plan 13-64",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_064",
        time_of_occurrence_min=664,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0065": IncidentContingencyPlan(
        plan_id="PLAN_P13_0065",
        title="Operational Action Plan 13-65",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_065",
        time_of_occurrence_min=665,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0066": IncidentContingencyPlan(
        plan_id="PLAN_P13_0066",
        title="Operational Action Plan 13-66",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_066",
        time_of_occurrence_min=666,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0067": IncidentContingencyPlan(
        plan_id="PLAN_P13_0067",
        title="Operational Action Plan 13-67",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_067",
        time_of_occurrence_min=667,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0068": IncidentContingencyPlan(
        plan_id="PLAN_P13_0068",
        title="Operational Action Plan 13-68",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_068",
        time_of_occurrence_min=668,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0069": IncidentContingencyPlan(
        plan_id="PLAN_P13_0069",
        title="Operational Action Plan 13-69",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_069",
        time_of_occurrence_min=669,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0070": IncidentContingencyPlan(
        plan_id="PLAN_P13_0070",
        title="Operational Action Plan 13-70",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_070",
        time_of_occurrence_min=670,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0071": IncidentContingencyPlan(
        plan_id="PLAN_P13_0071",
        title="Operational Action Plan 13-71",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_071",
        time_of_occurrence_min=671,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0072": IncidentContingencyPlan(
        plan_id="PLAN_P13_0072",
        title="Operational Action Plan 13-72",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_072",
        time_of_occurrence_min=672,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0073": IncidentContingencyPlan(
        plan_id="PLAN_P13_0073",
        title="Operational Action Plan 13-73",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_073",
        time_of_occurrence_min=673,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0074": IncidentContingencyPlan(
        plan_id="PLAN_P13_0074",
        title="Operational Action Plan 13-74",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_074",
        time_of_occurrence_min=674,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0075": IncidentContingencyPlan(
        plan_id="PLAN_P13_0075",
        title="Operational Action Plan 13-75",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_075",
        time_of_occurrence_min=675,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0076": IncidentContingencyPlan(
        plan_id="PLAN_P13_0076",
        title="Operational Action Plan 13-76",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_076",
        time_of_occurrence_min=676,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0077": IncidentContingencyPlan(
        plan_id="PLAN_P13_0077",
        title="Operational Action Plan 13-77",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_077",
        time_of_occurrence_min=677,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0078": IncidentContingencyPlan(
        plan_id="PLAN_P13_0078",
        title="Operational Action Plan 13-78",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_078",
        time_of_occurrence_min=678,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0079": IncidentContingencyPlan(
        plan_id="PLAN_P13_0079",
        title="Operational Action Plan 13-79",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_079",
        time_of_occurrence_min=679,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0080": IncidentContingencyPlan(
        plan_id="PLAN_P13_0080",
        title="Operational Action Plan 13-80",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_080",
        time_of_occurrence_min=680,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0081": IncidentContingencyPlan(
        plan_id="PLAN_P13_0081",
        title="Operational Action Plan 13-81",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_081",
        time_of_occurrence_min=681,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0082": IncidentContingencyPlan(
        plan_id="PLAN_P13_0082",
        title="Operational Action Plan 13-82",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_082",
        time_of_occurrence_min=682,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0083": IncidentContingencyPlan(
        plan_id="PLAN_P13_0083",
        title="Operational Action Plan 13-83",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_083",
        time_of_occurrence_min=683,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0084": IncidentContingencyPlan(
        plan_id="PLAN_P13_0084",
        title="Operational Action Plan 13-84",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_084",
        time_of_occurrence_min=684,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0085": IncidentContingencyPlan(
        plan_id="PLAN_P13_0085",
        title="Operational Action Plan 13-85",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_085",
        time_of_occurrence_min=685,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0086": IncidentContingencyPlan(
        plan_id="PLAN_P13_0086",
        title="Operational Action Plan 13-86",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_086",
        time_of_occurrence_min=686,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0087": IncidentContingencyPlan(
        plan_id="PLAN_P13_0087",
        title="Operational Action Plan 13-87",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_087",
        time_of_occurrence_min=687,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0088": IncidentContingencyPlan(
        plan_id="PLAN_P13_0088",
        title="Operational Action Plan 13-88",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_088",
        time_of_occurrence_min=688,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0089": IncidentContingencyPlan(
        plan_id="PLAN_P13_0089",
        title="Operational Action Plan 13-89",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_089",
        time_of_occurrence_min=689,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0090": IncidentContingencyPlan(
        plan_id="PLAN_P13_0090",
        title="Operational Action Plan 13-90",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_090",
        time_of_occurrence_min=690,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0091": IncidentContingencyPlan(
        plan_id="PLAN_P13_0091",
        title="Operational Action Plan 13-91",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_091",
        time_of_occurrence_min=691,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0092": IncidentContingencyPlan(
        plan_id="PLAN_P13_0092",
        title="Operational Action Plan 13-92",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_092",
        time_of_occurrence_min=692,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0093": IncidentContingencyPlan(
        plan_id="PLAN_P13_0093",
        title="Operational Action Plan 13-93",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_093",
        time_of_occurrence_min=693,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0094": IncidentContingencyPlan(
        plan_id="PLAN_P13_0094",
        title="Operational Action Plan 13-94",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_094",
        time_of_occurrence_min=694,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0095": IncidentContingencyPlan(
        plan_id="PLAN_P13_0095",
        title="Operational Action Plan 13-95",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_095",
        time_of_occurrence_min=695,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0096": IncidentContingencyPlan(
        plan_id="PLAN_P13_0096",
        title="Operational Action Plan 13-96",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_096",
        time_of_occurrence_min=696,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0097": IncidentContingencyPlan(
        plan_id="PLAN_P13_0097",
        title="Operational Action Plan 13-97",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_097",
        time_of_occurrence_min=697,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0098": IncidentContingencyPlan(
        plan_id="PLAN_P13_0098",
        title="Operational Action Plan 13-98",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_098",
        time_of_occurrence_min=698,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0099": IncidentContingencyPlan(
        plan_id="PLAN_P13_0099",
        title="Operational Action Plan 13-99",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_099",
        time_of_occurrence_min=699,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0100": IncidentContingencyPlan(
        plan_id="PLAN_P13_0100",
        title="Operational Action Plan 13-100",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_100",
        time_of_occurrence_min=700,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0101": IncidentContingencyPlan(
        plan_id="PLAN_P13_0101",
        title="Operational Action Plan 13-101",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_101",
        time_of_occurrence_min=701,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0102": IncidentContingencyPlan(
        plan_id="PLAN_P13_0102",
        title="Operational Action Plan 13-102",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_102",
        time_of_occurrence_min=702,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0103": IncidentContingencyPlan(
        plan_id="PLAN_P13_0103",
        title="Operational Action Plan 13-103",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_103",
        time_of_occurrence_min=703,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0104": IncidentContingencyPlan(
        plan_id="PLAN_P13_0104",
        title="Operational Action Plan 13-104",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_104",
        time_of_occurrence_min=704,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0105": IncidentContingencyPlan(
        plan_id="PLAN_P13_0105",
        title="Operational Action Plan 13-105",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_105",
        time_of_occurrence_min=705,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0106": IncidentContingencyPlan(
        plan_id="PLAN_P13_0106",
        title="Operational Action Plan 13-106",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_106",
        time_of_occurrence_min=706,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0107": IncidentContingencyPlan(
        plan_id="PLAN_P13_0107",
        title="Operational Action Plan 13-107",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_107",
        time_of_occurrence_min=707,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0108": IncidentContingencyPlan(
        plan_id="PLAN_P13_0108",
        title="Operational Action Plan 13-108",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_108",
        time_of_occurrence_min=708,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0109": IncidentContingencyPlan(
        plan_id="PLAN_P13_0109",
        title="Operational Action Plan 13-109",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_109",
        time_of_occurrence_min=709,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0110": IncidentContingencyPlan(
        plan_id="PLAN_P13_0110",
        title="Operational Action Plan 13-110",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_110",
        time_of_occurrence_min=710,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0111": IncidentContingencyPlan(
        plan_id="PLAN_P13_0111",
        title="Operational Action Plan 13-111",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_111",
        time_of_occurrence_min=711,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0112": IncidentContingencyPlan(
        plan_id="PLAN_P13_0112",
        title="Operational Action Plan 13-112",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_112",
        time_of_occurrence_min=712,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0113": IncidentContingencyPlan(
        plan_id="PLAN_P13_0113",
        title="Operational Action Plan 13-113",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_113",
        time_of_occurrence_min=713,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0114": IncidentContingencyPlan(
        plan_id="PLAN_P13_0114",
        title="Operational Action Plan 13-114",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_114",
        time_of_occurrence_min=714,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0115": IncidentContingencyPlan(
        plan_id="PLAN_P13_0115",
        title="Operational Action Plan 13-115",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_115",
        time_of_occurrence_min=715,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0116": IncidentContingencyPlan(
        plan_id="PLAN_P13_0116",
        title="Operational Action Plan 13-116",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_116",
        time_of_occurrence_min=716,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0117": IncidentContingencyPlan(
        plan_id="PLAN_P13_0117",
        title="Operational Action Plan 13-117",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_117",
        time_of_occurrence_min=717,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0118": IncidentContingencyPlan(
        plan_id="PLAN_P13_0118",
        title="Operational Action Plan 13-118",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_118",
        time_of_occurrence_min=718,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0119": IncidentContingencyPlan(
        plan_id="PLAN_P13_0119",
        title="Operational Action Plan 13-119",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_119",
        time_of_occurrence_min=719,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0120": IncidentContingencyPlan(
        plan_id="PLAN_P13_0120",
        title="Operational Action Plan 13-120",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_120",
        time_of_occurrence_min=720,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0121": IncidentContingencyPlan(
        plan_id="PLAN_P13_0121",
        title="Operational Action Plan 13-121",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_121",
        time_of_occurrence_min=721,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0122": IncidentContingencyPlan(
        plan_id="PLAN_P13_0122",
        title="Operational Action Plan 13-122",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_122",
        time_of_occurrence_min=722,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0123": IncidentContingencyPlan(
        plan_id="PLAN_P13_0123",
        title="Operational Action Plan 13-123",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_123",
        time_of_occurrence_min=723,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0124": IncidentContingencyPlan(
        plan_id="PLAN_P13_0124",
        title="Operational Action Plan 13-124",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_124",
        time_of_occurrence_min=724,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0125": IncidentContingencyPlan(
        plan_id="PLAN_P13_0125",
        title="Operational Action Plan 13-125",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_125",
        time_of_occurrence_min=725,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0126": IncidentContingencyPlan(
        plan_id="PLAN_P13_0126",
        title="Operational Action Plan 13-126",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_126",
        time_of_occurrence_min=726,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0127": IncidentContingencyPlan(
        plan_id="PLAN_P13_0127",
        title="Operational Action Plan 13-127",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_127",
        time_of_occurrence_min=727,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0128": IncidentContingencyPlan(
        plan_id="PLAN_P13_0128",
        title="Operational Action Plan 13-128",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_128",
        time_of_occurrence_min=728,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0129": IncidentContingencyPlan(
        plan_id="PLAN_P13_0129",
        title="Operational Action Plan 13-129",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_129",
        time_of_occurrence_min=729,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0130": IncidentContingencyPlan(
        plan_id="PLAN_P13_0130",
        title="Operational Action Plan 13-130",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_130",
        time_of_occurrence_min=730,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0131": IncidentContingencyPlan(
        plan_id="PLAN_P13_0131",
        title="Operational Action Plan 13-131",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_131",
        time_of_occurrence_min=731,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0132": IncidentContingencyPlan(
        plan_id="PLAN_P13_0132",
        title="Operational Action Plan 13-132",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_132",
        time_of_occurrence_min=732,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0133": IncidentContingencyPlan(
        plan_id="PLAN_P13_0133",
        title="Operational Action Plan 13-133",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_133",
        time_of_occurrence_min=733,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0134": IncidentContingencyPlan(
        plan_id="PLAN_P13_0134",
        title="Operational Action Plan 13-134",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_134",
        time_of_occurrence_min=734,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0135": IncidentContingencyPlan(
        plan_id="PLAN_P13_0135",
        title="Operational Action Plan 13-135",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_135",
        time_of_occurrence_min=735,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0136": IncidentContingencyPlan(
        plan_id="PLAN_P13_0136",
        title="Operational Action Plan 13-136",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_136",
        time_of_occurrence_min=736,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0137": IncidentContingencyPlan(
        plan_id="PLAN_P13_0137",
        title="Operational Action Plan 13-137",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_137",
        time_of_occurrence_min=737,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0138": IncidentContingencyPlan(
        plan_id="PLAN_P13_0138",
        title="Operational Action Plan 13-138",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_138",
        time_of_occurrence_min=738,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0139": IncidentContingencyPlan(
        plan_id="PLAN_P13_0139",
        title="Operational Action Plan 13-139",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_139",
        time_of_occurrence_min=739,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0140": IncidentContingencyPlan(
        plan_id="PLAN_P13_0140",
        title="Operational Action Plan 13-140",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_140",
        time_of_occurrence_min=740,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0141": IncidentContingencyPlan(
        plan_id="PLAN_P13_0141",
        title="Operational Action Plan 13-141",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_141",
        time_of_occurrence_min=741,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0142": IncidentContingencyPlan(
        plan_id="PLAN_P13_0142",
        title="Operational Action Plan 13-142",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_142",
        time_of_occurrence_min=742,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0143": IncidentContingencyPlan(
        plan_id="PLAN_P13_0143",
        title="Operational Action Plan 13-143",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_143",
        time_of_occurrence_min=743,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0144": IncidentContingencyPlan(
        plan_id="PLAN_P13_0144",
        title="Operational Action Plan 13-144",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_144",
        time_of_occurrence_min=744,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0145": IncidentContingencyPlan(
        plan_id="PLAN_P13_0145",
        title="Operational Action Plan 13-145",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_145",
        time_of_occurrence_min=745,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0146": IncidentContingencyPlan(
        plan_id="PLAN_P13_0146",
        title="Operational Action Plan 13-146",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_146",
        time_of_occurrence_min=746,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0147": IncidentContingencyPlan(
        plan_id="PLAN_P13_0147",
        title="Operational Action Plan 13-147",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_147",
        time_of_occurrence_min=747,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0148": IncidentContingencyPlan(
        plan_id="PLAN_P13_0148",
        title="Operational Action Plan 13-148",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_148",
        time_of_occurrence_min=748,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0149": IncidentContingencyPlan(
        plan_id="PLAN_P13_0149",
        title="Operational Action Plan 13-149",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_149",
        time_of_occurrence_min=749,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0150": IncidentContingencyPlan(
        plan_id="PLAN_P13_0150",
        title="Operational Action Plan 13-150",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_150",
        time_of_occurrence_min=750,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0151": IncidentContingencyPlan(
        plan_id="PLAN_P13_0151",
        title="Operational Action Plan 13-151",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_151",
        time_of_occurrence_min=751,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0152": IncidentContingencyPlan(
        plan_id="PLAN_P13_0152",
        title="Operational Action Plan 13-152",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_152",
        time_of_occurrence_min=752,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0153": IncidentContingencyPlan(
        plan_id="PLAN_P13_0153",
        title="Operational Action Plan 13-153",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_153",
        time_of_occurrence_min=753,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0154": IncidentContingencyPlan(
        plan_id="PLAN_P13_0154",
        title="Operational Action Plan 13-154",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_154",
        time_of_occurrence_min=754,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0155": IncidentContingencyPlan(
        plan_id="PLAN_P13_0155",
        title="Operational Action Plan 13-155",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_155",
        time_of_occurrence_min=755,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0156": IncidentContingencyPlan(
        plan_id="PLAN_P13_0156",
        title="Operational Action Plan 13-156",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_156",
        time_of_occurrence_min=756,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0157": IncidentContingencyPlan(
        plan_id="PLAN_P13_0157",
        title="Operational Action Plan 13-157",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_157",
        time_of_occurrence_min=757,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0158": IncidentContingencyPlan(
        plan_id="PLAN_P13_0158",
        title="Operational Action Plan 13-158",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_158",
        time_of_occurrence_min=758,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0159": IncidentContingencyPlan(
        plan_id="PLAN_P13_0159",
        title="Operational Action Plan 13-159",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_159",
        time_of_occurrence_min=759,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0160": IncidentContingencyPlan(
        plan_id="PLAN_P13_0160",
        title="Operational Action Plan 13-160",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_160",
        time_of_occurrence_min=760,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0161": IncidentContingencyPlan(
        plan_id="PLAN_P13_0161",
        title="Operational Action Plan 13-161",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_161",
        time_of_occurrence_min=761,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0162": IncidentContingencyPlan(
        plan_id="PLAN_P13_0162",
        title="Operational Action Plan 13-162",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_162",
        time_of_occurrence_min=762,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0163": IncidentContingencyPlan(
        plan_id="PLAN_P13_0163",
        title="Operational Action Plan 13-163",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_163",
        time_of_occurrence_min=763,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0164": IncidentContingencyPlan(
        plan_id="PLAN_P13_0164",
        title="Operational Action Plan 13-164",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_164",
        time_of_occurrence_min=764,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
    "PLAN_P13_0165": IncidentContingencyPlan(
        plan_id="PLAN_P13_0165",
        title="Operational Action Plan 13-165",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_165",
        time_of_occurrence_min=765,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_05"
    ),
    "PLAN_P13_0166": IncidentContingencyPlan(
        plan_id="PLAN_P13_0166",
        title="Operational Action Plan 13-166",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_166",
        time_of_occurrence_min=766,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_06"
    ),
    "PLAN_P13_0167": IncidentContingencyPlan(
        plan_id="PLAN_P13_0167",
        title="Operational Action Plan 13-167",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_167",
        time_of_occurrence_min=767,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_07"
    ),
    "PLAN_P13_0168": IncidentContingencyPlan(
        plan_id="PLAN_P13_0168",
        title="Operational Action Plan 13-168",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_168",
        time_of_occurrence_min=768,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_08"
    ),
    "PLAN_P13_0169": IncidentContingencyPlan(
        plan_id="PLAN_P13_0169",
        title="Operational Action Plan 13-169",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P13_169",
        time_of_occurrence_min=769,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_09"
    ),
    "PLAN_P13_0170": IncidentContingencyPlan(
        plan_id="PLAN_P13_0170",
        title="Operational Action Plan 13-170",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P13_170",
        time_of_occurrence_min=770,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_00"
    ),
    "PLAN_P13_0171": IncidentContingencyPlan(
        plan_id="PLAN_P13_0171",
        title="Operational Action Plan 13-171",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P13_171",
        time_of_occurrence_min=771,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_01"
    ),
    "PLAN_P13_0172": IncidentContingencyPlan(
        plan_id="PLAN_P13_0172",
        title="Operational Action Plan 13-172",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P13_172",
        time_of_occurrence_min=772,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_02"
    ),
    "PLAN_P13_0173": IncidentContingencyPlan(
        plan_id="PLAN_P13_0173",
        title="Operational Action Plan 13-173",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P13_173",
        time_of_occurrence_min=773,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_03"
    ),
    "PLAN_P13_0174": IncidentContingencyPlan(
        plan_id="PLAN_P13_0174",
        title="Operational Action Plan 13-174",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P13_174",
        time_of_occurrence_min=774,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_13_04"
    ),
}
