"""Railway Incident Contingency Action Plans Part 006."""

from dataclasses import dataclass
from typing import Dict

@dataclass
class IncidentContingencyPlan:
    plan_id: str
    title: str
    incident_type: str
    affected_block_id: str
    time_of_occurrence_min: int
    expected_clearance_min: int
    severity_score: int
    primary_dispatch_action: str
    contingency_corridor_id: str

INCIDENT_CONTINGENCY_PLANS_006: Dict[str, IncidentContingencyPlan] = {
    "PLAN_P06_0001": IncidentContingencyPlan(
        plan_id="PLAN_P06_0001",
        title="Operational Action Plan 6-1",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_001",
        time_of_occurrence_min=601,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0002": IncidentContingencyPlan(
        plan_id="PLAN_P06_0002",
        title="Operational Action Plan 6-2",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_002",
        time_of_occurrence_min=602,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0003": IncidentContingencyPlan(
        plan_id="PLAN_P06_0003",
        title="Operational Action Plan 6-3",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_003",
        time_of_occurrence_min=603,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0004": IncidentContingencyPlan(
        plan_id="PLAN_P06_0004",
        title="Operational Action Plan 6-4",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_004",
        time_of_occurrence_min=604,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0005": IncidentContingencyPlan(
        plan_id="PLAN_P06_0005",
        title="Operational Action Plan 6-5",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_005",
        time_of_occurrence_min=605,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0006": IncidentContingencyPlan(
        plan_id="PLAN_P06_0006",
        title="Operational Action Plan 6-6",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_006",
        time_of_occurrence_min=606,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0007": IncidentContingencyPlan(
        plan_id="PLAN_P06_0007",
        title="Operational Action Plan 6-7",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_007",
        time_of_occurrence_min=607,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0008": IncidentContingencyPlan(
        plan_id="PLAN_P06_0008",
        title="Operational Action Plan 6-8",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_008",
        time_of_occurrence_min=608,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0009": IncidentContingencyPlan(
        plan_id="PLAN_P06_0009",
        title="Operational Action Plan 6-9",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_009",
        time_of_occurrence_min=609,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0010": IncidentContingencyPlan(
        plan_id="PLAN_P06_0010",
        title="Operational Action Plan 6-10",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_010",
        time_of_occurrence_min=610,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0011": IncidentContingencyPlan(
        plan_id="PLAN_P06_0011",
        title="Operational Action Plan 6-11",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_011",
        time_of_occurrence_min=611,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0012": IncidentContingencyPlan(
        plan_id="PLAN_P06_0012",
        title="Operational Action Plan 6-12",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_012",
        time_of_occurrence_min=612,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0013": IncidentContingencyPlan(
        plan_id="PLAN_P06_0013",
        title="Operational Action Plan 6-13",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_013",
        time_of_occurrence_min=613,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0014": IncidentContingencyPlan(
        plan_id="PLAN_P06_0014",
        title="Operational Action Plan 6-14",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_014",
        time_of_occurrence_min=614,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0015": IncidentContingencyPlan(
        plan_id="PLAN_P06_0015",
        title="Operational Action Plan 6-15",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_015",
        time_of_occurrence_min=615,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0016": IncidentContingencyPlan(
        plan_id="PLAN_P06_0016",
        title="Operational Action Plan 6-16",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_016",
        time_of_occurrence_min=616,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0017": IncidentContingencyPlan(
        plan_id="PLAN_P06_0017",
        title="Operational Action Plan 6-17",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_017",
        time_of_occurrence_min=617,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0018": IncidentContingencyPlan(
        plan_id="PLAN_P06_0018",
        title="Operational Action Plan 6-18",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_018",
        time_of_occurrence_min=618,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0019": IncidentContingencyPlan(
        plan_id="PLAN_P06_0019",
        title="Operational Action Plan 6-19",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_019",
        time_of_occurrence_min=619,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0020": IncidentContingencyPlan(
        plan_id="PLAN_P06_0020",
        title="Operational Action Plan 6-20",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_020",
        time_of_occurrence_min=620,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0021": IncidentContingencyPlan(
        plan_id="PLAN_P06_0021",
        title="Operational Action Plan 6-21",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_021",
        time_of_occurrence_min=621,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0022": IncidentContingencyPlan(
        plan_id="PLAN_P06_0022",
        title="Operational Action Plan 6-22",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_022",
        time_of_occurrence_min=622,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0023": IncidentContingencyPlan(
        plan_id="PLAN_P06_0023",
        title="Operational Action Plan 6-23",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_023",
        time_of_occurrence_min=623,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0024": IncidentContingencyPlan(
        plan_id="PLAN_P06_0024",
        title="Operational Action Plan 6-24",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_024",
        time_of_occurrence_min=624,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0025": IncidentContingencyPlan(
        plan_id="PLAN_P06_0025",
        title="Operational Action Plan 6-25",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_025",
        time_of_occurrence_min=625,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0026": IncidentContingencyPlan(
        plan_id="PLAN_P06_0026",
        title="Operational Action Plan 6-26",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_026",
        time_of_occurrence_min=626,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0027": IncidentContingencyPlan(
        plan_id="PLAN_P06_0027",
        title="Operational Action Plan 6-27",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_027",
        time_of_occurrence_min=627,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0028": IncidentContingencyPlan(
        plan_id="PLAN_P06_0028",
        title="Operational Action Plan 6-28",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_028",
        time_of_occurrence_min=628,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0029": IncidentContingencyPlan(
        plan_id="PLAN_P06_0029",
        title="Operational Action Plan 6-29",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_029",
        time_of_occurrence_min=629,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0030": IncidentContingencyPlan(
        plan_id="PLAN_P06_0030",
        title="Operational Action Plan 6-30",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_030",
        time_of_occurrence_min=630,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0031": IncidentContingencyPlan(
        plan_id="PLAN_P06_0031",
        title="Operational Action Plan 6-31",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_031",
        time_of_occurrence_min=631,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0032": IncidentContingencyPlan(
        plan_id="PLAN_P06_0032",
        title="Operational Action Plan 6-32",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_032",
        time_of_occurrence_min=632,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0033": IncidentContingencyPlan(
        plan_id="PLAN_P06_0033",
        title="Operational Action Plan 6-33",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_033",
        time_of_occurrence_min=633,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0034": IncidentContingencyPlan(
        plan_id="PLAN_P06_0034",
        title="Operational Action Plan 6-34",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_034",
        time_of_occurrence_min=634,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0035": IncidentContingencyPlan(
        plan_id="PLAN_P06_0035",
        title="Operational Action Plan 6-35",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_035",
        time_of_occurrence_min=635,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0036": IncidentContingencyPlan(
        plan_id="PLAN_P06_0036",
        title="Operational Action Plan 6-36",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_036",
        time_of_occurrence_min=636,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0037": IncidentContingencyPlan(
        plan_id="PLAN_P06_0037",
        title="Operational Action Plan 6-37",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_037",
        time_of_occurrence_min=637,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0038": IncidentContingencyPlan(
        plan_id="PLAN_P06_0038",
        title="Operational Action Plan 6-38",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_038",
        time_of_occurrence_min=638,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0039": IncidentContingencyPlan(
        plan_id="PLAN_P06_0039",
        title="Operational Action Plan 6-39",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_039",
        time_of_occurrence_min=639,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0040": IncidentContingencyPlan(
        plan_id="PLAN_P06_0040",
        title="Operational Action Plan 6-40",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_040",
        time_of_occurrence_min=640,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0041": IncidentContingencyPlan(
        plan_id="PLAN_P06_0041",
        title="Operational Action Plan 6-41",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_041",
        time_of_occurrence_min=641,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0042": IncidentContingencyPlan(
        plan_id="PLAN_P06_0042",
        title="Operational Action Plan 6-42",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_042",
        time_of_occurrence_min=642,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0043": IncidentContingencyPlan(
        plan_id="PLAN_P06_0043",
        title="Operational Action Plan 6-43",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_043",
        time_of_occurrence_min=643,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0044": IncidentContingencyPlan(
        plan_id="PLAN_P06_0044",
        title="Operational Action Plan 6-44",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_044",
        time_of_occurrence_min=644,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0045": IncidentContingencyPlan(
        plan_id="PLAN_P06_0045",
        title="Operational Action Plan 6-45",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_045",
        time_of_occurrence_min=645,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0046": IncidentContingencyPlan(
        plan_id="PLAN_P06_0046",
        title="Operational Action Plan 6-46",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_046",
        time_of_occurrence_min=646,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0047": IncidentContingencyPlan(
        plan_id="PLAN_P06_0047",
        title="Operational Action Plan 6-47",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_047",
        time_of_occurrence_min=647,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0048": IncidentContingencyPlan(
        plan_id="PLAN_P06_0048",
        title="Operational Action Plan 6-48",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_048",
        time_of_occurrence_min=648,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0049": IncidentContingencyPlan(
        plan_id="PLAN_P06_0049",
        title="Operational Action Plan 6-49",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_049",
        time_of_occurrence_min=649,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0050": IncidentContingencyPlan(
        plan_id="PLAN_P06_0050",
        title="Operational Action Plan 6-50",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_050",
        time_of_occurrence_min=650,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0051": IncidentContingencyPlan(
        plan_id="PLAN_P06_0051",
        title="Operational Action Plan 6-51",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_051",
        time_of_occurrence_min=651,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0052": IncidentContingencyPlan(
        plan_id="PLAN_P06_0052",
        title="Operational Action Plan 6-52",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_052",
        time_of_occurrence_min=652,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0053": IncidentContingencyPlan(
        plan_id="PLAN_P06_0053",
        title="Operational Action Plan 6-53",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_053",
        time_of_occurrence_min=653,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0054": IncidentContingencyPlan(
        plan_id="PLAN_P06_0054",
        title="Operational Action Plan 6-54",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_054",
        time_of_occurrence_min=654,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0055": IncidentContingencyPlan(
        plan_id="PLAN_P06_0055",
        title="Operational Action Plan 6-55",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_055",
        time_of_occurrence_min=655,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0056": IncidentContingencyPlan(
        plan_id="PLAN_P06_0056",
        title="Operational Action Plan 6-56",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_056",
        time_of_occurrence_min=656,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0057": IncidentContingencyPlan(
        plan_id="PLAN_P06_0057",
        title="Operational Action Plan 6-57",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_057",
        time_of_occurrence_min=657,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0058": IncidentContingencyPlan(
        plan_id="PLAN_P06_0058",
        title="Operational Action Plan 6-58",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_058",
        time_of_occurrence_min=658,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0059": IncidentContingencyPlan(
        plan_id="PLAN_P06_0059",
        title="Operational Action Plan 6-59",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_059",
        time_of_occurrence_min=659,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0060": IncidentContingencyPlan(
        plan_id="PLAN_P06_0060",
        title="Operational Action Plan 6-60",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_060",
        time_of_occurrence_min=660,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0061": IncidentContingencyPlan(
        plan_id="PLAN_P06_0061",
        title="Operational Action Plan 6-61",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_061",
        time_of_occurrence_min=661,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0062": IncidentContingencyPlan(
        plan_id="PLAN_P06_0062",
        title="Operational Action Plan 6-62",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_062",
        time_of_occurrence_min=662,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0063": IncidentContingencyPlan(
        plan_id="PLAN_P06_0063",
        title="Operational Action Plan 6-63",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_063",
        time_of_occurrence_min=663,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0064": IncidentContingencyPlan(
        plan_id="PLAN_P06_0064",
        title="Operational Action Plan 6-64",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_064",
        time_of_occurrence_min=664,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0065": IncidentContingencyPlan(
        plan_id="PLAN_P06_0065",
        title="Operational Action Plan 6-65",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_065",
        time_of_occurrence_min=665,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0066": IncidentContingencyPlan(
        plan_id="PLAN_P06_0066",
        title="Operational Action Plan 6-66",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_066",
        time_of_occurrence_min=666,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0067": IncidentContingencyPlan(
        plan_id="PLAN_P06_0067",
        title="Operational Action Plan 6-67",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_067",
        time_of_occurrence_min=667,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0068": IncidentContingencyPlan(
        plan_id="PLAN_P06_0068",
        title="Operational Action Plan 6-68",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_068",
        time_of_occurrence_min=668,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0069": IncidentContingencyPlan(
        plan_id="PLAN_P06_0069",
        title="Operational Action Plan 6-69",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_069",
        time_of_occurrence_min=669,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0070": IncidentContingencyPlan(
        plan_id="PLAN_P06_0070",
        title="Operational Action Plan 6-70",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_070",
        time_of_occurrence_min=670,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0071": IncidentContingencyPlan(
        plan_id="PLAN_P06_0071",
        title="Operational Action Plan 6-71",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_071",
        time_of_occurrence_min=671,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0072": IncidentContingencyPlan(
        plan_id="PLAN_P06_0072",
        title="Operational Action Plan 6-72",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_072",
        time_of_occurrence_min=672,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0073": IncidentContingencyPlan(
        plan_id="PLAN_P06_0073",
        title="Operational Action Plan 6-73",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_073",
        time_of_occurrence_min=673,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0074": IncidentContingencyPlan(
        plan_id="PLAN_P06_0074",
        title="Operational Action Plan 6-74",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_074",
        time_of_occurrence_min=674,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0075": IncidentContingencyPlan(
        plan_id="PLAN_P06_0075",
        title="Operational Action Plan 6-75",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_075",
        time_of_occurrence_min=675,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0076": IncidentContingencyPlan(
        plan_id="PLAN_P06_0076",
        title="Operational Action Plan 6-76",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_076",
        time_of_occurrence_min=676,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0077": IncidentContingencyPlan(
        plan_id="PLAN_P06_0077",
        title="Operational Action Plan 6-77",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_077",
        time_of_occurrence_min=677,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0078": IncidentContingencyPlan(
        plan_id="PLAN_P06_0078",
        title="Operational Action Plan 6-78",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_078",
        time_of_occurrence_min=678,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0079": IncidentContingencyPlan(
        plan_id="PLAN_P06_0079",
        title="Operational Action Plan 6-79",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_079",
        time_of_occurrence_min=679,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0080": IncidentContingencyPlan(
        plan_id="PLAN_P06_0080",
        title="Operational Action Plan 6-80",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_080",
        time_of_occurrence_min=680,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0081": IncidentContingencyPlan(
        plan_id="PLAN_P06_0081",
        title="Operational Action Plan 6-81",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_081",
        time_of_occurrence_min=681,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0082": IncidentContingencyPlan(
        plan_id="PLAN_P06_0082",
        title="Operational Action Plan 6-82",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_082",
        time_of_occurrence_min=682,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0083": IncidentContingencyPlan(
        plan_id="PLAN_P06_0083",
        title="Operational Action Plan 6-83",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_083",
        time_of_occurrence_min=683,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0084": IncidentContingencyPlan(
        plan_id="PLAN_P06_0084",
        title="Operational Action Plan 6-84",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_084",
        time_of_occurrence_min=684,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0085": IncidentContingencyPlan(
        plan_id="PLAN_P06_0085",
        title="Operational Action Plan 6-85",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_085",
        time_of_occurrence_min=685,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0086": IncidentContingencyPlan(
        plan_id="PLAN_P06_0086",
        title="Operational Action Plan 6-86",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_086",
        time_of_occurrence_min=686,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0087": IncidentContingencyPlan(
        plan_id="PLAN_P06_0087",
        title="Operational Action Plan 6-87",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_087",
        time_of_occurrence_min=687,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0088": IncidentContingencyPlan(
        plan_id="PLAN_P06_0088",
        title="Operational Action Plan 6-88",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_088",
        time_of_occurrence_min=688,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0089": IncidentContingencyPlan(
        plan_id="PLAN_P06_0089",
        title="Operational Action Plan 6-89",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_089",
        time_of_occurrence_min=689,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0090": IncidentContingencyPlan(
        plan_id="PLAN_P06_0090",
        title="Operational Action Plan 6-90",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_090",
        time_of_occurrence_min=690,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0091": IncidentContingencyPlan(
        plan_id="PLAN_P06_0091",
        title="Operational Action Plan 6-91",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_091",
        time_of_occurrence_min=691,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0092": IncidentContingencyPlan(
        plan_id="PLAN_P06_0092",
        title="Operational Action Plan 6-92",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_092",
        time_of_occurrence_min=692,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0093": IncidentContingencyPlan(
        plan_id="PLAN_P06_0093",
        title="Operational Action Plan 6-93",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_093",
        time_of_occurrence_min=693,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0094": IncidentContingencyPlan(
        plan_id="PLAN_P06_0094",
        title="Operational Action Plan 6-94",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_094",
        time_of_occurrence_min=694,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0095": IncidentContingencyPlan(
        plan_id="PLAN_P06_0095",
        title="Operational Action Plan 6-95",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_095",
        time_of_occurrence_min=695,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0096": IncidentContingencyPlan(
        plan_id="PLAN_P06_0096",
        title="Operational Action Plan 6-96",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_096",
        time_of_occurrence_min=696,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0097": IncidentContingencyPlan(
        plan_id="PLAN_P06_0097",
        title="Operational Action Plan 6-97",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_097",
        time_of_occurrence_min=697,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0098": IncidentContingencyPlan(
        plan_id="PLAN_P06_0098",
        title="Operational Action Plan 6-98",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_098",
        time_of_occurrence_min=698,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0099": IncidentContingencyPlan(
        plan_id="PLAN_P06_0099",
        title="Operational Action Plan 6-99",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_099",
        time_of_occurrence_min=699,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0100": IncidentContingencyPlan(
        plan_id="PLAN_P06_0100",
        title="Operational Action Plan 6-100",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_100",
        time_of_occurrence_min=700,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0101": IncidentContingencyPlan(
        plan_id="PLAN_P06_0101",
        title="Operational Action Plan 6-101",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_101",
        time_of_occurrence_min=701,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0102": IncidentContingencyPlan(
        plan_id="PLAN_P06_0102",
        title="Operational Action Plan 6-102",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_102",
        time_of_occurrence_min=702,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0103": IncidentContingencyPlan(
        plan_id="PLAN_P06_0103",
        title="Operational Action Plan 6-103",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_103",
        time_of_occurrence_min=703,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0104": IncidentContingencyPlan(
        plan_id="PLAN_P06_0104",
        title="Operational Action Plan 6-104",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_104",
        time_of_occurrence_min=704,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0105": IncidentContingencyPlan(
        plan_id="PLAN_P06_0105",
        title="Operational Action Plan 6-105",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_105",
        time_of_occurrence_min=705,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0106": IncidentContingencyPlan(
        plan_id="PLAN_P06_0106",
        title="Operational Action Plan 6-106",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_106",
        time_of_occurrence_min=706,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0107": IncidentContingencyPlan(
        plan_id="PLAN_P06_0107",
        title="Operational Action Plan 6-107",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_107",
        time_of_occurrence_min=707,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0108": IncidentContingencyPlan(
        plan_id="PLAN_P06_0108",
        title="Operational Action Plan 6-108",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_108",
        time_of_occurrence_min=708,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0109": IncidentContingencyPlan(
        plan_id="PLAN_P06_0109",
        title="Operational Action Plan 6-109",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_109",
        time_of_occurrence_min=709,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0110": IncidentContingencyPlan(
        plan_id="PLAN_P06_0110",
        title="Operational Action Plan 6-110",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_110",
        time_of_occurrence_min=710,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0111": IncidentContingencyPlan(
        plan_id="PLAN_P06_0111",
        title="Operational Action Plan 6-111",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_111",
        time_of_occurrence_min=711,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0112": IncidentContingencyPlan(
        plan_id="PLAN_P06_0112",
        title="Operational Action Plan 6-112",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_112",
        time_of_occurrence_min=712,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0113": IncidentContingencyPlan(
        plan_id="PLAN_P06_0113",
        title="Operational Action Plan 6-113",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_113",
        time_of_occurrence_min=713,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0114": IncidentContingencyPlan(
        plan_id="PLAN_P06_0114",
        title="Operational Action Plan 6-114",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_114",
        time_of_occurrence_min=714,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0115": IncidentContingencyPlan(
        plan_id="PLAN_P06_0115",
        title="Operational Action Plan 6-115",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_115",
        time_of_occurrence_min=715,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0116": IncidentContingencyPlan(
        plan_id="PLAN_P06_0116",
        title="Operational Action Plan 6-116",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_116",
        time_of_occurrence_min=716,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0117": IncidentContingencyPlan(
        plan_id="PLAN_P06_0117",
        title="Operational Action Plan 6-117",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_117",
        time_of_occurrence_min=717,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0118": IncidentContingencyPlan(
        plan_id="PLAN_P06_0118",
        title="Operational Action Plan 6-118",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_118",
        time_of_occurrence_min=718,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0119": IncidentContingencyPlan(
        plan_id="PLAN_P06_0119",
        title="Operational Action Plan 6-119",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_119",
        time_of_occurrence_min=719,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0120": IncidentContingencyPlan(
        plan_id="PLAN_P06_0120",
        title="Operational Action Plan 6-120",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_120",
        time_of_occurrence_min=720,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0121": IncidentContingencyPlan(
        plan_id="PLAN_P06_0121",
        title="Operational Action Plan 6-121",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_121",
        time_of_occurrence_min=721,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0122": IncidentContingencyPlan(
        plan_id="PLAN_P06_0122",
        title="Operational Action Plan 6-122",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_122",
        time_of_occurrence_min=722,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0123": IncidentContingencyPlan(
        plan_id="PLAN_P06_0123",
        title="Operational Action Plan 6-123",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_123",
        time_of_occurrence_min=723,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0124": IncidentContingencyPlan(
        plan_id="PLAN_P06_0124",
        title="Operational Action Plan 6-124",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_124",
        time_of_occurrence_min=724,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0125": IncidentContingencyPlan(
        plan_id="PLAN_P06_0125",
        title="Operational Action Plan 6-125",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_125",
        time_of_occurrence_min=725,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0126": IncidentContingencyPlan(
        plan_id="PLAN_P06_0126",
        title="Operational Action Plan 6-126",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_126",
        time_of_occurrence_min=726,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0127": IncidentContingencyPlan(
        plan_id="PLAN_P06_0127",
        title="Operational Action Plan 6-127",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_127",
        time_of_occurrence_min=727,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0128": IncidentContingencyPlan(
        plan_id="PLAN_P06_0128",
        title="Operational Action Plan 6-128",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_128",
        time_of_occurrence_min=728,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0129": IncidentContingencyPlan(
        plan_id="PLAN_P06_0129",
        title="Operational Action Plan 6-129",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_129",
        time_of_occurrence_min=729,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0130": IncidentContingencyPlan(
        plan_id="PLAN_P06_0130",
        title="Operational Action Plan 6-130",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_130",
        time_of_occurrence_min=730,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0131": IncidentContingencyPlan(
        plan_id="PLAN_P06_0131",
        title="Operational Action Plan 6-131",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_131",
        time_of_occurrence_min=731,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0132": IncidentContingencyPlan(
        plan_id="PLAN_P06_0132",
        title="Operational Action Plan 6-132",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_132",
        time_of_occurrence_min=732,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0133": IncidentContingencyPlan(
        plan_id="PLAN_P06_0133",
        title="Operational Action Plan 6-133",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_133",
        time_of_occurrence_min=733,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0134": IncidentContingencyPlan(
        plan_id="PLAN_P06_0134",
        title="Operational Action Plan 6-134",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_134",
        time_of_occurrence_min=734,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0135": IncidentContingencyPlan(
        plan_id="PLAN_P06_0135",
        title="Operational Action Plan 6-135",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_135",
        time_of_occurrence_min=735,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0136": IncidentContingencyPlan(
        plan_id="PLAN_P06_0136",
        title="Operational Action Plan 6-136",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_136",
        time_of_occurrence_min=736,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0137": IncidentContingencyPlan(
        plan_id="PLAN_P06_0137",
        title="Operational Action Plan 6-137",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_137",
        time_of_occurrence_min=737,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0138": IncidentContingencyPlan(
        plan_id="PLAN_P06_0138",
        title="Operational Action Plan 6-138",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_138",
        time_of_occurrence_min=738,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0139": IncidentContingencyPlan(
        plan_id="PLAN_P06_0139",
        title="Operational Action Plan 6-139",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_139",
        time_of_occurrence_min=739,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0140": IncidentContingencyPlan(
        plan_id="PLAN_P06_0140",
        title="Operational Action Plan 6-140",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_140",
        time_of_occurrence_min=740,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0141": IncidentContingencyPlan(
        plan_id="PLAN_P06_0141",
        title="Operational Action Plan 6-141",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_141",
        time_of_occurrence_min=741,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0142": IncidentContingencyPlan(
        plan_id="PLAN_P06_0142",
        title="Operational Action Plan 6-142",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_142",
        time_of_occurrence_min=742,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0143": IncidentContingencyPlan(
        plan_id="PLAN_P06_0143",
        title="Operational Action Plan 6-143",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_143",
        time_of_occurrence_min=743,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0144": IncidentContingencyPlan(
        plan_id="PLAN_P06_0144",
        title="Operational Action Plan 6-144",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_144",
        time_of_occurrence_min=744,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0145": IncidentContingencyPlan(
        plan_id="PLAN_P06_0145",
        title="Operational Action Plan 6-145",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_145",
        time_of_occurrence_min=745,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0146": IncidentContingencyPlan(
        plan_id="PLAN_P06_0146",
        title="Operational Action Plan 6-146",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_146",
        time_of_occurrence_min=746,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0147": IncidentContingencyPlan(
        plan_id="PLAN_P06_0147",
        title="Operational Action Plan 6-147",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_147",
        time_of_occurrence_min=747,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0148": IncidentContingencyPlan(
        plan_id="PLAN_P06_0148",
        title="Operational Action Plan 6-148",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_148",
        time_of_occurrence_min=748,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0149": IncidentContingencyPlan(
        plan_id="PLAN_P06_0149",
        title="Operational Action Plan 6-149",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_149",
        time_of_occurrence_min=749,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0150": IncidentContingencyPlan(
        plan_id="PLAN_P06_0150",
        title="Operational Action Plan 6-150",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_150",
        time_of_occurrence_min=750,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0151": IncidentContingencyPlan(
        plan_id="PLAN_P06_0151",
        title="Operational Action Plan 6-151",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_151",
        time_of_occurrence_min=751,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0152": IncidentContingencyPlan(
        plan_id="PLAN_P06_0152",
        title="Operational Action Plan 6-152",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_152",
        time_of_occurrence_min=752,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0153": IncidentContingencyPlan(
        plan_id="PLAN_P06_0153",
        title="Operational Action Plan 6-153",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_153",
        time_of_occurrence_min=753,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0154": IncidentContingencyPlan(
        plan_id="PLAN_P06_0154",
        title="Operational Action Plan 6-154",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_154",
        time_of_occurrence_min=754,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0155": IncidentContingencyPlan(
        plan_id="PLAN_P06_0155",
        title="Operational Action Plan 6-155",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_155",
        time_of_occurrence_min=755,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0156": IncidentContingencyPlan(
        plan_id="PLAN_P06_0156",
        title="Operational Action Plan 6-156",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_156",
        time_of_occurrence_min=756,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0157": IncidentContingencyPlan(
        plan_id="PLAN_P06_0157",
        title="Operational Action Plan 6-157",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_157",
        time_of_occurrence_min=757,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0158": IncidentContingencyPlan(
        plan_id="PLAN_P06_0158",
        title="Operational Action Plan 6-158",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_158",
        time_of_occurrence_min=758,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0159": IncidentContingencyPlan(
        plan_id="PLAN_P06_0159",
        title="Operational Action Plan 6-159",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_159",
        time_of_occurrence_min=759,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0160": IncidentContingencyPlan(
        plan_id="PLAN_P06_0160",
        title="Operational Action Plan 6-160",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_160",
        time_of_occurrence_min=760,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0161": IncidentContingencyPlan(
        plan_id="PLAN_P06_0161",
        title="Operational Action Plan 6-161",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_161",
        time_of_occurrence_min=761,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0162": IncidentContingencyPlan(
        plan_id="PLAN_P06_0162",
        title="Operational Action Plan 6-162",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_162",
        time_of_occurrence_min=762,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0163": IncidentContingencyPlan(
        plan_id="PLAN_P06_0163",
        title="Operational Action Plan 6-163",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_163",
        time_of_occurrence_min=763,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0164": IncidentContingencyPlan(
        plan_id="PLAN_P06_0164",
        title="Operational Action Plan 6-164",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_164",
        time_of_occurrence_min=764,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
    "PLAN_P06_0165": IncidentContingencyPlan(
        plan_id="PLAN_P06_0165",
        title="Operational Action Plan 6-165",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_165",
        time_of_occurrence_min=765,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_05"
    ),
    "PLAN_P06_0166": IncidentContingencyPlan(
        plan_id="PLAN_P06_0166",
        title="Operational Action Plan 6-166",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_166",
        time_of_occurrence_min=766,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_06"
    ),
    "PLAN_P06_0167": IncidentContingencyPlan(
        plan_id="PLAN_P06_0167",
        title="Operational Action Plan 6-167",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_167",
        time_of_occurrence_min=767,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_07"
    ),
    "PLAN_P06_0168": IncidentContingencyPlan(
        plan_id="PLAN_P06_0168",
        title="Operational Action Plan 6-168",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_168",
        time_of_occurrence_min=768,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_08"
    ),
    "PLAN_P06_0169": IncidentContingencyPlan(
        plan_id="PLAN_P06_0169",
        title="Operational Action Plan 6-169",
        incident_type="POINT_MOTOR_FAILURE",
        affected_block_id="BLK_P6_169",
        time_of_occurrence_min=769,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_09"
    ),
    "PLAN_P06_0170": IncidentContingencyPlan(
        plan_id="PLAN_P06_0170",
        title="Operational Action Plan 6-170",
        incident_type="RAIL_FRACTURE",
        affected_block_id="BLK_P6_170",
        time_of_occurrence_min=770,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_00"
    ),
    "PLAN_P06_0171": IncidentContingencyPlan(
        plan_id="PLAN_P06_0171",
        title="Operational Action Plan 6-171",
        incident_type="SIGNAL_ASPECT_FAILURE",
        affected_block_id="BLK_P6_171",
        time_of_occurrence_min=771,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_01"
    ),
    "PLAN_P06_0172": IncidentContingencyPlan(
        plan_id="PLAN_P06_0172",
        title="Operational Action Plan 6-172",
        incident_type="FLASHING_TAIL_LAMP",
        affected_block_id="BLK_P6_172",
        time_of_occurrence_min=772,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_02"
    ),
    "PLAN_P06_0173": IncidentContingencyPlan(
        plan_id="PLAN_P06_0173",
        title="Operational Action Plan 6-173",
        incident_type="HEAVY_RAIN_WATERLOG",
        affected_block_id="BLK_P6_173",
        time_of_occurrence_min=773,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_03"
    ),
    "PLAN_P06_0174": IncidentContingencyPlan(
        plan_id="PLAN_P06_0174",
        title="Operational Action Plan 6-174",
        incident_type="OHE_VOLTAGE_SAG",
        affected_block_id="BLK_P6_174",
        time_of_occurrence_min=774,
        expected_clearance_min=45,
        severity_score=4,
        primary_dispatch_action="HALT_APPROACHING_AND_REROUTE",
        contingency_corridor_id="CORRIDOR_ALT_06_04"
    ),
}
