"""Incident Contingency Action Plans - Modular Playbook Aggregator."""
from typing import Dict
from simulation.dispatching.contingency_plans.contingency_playbook_part_001 import IncidentContingencyPlan

INCIDENT_CONTINGENCY_PLANS: Dict[str, IncidentContingencyPlan] = {}

from simulation.dispatching.contingency_plans.contingency_playbook_part_001 import INCIDENT_CONTINGENCY_PLANS_001
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_001)
from simulation.dispatching.contingency_plans.contingency_playbook_part_002 import INCIDENT_CONTINGENCY_PLANS_002
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_002)
from simulation.dispatching.contingency_plans.contingency_playbook_part_003 import INCIDENT_CONTINGENCY_PLANS_003
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_003)
from simulation.dispatching.contingency_plans.contingency_playbook_part_004 import INCIDENT_CONTINGENCY_PLANS_004
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_004)
from simulation.dispatching.contingency_plans.contingency_playbook_part_005 import INCIDENT_CONTINGENCY_PLANS_005
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_005)
from simulation.dispatching.contingency_plans.contingency_playbook_part_006 import INCIDENT_CONTINGENCY_PLANS_006
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_006)
from simulation.dispatching.contingency_plans.contingency_playbook_part_007 import INCIDENT_CONTINGENCY_PLANS_007
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_007)
from simulation.dispatching.contingency_plans.contingency_playbook_part_008 import INCIDENT_CONTINGENCY_PLANS_008
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_008)
from simulation.dispatching.contingency_plans.contingency_playbook_part_009 import INCIDENT_CONTINGENCY_PLANS_009
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_009)
from simulation.dispatching.contingency_plans.contingency_playbook_part_010 import INCIDENT_CONTINGENCY_PLANS_010
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_010)
from simulation.dispatching.contingency_plans.contingency_playbook_part_011 import INCIDENT_CONTINGENCY_PLANS_011
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_011)
from simulation.dispatching.contingency_plans.contingency_playbook_part_012 import INCIDENT_CONTINGENCY_PLANS_012
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_012)
from simulation.dispatching.contingency_plans.contingency_playbook_part_013 import INCIDENT_CONTINGENCY_PLANS_013
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_013)
from simulation.dispatching.contingency_plans.contingency_playbook_part_014 import INCIDENT_CONTINGENCY_PLANS_014
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_014)
from simulation.dispatching.contingency_plans.contingency_playbook_part_015 import INCIDENT_CONTINGENCY_PLANS_015
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_015)
from simulation.dispatching.contingency_plans.contingency_playbook_part_016 import INCIDENT_CONTINGENCY_PLANS_016
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_016)
from simulation.dispatching.contingency_plans.contingency_playbook_part_017 import INCIDENT_CONTINGENCY_PLANS_017
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_017)
from simulation.dispatching.contingency_plans.contingency_playbook_part_018 import INCIDENT_CONTINGENCY_PLANS_018
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_018)
from simulation.dispatching.contingency_plans.contingency_playbook_part_019 import INCIDENT_CONTINGENCY_PLANS_019
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_019)
from simulation.dispatching.contingency_plans.contingency_playbook_part_020 import INCIDENT_CONTINGENCY_PLANS_020
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_020)
from simulation.dispatching.contingency_plans.contingency_playbook_part_021 import INCIDENT_CONTINGENCY_PLANS_021
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_021)
from simulation.dispatching.contingency_plans.contingency_playbook_part_022 import INCIDENT_CONTINGENCY_PLANS_022
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_022)
from simulation.dispatching.contingency_plans.contingency_playbook_part_023 import INCIDENT_CONTINGENCY_PLANS_023
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_023)
from simulation.dispatching.contingency_plans.contingency_playbook_part_024 import INCIDENT_CONTINGENCY_PLANS_024
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_024)
from simulation.dispatching.contingency_plans.contingency_playbook_part_025 import INCIDENT_CONTINGENCY_PLANS_025
INCIDENT_CONTINGENCY_PLANS.update(INCIDENT_CONTINGENCY_PLANS_025)
