"""Route Locking Safety Matrix Partition 033."""

from dataclasses import dataclass
from typing import List, Dict

@dataclass
class RouteLockingRule:
    route_id: str
    entry_signal: str
    exit_signal: str
    points_normal: List[str]
    points_reverse: List[str]
    conflicting_routes: List[str]
    flank_protection_points: List[str]
    track_circuits_in_route: List[str]
    approach_locking_timeout_sec: int
    overlap_track_circuits: List[str]
    permissible_aspect: str

ROUTE_LOCKING_MATRIX_033: Dict[str, RouteLockingRule] = {
    "ROUTE_P33_0001": RouteLockingRule(
        route_id="ROUTE_P33_0001",
        entry_signal="SIG_P33_1_ENTRY",
        exit_signal="SIG_P33_1_EXIT",
        points_normal=["PT_001_N"],
        points_reverse=["PT_002_R"],
        conflicting_routes=["ROUTE_P33_0006"],
        flank_protection_points=["FLANK_PT_001"],
        track_circuits_in_route=["TC_P33_1_A", "TC_P33_1_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_001"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0002": RouteLockingRule(
        route_id="ROUTE_P33_0002",
        entry_signal="SIG_P33_2_ENTRY",
        exit_signal="SIG_P33_2_EXIT",
        points_normal=["PT_002_N"],
        points_reverse=["PT_003_R"],
        conflicting_routes=["ROUTE_P33_0007"],
        flank_protection_points=["FLANK_PT_002"],
        track_circuits_in_route=["TC_P33_2_A", "TC_P33_2_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_002"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0003": RouteLockingRule(
        route_id="ROUTE_P33_0003",
        entry_signal="SIG_P33_3_ENTRY",
        exit_signal="SIG_P33_3_EXIT",
        points_normal=["PT_003_N"],
        points_reverse=["PT_004_R"],
        conflicting_routes=["ROUTE_P33_0008"],
        flank_protection_points=["FLANK_PT_003"],
        track_circuits_in_route=["TC_P33_3_A", "TC_P33_3_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_003"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0004": RouteLockingRule(
        route_id="ROUTE_P33_0004",
        entry_signal="SIG_P33_4_ENTRY",
        exit_signal="SIG_P33_4_EXIT",
        points_normal=["PT_004_N"],
        points_reverse=["PT_005_R"],
        conflicting_routes=["ROUTE_P33_0009"],
        flank_protection_points=["FLANK_PT_004"],
        track_circuits_in_route=["TC_P33_4_A", "TC_P33_4_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_004"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0005": RouteLockingRule(
        route_id="ROUTE_P33_0005",
        entry_signal="SIG_P33_5_ENTRY",
        exit_signal="SIG_P33_5_EXIT",
        points_normal=["PT_005_N"],
        points_reverse=["PT_006_R"],
        conflicting_routes=["ROUTE_P33_0010"],
        flank_protection_points=["FLANK_PT_005"],
        track_circuits_in_route=["TC_P33_5_A", "TC_P33_5_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_005"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0006": RouteLockingRule(
        route_id="ROUTE_P33_0006",
        entry_signal="SIG_P33_6_ENTRY",
        exit_signal="SIG_P33_6_EXIT",
        points_normal=["PT_006_N"],
        points_reverse=["PT_007_R"],
        conflicting_routes=["ROUTE_P33_0011"],
        flank_protection_points=["FLANK_PT_006"],
        track_circuits_in_route=["TC_P33_6_A", "TC_P33_6_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_006"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0007": RouteLockingRule(
        route_id="ROUTE_P33_0007",
        entry_signal="SIG_P33_7_ENTRY",
        exit_signal="SIG_P33_7_EXIT",
        points_normal=["PT_007_N"],
        points_reverse=["PT_008_R"],
        conflicting_routes=["ROUTE_P33_0012"],
        flank_protection_points=["FLANK_PT_007"],
        track_circuits_in_route=["TC_P33_7_A", "TC_P33_7_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_007"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0008": RouteLockingRule(
        route_id="ROUTE_P33_0008",
        entry_signal="SIG_P33_8_ENTRY",
        exit_signal="SIG_P33_8_EXIT",
        points_normal=["PT_008_N"],
        points_reverse=["PT_009_R"],
        conflicting_routes=["ROUTE_P33_0013"],
        flank_protection_points=["FLANK_PT_008"],
        track_circuits_in_route=["TC_P33_8_A", "TC_P33_8_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_008"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0009": RouteLockingRule(
        route_id="ROUTE_P33_0009",
        entry_signal="SIG_P33_9_ENTRY",
        exit_signal="SIG_P33_9_EXIT",
        points_normal=["PT_009_N"],
        points_reverse=["PT_010_R"],
        conflicting_routes=["ROUTE_P33_0014"],
        flank_protection_points=["FLANK_PT_009"],
        track_circuits_in_route=["TC_P33_9_A", "TC_P33_9_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_009"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0010": RouteLockingRule(
        route_id="ROUTE_P33_0010",
        entry_signal="SIG_P33_10_ENTRY",
        exit_signal="SIG_P33_10_EXIT",
        points_normal=["PT_010_N"],
        points_reverse=["PT_011_R"],
        conflicting_routes=["ROUTE_P33_0015"],
        flank_protection_points=["FLANK_PT_010"],
        track_circuits_in_route=["TC_P33_10_A", "TC_P33_10_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_010"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0011": RouteLockingRule(
        route_id="ROUTE_P33_0011",
        entry_signal="SIG_P33_11_ENTRY",
        exit_signal="SIG_P33_11_EXIT",
        points_normal=["PT_011_N"],
        points_reverse=["PT_012_R"],
        conflicting_routes=["ROUTE_P33_0016"],
        flank_protection_points=["FLANK_PT_011"],
        track_circuits_in_route=["TC_P33_11_A", "TC_P33_11_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_011"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0012": RouteLockingRule(
        route_id="ROUTE_P33_0012",
        entry_signal="SIG_P33_12_ENTRY",
        exit_signal="SIG_P33_12_EXIT",
        points_normal=["PT_012_N"],
        points_reverse=["PT_013_R"],
        conflicting_routes=["ROUTE_P33_0017"],
        flank_protection_points=["FLANK_PT_012"],
        track_circuits_in_route=["TC_P33_12_A", "TC_P33_12_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_012"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0013": RouteLockingRule(
        route_id="ROUTE_P33_0013",
        entry_signal="SIG_P33_13_ENTRY",
        exit_signal="SIG_P33_13_EXIT",
        points_normal=["PT_013_N"],
        points_reverse=["PT_014_R"],
        conflicting_routes=["ROUTE_P33_0018"],
        flank_protection_points=["FLANK_PT_013"],
        track_circuits_in_route=["TC_P33_13_A", "TC_P33_13_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_013"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0014": RouteLockingRule(
        route_id="ROUTE_P33_0014",
        entry_signal="SIG_P33_14_ENTRY",
        exit_signal="SIG_P33_14_EXIT",
        points_normal=["PT_014_N"],
        points_reverse=["PT_015_R"],
        conflicting_routes=["ROUTE_P33_0019"],
        flank_protection_points=["FLANK_PT_014"],
        track_circuits_in_route=["TC_P33_14_A", "TC_P33_14_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_014"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0015": RouteLockingRule(
        route_id="ROUTE_P33_0015",
        entry_signal="SIG_P33_15_ENTRY",
        exit_signal="SIG_P33_15_EXIT",
        points_normal=["PT_015_N"],
        points_reverse=["PT_016_R"],
        conflicting_routes=["ROUTE_P33_0020"],
        flank_protection_points=["FLANK_PT_015"],
        track_circuits_in_route=["TC_P33_15_A", "TC_P33_15_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_015"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0016": RouteLockingRule(
        route_id="ROUTE_P33_0016",
        entry_signal="SIG_P33_16_ENTRY",
        exit_signal="SIG_P33_16_EXIT",
        points_normal=["PT_016_N"],
        points_reverse=["PT_017_R"],
        conflicting_routes=["ROUTE_P33_0021"],
        flank_protection_points=["FLANK_PT_016"],
        track_circuits_in_route=["TC_P33_16_A", "TC_P33_16_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_016"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0017": RouteLockingRule(
        route_id="ROUTE_P33_0017",
        entry_signal="SIG_P33_17_ENTRY",
        exit_signal="SIG_P33_17_EXIT",
        points_normal=["PT_017_N"],
        points_reverse=["PT_018_R"],
        conflicting_routes=["ROUTE_P33_0022"],
        flank_protection_points=["FLANK_PT_017"],
        track_circuits_in_route=["TC_P33_17_A", "TC_P33_17_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_017"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0018": RouteLockingRule(
        route_id="ROUTE_P33_0018",
        entry_signal="SIG_P33_18_ENTRY",
        exit_signal="SIG_P33_18_EXIT",
        points_normal=["PT_018_N"],
        points_reverse=["PT_019_R"],
        conflicting_routes=["ROUTE_P33_0023"],
        flank_protection_points=["FLANK_PT_018"],
        track_circuits_in_route=["TC_P33_18_A", "TC_P33_18_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_018"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0019": RouteLockingRule(
        route_id="ROUTE_P33_0019",
        entry_signal="SIG_P33_19_ENTRY",
        exit_signal="SIG_P33_19_EXIT",
        points_normal=["PT_019_N"],
        points_reverse=["PT_020_R"],
        conflicting_routes=["ROUTE_P33_0024"],
        flank_protection_points=["FLANK_PT_019"],
        track_circuits_in_route=["TC_P33_19_A", "TC_P33_19_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_019"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0020": RouteLockingRule(
        route_id="ROUTE_P33_0020",
        entry_signal="SIG_P33_20_ENTRY",
        exit_signal="SIG_P33_20_EXIT",
        points_normal=["PT_020_N"],
        points_reverse=["PT_021_R"],
        conflicting_routes=["ROUTE_P33_0025"],
        flank_protection_points=["FLANK_PT_020"],
        track_circuits_in_route=["TC_P33_20_A", "TC_P33_20_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_020"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0021": RouteLockingRule(
        route_id="ROUTE_P33_0021",
        entry_signal="SIG_P33_21_ENTRY",
        exit_signal="SIG_P33_21_EXIT",
        points_normal=["PT_021_N"],
        points_reverse=["PT_022_R"],
        conflicting_routes=["ROUTE_P33_0026"],
        flank_protection_points=["FLANK_PT_021"],
        track_circuits_in_route=["TC_P33_21_A", "TC_P33_21_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_021"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0022": RouteLockingRule(
        route_id="ROUTE_P33_0022",
        entry_signal="SIG_P33_22_ENTRY",
        exit_signal="SIG_P33_22_EXIT",
        points_normal=["PT_022_N"],
        points_reverse=["PT_023_R"],
        conflicting_routes=["ROUTE_P33_0027"],
        flank_protection_points=["FLANK_PT_022"],
        track_circuits_in_route=["TC_P33_22_A", "TC_P33_22_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_022"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0023": RouteLockingRule(
        route_id="ROUTE_P33_0023",
        entry_signal="SIG_P33_23_ENTRY",
        exit_signal="SIG_P33_23_EXIT",
        points_normal=["PT_023_N"],
        points_reverse=["PT_024_R"],
        conflicting_routes=["ROUTE_P33_0028"],
        flank_protection_points=["FLANK_PT_023"],
        track_circuits_in_route=["TC_P33_23_A", "TC_P33_23_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_023"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0024": RouteLockingRule(
        route_id="ROUTE_P33_0024",
        entry_signal="SIG_P33_24_ENTRY",
        exit_signal="SIG_P33_24_EXIT",
        points_normal=["PT_024_N"],
        points_reverse=["PT_025_R"],
        conflicting_routes=["ROUTE_P33_0029"],
        flank_protection_points=["FLANK_PT_024"],
        track_circuits_in_route=["TC_P33_24_A", "TC_P33_24_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_024"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0025": RouteLockingRule(
        route_id="ROUTE_P33_0025",
        entry_signal="SIG_P33_25_ENTRY",
        exit_signal="SIG_P33_25_EXIT",
        points_normal=["PT_025_N"],
        points_reverse=["PT_026_R"],
        conflicting_routes=["ROUTE_P33_0030"],
        flank_protection_points=["FLANK_PT_025"],
        track_circuits_in_route=["TC_P33_25_A", "TC_P33_25_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_025"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0026": RouteLockingRule(
        route_id="ROUTE_P33_0026",
        entry_signal="SIG_P33_26_ENTRY",
        exit_signal="SIG_P33_26_EXIT",
        points_normal=["PT_026_N"],
        points_reverse=["PT_027_R"],
        conflicting_routes=["ROUTE_P33_0031"],
        flank_protection_points=["FLANK_PT_026"],
        track_circuits_in_route=["TC_P33_26_A", "TC_P33_26_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_026"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0027": RouteLockingRule(
        route_id="ROUTE_P33_0027",
        entry_signal="SIG_P33_27_ENTRY",
        exit_signal="SIG_P33_27_EXIT",
        points_normal=["PT_027_N"],
        points_reverse=["PT_028_R"],
        conflicting_routes=["ROUTE_P33_0032"],
        flank_protection_points=["FLANK_PT_027"],
        track_circuits_in_route=["TC_P33_27_A", "TC_P33_27_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_027"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0028": RouteLockingRule(
        route_id="ROUTE_P33_0028",
        entry_signal="SIG_P33_28_ENTRY",
        exit_signal="SIG_P33_28_EXIT",
        points_normal=["PT_028_N"],
        points_reverse=["PT_029_R"],
        conflicting_routes=["ROUTE_P33_0033"],
        flank_protection_points=["FLANK_PT_028"],
        track_circuits_in_route=["TC_P33_28_A", "TC_P33_28_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_028"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0029": RouteLockingRule(
        route_id="ROUTE_P33_0029",
        entry_signal="SIG_P33_29_ENTRY",
        exit_signal="SIG_P33_29_EXIT",
        points_normal=["PT_029_N"],
        points_reverse=["PT_030_R"],
        conflicting_routes=["ROUTE_P33_0034"],
        flank_protection_points=["FLANK_PT_029"],
        track_circuits_in_route=["TC_P33_29_A", "TC_P33_29_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_029"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0030": RouteLockingRule(
        route_id="ROUTE_P33_0030",
        entry_signal="SIG_P33_30_ENTRY",
        exit_signal="SIG_P33_30_EXIT",
        points_normal=["PT_030_N"],
        points_reverse=["PT_031_R"],
        conflicting_routes=["ROUTE_P33_0035"],
        flank_protection_points=["FLANK_PT_030"],
        track_circuits_in_route=["TC_P33_30_A", "TC_P33_30_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_030"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0031": RouteLockingRule(
        route_id="ROUTE_P33_0031",
        entry_signal="SIG_P33_31_ENTRY",
        exit_signal="SIG_P33_31_EXIT",
        points_normal=["PT_031_N"],
        points_reverse=["PT_032_R"],
        conflicting_routes=["ROUTE_P33_0036"],
        flank_protection_points=["FLANK_PT_031"],
        track_circuits_in_route=["TC_P33_31_A", "TC_P33_31_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_031"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0032": RouteLockingRule(
        route_id="ROUTE_P33_0032",
        entry_signal="SIG_P33_32_ENTRY",
        exit_signal="SIG_P33_32_EXIT",
        points_normal=["PT_032_N"],
        points_reverse=["PT_033_R"],
        conflicting_routes=["ROUTE_P33_0037"],
        flank_protection_points=["FLANK_PT_032"],
        track_circuits_in_route=["TC_P33_32_A", "TC_P33_32_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_032"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0033": RouteLockingRule(
        route_id="ROUTE_P33_0033",
        entry_signal="SIG_P33_33_ENTRY",
        exit_signal="SIG_P33_33_EXIT",
        points_normal=["PT_033_N"],
        points_reverse=["PT_034_R"],
        conflicting_routes=["ROUTE_P33_0038"],
        flank_protection_points=["FLANK_PT_033"],
        track_circuits_in_route=["TC_P33_33_A", "TC_P33_33_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_033"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0034": RouteLockingRule(
        route_id="ROUTE_P33_0034",
        entry_signal="SIG_P33_34_ENTRY",
        exit_signal="SIG_P33_34_EXIT",
        points_normal=["PT_034_N"],
        points_reverse=["PT_035_R"],
        conflicting_routes=["ROUTE_P33_0039"],
        flank_protection_points=["FLANK_PT_034"],
        track_circuits_in_route=["TC_P33_34_A", "TC_P33_34_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_034"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0035": RouteLockingRule(
        route_id="ROUTE_P33_0035",
        entry_signal="SIG_P33_35_ENTRY",
        exit_signal="SIG_P33_35_EXIT",
        points_normal=["PT_035_N"],
        points_reverse=["PT_036_R"],
        conflicting_routes=["ROUTE_P33_0040"],
        flank_protection_points=["FLANK_PT_035"],
        track_circuits_in_route=["TC_P33_35_A", "TC_P33_35_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_035"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0036": RouteLockingRule(
        route_id="ROUTE_P33_0036",
        entry_signal="SIG_P33_36_ENTRY",
        exit_signal="SIG_P33_36_EXIT",
        points_normal=["PT_036_N"],
        points_reverse=["PT_037_R"],
        conflicting_routes=["ROUTE_P33_0041"],
        flank_protection_points=["FLANK_PT_036"],
        track_circuits_in_route=["TC_P33_36_A", "TC_P33_36_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_036"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0037": RouteLockingRule(
        route_id="ROUTE_P33_0037",
        entry_signal="SIG_P33_37_ENTRY",
        exit_signal="SIG_P33_37_EXIT",
        points_normal=["PT_037_N"],
        points_reverse=["PT_038_R"],
        conflicting_routes=["ROUTE_P33_0042"],
        flank_protection_points=["FLANK_PT_037"],
        track_circuits_in_route=["TC_P33_37_A", "TC_P33_37_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_037"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0038": RouteLockingRule(
        route_id="ROUTE_P33_0038",
        entry_signal="SIG_P33_38_ENTRY",
        exit_signal="SIG_P33_38_EXIT",
        points_normal=["PT_038_N"],
        points_reverse=["PT_039_R"],
        conflicting_routes=["ROUTE_P33_0043"],
        flank_protection_points=["FLANK_PT_038"],
        track_circuits_in_route=["TC_P33_38_A", "TC_P33_38_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_038"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0039": RouteLockingRule(
        route_id="ROUTE_P33_0039",
        entry_signal="SIG_P33_39_ENTRY",
        exit_signal="SIG_P33_39_EXIT",
        points_normal=["PT_039_N"],
        points_reverse=["PT_040_R"],
        conflicting_routes=["ROUTE_P33_0044"],
        flank_protection_points=["FLANK_PT_039"],
        track_circuits_in_route=["TC_P33_39_A", "TC_P33_39_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_039"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0040": RouteLockingRule(
        route_id="ROUTE_P33_0040",
        entry_signal="SIG_P33_40_ENTRY",
        exit_signal="SIG_P33_40_EXIT",
        points_normal=["PT_040_N"],
        points_reverse=["PT_041_R"],
        conflicting_routes=["ROUTE_P33_0045"],
        flank_protection_points=["FLANK_PT_040"],
        track_circuits_in_route=["TC_P33_40_A", "TC_P33_40_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_040"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0041": RouteLockingRule(
        route_id="ROUTE_P33_0041",
        entry_signal="SIG_P33_41_ENTRY",
        exit_signal="SIG_P33_41_EXIT",
        points_normal=["PT_041_N"],
        points_reverse=["PT_042_R"],
        conflicting_routes=["ROUTE_P33_0046"],
        flank_protection_points=["FLANK_PT_041"],
        track_circuits_in_route=["TC_P33_41_A", "TC_P33_41_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_041"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0042": RouteLockingRule(
        route_id="ROUTE_P33_0042",
        entry_signal="SIG_P33_42_ENTRY",
        exit_signal="SIG_P33_42_EXIT",
        points_normal=["PT_042_N"],
        points_reverse=["PT_043_R"],
        conflicting_routes=["ROUTE_P33_0047"],
        flank_protection_points=["FLANK_PT_042"],
        track_circuits_in_route=["TC_P33_42_A", "TC_P33_42_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_042"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0043": RouteLockingRule(
        route_id="ROUTE_P33_0043",
        entry_signal="SIG_P33_43_ENTRY",
        exit_signal="SIG_P33_43_EXIT",
        points_normal=["PT_043_N"],
        points_reverse=["PT_044_R"],
        conflicting_routes=["ROUTE_P33_0048"],
        flank_protection_points=["FLANK_PT_043"],
        track_circuits_in_route=["TC_P33_43_A", "TC_P33_43_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_043"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0044": RouteLockingRule(
        route_id="ROUTE_P33_0044",
        entry_signal="SIG_P33_44_ENTRY",
        exit_signal="SIG_P33_44_EXIT",
        points_normal=["PT_044_N"],
        points_reverse=["PT_045_R"],
        conflicting_routes=["ROUTE_P33_0049"],
        flank_protection_points=["FLANK_PT_044"],
        track_circuits_in_route=["TC_P33_44_A", "TC_P33_44_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_044"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0045": RouteLockingRule(
        route_id="ROUTE_P33_0045",
        entry_signal="SIG_P33_45_ENTRY",
        exit_signal="SIG_P33_45_EXIT",
        points_normal=["PT_045_N"],
        points_reverse=["PT_046_R"],
        conflicting_routes=["ROUTE_P33_0050"],
        flank_protection_points=["FLANK_PT_045"],
        track_circuits_in_route=["TC_P33_45_A", "TC_P33_45_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_045"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0046": RouteLockingRule(
        route_id="ROUTE_P33_0046",
        entry_signal="SIG_P33_46_ENTRY",
        exit_signal="SIG_P33_46_EXIT",
        points_normal=["PT_046_N"],
        points_reverse=["PT_047_R"],
        conflicting_routes=["ROUTE_P33_0051"],
        flank_protection_points=["FLANK_PT_046"],
        track_circuits_in_route=["TC_P33_46_A", "TC_P33_46_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_046"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0047": RouteLockingRule(
        route_id="ROUTE_P33_0047",
        entry_signal="SIG_P33_47_ENTRY",
        exit_signal="SIG_P33_47_EXIT",
        points_normal=["PT_047_N"],
        points_reverse=["PT_048_R"],
        conflicting_routes=["ROUTE_P33_0052"],
        flank_protection_points=["FLANK_PT_047"],
        track_circuits_in_route=["TC_P33_47_A", "TC_P33_47_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_047"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0048": RouteLockingRule(
        route_id="ROUTE_P33_0048",
        entry_signal="SIG_P33_48_ENTRY",
        exit_signal="SIG_P33_48_EXIT",
        points_normal=["PT_048_N"],
        points_reverse=["PT_049_R"],
        conflicting_routes=["ROUTE_P33_0053"],
        flank_protection_points=["FLANK_PT_048"],
        track_circuits_in_route=["TC_P33_48_A", "TC_P33_48_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_048"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0049": RouteLockingRule(
        route_id="ROUTE_P33_0049",
        entry_signal="SIG_P33_49_ENTRY",
        exit_signal="SIG_P33_49_EXIT",
        points_normal=["PT_049_N"],
        points_reverse=["PT_050_R"],
        conflicting_routes=["ROUTE_P33_0054"],
        flank_protection_points=["FLANK_PT_049"],
        track_circuits_in_route=["TC_P33_49_A", "TC_P33_49_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_049"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0050": RouteLockingRule(
        route_id="ROUTE_P33_0050",
        entry_signal="SIG_P33_50_ENTRY",
        exit_signal="SIG_P33_50_EXIT",
        points_normal=["PT_050_N"],
        points_reverse=["PT_051_R"],
        conflicting_routes=["ROUTE_P33_0055"],
        flank_protection_points=["FLANK_PT_000"],
        track_circuits_in_route=["TC_P33_50_A", "TC_P33_50_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_050"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0051": RouteLockingRule(
        route_id="ROUTE_P33_0051",
        entry_signal="SIG_P33_51_ENTRY",
        exit_signal="SIG_P33_51_EXIT",
        points_normal=["PT_051_N"],
        points_reverse=["PT_052_R"],
        conflicting_routes=["ROUTE_P33_0056"],
        flank_protection_points=["FLANK_PT_001"],
        track_circuits_in_route=["TC_P33_51_A", "TC_P33_51_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_051"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0052": RouteLockingRule(
        route_id="ROUTE_P33_0052",
        entry_signal="SIG_P33_52_ENTRY",
        exit_signal="SIG_P33_52_EXIT",
        points_normal=["PT_052_N"],
        points_reverse=["PT_053_R"],
        conflicting_routes=["ROUTE_P33_0057"],
        flank_protection_points=["FLANK_PT_002"],
        track_circuits_in_route=["TC_P33_52_A", "TC_P33_52_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_052"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0053": RouteLockingRule(
        route_id="ROUTE_P33_0053",
        entry_signal="SIG_P33_53_ENTRY",
        exit_signal="SIG_P33_53_EXIT",
        points_normal=["PT_053_N"],
        points_reverse=["PT_054_R"],
        conflicting_routes=["ROUTE_P33_0058"],
        flank_protection_points=["FLANK_PT_003"],
        track_circuits_in_route=["TC_P33_53_A", "TC_P33_53_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_053"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0054": RouteLockingRule(
        route_id="ROUTE_P33_0054",
        entry_signal="SIG_P33_54_ENTRY",
        exit_signal="SIG_P33_54_EXIT",
        points_normal=["PT_054_N"],
        points_reverse=["PT_055_R"],
        conflicting_routes=["ROUTE_P33_0059"],
        flank_protection_points=["FLANK_PT_004"],
        track_circuits_in_route=["TC_P33_54_A", "TC_P33_54_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_054"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0055": RouteLockingRule(
        route_id="ROUTE_P33_0055",
        entry_signal="SIG_P33_55_ENTRY",
        exit_signal="SIG_P33_55_EXIT",
        points_normal=["PT_055_N"],
        points_reverse=["PT_056_R"],
        conflicting_routes=["ROUTE_P33_0060"],
        flank_protection_points=["FLANK_PT_005"],
        track_circuits_in_route=["TC_P33_55_A", "TC_P33_55_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_055"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0056": RouteLockingRule(
        route_id="ROUTE_P33_0056",
        entry_signal="SIG_P33_56_ENTRY",
        exit_signal="SIG_P33_56_EXIT",
        points_normal=["PT_056_N"],
        points_reverse=["PT_057_R"],
        conflicting_routes=["ROUTE_P33_0061"],
        flank_protection_points=["FLANK_PT_006"],
        track_circuits_in_route=["TC_P33_56_A", "TC_P33_56_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_056"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0057": RouteLockingRule(
        route_id="ROUTE_P33_0057",
        entry_signal="SIG_P33_57_ENTRY",
        exit_signal="SIG_P33_57_EXIT",
        points_normal=["PT_057_N"],
        points_reverse=["PT_058_R"],
        conflicting_routes=["ROUTE_P33_0062"],
        flank_protection_points=["FLANK_PT_007"],
        track_circuits_in_route=["TC_P33_57_A", "TC_P33_57_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_057"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0058": RouteLockingRule(
        route_id="ROUTE_P33_0058",
        entry_signal="SIG_P33_58_ENTRY",
        exit_signal="SIG_P33_58_EXIT",
        points_normal=["PT_058_N"],
        points_reverse=["PT_059_R"],
        conflicting_routes=["ROUTE_P33_0063"],
        flank_protection_points=["FLANK_PT_008"],
        track_circuits_in_route=["TC_P33_58_A", "TC_P33_58_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_058"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0059": RouteLockingRule(
        route_id="ROUTE_P33_0059",
        entry_signal="SIG_P33_59_ENTRY",
        exit_signal="SIG_P33_59_EXIT",
        points_normal=["PT_059_N"],
        points_reverse=["PT_060_R"],
        conflicting_routes=["ROUTE_P33_0064"],
        flank_protection_points=["FLANK_PT_009"],
        track_circuits_in_route=["TC_P33_59_A", "TC_P33_59_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_059"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0060": RouteLockingRule(
        route_id="ROUTE_P33_0060",
        entry_signal="SIG_P33_60_ENTRY",
        exit_signal="SIG_P33_60_EXIT",
        points_normal=["PT_060_N"],
        points_reverse=["PT_061_R"],
        conflicting_routes=["ROUTE_P33_0065"],
        flank_protection_points=["FLANK_PT_010"],
        track_circuits_in_route=["TC_P33_60_A", "TC_P33_60_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_060"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0061": RouteLockingRule(
        route_id="ROUTE_P33_0061",
        entry_signal="SIG_P33_61_ENTRY",
        exit_signal="SIG_P33_61_EXIT",
        points_normal=["PT_061_N"],
        points_reverse=["PT_062_R"],
        conflicting_routes=["ROUTE_P33_0066"],
        flank_protection_points=["FLANK_PT_011"],
        track_circuits_in_route=["TC_P33_61_A", "TC_P33_61_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_061"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0062": RouteLockingRule(
        route_id="ROUTE_P33_0062",
        entry_signal="SIG_P33_62_ENTRY",
        exit_signal="SIG_P33_62_EXIT",
        points_normal=["PT_062_N"],
        points_reverse=["PT_063_R"],
        conflicting_routes=["ROUTE_P33_0067"],
        flank_protection_points=["FLANK_PT_012"],
        track_circuits_in_route=["TC_P33_62_A", "TC_P33_62_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_062"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0063": RouteLockingRule(
        route_id="ROUTE_P33_0063",
        entry_signal="SIG_P33_63_ENTRY",
        exit_signal="SIG_P33_63_EXIT",
        points_normal=["PT_063_N"],
        points_reverse=["PT_064_R"],
        conflicting_routes=["ROUTE_P33_0068"],
        flank_protection_points=["FLANK_PT_013"],
        track_circuits_in_route=["TC_P33_63_A", "TC_P33_63_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_063"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0064": RouteLockingRule(
        route_id="ROUTE_P33_0064",
        entry_signal="SIG_P33_64_ENTRY",
        exit_signal="SIG_P33_64_EXIT",
        points_normal=["PT_064_N"],
        points_reverse=["PT_065_R"],
        conflicting_routes=["ROUTE_P33_0069"],
        flank_protection_points=["FLANK_PT_014"],
        track_circuits_in_route=["TC_P33_64_A", "TC_P33_64_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_064"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0065": RouteLockingRule(
        route_id="ROUTE_P33_0065",
        entry_signal="SIG_P33_65_ENTRY",
        exit_signal="SIG_P33_65_EXIT",
        points_normal=["PT_065_N"],
        points_reverse=["PT_066_R"],
        conflicting_routes=["ROUTE_P33_0070"],
        flank_protection_points=["FLANK_PT_015"],
        track_circuits_in_route=["TC_P33_65_A", "TC_P33_65_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_065"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0066": RouteLockingRule(
        route_id="ROUTE_P33_0066",
        entry_signal="SIG_P33_66_ENTRY",
        exit_signal="SIG_P33_66_EXIT",
        points_normal=["PT_066_N"],
        points_reverse=["PT_067_R"],
        conflicting_routes=["ROUTE_P33_0071"],
        flank_protection_points=["FLANK_PT_016"],
        track_circuits_in_route=["TC_P33_66_A", "TC_P33_66_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_066"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0067": RouteLockingRule(
        route_id="ROUTE_P33_0067",
        entry_signal="SIG_P33_67_ENTRY",
        exit_signal="SIG_P33_67_EXIT",
        points_normal=["PT_067_N"],
        points_reverse=["PT_068_R"],
        conflicting_routes=["ROUTE_P33_0072"],
        flank_protection_points=["FLANK_PT_017"],
        track_circuits_in_route=["TC_P33_67_A", "TC_P33_67_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_067"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0068": RouteLockingRule(
        route_id="ROUTE_P33_0068",
        entry_signal="SIG_P33_68_ENTRY",
        exit_signal="SIG_P33_68_EXIT",
        points_normal=["PT_068_N"],
        points_reverse=["PT_069_R"],
        conflicting_routes=["ROUTE_P33_0073"],
        flank_protection_points=["FLANK_PT_018"],
        track_circuits_in_route=["TC_P33_68_A", "TC_P33_68_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_068"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0069": RouteLockingRule(
        route_id="ROUTE_P33_0069",
        entry_signal="SIG_P33_69_ENTRY",
        exit_signal="SIG_P33_69_EXIT",
        points_normal=["PT_069_N"],
        points_reverse=["PT_070_R"],
        conflicting_routes=["ROUTE_P33_0074"],
        flank_protection_points=["FLANK_PT_019"],
        track_circuits_in_route=["TC_P33_69_A", "TC_P33_69_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_069"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0070": RouteLockingRule(
        route_id="ROUTE_P33_0070",
        entry_signal="SIG_P33_70_ENTRY",
        exit_signal="SIG_P33_70_EXIT",
        points_normal=["PT_070_N"],
        points_reverse=["PT_071_R"],
        conflicting_routes=["ROUTE_P33_0075"],
        flank_protection_points=["FLANK_PT_020"],
        track_circuits_in_route=["TC_P33_70_A", "TC_P33_70_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_070"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0071": RouteLockingRule(
        route_id="ROUTE_P33_0071",
        entry_signal="SIG_P33_71_ENTRY",
        exit_signal="SIG_P33_71_EXIT",
        points_normal=["PT_071_N"],
        points_reverse=["PT_072_R"],
        conflicting_routes=["ROUTE_P33_0076"],
        flank_protection_points=["FLANK_PT_021"],
        track_circuits_in_route=["TC_P33_71_A", "TC_P33_71_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_071"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0072": RouteLockingRule(
        route_id="ROUTE_P33_0072",
        entry_signal="SIG_P33_72_ENTRY",
        exit_signal="SIG_P33_72_EXIT",
        points_normal=["PT_072_N"],
        points_reverse=["PT_073_R"],
        conflicting_routes=["ROUTE_P33_0077"],
        flank_protection_points=["FLANK_PT_022"],
        track_circuits_in_route=["TC_P33_72_A", "TC_P33_72_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_072"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0073": RouteLockingRule(
        route_id="ROUTE_P33_0073",
        entry_signal="SIG_P33_73_ENTRY",
        exit_signal="SIG_P33_73_EXIT",
        points_normal=["PT_073_N"],
        points_reverse=["PT_074_R"],
        conflicting_routes=["ROUTE_P33_0078"],
        flank_protection_points=["FLANK_PT_023"],
        track_circuits_in_route=["TC_P33_73_A", "TC_P33_73_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_073"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0074": RouteLockingRule(
        route_id="ROUTE_P33_0074",
        entry_signal="SIG_P33_74_ENTRY",
        exit_signal="SIG_P33_74_EXIT",
        points_normal=["PT_074_N"],
        points_reverse=["PT_075_R"],
        conflicting_routes=["ROUTE_P33_0079"],
        flank_protection_points=["FLANK_PT_024"],
        track_circuits_in_route=["TC_P33_74_A", "TC_P33_74_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_074"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0075": RouteLockingRule(
        route_id="ROUTE_P33_0075",
        entry_signal="SIG_P33_75_ENTRY",
        exit_signal="SIG_P33_75_EXIT",
        points_normal=["PT_075_N"],
        points_reverse=["PT_076_R"],
        conflicting_routes=["ROUTE_P33_0080"],
        flank_protection_points=["FLANK_PT_025"],
        track_circuits_in_route=["TC_P33_75_A", "TC_P33_75_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_075"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0076": RouteLockingRule(
        route_id="ROUTE_P33_0076",
        entry_signal="SIG_P33_76_ENTRY",
        exit_signal="SIG_P33_76_EXIT",
        points_normal=["PT_076_N"],
        points_reverse=["PT_077_R"],
        conflicting_routes=["ROUTE_P33_0081"],
        flank_protection_points=["FLANK_PT_026"],
        track_circuits_in_route=["TC_P33_76_A", "TC_P33_76_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_076"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0077": RouteLockingRule(
        route_id="ROUTE_P33_0077",
        entry_signal="SIG_P33_77_ENTRY",
        exit_signal="SIG_P33_77_EXIT",
        points_normal=["PT_077_N"],
        points_reverse=["PT_078_R"],
        conflicting_routes=["ROUTE_P33_0082"],
        flank_protection_points=["FLANK_PT_027"],
        track_circuits_in_route=["TC_P33_77_A", "TC_P33_77_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_077"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0078": RouteLockingRule(
        route_id="ROUTE_P33_0078",
        entry_signal="SIG_P33_78_ENTRY",
        exit_signal="SIG_P33_78_EXIT",
        points_normal=["PT_078_N"],
        points_reverse=["PT_079_R"],
        conflicting_routes=["ROUTE_P33_0083"],
        flank_protection_points=["FLANK_PT_028"],
        track_circuits_in_route=["TC_P33_78_A", "TC_P33_78_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_078"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0079": RouteLockingRule(
        route_id="ROUTE_P33_0079",
        entry_signal="SIG_P33_79_ENTRY",
        exit_signal="SIG_P33_79_EXIT",
        points_normal=["PT_079_N"],
        points_reverse=["PT_080_R"],
        conflicting_routes=["ROUTE_P33_0084"],
        flank_protection_points=["FLANK_PT_029"],
        track_circuits_in_route=["TC_P33_79_A", "TC_P33_79_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_079"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0080": RouteLockingRule(
        route_id="ROUTE_P33_0080",
        entry_signal="SIG_P33_80_ENTRY",
        exit_signal="SIG_P33_80_EXIT",
        points_normal=["PT_080_N"],
        points_reverse=["PT_081_R"],
        conflicting_routes=["ROUTE_P33_0085"],
        flank_protection_points=["FLANK_PT_030"],
        track_circuits_in_route=["TC_P33_80_A", "TC_P33_80_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_080"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0081": RouteLockingRule(
        route_id="ROUTE_P33_0081",
        entry_signal="SIG_P33_81_ENTRY",
        exit_signal="SIG_P33_81_EXIT",
        points_normal=["PT_081_N"],
        points_reverse=["PT_082_R"],
        conflicting_routes=["ROUTE_P33_0086"],
        flank_protection_points=["FLANK_PT_031"],
        track_circuits_in_route=["TC_P33_81_A", "TC_P33_81_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_081"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0082": RouteLockingRule(
        route_id="ROUTE_P33_0082",
        entry_signal="SIG_P33_82_ENTRY",
        exit_signal="SIG_P33_82_EXIT",
        points_normal=["PT_082_N"],
        points_reverse=["PT_083_R"],
        conflicting_routes=["ROUTE_P33_0087"],
        flank_protection_points=["FLANK_PT_032"],
        track_circuits_in_route=["TC_P33_82_A", "TC_P33_82_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_082"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0083": RouteLockingRule(
        route_id="ROUTE_P33_0083",
        entry_signal="SIG_P33_83_ENTRY",
        exit_signal="SIG_P33_83_EXIT",
        points_normal=["PT_083_N"],
        points_reverse=["PT_084_R"],
        conflicting_routes=["ROUTE_P33_0088"],
        flank_protection_points=["FLANK_PT_033"],
        track_circuits_in_route=["TC_P33_83_A", "TC_P33_83_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_083"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0084": RouteLockingRule(
        route_id="ROUTE_P33_0084",
        entry_signal="SIG_P33_84_ENTRY",
        exit_signal="SIG_P33_84_EXIT",
        points_normal=["PT_084_N"],
        points_reverse=["PT_085_R"],
        conflicting_routes=["ROUTE_P33_0089"],
        flank_protection_points=["FLANK_PT_034"],
        track_circuits_in_route=["TC_P33_84_A", "TC_P33_84_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_084"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0085": RouteLockingRule(
        route_id="ROUTE_P33_0085",
        entry_signal="SIG_P33_85_ENTRY",
        exit_signal="SIG_P33_85_EXIT",
        points_normal=["PT_085_N"],
        points_reverse=["PT_086_R"],
        conflicting_routes=["ROUTE_P33_0090"],
        flank_protection_points=["FLANK_PT_035"],
        track_circuits_in_route=["TC_P33_85_A", "TC_P33_85_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_085"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0086": RouteLockingRule(
        route_id="ROUTE_P33_0086",
        entry_signal="SIG_P33_86_ENTRY",
        exit_signal="SIG_P33_86_EXIT",
        points_normal=["PT_086_N"],
        points_reverse=["PT_087_R"],
        conflicting_routes=["ROUTE_P33_0091"],
        flank_protection_points=["FLANK_PT_036"],
        track_circuits_in_route=["TC_P33_86_A", "TC_P33_86_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_086"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0087": RouteLockingRule(
        route_id="ROUTE_P33_0087",
        entry_signal="SIG_P33_87_ENTRY",
        exit_signal="SIG_P33_87_EXIT",
        points_normal=["PT_087_N"],
        points_reverse=["PT_088_R"],
        conflicting_routes=["ROUTE_P33_0092"],
        flank_protection_points=["FLANK_PT_037"],
        track_circuits_in_route=["TC_P33_87_A", "TC_P33_87_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_087"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0088": RouteLockingRule(
        route_id="ROUTE_P33_0088",
        entry_signal="SIG_P33_88_ENTRY",
        exit_signal="SIG_P33_88_EXIT",
        points_normal=["PT_088_N"],
        points_reverse=["PT_089_R"],
        conflicting_routes=["ROUTE_P33_0093"],
        flank_protection_points=["FLANK_PT_038"],
        track_circuits_in_route=["TC_P33_88_A", "TC_P33_88_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_088"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0089": RouteLockingRule(
        route_id="ROUTE_P33_0089",
        entry_signal="SIG_P33_89_ENTRY",
        exit_signal="SIG_P33_89_EXIT",
        points_normal=["PT_089_N"],
        points_reverse=["PT_090_R"],
        conflicting_routes=["ROUTE_P33_0094"],
        flank_protection_points=["FLANK_PT_039"],
        track_circuits_in_route=["TC_P33_89_A", "TC_P33_89_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_089"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0090": RouteLockingRule(
        route_id="ROUTE_P33_0090",
        entry_signal="SIG_P33_90_ENTRY",
        exit_signal="SIG_P33_90_EXIT",
        points_normal=["PT_090_N"],
        points_reverse=["PT_091_R"],
        conflicting_routes=["ROUTE_P33_0095"],
        flank_protection_points=["FLANK_PT_040"],
        track_circuits_in_route=["TC_P33_90_A", "TC_P33_90_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_090"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0091": RouteLockingRule(
        route_id="ROUTE_P33_0091",
        entry_signal="SIG_P33_91_ENTRY",
        exit_signal="SIG_P33_91_EXIT",
        points_normal=["PT_091_N"],
        points_reverse=["PT_092_R"],
        conflicting_routes=["ROUTE_P33_0096"],
        flank_protection_points=["FLANK_PT_041"],
        track_circuits_in_route=["TC_P33_91_A", "TC_P33_91_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_091"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0092": RouteLockingRule(
        route_id="ROUTE_P33_0092",
        entry_signal="SIG_P33_92_ENTRY",
        exit_signal="SIG_P33_92_EXIT",
        points_normal=["PT_092_N"],
        points_reverse=["PT_093_R"],
        conflicting_routes=["ROUTE_P33_0097"],
        flank_protection_points=["FLANK_PT_042"],
        track_circuits_in_route=["TC_P33_92_A", "TC_P33_92_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_092"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0093": RouteLockingRule(
        route_id="ROUTE_P33_0093",
        entry_signal="SIG_P33_93_ENTRY",
        exit_signal="SIG_P33_93_EXIT",
        points_normal=["PT_093_N"],
        points_reverse=["PT_094_R"],
        conflicting_routes=["ROUTE_P33_0098"],
        flank_protection_points=["FLANK_PT_043"],
        track_circuits_in_route=["TC_P33_93_A", "TC_P33_93_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_093"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0094": RouteLockingRule(
        route_id="ROUTE_P33_0094",
        entry_signal="SIG_P33_94_ENTRY",
        exit_signal="SIG_P33_94_EXIT",
        points_normal=["PT_094_N"],
        points_reverse=["PT_095_R"],
        conflicting_routes=["ROUTE_P33_0099"],
        flank_protection_points=["FLANK_PT_044"],
        track_circuits_in_route=["TC_P33_94_A", "TC_P33_94_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_094"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0095": RouteLockingRule(
        route_id="ROUTE_P33_0095",
        entry_signal="SIG_P33_95_ENTRY",
        exit_signal="SIG_P33_95_EXIT",
        points_normal=["PT_095_N"],
        points_reverse=["PT_096_R"],
        conflicting_routes=["ROUTE_P33_0100"],
        flank_protection_points=["FLANK_PT_045"],
        track_circuits_in_route=["TC_P33_95_A", "TC_P33_95_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_095"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0096": RouteLockingRule(
        route_id="ROUTE_P33_0096",
        entry_signal="SIG_P33_96_ENTRY",
        exit_signal="SIG_P33_96_EXIT",
        points_normal=["PT_096_N"],
        points_reverse=["PT_097_R"],
        conflicting_routes=["ROUTE_P33_0101"],
        flank_protection_points=["FLANK_PT_046"],
        track_circuits_in_route=["TC_P33_96_A", "TC_P33_96_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_096"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0097": RouteLockingRule(
        route_id="ROUTE_P33_0097",
        entry_signal="SIG_P33_97_ENTRY",
        exit_signal="SIG_P33_97_EXIT",
        points_normal=["PT_097_N"],
        points_reverse=["PT_098_R"],
        conflicting_routes=["ROUTE_P33_0102"],
        flank_protection_points=["FLANK_PT_047"],
        track_circuits_in_route=["TC_P33_97_A", "TC_P33_97_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_097"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0098": RouteLockingRule(
        route_id="ROUTE_P33_0098",
        entry_signal="SIG_P33_98_ENTRY",
        exit_signal="SIG_P33_98_EXIT",
        points_normal=["PT_098_N"],
        points_reverse=["PT_099_R"],
        conflicting_routes=["ROUTE_P33_0103"],
        flank_protection_points=["FLANK_PT_048"],
        track_circuits_in_route=["TC_P33_98_A", "TC_P33_98_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_098"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0099": RouteLockingRule(
        route_id="ROUTE_P33_0099",
        entry_signal="SIG_P33_99_ENTRY",
        exit_signal="SIG_P33_99_EXIT",
        points_normal=["PT_099_N"],
        points_reverse=["PT_100_R"],
        conflicting_routes=["ROUTE_P33_0104"],
        flank_protection_points=["FLANK_PT_049"],
        track_circuits_in_route=["TC_P33_99_A", "TC_P33_99_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_099"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0100": RouteLockingRule(
        route_id="ROUTE_P33_0100",
        entry_signal="SIG_P33_100_ENTRY",
        exit_signal="SIG_P33_100_EXIT",
        points_normal=["PT_100_N"],
        points_reverse=["PT_101_R"],
        conflicting_routes=["ROUTE_P33_0105"],
        flank_protection_points=["FLANK_PT_000"],
        track_circuits_in_route=["TC_P33_100_A", "TC_P33_100_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_000"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0101": RouteLockingRule(
        route_id="ROUTE_P33_0101",
        entry_signal="SIG_P33_101_ENTRY",
        exit_signal="SIG_P33_101_EXIT",
        points_normal=["PT_101_N"],
        points_reverse=["PT_102_R"],
        conflicting_routes=["ROUTE_P33_0106"],
        flank_protection_points=["FLANK_PT_001"],
        track_circuits_in_route=["TC_P33_101_A", "TC_P33_101_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_001"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0102": RouteLockingRule(
        route_id="ROUTE_P33_0102",
        entry_signal="SIG_P33_102_ENTRY",
        exit_signal="SIG_P33_102_EXIT",
        points_normal=["PT_102_N"],
        points_reverse=["PT_103_R"],
        conflicting_routes=["ROUTE_P33_0107"],
        flank_protection_points=["FLANK_PT_002"],
        track_circuits_in_route=["TC_P33_102_A", "TC_P33_102_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_002"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0103": RouteLockingRule(
        route_id="ROUTE_P33_0103",
        entry_signal="SIG_P33_103_ENTRY",
        exit_signal="SIG_P33_103_EXIT",
        points_normal=["PT_103_N"],
        points_reverse=["PT_104_R"],
        conflicting_routes=["ROUTE_P33_0108"],
        flank_protection_points=["FLANK_PT_003"],
        track_circuits_in_route=["TC_P33_103_A", "TC_P33_103_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_003"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0104": RouteLockingRule(
        route_id="ROUTE_P33_0104",
        entry_signal="SIG_P33_104_ENTRY",
        exit_signal="SIG_P33_104_EXIT",
        points_normal=["PT_104_N"],
        points_reverse=["PT_105_R"],
        conflicting_routes=["ROUTE_P33_0109"],
        flank_protection_points=["FLANK_PT_004"],
        track_circuits_in_route=["TC_P33_104_A", "TC_P33_104_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_004"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0105": RouteLockingRule(
        route_id="ROUTE_P33_0105",
        entry_signal="SIG_P33_105_ENTRY",
        exit_signal="SIG_P33_105_EXIT",
        points_normal=["PT_105_N"],
        points_reverse=["PT_106_R"],
        conflicting_routes=["ROUTE_P33_0110"],
        flank_protection_points=["FLANK_PT_005"],
        track_circuits_in_route=["TC_P33_105_A", "TC_P33_105_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_005"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0106": RouteLockingRule(
        route_id="ROUTE_P33_0106",
        entry_signal="SIG_P33_106_ENTRY",
        exit_signal="SIG_P33_106_EXIT",
        points_normal=["PT_106_N"],
        points_reverse=["PT_107_R"],
        conflicting_routes=["ROUTE_P33_0111"],
        flank_protection_points=["FLANK_PT_006"],
        track_circuits_in_route=["TC_P33_106_A", "TC_P33_106_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_006"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0107": RouteLockingRule(
        route_id="ROUTE_P33_0107",
        entry_signal="SIG_P33_107_ENTRY",
        exit_signal="SIG_P33_107_EXIT",
        points_normal=["PT_107_N"],
        points_reverse=["PT_108_R"],
        conflicting_routes=["ROUTE_P33_0112"],
        flank_protection_points=["FLANK_PT_007"],
        track_circuits_in_route=["TC_P33_107_A", "TC_P33_107_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_007"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0108": RouteLockingRule(
        route_id="ROUTE_P33_0108",
        entry_signal="SIG_P33_108_ENTRY",
        exit_signal="SIG_P33_108_EXIT",
        points_normal=["PT_108_N"],
        points_reverse=["PT_109_R"],
        conflicting_routes=["ROUTE_P33_0113"],
        flank_protection_points=["FLANK_PT_008"],
        track_circuits_in_route=["TC_P33_108_A", "TC_P33_108_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_008"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0109": RouteLockingRule(
        route_id="ROUTE_P33_0109",
        entry_signal="SIG_P33_109_ENTRY",
        exit_signal="SIG_P33_109_EXIT",
        points_normal=["PT_109_N"],
        points_reverse=["PT_110_R"],
        conflicting_routes=["ROUTE_P33_0114"],
        flank_protection_points=["FLANK_PT_009"],
        track_circuits_in_route=["TC_P33_109_A", "TC_P33_109_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_009"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0110": RouteLockingRule(
        route_id="ROUTE_P33_0110",
        entry_signal="SIG_P33_110_ENTRY",
        exit_signal="SIG_P33_110_EXIT",
        points_normal=["PT_110_N"],
        points_reverse=["PT_111_R"],
        conflicting_routes=["ROUTE_P33_0115"],
        flank_protection_points=["FLANK_PT_010"],
        track_circuits_in_route=["TC_P33_110_A", "TC_P33_110_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_010"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0111": RouteLockingRule(
        route_id="ROUTE_P33_0111",
        entry_signal="SIG_P33_111_ENTRY",
        exit_signal="SIG_P33_111_EXIT",
        points_normal=["PT_111_N"],
        points_reverse=["PT_112_R"],
        conflicting_routes=["ROUTE_P33_0116"],
        flank_protection_points=["FLANK_PT_011"],
        track_circuits_in_route=["TC_P33_111_A", "TC_P33_111_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_011"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0112": RouteLockingRule(
        route_id="ROUTE_P33_0112",
        entry_signal="SIG_P33_112_ENTRY",
        exit_signal="SIG_P33_112_EXIT",
        points_normal=["PT_112_N"],
        points_reverse=["PT_113_R"],
        conflicting_routes=["ROUTE_P33_0117"],
        flank_protection_points=["FLANK_PT_012"],
        track_circuits_in_route=["TC_P33_112_A", "TC_P33_112_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_012"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0113": RouteLockingRule(
        route_id="ROUTE_P33_0113",
        entry_signal="SIG_P33_113_ENTRY",
        exit_signal="SIG_P33_113_EXIT",
        points_normal=["PT_113_N"],
        points_reverse=["PT_114_R"],
        conflicting_routes=["ROUTE_P33_0118"],
        flank_protection_points=["FLANK_PT_013"],
        track_circuits_in_route=["TC_P33_113_A", "TC_P33_113_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_013"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0114": RouteLockingRule(
        route_id="ROUTE_P33_0114",
        entry_signal="SIG_P33_114_ENTRY",
        exit_signal="SIG_P33_114_EXIT",
        points_normal=["PT_114_N"],
        points_reverse=["PT_115_R"],
        conflicting_routes=["ROUTE_P33_0119"],
        flank_protection_points=["FLANK_PT_014"],
        track_circuits_in_route=["TC_P33_114_A", "TC_P33_114_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_014"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0115": RouteLockingRule(
        route_id="ROUTE_P33_0115",
        entry_signal="SIG_P33_115_ENTRY",
        exit_signal="SIG_P33_115_EXIT",
        points_normal=["PT_115_N"],
        points_reverse=["PT_116_R"],
        conflicting_routes=["ROUTE_P33_0120"],
        flank_protection_points=["FLANK_PT_015"],
        track_circuits_in_route=["TC_P33_115_A", "TC_P33_115_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_015"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0116": RouteLockingRule(
        route_id="ROUTE_P33_0116",
        entry_signal="SIG_P33_116_ENTRY",
        exit_signal="SIG_P33_116_EXIT",
        points_normal=["PT_116_N"],
        points_reverse=["PT_117_R"],
        conflicting_routes=["ROUTE_P33_0121"],
        flank_protection_points=["FLANK_PT_016"],
        track_circuits_in_route=["TC_P33_116_A", "TC_P33_116_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_016"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0117": RouteLockingRule(
        route_id="ROUTE_P33_0117",
        entry_signal="SIG_P33_117_ENTRY",
        exit_signal="SIG_P33_117_EXIT",
        points_normal=["PT_117_N"],
        points_reverse=["PT_118_R"],
        conflicting_routes=["ROUTE_P33_0122"],
        flank_protection_points=["FLANK_PT_017"],
        track_circuits_in_route=["TC_P33_117_A", "TC_P33_117_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_017"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0118": RouteLockingRule(
        route_id="ROUTE_P33_0118",
        entry_signal="SIG_P33_118_ENTRY",
        exit_signal="SIG_P33_118_EXIT",
        points_normal=["PT_118_N"],
        points_reverse=["PT_119_R"],
        conflicting_routes=["ROUTE_P33_0123"],
        flank_protection_points=["FLANK_PT_018"],
        track_circuits_in_route=["TC_P33_118_A", "TC_P33_118_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_018"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0119": RouteLockingRule(
        route_id="ROUTE_P33_0119",
        entry_signal="SIG_P33_119_ENTRY",
        exit_signal="SIG_P33_119_EXIT",
        points_normal=["PT_119_N"],
        points_reverse=["PT_120_R"],
        conflicting_routes=["ROUTE_P33_0124"],
        flank_protection_points=["FLANK_PT_019"],
        track_circuits_in_route=["TC_P33_119_A", "TC_P33_119_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_019"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0120": RouteLockingRule(
        route_id="ROUTE_P33_0120",
        entry_signal="SIG_P33_120_ENTRY",
        exit_signal="SIG_P33_120_EXIT",
        points_normal=["PT_120_N"],
        points_reverse=["PT_121_R"],
        conflicting_routes=["ROUTE_P33_0125"],
        flank_protection_points=["FLANK_PT_020"],
        track_circuits_in_route=["TC_P33_120_A", "TC_P33_120_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_020"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0121": RouteLockingRule(
        route_id="ROUTE_P33_0121",
        entry_signal="SIG_P33_121_ENTRY",
        exit_signal="SIG_P33_121_EXIT",
        points_normal=["PT_121_N"],
        points_reverse=["PT_122_R"],
        conflicting_routes=["ROUTE_P33_0126"],
        flank_protection_points=["FLANK_PT_021"],
        track_circuits_in_route=["TC_P33_121_A", "TC_P33_121_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_021"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0122": RouteLockingRule(
        route_id="ROUTE_P33_0122",
        entry_signal="SIG_P33_122_ENTRY",
        exit_signal="SIG_P33_122_EXIT",
        points_normal=["PT_122_N"],
        points_reverse=["PT_123_R"],
        conflicting_routes=["ROUTE_P33_0127"],
        flank_protection_points=["FLANK_PT_022"],
        track_circuits_in_route=["TC_P33_122_A", "TC_P33_122_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_022"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0123": RouteLockingRule(
        route_id="ROUTE_P33_0123",
        entry_signal="SIG_P33_123_ENTRY",
        exit_signal="SIG_P33_123_EXIT",
        points_normal=["PT_123_N"],
        points_reverse=["PT_124_R"],
        conflicting_routes=["ROUTE_P33_0128"],
        flank_protection_points=["FLANK_PT_023"],
        track_circuits_in_route=["TC_P33_123_A", "TC_P33_123_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_023"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0124": RouteLockingRule(
        route_id="ROUTE_P33_0124",
        entry_signal="SIG_P33_124_ENTRY",
        exit_signal="SIG_P33_124_EXIT",
        points_normal=["PT_124_N"],
        points_reverse=["PT_125_R"],
        conflicting_routes=["ROUTE_P33_0129"],
        flank_protection_points=["FLANK_PT_024"],
        track_circuits_in_route=["TC_P33_124_A", "TC_P33_124_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_024"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0125": RouteLockingRule(
        route_id="ROUTE_P33_0125",
        entry_signal="SIG_P33_125_ENTRY",
        exit_signal="SIG_P33_125_EXIT",
        points_normal=["PT_125_N"],
        points_reverse=["PT_126_R"],
        conflicting_routes=["ROUTE_P33_0130"],
        flank_protection_points=["FLANK_PT_025"],
        track_circuits_in_route=["TC_P33_125_A", "TC_P33_125_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_025"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0126": RouteLockingRule(
        route_id="ROUTE_P33_0126",
        entry_signal="SIG_P33_126_ENTRY",
        exit_signal="SIG_P33_126_EXIT",
        points_normal=["PT_126_N"],
        points_reverse=["PT_127_R"],
        conflicting_routes=["ROUTE_P33_0131"],
        flank_protection_points=["FLANK_PT_026"],
        track_circuits_in_route=["TC_P33_126_A", "TC_P33_126_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_026"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0127": RouteLockingRule(
        route_id="ROUTE_P33_0127",
        entry_signal="SIG_P33_127_ENTRY",
        exit_signal="SIG_P33_127_EXIT",
        points_normal=["PT_127_N"],
        points_reverse=["PT_128_R"],
        conflicting_routes=["ROUTE_P33_0132"],
        flank_protection_points=["FLANK_PT_027"],
        track_circuits_in_route=["TC_P33_127_A", "TC_P33_127_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_027"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0128": RouteLockingRule(
        route_id="ROUTE_P33_0128",
        entry_signal="SIG_P33_128_ENTRY",
        exit_signal="SIG_P33_128_EXIT",
        points_normal=["PT_128_N"],
        points_reverse=["PT_129_R"],
        conflicting_routes=["ROUTE_P33_0133"],
        flank_protection_points=["FLANK_PT_028"],
        track_circuits_in_route=["TC_P33_128_A", "TC_P33_128_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_028"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0129": RouteLockingRule(
        route_id="ROUTE_P33_0129",
        entry_signal="SIG_P33_129_ENTRY",
        exit_signal="SIG_P33_129_EXIT",
        points_normal=["PT_129_N"],
        points_reverse=["PT_130_R"],
        conflicting_routes=["ROUTE_P33_0134"],
        flank_protection_points=["FLANK_PT_029"],
        track_circuits_in_route=["TC_P33_129_A", "TC_P33_129_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_029"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0130": RouteLockingRule(
        route_id="ROUTE_P33_0130",
        entry_signal="SIG_P33_130_ENTRY",
        exit_signal="SIG_P33_130_EXIT",
        points_normal=["PT_130_N"],
        points_reverse=["PT_131_R"],
        conflicting_routes=["ROUTE_P33_0135"],
        flank_protection_points=["FLANK_PT_030"],
        track_circuits_in_route=["TC_P33_130_A", "TC_P33_130_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_030"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0131": RouteLockingRule(
        route_id="ROUTE_P33_0131",
        entry_signal="SIG_P33_131_ENTRY",
        exit_signal="SIG_P33_131_EXIT",
        points_normal=["PT_131_N"],
        points_reverse=["PT_132_R"],
        conflicting_routes=["ROUTE_P33_0136"],
        flank_protection_points=["FLANK_PT_031"],
        track_circuits_in_route=["TC_P33_131_A", "TC_P33_131_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_031"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0132": RouteLockingRule(
        route_id="ROUTE_P33_0132",
        entry_signal="SIG_P33_132_ENTRY",
        exit_signal="SIG_P33_132_EXIT",
        points_normal=["PT_132_N"],
        points_reverse=["PT_133_R"],
        conflicting_routes=["ROUTE_P33_0137"],
        flank_protection_points=["FLANK_PT_032"],
        track_circuits_in_route=["TC_P33_132_A", "TC_P33_132_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_032"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0133": RouteLockingRule(
        route_id="ROUTE_P33_0133",
        entry_signal="SIG_P33_133_ENTRY",
        exit_signal="SIG_P33_133_EXIT",
        points_normal=["PT_133_N"],
        points_reverse=["PT_134_R"],
        conflicting_routes=["ROUTE_P33_0138"],
        flank_protection_points=["FLANK_PT_033"],
        track_circuits_in_route=["TC_P33_133_A", "TC_P33_133_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_033"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0134": RouteLockingRule(
        route_id="ROUTE_P33_0134",
        entry_signal="SIG_P33_134_ENTRY",
        exit_signal="SIG_P33_134_EXIT",
        points_normal=["PT_134_N"],
        points_reverse=["PT_135_R"],
        conflicting_routes=["ROUTE_P33_0139"],
        flank_protection_points=["FLANK_PT_034"],
        track_circuits_in_route=["TC_P33_134_A", "TC_P33_134_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_034"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0135": RouteLockingRule(
        route_id="ROUTE_P33_0135",
        entry_signal="SIG_P33_135_ENTRY",
        exit_signal="SIG_P33_135_EXIT",
        points_normal=["PT_135_N"],
        points_reverse=["PT_136_R"],
        conflicting_routes=["ROUTE_P33_0140"],
        flank_protection_points=["FLANK_PT_035"],
        track_circuits_in_route=["TC_P33_135_A", "TC_P33_135_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_035"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0136": RouteLockingRule(
        route_id="ROUTE_P33_0136",
        entry_signal="SIG_P33_136_ENTRY",
        exit_signal="SIG_P33_136_EXIT",
        points_normal=["PT_136_N"],
        points_reverse=["PT_137_R"],
        conflicting_routes=["ROUTE_P33_0141"],
        flank_protection_points=["FLANK_PT_036"],
        track_circuits_in_route=["TC_P33_136_A", "TC_P33_136_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_036"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0137": RouteLockingRule(
        route_id="ROUTE_P33_0137",
        entry_signal="SIG_P33_137_ENTRY",
        exit_signal="SIG_P33_137_EXIT",
        points_normal=["PT_137_N"],
        points_reverse=["PT_138_R"],
        conflicting_routes=["ROUTE_P33_0142"],
        flank_protection_points=["FLANK_PT_037"],
        track_circuits_in_route=["TC_P33_137_A", "TC_P33_137_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_037"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0138": RouteLockingRule(
        route_id="ROUTE_P33_0138",
        entry_signal="SIG_P33_138_ENTRY",
        exit_signal="SIG_P33_138_EXIT",
        points_normal=["PT_138_N"],
        points_reverse=["PT_139_R"],
        conflicting_routes=["ROUTE_P33_0143"],
        flank_protection_points=["FLANK_PT_038"],
        track_circuits_in_route=["TC_P33_138_A", "TC_P33_138_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_038"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0139": RouteLockingRule(
        route_id="ROUTE_P33_0139",
        entry_signal="SIG_P33_139_ENTRY",
        exit_signal="SIG_P33_139_EXIT",
        points_normal=["PT_139_N"],
        points_reverse=["PT_140_R"],
        conflicting_routes=["ROUTE_P33_0144"],
        flank_protection_points=["FLANK_PT_039"],
        track_circuits_in_route=["TC_P33_139_A", "TC_P33_139_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_039"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0140": RouteLockingRule(
        route_id="ROUTE_P33_0140",
        entry_signal="SIG_P33_140_ENTRY",
        exit_signal="SIG_P33_140_EXIT",
        points_normal=["PT_140_N"],
        points_reverse=["PT_141_R"],
        conflicting_routes=["ROUTE_P33_0145"],
        flank_protection_points=["FLANK_PT_040"],
        track_circuits_in_route=["TC_P33_140_A", "TC_P33_140_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_040"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0141": RouteLockingRule(
        route_id="ROUTE_P33_0141",
        entry_signal="SIG_P33_141_ENTRY",
        exit_signal="SIG_P33_141_EXIT",
        points_normal=["PT_141_N"],
        points_reverse=["PT_142_R"],
        conflicting_routes=["ROUTE_P33_0146"],
        flank_protection_points=["FLANK_PT_041"],
        track_circuits_in_route=["TC_P33_141_A", "TC_P33_141_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_041"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0142": RouteLockingRule(
        route_id="ROUTE_P33_0142",
        entry_signal="SIG_P33_142_ENTRY",
        exit_signal="SIG_P33_142_EXIT",
        points_normal=["PT_142_N"],
        points_reverse=["PT_143_R"],
        conflicting_routes=["ROUTE_P33_0147"],
        flank_protection_points=["FLANK_PT_042"],
        track_circuits_in_route=["TC_P33_142_A", "TC_P33_142_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_042"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0143": RouteLockingRule(
        route_id="ROUTE_P33_0143",
        entry_signal="SIG_P33_143_ENTRY",
        exit_signal="SIG_P33_143_EXIT",
        points_normal=["PT_143_N"],
        points_reverse=["PT_144_R"],
        conflicting_routes=["ROUTE_P33_0148"],
        flank_protection_points=["FLANK_PT_043"],
        track_circuits_in_route=["TC_P33_143_A", "TC_P33_143_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_043"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0144": RouteLockingRule(
        route_id="ROUTE_P33_0144",
        entry_signal="SIG_P33_144_ENTRY",
        exit_signal="SIG_P33_144_EXIT",
        points_normal=["PT_144_N"],
        points_reverse=["PT_145_R"],
        conflicting_routes=["ROUTE_P33_0149"],
        flank_protection_points=["FLANK_PT_044"],
        track_circuits_in_route=["TC_P33_144_A", "TC_P33_144_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_044"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0145": RouteLockingRule(
        route_id="ROUTE_P33_0145",
        entry_signal="SIG_P33_145_ENTRY",
        exit_signal="SIG_P33_145_EXIT",
        points_normal=["PT_145_N"],
        points_reverse=["PT_146_R"],
        conflicting_routes=["ROUTE_P33_0000"],
        flank_protection_points=["FLANK_PT_045"],
        track_circuits_in_route=["TC_P33_145_A", "TC_P33_145_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_045"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0146": RouteLockingRule(
        route_id="ROUTE_P33_0146",
        entry_signal="SIG_P33_146_ENTRY",
        exit_signal="SIG_P33_146_EXIT",
        points_normal=["PT_146_N"],
        points_reverse=["PT_147_R"],
        conflicting_routes=["ROUTE_P33_0001"],
        flank_protection_points=["FLANK_PT_046"],
        track_circuits_in_route=["TC_P33_146_A", "TC_P33_146_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_046"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0147": RouteLockingRule(
        route_id="ROUTE_P33_0147",
        entry_signal="SIG_P33_147_ENTRY",
        exit_signal="SIG_P33_147_EXIT",
        points_normal=["PT_147_N"],
        points_reverse=["PT_148_R"],
        conflicting_routes=["ROUTE_P33_0002"],
        flank_protection_points=["FLANK_PT_047"],
        track_circuits_in_route=["TC_P33_147_A", "TC_P33_147_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_047"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0148": RouteLockingRule(
        route_id="ROUTE_P33_0148",
        entry_signal="SIG_P33_148_ENTRY",
        exit_signal="SIG_P33_148_EXIT",
        points_normal=["PT_148_N"],
        points_reverse=["PT_149_R"],
        conflicting_routes=["ROUTE_P33_0003"],
        flank_protection_points=["FLANK_PT_048"],
        track_circuits_in_route=["TC_P33_148_A", "TC_P33_148_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_048"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P33_0149": RouteLockingRule(
        route_id="ROUTE_P33_0149",
        entry_signal="SIG_P33_149_ENTRY",
        exit_signal="SIG_P33_149_EXIT",
        points_normal=["PT_149_N"],
        points_reverse=["PT_150_R"],
        conflicting_routes=["ROUTE_P33_0004"],
        flank_protection_points=["FLANK_PT_049"],
        track_circuits_in_route=["TC_P33_149_A", "TC_P33_149_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_049"],
        permissible_aspect="PROCEED_GREEN"
    ),
}
