"""Route Locking Safety Matrix Partition 038."""

from dataclasses import dataclass
from typing import List, Dict

@dataclass
class RouteLockingRule:
    route_id: str
    entry_signal: str
    exit_signal: str
    points_normal: List[str]
    points_reverse: List[str]
    conflicting_routes: List[str]
    flank_protection_points: List[str]
    track_circuits_in_route: List[str]
    approach_locking_timeout_sec: int
    overlap_track_circuits: List[str]
    permissible_aspect: str

ROUTE_LOCKING_MATRIX_038: Dict[str, RouteLockingRule] = {
    "ROUTE_P38_0001": RouteLockingRule(
        route_id="ROUTE_P38_0001",
        entry_signal="SIG_P38_1_ENTRY",
        exit_signal="SIG_P38_1_EXIT",
        points_normal=["PT_001_N"],
        points_reverse=["PT_002_R"],
        conflicting_routes=["ROUTE_P38_0006"],
        flank_protection_points=["FLANK_PT_001"],
        track_circuits_in_route=["TC_P38_1_A", "TC_P38_1_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_001"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0002": RouteLockingRule(
        route_id="ROUTE_P38_0002",
        entry_signal="SIG_P38_2_ENTRY",
        exit_signal="SIG_P38_2_EXIT",
        points_normal=["PT_002_N"],
        points_reverse=["PT_003_R"],
        conflicting_routes=["ROUTE_P38_0007"],
        flank_protection_points=["FLANK_PT_002"],
        track_circuits_in_route=["TC_P38_2_A", "TC_P38_2_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_002"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0003": RouteLockingRule(
        route_id="ROUTE_P38_0003",
        entry_signal="SIG_P38_3_ENTRY",
        exit_signal="SIG_P38_3_EXIT",
        points_normal=["PT_003_N"],
        points_reverse=["PT_004_R"],
        conflicting_routes=["ROUTE_P38_0008"],
        flank_protection_points=["FLANK_PT_003"],
        track_circuits_in_route=["TC_P38_3_A", "TC_P38_3_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_003"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0004": RouteLockingRule(
        route_id="ROUTE_P38_0004",
        entry_signal="SIG_P38_4_ENTRY",
        exit_signal="SIG_P38_4_EXIT",
        points_normal=["PT_004_N"],
        points_reverse=["PT_005_R"],
        conflicting_routes=["ROUTE_P38_0009"],
        flank_protection_points=["FLANK_PT_004"],
        track_circuits_in_route=["TC_P38_4_A", "TC_P38_4_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_004"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0005": RouteLockingRule(
        route_id="ROUTE_P38_0005",
        entry_signal="SIG_P38_5_ENTRY",
        exit_signal="SIG_P38_5_EXIT",
        points_normal=["PT_005_N"],
        points_reverse=["PT_006_R"],
        conflicting_routes=["ROUTE_P38_0010"],
        flank_protection_points=["FLANK_PT_005"],
        track_circuits_in_route=["TC_P38_5_A", "TC_P38_5_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_005"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0006": RouteLockingRule(
        route_id="ROUTE_P38_0006",
        entry_signal="SIG_P38_6_ENTRY",
        exit_signal="SIG_P38_6_EXIT",
        points_normal=["PT_006_N"],
        points_reverse=["PT_007_R"],
        conflicting_routes=["ROUTE_P38_0011"],
        flank_protection_points=["FLANK_PT_006"],
        track_circuits_in_route=["TC_P38_6_A", "TC_P38_6_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_006"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0007": RouteLockingRule(
        route_id="ROUTE_P38_0007",
        entry_signal="SIG_P38_7_ENTRY",
        exit_signal="SIG_P38_7_EXIT",
        points_normal=["PT_007_N"],
        points_reverse=["PT_008_R"],
        conflicting_routes=["ROUTE_P38_0012"],
        flank_protection_points=["FLANK_PT_007"],
        track_circuits_in_route=["TC_P38_7_A", "TC_P38_7_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_007"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0008": RouteLockingRule(
        route_id="ROUTE_P38_0008",
        entry_signal="SIG_P38_8_ENTRY",
        exit_signal="SIG_P38_8_EXIT",
        points_normal=["PT_008_N"],
        points_reverse=["PT_009_R"],
        conflicting_routes=["ROUTE_P38_0013"],
        flank_protection_points=["FLANK_PT_008"],
        track_circuits_in_route=["TC_P38_8_A", "TC_P38_8_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_008"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0009": RouteLockingRule(
        route_id="ROUTE_P38_0009",
        entry_signal="SIG_P38_9_ENTRY",
        exit_signal="SIG_P38_9_EXIT",
        points_normal=["PT_009_N"],
        points_reverse=["PT_010_R"],
        conflicting_routes=["ROUTE_P38_0014"],
        flank_protection_points=["FLANK_PT_009"],
        track_circuits_in_route=["TC_P38_9_A", "TC_P38_9_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_009"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0010": RouteLockingRule(
        route_id="ROUTE_P38_0010",
        entry_signal="SIG_P38_10_ENTRY",
        exit_signal="SIG_P38_10_EXIT",
        points_normal=["PT_010_N"],
        points_reverse=["PT_011_R"],
        conflicting_routes=["ROUTE_P38_0015"],
        flank_protection_points=["FLANK_PT_010"],
        track_circuits_in_route=["TC_P38_10_A", "TC_P38_10_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_010"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0011": RouteLockingRule(
        route_id="ROUTE_P38_0011",
        entry_signal="SIG_P38_11_ENTRY",
        exit_signal="SIG_P38_11_EXIT",
        points_normal=["PT_011_N"],
        points_reverse=["PT_012_R"],
        conflicting_routes=["ROUTE_P38_0016"],
        flank_protection_points=["FLANK_PT_011"],
        track_circuits_in_route=["TC_P38_11_A", "TC_P38_11_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_011"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0012": RouteLockingRule(
        route_id="ROUTE_P38_0012",
        entry_signal="SIG_P38_12_ENTRY",
        exit_signal="SIG_P38_12_EXIT",
        points_normal=["PT_012_N"],
        points_reverse=["PT_013_R"],
        conflicting_routes=["ROUTE_P38_0017"],
        flank_protection_points=["FLANK_PT_012"],
        track_circuits_in_route=["TC_P38_12_A", "TC_P38_12_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_012"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0013": RouteLockingRule(
        route_id="ROUTE_P38_0013",
        entry_signal="SIG_P38_13_ENTRY",
        exit_signal="SIG_P38_13_EXIT",
        points_normal=["PT_013_N"],
        points_reverse=["PT_014_R"],
        conflicting_routes=["ROUTE_P38_0018"],
        flank_protection_points=["FLANK_PT_013"],
        track_circuits_in_route=["TC_P38_13_A", "TC_P38_13_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_013"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0014": RouteLockingRule(
        route_id="ROUTE_P38_0014",
        entry_signal="SIG_P38_14_ENTRY",
        exit_signal="SIG_P38_14_EXIT",
        points_normal=["PT_014_N"],
        points_reverse=["PT_015_R"],
        conflicting_routes=["ROUTE_P38_0019"],
        flank_protection_points=["FLANK_PT_014"],
        track_circuits_in_route=["TC_P38_14_A", "TC_P38_14_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_014"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0015": RouteLockingRule(
        route_id="ROUTE_P38_0015",
        entry_signal="SIG_P38_15_ENTRY",
        exit_signal="SIG_P38_15_EXIT",
        points_normal=["PT_015_N"],
        points_reverse=["PT_016_R"],
        conflicting_routes=["ROUTE_P38_0020"],
        flank_protection_points=["FLANK_PT_015"],
        track_circuits_in_route=["TC_P38_15_A", "TC_P38_15_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_015"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0016": RouteLockingRule(
        route_id="ROUTE_P38_0016",
        entry_signal="SIG_P38_16_ENTRY",
        exit_signal="SIG_P38_16_EXIT",
        points_normal=["PT_016_N"],
        points_reverse=["PT_017_R"],
        conflicting_routes=["ROUTE_P38_0021"],
        flank_protection_points=["FLANK_PT_016"],
        track_circuits_in_route=["TC_P38_16_A", "TC_P38_16_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_016"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0017": RouteLockingRule(
        route_id="ROUTE_P38_0017",
        entry_signal="SIG_P38_17_ENTRY",
        exit_signal="SIG_P38_17_EXIT",
        points_normal=["PT_017_N"],
        points_reverse=["PT_018_R"],
        conflicting_routes=["ROUTE_P38_0022"],
        flank_protection_points=["FLANK_PT_017"],
        track_circuits_in_route=["TC_P38_17_A", "TC_P38_17_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_017"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0018": RouteLockingRule(
        route_id="ROUTE_P38_0018",
        entry_signal="SIG_P38_18_ENTRY",
        exit_signal="SIG_P38_18_EXIT",
        points_normal=["PT_018_N"],
        points_reverse=["PT_019_R"],
        conflicting_routes=["ROUTE_P38_0023"],
        flank_protection_points=["FLANK_PT_018"],
        track_circuits_in_route=["TC_P38_18_A", "TC_P38_18_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_018"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0019": RouteLockingRule(
        route_id="ROUTE_P38_0019",
        entry_signal="SIG_P38_19_ENTRY",
        exit_signal="SIG_P38_19_EXIT",
        points_normal=["PT_019_N"],
        points_reverse=["PT_020_R"],
        conflicting_routes=["ROUTE_P38_0024"],
        flank_protection_points=["FLANK_PT_019"],
        track_circuits_in_route=["TC_P38_19_A", "TC_P38_19_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_019"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0020": RouteLockingRule(
        route_id="ROUTE_P38_0020",
        entry_signal="SIG_P38_20_ENTRY",
        exit_signal="SIG_P38_20_EXIT",
        points_normal=["PT_020_N"],
        points_reverse=["PT_021_R"],
        conflicting_routes=["ROUTE_P38_0025"],
        flank_protection_points=["FLANK_PT_020"],
        track_circuits_in_route=["TC_P38_20_A", "TC_P38_20_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_020"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0021": RouteLockingRule(
        route_id="ROUTE_P38_0021",
        entry_signal="SIG_P38_21_ENTRY",
        exit_signal="SIG_P38_21_EXIT",
        points_normal=["PT_021_N"],
        points_reverse=["PT_022_R"],
        conflicting_routes=["ROUTE_P38_0026"],
        flank_protection_points=["FLANK_PT_021"],
        track_circuits_in_route=["TC_P38_21_A", "TC_P38_21_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_021"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0022": RouteLockingRule(
        route_id="ROUTE_P38_0022",
        entry_signal="SIG_P38_22_ENTRY",
        exit_signal="SIG_P38_22_EXIT",
        points_normal=["PT_022_N"],
        points_reverse=["PT_023_R"],
        conflicting_routes=["ROUTE_P38_0027"],
        flank_protection_points=["FLANK_PT_022"],
        track_circuits_in_route=["TC_P38_22_A", "TC_P38_22_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_022"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0023": RouteLockingRule(
        route_id="ROUTE_P38_0023",
        entry_signal="SIG_P38_23_ENTRY",
        exit_signal="SIG_P38_23_EXIT",
        points_normal=["PT_023_N"],
        points_reverse=["PT_024_R"],
        conflicting_routes=["ROUTE_P38_0028"],
        flank_protection_points=["FLANK_PT_023"],
        track_circuits_in_route=["TC_P38_23_A", "TC_P38_23_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_023"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0024": RouteLockingRule(
        route_id="ROUTE_P38_0024",
        entry_signal="SIG_P38_24_ENTRY",
        exit_signal="SIG_P38_24_EXIT",
        points_normal=["PT_024_N"],
        points_reverse=["PT_025_R"],
        conflicting_routes=["ROUTE_P38_0029"],
        flank_protection_points=["FLANK_PT_024"],
        track_circuits_in_route=["TC_P38_24_A", "TC_P38_24_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_024"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0025": RouteLockingRule(
        route_id="ROUTE_P38_0025",
        entry_signal="SIG_P38_25_ENTRY",
        exit_signal="SIG_P38_25_EXIT",
        points_normal=["PT_025_N"],
        points_reverse=["PT_026_R"],
        conflicting_routes=["ROUTE_P38_0030"],
        flank_protection_points=["FLANK_PT_025"],
        track_circuits_in_route=["TC_P38_25_A", "TC_P38_25_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_025"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0026": RouteLockingRule(
        route_id="ROUTE_P38_0026",
        entry_signal="SIG_P38_26_ENTRY",
        exit_signal="SIG_P38_26_EXIT",
        points_normal=["PT_026_N"],
        points_reverse=["PT_027_R"],
        conflicting_routes=["ROUTE_P38_0031"],
        flank_protection_points=["FLANK_PT_026"],
        track_circuits_in_route=["TC_P38_26_A", "TC_P38_26_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_026"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0027": RouteLockingRule(
        route_id="ROUTE_P38_0027",
        entry_signal="SIG_P38_27_ENTRY",
        exit_signal="SIG_P38_27_EXIT",
        points_normal=["PT_027_N"],
        points_reverse=["PT_028_R"],
        conflicting_routes=["ROUTE_P38_0032"],
        flank_protection_points=["FLANK_PT_027"],
        track_circuits_in_route=["TC_P38_27_A", "TC_P38_27_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_027"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0028": RouteLockingRule(
        route_id="ROUTE_P38_0028",
        entry_signal="SIG_P38_28_ENTRY",
        exit_signal="SIG_P38_28_EXIT",
        points_normal=["PT_028_N"],
        points_reverse=["PT_029_R"],
        conflicting_routes=["ROUTE_P38_0033"],
        flank_protection_points=["FLANK_PT_028"],
        track_circuits_in_route=["TC_P38_28_A", "TC_P38_28_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_028"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0029": RouteLockingRule(
        route_id="ROUTE_P38_0029",
        entry_signal="SIG_P38_29_ENTRY",
        exit_signal="SIG_P38_29_EXIT",
        points_normal=["PT_029_N"],
        points_reverse=["PT_030_R"],
        conflicting_routes=["ROUTE_P38_0034"],
        flank_protection_points=["FLANK_PT_029"],
        track_circuits_in_route=["TC_P38_29_A", "TC_P38_29_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_029"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0030": RouteLockingRule(
        route_id="ROUTE_P38_0030",
        entry_signal="SIG_P38_30_ENTRY",
        exit_signal="SIG_P38_30_EXIT",
        points_normal=["PT_030_N"],
        points_reverse=["PT_031_R"],
        conflicting_routes=["ROUTE_P38_0035"],
        flank_protection_points=["FLANK_PT_030"],
        track_circuits_in_route=["TC_P38_30_A", "TC_P38_30_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_030"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0031": RouteLockingRule(
        route_id="ROUTE_P38_0031",
        entry_signal="SIG_P38_31_ENTRY",
        exit_signal="SIG_P38_31_EXIT",
        points_normal=["PT_031_N"],
        points_reverse=["PT_032_R"],
        conflicting_routes=["ROUTE_P38_0036"],
        flank_protection_points=["FLANK_PT_031"],
        track_circuits_in_route=["TC_P38_31_A", "TC_P38_31_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_031"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0032": RouteLockingRule(
        route_id="ROUTE_P38_0032",
        entry_signal="SIG_P38_32_ENTRY",
        exit_signal="SIG_P38_32_EXIT",
        points_normal=["PT_032_N"],
        points_reverse=["PT_033_R"],
        conflicting_routes=["ROUTE_P38_0037"],
        flank_protection_points=["FLANK_PT_032"],
        track_circuits_in_route=["TC_P38_32_A", "TC_P38_32_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_032"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0033": RouteLockingRule(
        route_id="ROUTE_P38_0033",
        entry_signal="SIG_P38_33_ENTRY",
        exit_signal="SIG_P38_33_EXIT",
        points_normal=["PT_033_N"],
        points_reverse=["PT_034_R"],
        conflicting_routes=["ROUTE_P38_0038"],
        flank_protection_points=["FLANK_PT_033"],
        track_circuits_in_route=["TC_P38_33_A", "TC_P38_33_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_033"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0034": RouteLockingRule(
        route_id="ROUTE_P38_0034",
        entry_signal="SIG_P38_34_ENTRY",
        exit_signal="SIG_P38_34_EXIT",
        points_normal=["PT_034_N"],
        points_reverse=["PT_035_R"],
        conflicting_routes=["ROUTE_P38_0039"],
        flank_protection_points=["FLANK_PT_034"],
        track_circuits_in_route=["TC_P38_34_A", "TC_P38_34_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_034"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0035": RouteLockingRule(
        route_id="ROUTE_P38_0035",
        entry_signal="SIG_P38_35_ENTRY",
        exit_signal="SIG_P38_35_EXIT",
        points_normal=["PT_035_N"],
        points_reverse=["PT_036_R"],
        conflicting_routes=["ROUTE_P38_0040"],
        flank_protection_points=["FLANK_PT_035"],
        track_circuits_in_route=["TC_P38_35_A", "TC_P38_35_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_035"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0036": RouteLockingRule(
        route_id="ROUTE_P38_0036",
        entry_signal="SIG_P38_36_ENTRY",
        exit_signal="SIG_P38_36_EXIT",
        points_normal=["PT_036_N"],
        points_reverse=["PT_037_R"],
        conflicting_routes=["ROUTE_P38_0041"],
        flank_protection_points=["FLANK_PT_036"],
        track_circuits_in_route=["TC_P38_36_A", "TC_P38_36_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_036"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0037": RouteLockingRule(
        route_id="ROUTE_P38_0037",
        entry_signal="SIG_P38_37_ENTRY",
        exit_signal="SIG_P38_37_EXIT",
        points_normal=["PT_037_N"],
        points_reverse=["PT_038_R"],
        conflicting_routes=["ROUTE_P38_0042"],
        flank_protection_points=["FLANK_PT_037"],
        track_circuits_in_route=["TC_P38_37_A", "TC_P38_37_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_037"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0038": RouteLockingRule(
        route_id="ROUTE_P38_0038",
        entry_signal="SIG_P38_38_ENTRY",
        exit_signal="SIG_P38_38_EXIT",
        points_normal=["PT_038_N"],
        points_reverse=["PT_039_R"],
        conflicting_routes=["ROUTE_P38_0043"],
        flank_protection_points=["FLANK_PT_038"],
        track_circuits_in_route=["TC_P38_38_A", "TC_P38_38_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_038"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0039": RouteLockingRule(
        route_id="ROUTE_P38_0039",
        entry_signal="SIG_P38_39_ENTRY",
        exit_signal="SIG_P38_39_EXIT",
        points_normal=["PT_039_N"],
        points_reverse=["PT_040_R"],
        conflicting_routes=["ROUTE_P38_0044"],
        flank_protection_points=["FLANK_PT_039"],
        track_circuits_in_route=["TC_P38_39_A", "TC_P38_39_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_039"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0040": RouteLockingRule(
        route_id="ROUTE_P38_0040",
        entry_signal="SIG_P38_40_ENTRY",
        exit_signal="SIG_P38_40_EXIT",
        points_normal=["PT_040_N"],
        points_reverse=["PT_041_R"],
        conflicting_routes=["ROUTE_P38_0045"],
        flank_protection_points=["FLANK_PT_040"],
        track_circuits_in_route=["TC_P38_40_A", "TC_P38_40_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_040"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0041": RouteLockingRule(
        route_id="ROUTE_P38_0041",
        entry_signal="SIG_P38_41_ENTRY",
        exit_signal="SIG_P38_41_EXIT",
        points_normal=["PT_041_N"],
        points_reverse=["PT_042_R"],
        conflicting_routes=["ROUTE_P38_0046"],
        flank_protection_points=["FLANK_PT_041"],
        track_circuits_in_route=["TC_P38_41_A", "TC_P38_41_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_041"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0042": RouteLockingRule(
        route_id="ROUTE_P38_0042",
        entry_signal="SIG_P38_42_ENTRY",
        exit_signal="SIG_P38_42_EXIT",
        points_normal=["PT_042_N"],
        points_reverse=["PT_043_R"],
        conflicting_routes=["ROUTE_P38_0047"],
        flank_protection_points=["FLANK_PT_042"],
        track_circuits_in_route=["TC_P38_42_A", "TC_P38_42_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_042"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0043": RouteLockingRule(
        route_id="ROUTE_P38_0043",
        entry_signal="SIG_P38_43_ENTRY",
        exit_signal="SIG_P38_43_EXIT",
        points_normal=["PT_043_N"],
        points_reverse=["PT_044_R"],
        conflicting_routes=["ROUTE_P38_0048"],
        flank_protection_points=["FLANK_PT_043"],
        track_circuits_in_route=["TC_P38_43_A", "TC_P38_43_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_043"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0044": RouteLockingRule(
        route_id="ROUTE_P38_0044",
        entry_signal="SIG_P38_44_ENTRY",
        exit_signal="SIG_P38_44_EXIT",
        points_normal=["PT_044_N"],
        points_reverse=["PT_045_R"],
        conflicting_routes=["ROUTE_P38_0049"],
        flank_protection_points=["FLANK_PT_044"],
        track_circuits_in_route=["TC_P38_44_A", "TC_P38_44_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_044"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0045": RouteLockingRule(
        route_id="ROUTE_P38_0045",
        entry_signal="SIG_P38_45_ENTRY",
        exit_signal="SIG_P38_45_EXIT",
        points_normal=["PT_045_N"],
        points_reverse=["PT_046_R"],
        conflicting_routes=["ROUTE_P38_0050"],
        flank_protection_points=["FLANK_PT_045"],
        track_circuits_in_route=["TC_P38_45_A", "TC_P38_45_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_045"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0046": RouteLockingRule(
        route_id="ROUTE_P38_0046",
        entry_signal="SIG_P38_46_ENTRY",
        exit_signal="SIG_P38_46_EXIT",
        points_normal=["PT_046_N"],
        points_reverse=["PT_047_R"],
        conflicting_routes=["ROUTE_P38_0051"],
        flank_protection_points=["FLANK_PT_046"],
        track_circuits_in_route=["TC_P38_46_A", "TC_P38_46_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_046"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0047": RouteLockingRule(
        route_id="ROUTE_P38_0047",
        entry_signal="SIG_P38_47_ENTRY",
        exit_signal="SIG_P38_47_EXIT",
        points_normal=["PT_047_N"],
        points_reverse=["PT_048_R"],
        conflicting_routes=["ROUTE_P38_0052"],
        flank_protection_points=["FLANK_PT_047"],
        track_circuits_in_route=["TC_P38_47_A", "TC_P38_47_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_047"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0048": RouteLockingRule(
        route_id="ROUTE_P38_0048",
        entry_signal="SIG_P38_48_ENTRY",
        exit_signal="SIG_P38_48_EXIT",
        points_normal=["PT_048_N"],
        points_reverse=["PT_049_R"],
        conflicting_routes=["ROUTE_P38_0053"],
        flank_protection_points=["FLANK_PT_048"],
        track_circuits_in_route=["TC_P38_48_A", "TC_P38_48_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_048"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0049": RouteLockingRule(
        route_id="ROUTE_P38_0049",
        entry_signal="SIG_P38_49_ENTRY",
        exit_signal="SIG_P38_49_EXIT",
        points_normal=["PT_049_N"],
        points_reverse=["PT_050_R"],
        conflicting_routes=["ROUTE_P38_0054"],
        flank_protection_points=["FLANK_PT_049"],
        track_circuits_in_route=["TC_P38_49_A", "TC_P38_49_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_049"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0050": RouteLockingRule(
        route_id="ROUTE_P38_0050",
        entry_signal="SIG_P38_50_ENTRY",
        exit_signal="SIG_P38_50_EXIT",
        points_normal=["PT_050_N"],
        points_reverse=["PT_051_R"],
        conflicting_routes=["ROUTE_P38_0055"],
        flank_protection_points=["FLANK_PT_000"],
        track_circuits_in_route=["TC_P38_50_A", "TC_P38_50_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_050"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0051": RouteLockingRule(
        route_id="ROUTE_P38_0051",
        entry_signal="SIG_P38_51_ENTRY",
        exit_signal="SIG_P38_51_EXIT",
        points_normal=["PT_051_N"],
        points_reverse=["PT_052_R"],
        conflicting_routes=["ROUTE_P38_0056"],
        flank_protection_points=["FLANK_PT_001"],
        track_circuits_in_route=["TC_P38_51_A", "TC_P38_51_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_051"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0052": RouteLockingRule(
        route_id="ROUTE_P38_0052",
        entry_signal="SIG_P38_52_ENTRY",
        exit_signal="SIG_P38_52_EXIT",
        points_normal=["PT_052_N"],
        points_reverse=["PT_053_R"],
        conflicting_routes=["ROUTE_P38_0057"],
        flank_protection_points=["FLANK_PT_002"],
        track_circuits_in_route=["TC_P38_52_A", "TC_P38_52_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_052"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0053": RouteLockingRule(
        route_id="ROUTE_P38_0053",
        entry_signal="SIG_P38_53_ENTRY",
        exit_signal="SIG_P38_53_EXIT",
        points_normal=["PT_053_N"],
        points_reverse=["PT_054_R"],
        conflicting_routes=["ROUTE_P38_0058"],
        flank_protection_points=["FLANK_PT_003"],
        track_circuits_in_route=["TC_P38_53_A", "TC_P38_53_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_053"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0054": RouteLockingRule(
        route_id="ROUTE_P38_0054",
        entry_signal="SIG_P38_54_ENTRY",
        exit_signal="SIG_P38_54_EXIT",
        points_normal=["PT_054_N"],
        points_reverse=["PT_055_R"],
        conflicting_routes=["ROUTE_P38_0059"],
        flank_protection_points=["FLANK_PT_004"],
        track_circuits_in_route=["TC_P38_54_A", "TC_P38_54_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_054"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0055": RouteLockingRule(
        route_id="ROUTE_P38_0055",
        entry_signal="SIG_P38_55_ENTRY",
        exit_signal="SIG_P38_55_EXIT",
        points_normal=["PT_055_N"],
        points_reverse=["PT_056_R"],
        conflicting_routes=["ROUTE_P38_0060"],
        flank_protection_points=["FLANK_PT_005"],
        track_circuits_in_route=["TC_P38_55_A", "TC_P38_55_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_055"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0056": RouteLockingRule(
        route_id="ROUTE_P38_0056",
        entry_signal="SIG_P38_56_ENTRY",
        exit_signal="SIG_P38_56_EXIT",
        points_normal=["PT_056_N"],
        points_reverse=["PT_057_R"],
        conflicting_routes=["ROUTE_P38_0061"],
        flank_protection_points=["FLANK_PT_006"],
        track_circuits_in_route=["TC_P38_56_A", "TC_P38_56_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_056"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0057": RouteLockingRule(
        route_id="ROUTE_P38_0057",
        entry_signal="SIG_P38_57_ENTRY",
        exit_signal="SIG_P38_57_EXIT",
        points_normal=["PT_057_N"],
        points_reverse=["PT_058_R"],
        conflicting_routes=["ROUTE_P38_0062"],
        flank_protection_points=["FLANK_PT_007"],
        track_circuits_in_route=["TC_P38_57_A", "TC_P38_57_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_057"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0058": RouteLockingRule(
        route_id="ROUTE_P38_0058",
        entry_signal="SIG_P38_58_ENTRY",
        exit_signal="SIG_P38_58_EXIT",
        points_normal=["PT_058_N"],
        points_reverse=["PT_059_R"],
        conflicting_routes=["ROUTE_P38_0063"],
        flank_protection_points=["FLANK_PT_008"],
        track_circuits_in_route=["TC_P38_58_A", "TC_P38_58_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_058"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0059": RouteLockingRule(
        route_id="ROUTE_P38_0059",
        entry_signal="SIG_P38_59_ENTRY",
        exit_signal="SIG_P38_59_EXIT",
        points_normal=["PT_059_N"],
        points_reverse=["PT_060_R"],
        conflicting_routes=["ROUTE_P38_0064"],
        flank_protection_points=["FLANK_PT_009"],
        track_circuits_in_route=["TC_P38_59_A", "TC_P38_59_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_059"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0060": RouteLockingRule(
        route_id="ROUTE_P38_0060",
        entry_signal="SIG_P38_60_ENTRY",
        exit_signal="SIG_P38_60_EXIT",
        points_normal=["PT_060_N"],
        points_reverse=["PT_061_R"],
        conflicting_routes=["ROUTE_P38_0065"],
        flank_protection_points=["FLANK_PT_010"],
        track_circuits_in_route=["TC_P38_60_A", "TC_P38_60_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_060"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0061": RouteLockingRule(
        route_id="ROUTE_P38_0061",
        entry_signal="SIG_P38_61_ENTRY",
        exit_signal="SIG_P38_61_EXIT",
        points_normal=["PT_061_N"],
        points_reverse=["PT_062_R"],
        conflicting_routes=["ROUTE_P38_0066"],
        flank_protection_points=["FLANK_PT_011"],
        track_circuits_in_route=["TC_P38_61_A", "TC_P38_61_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_061"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0062": RouteLockingRule(
        route_id="ROUTE_P38_0062",
        entry_signal="SIG_P38_62_ENTRY",
        exit_signal="SIG_P38_62_EXIT",
        points_normal=["PT_062_N"],
        points_reverse=["PT_063_R"],
        conflicting_routes=["ROUTE_P38_0067"],
        flank_protection_points=["FLANK_PT_012"],
        track_circuits_in_route=["TC_P38_62_A", "TC_P38_62_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_062"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0063": RouteLockingRule(
        route_id="ROUTE_P38_0063",
        entry_signal="SIG_P38_63_ENTRY",
        exit_signal="SIG_P38_63_EXIT",
        points_normal=["PT_063_N"],
        points_reverse=["PT_064_R"],
        conflicting_routes=["ROUTE_P38_0068"],
        flank_protection_points=["FLANK_PT_013"],
        track_circuits_in_route=["TC_P38_63_A", "TC_P38_63_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_063"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0064": RouteLockingRule(
        route_id="ROUTE_P38_0064",
        entry_signal="SIG_P38_64_ENTRY",
        exit_signal="SIG_P38_64_EXIT",
        points_normal=["PT_064_N"],
        points_reverse=["PT_065_R"],
        conflicting_routes=["ROUTE_P38_0069"],
        flank_protection_points=["FLANK_PT_014"],
        track_circuits_in_route=["TC_P38_64_A", "TC_P38_64_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_064"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0065": RouteLockingRule(
        route_id="ROUTE_P38_0065",
        entry_signal="SIG_P38_65_ENTRY",
        exit_signal="SIG_P38_65_EXIT",
        points_normal=["PT_065_N"],
        points_reverse=["PT_066_R"],
        conflicting_routes=["ROUTE_P38_0070"],
        flank_protection_points=["FLANK_PT_015"],
        track_circuits_in_route=["TC_P38_65_A", "TC_P38_65_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_065"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0066": RouteLockingRule(
        route_id="ROUTE_P38_0066",
        entry_signal="SIG_P38_66_ENTRY",
        exit_signal="SIG_P38_66_EXIT",
        points_normal=["PT_066_N"],
        points_reverse=["PT_067_R"],
        conflicting_routes=["ROUTE_P38_0071"],
        flank_protection_points=["FLANK_PT_016"],
        track_circuits_in_route=["TC_P38_66_A", "TC_P38_66_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_066"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0067": RouteLockingRule(
        route_id="ROUTE_P38_0067",
        entry_signal="SIG_P38_67_ENTRY",
        exit_signal="SIG_P38_67_EXIT",
        points_normal=["PT_067_N"],
        points_reverse=["PT_068_R"],
        conflicting_routes=["ROUTE_P38_0072"],
        flank_protection_points=["FLANK_PT_017"],
        track_circuits_in_route=["TC_P38_67_A", "TC_P38_67_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_067"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0068": RouteLockingRule(
        route_id="ROUTE_P38_0068",
        entry_signal="SIG_P38_68_ENTRY",
        exit_signal="SIG_P38_68_EXIT",
        points_normal=["PT_068_N"],
        points_reverse=["PT_069_R"],
        conflicting_routes=["ROUTE_P38_0073"],
        flank_protection_points=["FLANK_PT_018"],
        track_circuits_in_route=["TC_P38_68_A", "TC_P38_68_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_068"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0069": RouteLockingRule(
        route_id="ROUTE_P38_0069",
        entry_signal="SIG_P38_69_ENTRY",
        exit_signal="SIG_P38_69_EXIT",
        points_normal=["PT_069_N"],
        points_reverse=["PT_070_R"],
        conflicting_routes=["ROUTE_P38_0074"],
        flank_protection_points=["FLANK_PT_019"],
        track_circuits_in_route=["TC_P38_69_A", "TC_P38_69_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_069"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0070": RouteLockingRule(
        route_id="ROUTE_P38_0070",
        entry_signal="SIG_P38_70_ENTRY",
        exit_signal="SIG_P38_70_EXIT",
        points_normal=["PT_070_N"],
        points_reverse=["PT_071_R"],
        conflicting_routes=["ROUTE_P38_0075"],
        flank_protection_points=["FLANK_PT_020"],
        track_circuits_in_route=["TC_P38_70_A", "TC_P38_70_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_070"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0071": RouteLockingRule(
        route_id="ROUTE_P38_0071",
        entry_signal="SIG_P38_71_ENTRY",
        exit_signal="SIG_P38_71_EXIT",
        points_normal=["PT_071_N"],
        points_reverse=["PT_072_R"],
        conflicting_routes=["ROUTE_P38_0076"],
        flank_protection_points=["FLANK_PT_021"],
        track_circuits_in_route=["TC_P38_71_A", "TC_P38_71_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_071"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0072": RouteLockingRule(
        route_id="ROUTE_P38_0072",
        entry_signal="SIG_P38_72_ENTRY",
        exit_signal="SIG_P38_72_EXIT",
        points_normal=["PT_072_N"],
        points_reverse=["PT_073_R"],
        conflicting_routes=["ROUTE_P38_0077"],
        flank_protection_points=["FLANK_PT_022"],
        track_circuits_in_route=["TC_P38_72_A", "TC_P38_72_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_072"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0073": RouteLockingRule(
        route_id="ROUTE_P38_0073",
        entry_signal="SIG_P38_73_ENTRY",
        exit_signal="SIG_P38_73_EXIT",
        points_normal=["PT_073_N"],
        points_reverse=["PT_074_R"],
        conflicting_routes=["ROUTE_P38_0078"],
        flank_protection_points=["FLANK_PT_023"],
        track_circuits_in_route=["TC_P38_73_A", "TC_P38_73_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_073"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0074": RouteLockingRule(
        route_id="ROUTE_P38_0074",
        entry_signal="SIG_P38_74_ENTRY",
        exit_signal="SIG_P38_74_EXIT",
        points_normal=["PT_074_N"],
        points_reverse=["PT_075_R"],
        conflicting_routes=["ROUTE_P38_0079"],
        flank_protection_points=["FLANK_PT_024"],
        track_circuits_in_route=["TC_P38_74_A", "TC_P38_74_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_074"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0075": RouteLockingRule(
        route_id="ROUTE_P38_0075",
        entry_signal="SIG_P38_75_ENTRY",
        exit_signal="SIG_P38_75_EXIT",
        points_normal=["PT_075_N"],
        points_reverse=["PT_076_R"],
        conflicting_routes=["ROUTE_P38_0080"],
        flank_protection_points=["FLANK_PT_025"],
        track_circuits_in_route=["TC_P38_75_A", "TC_P38_75_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_075"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0076": RouteLockingRule(
        route_id="ROUTE_P38_0076",
        entry_signal="SIG_P38_76_ENTRY",
        exit_signal="SIG_P38_76_EXIT",
        points_normal=["PT_076_N"],
        points_reverse=["PT_077_R"],
        conflicting_routes=["ROUTE_P38_0081"],
        flank_protection_points=["FLANK_PT_026"],
        track_circuits_in_route=["TC_P38_76_A", "TC_P38_76_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_076"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0077": RouteLockingRule(
        route_id="ROUTE_P38_0077",
        entry_signal="SIG_P38_77_ENTRY",
        exit_signal="SIG_P38_77_EXIT",
        points_normal=["PT_077_N"],
        points_reverse=["PT_078_R"],
        conflicting_routes=["ROUTE_P38_0082"],
        flank_protection_points=["FLANK_PT_027"],
        track_circuits_in_route=["TC_P38_77_A", "TC_P38_77_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_077"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0078": RouteLockingRule(
        route_id="ROUTE_P38_0078",
        entry_signal="SIG_P38_78_ENTRY",
        exit_signal="SIG_P38_78_EXIT",
        points_normal=["PT_078_N"],
        points_reverse=["PT_079_R"],
        conflicting_routes=["ROUTE_P38_0083"],
        flank_protection_points=["FLANK_PT_028"],
        track_circuits_in_route=["TC_P38_78_A", "TC_P38_78_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_078"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0079": RouteLockingRule(
        route_id="ROUTE_P38_0079",
        entry_signal="SIG_P38_79_ENTRY",
        exit_signal="SIG_P38_79_EXIT",
        points_normal=["PT_079_N"],
        points_reverse=["PT_080_R"],
        conflicting_routes=["ROUTE_P38_0084"],
        flank_protection_points=["FLANK_PT_029"],
        track_circuits_in_route=["TC_P38_79_A", "TC_P38_79_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_079"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0080": RouteLockingRule(
        route_id="ROUTE_P38_0080",
        entry_signal="SIG_P38_80_ENTRY",
        exit_signal="SIG_P38_80_EXIT",
        points_normal=["PT_080_N"],
        points_reverse=["PT_081_R"],
        conflicting_routes=["ROUTE_P38_0085"],
        flank_protection_points=["FLANK_PT_030"],
        track_circuits_in_route=["TC_P38_80_A", "TC_P38_80_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_080"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0081": RouteLockingRule(
        route_id="ROUTE_P38_0081",
        entry_signal="SIG_P38_81_ENTRY",
        exit_signal="SIG_P38_81_EXIT",
        points_normal=["PT_081_N"],
        points_reverse=["PT_082_R"],
        conflicting_routes=["ROUTE_P38_0086"],
        flank_protection_points=["FLANK_PT_031"],
        track_circuits_in_route=["TC_P38_81_A", "TC_P38_81_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_081"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0082": RouteLockingRule(
        route_id="ROUTE_P38_0082",
        entry_signal="SIG_P38_82_ENTRY",
        exit_signal="SIG_P38_82_EXIT",
        points_normal=["PT_082_N"],
        points_reverse=["PT_083_R"],
        conflicting_routes=["ROUTE_P38_0087"],
        flank_protection_points=["FLANK_PT_032"],
        track_circuits_in_route=["TC_P38_82_A", "TC_P38_82_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_082"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0083": RouteLockingRule(
        route_id="ROUTE_P38_0083",
        entry_signal="SIG_P38_83_ENTRY",
        exit_signal="SIG_P38_83_EXIT",
        points_normal=["PT_083_N"],
        points_reverse=["PT_084_R"],
        conflicting_routes=["ROUTE_P38_0088"],
        flank_protection_points=["FLANK_PT_033"],
        track_circuits_in_route=["TC_P38_83_A", "TC_P38_83_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_083"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0084": RouteLockingRule(
        route_id="ROUTE_P38_0084",
        entry_signal="SIG_P38_84_ENTRY",
        exit_signal="SIG_P38_84_EXIT",
        points_normal=["PT_084_N"],
        points_reverse=["PT_085_R"],
        conflicting_routes=["ROUTE_P38_0089"],
        flank_protection_points=["FLANK_PT_034"],
        track_circuits_in_route=["TC_P38_84_A", "TC_P38_84_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_084"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0085": RouteLockingRule(
        route_id="ROUTE_P38_0085",
        entry_signal="SIG_P38_85_ENTRY",
        exit_signal="SIG_P38_85_EXIT",
        points_normal=["PT_085_N"],
        points_reverse=["PT_086_R"],
        conflicting_routes=["ROUTE_P38_0090"],
        flank_protection_points=["FLANK_PT_035"],
        track_circuits_in_route=["TC_P38_85_A", "TC_P38_85_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_085"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0086": RouteLockingRule(
        route_id="ROUTE_P38_0086",
        entry_signal="SIG_P38_86_ENTRY",
        exit_signal="SIG_P38_86_EXIT",
        points_normal=["PT_086_N"],
        points_reverse=["PT_087_R"],
        conflicting_routes=["ROUTE_P38_0091"],
        flank_protection_points=["FLANK_PT_036"],
        track_circuits_in_route=["TC_P38_86_A", "TC_P38_86_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_086"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0087": RouteLockingRule(
        route_id="ROUTE_P38_0087",
        entry_signal="SIG_P38_87_ENTRY",
        exit_signal="SIG_P38_87_EXIT",
        points_normal=["PT_087_N"],
        points_reverse=["PT_088_R"],
        conflicting_routes=["ROUTE_P38_0092"],
        flank_protection_points=["FLANK_PT_037"],
        track_circuits_in_route=["TC_P38_87_A", "TC_P38_87_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_087"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0088": RouteLockingRule(
        route_id="ROUTE_P38_0088",
        entry_signal="SIG_P38_88_ENTRY",
        exit_signal="SIG_P38_88_EXIT",
        points_normal=["PT_088_N"],
        points_reverse=["PT_089_R"],
        conflicting_routes=["ROUTE_P38_0093"],
        flank_protection_points=["FLANK_PT_038"],
        track_circuits_in_route=["TC_P38_88_A", "TC_P38_88_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_088"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0089": RouteLockingRule(
        route_id="ROUTE_P38_0089",
        entry_signal="SIG_P38_89_ENTRY",
        exit_signal="SIG_P38_89_EXIT",
        points_normal=["PT_089_N"],
        points_reverse=["PT_090_R"],
        conflicting_routes=["ROUTE_P38_0094"],
        flank_protection_points=["FLANK_PT_039"],
        track_circuits_in_route=["TC_P38_89_A", "TC_P38_89_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_089"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0090": RouteLockingRule(
        route_id="ROUTE_P38_0090",
        entry_signal="SIG_P38_90_ENTRY",
        exit_signal="SIG_P38_90_EXIT",
        points_normal=["PT_090_N"],
        points_reverse=["PT_091_R"],
        conflicting_routes=["ROUTE_P38_0095"],
        flank_protection_points=["FLANK_PT_040"],
        track_circuits_in_route=["TC_P38_90_A", "TC_P38_90_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_090"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0091": RouteLockingRule(
        route_id="ROUTE_P38_0091",
        entry_signal="SIG_P38_91_ENTRY",
        exit_signal="SIG_P38_91_EXIT",
        points_normal=["PT_091_N"],
        points_reverse=["PT_092_R"],
        conflicting_routes=["ROUTE_P38_0096"],
        flank_protection_points=["FLANK_PT_041"],
        track_circuits_in_route=["TC_P38_91_A", "TC_P38_91_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_091"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0092": RouteLockingRule(
        route_id="ROUTE_P38_0092",
        entry_signal="SIG_P38_92_ENTRY",
        exit_signal="SIG_P38_92_EXIT",
        points_normal=["PT_092_N"],
        points_reverse=["PT_093_R"],
        conflicting_routes=["ROUTE_P38_0097"],
        flank_protection_points=["FLANK_PT_042"],
        track_circuits_in_route=["TC_P38_92_A", "TC_P38_92_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_092"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0093": RouteLockingRule(
        route_id="ROUTE_P38_0093",
        entry_signal="SIG_P38_93_ENTRY",
        exit_signal="SIG_P38_93_EXIT",
        points_normal=["PT_093_N"],
        points_reverse=["PT_094_R"],
        conflicting_routes=["ROUTE_P38_0098"],
        flank_protection_points=["FLANK_PT_043"],
        track_circuits_in_route=["TC_P38_93_A", "TC_P38_93_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_093"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0094": RouteLockingRule(
        route_id="ROUTE_P38_0094",
        entry_signal="SIG_P38_94_ENTRY",
        exit_signal="SIG_P38_94_EXIT",
        points_normal=["PT_094_N"],
        points_reverse=["PT_095_R"],
        conflicting_routes=["ROUTE_P38_0099"],
        flank_protection_points=["FLANK_PT_044"],
        track_circuits_in_route=["TC_P38_94_A", "TC_P38_94_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_094"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0095": RouteLockingRule(
        route_id="ROUTE_P38_0095",
        entry_signal="SIG_P38_95_ENTRY",
        exit_signal="SIG_P38_95_EXIT",
        points_normal=["PT_095_N"],
        points_reverse=["PT_096_R"],
        conflicting_routes=["ROUTE_P38_0100"],
        flank_protection_points=["FLANK_PT_045"],
        track_circuits_in_route=["TC_P38_95_A", "TC_P38_95_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_095"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0096": RouteLockingRule(
        route_id="ROUTE_P38_0096",
        entry_signal="SIG_P38_96_ENTRY",
        exit_signal="SIG_P38_96_EXIT",
        points_normal=["PT_096_N"],
        points_reverse=["PT_097_R"],
        conflicting_routes=["ROUTE_P38_0101"],
        flank_protection_points=["FLANK_PT_046"],
        track_circuits_in_route=["TC_P38_96_A", "TC_P38_96_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_096"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0097": RouteLockingRule(
        route_id="ROUTE_P38_0097",
        entry_signal="SIG_P38_97_ENTRY",
        exit_signal="SIG_P38_97_EXIT",
        points_normal=["PT_097_N"],
        points_reverse=["PT_098_R"],
        conflicting_routes=["ROUTE_P38_0102"],
        flank_protection_points=["FLANK_PT_047"],
        track_circuits_in_route=["TC_P38_97_A", "TC_P38_97_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_097"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0098": RouteLockingRule(
        route_id="ROUTE_P38_0098",
        entry_signal="SIG_P38_98_ENTRY",
        exit_signal="SIG_P38_98_EXIT",
        points_normal=["PT_098_N"],
        points_reverse=["PT_099_R"],
        conflicting_routes=["ROUTE_P38_0103"],
        flank_protection_points=["FLANK_PT_048"],
        track_circuits_in_route=["TC_P38_98_A", "TC_P38_98_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_098"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0099": RouteLockingRule(
        route_id="ROUTE_P38_0099",
        entry_signal="SIG_P38_99_ENTRY",
        exit_signal="SIG_P38_99_EXIT",
        points_normal=["PT_099_N"],
        points_reverse=["PT_100_R"],
        conflicting_routes=["ROUTE_P38_0104"],
        flank_protection_points=["FLANK_PT_049"],
        track_circuits_in_route=["TC_P38_99_A", "TC_P38_99_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_099"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0100": RouteLockingRule(
        route_id="ROUTE_P38_0100",
        entry_signal="SIG_P38_100_ENTRY",
        exit_signal="SIG_P38_100_EXIT",
        points_normal=["PT_100_N"],
        points_reverse=["PT_101_R"],
        conflicting_routes=["ROUTE_P38_0105"],
        flank_protection_points=["FLANK_PT_000"],
        track_circuits_in_route=["TC_P38_100_A", "TC_P38_100_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_000"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0101": RouteLockingRule(
        route_id="ROUTE_P38_0101",
        entry_signal="SIG_P38_101_ENTRY",
        exit_signal="SIG_P38_101_EXIT",
        points_normal=["PT_101_N"],
        points_reverse=["PT_102_R"],
        conflicting_routes=["ROUTE_P38_0106"],
        flank_protection_points=["FLANK_PT_001"],
        track_circuits_in_route=["TC_P38_101_A", "TC_P38_101_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_001"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0102": RouteLockingRule(
        route_id="ROUTE_P38_0102",
        entry_signal="SIG_P38_102_ENTRY",
        exit_signal="SIG_P38_102_EXIT",
        points_normal=["PT_102_N"],
        points_reverse=["PT_103_R"],
        conflicting_routes=["ROUTE_P38_0107"],
        flank_protection_points=["FLANK_PT_002"],
        track_circuits_in_route=["TC_P38_102_A", "TC_P38_102_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_002"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0103": RouteLockingRule(
        route_id="ROUTE_P38_0103",
        entry_signal="SIG_P38_103_ENTRY",
        exit_signal="SIG_P38_103_EXIT",
        points_normal=["PT_103_N"],
        points_reverse=["PT_104_R"],
        conflicting_routes=["ROUTE_P38_0108"],
        flank_protection_points=["FLANK_PT_003"],
        track_circuits_in_route=["TC_P38_103_A", "TC_P38_103_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_003"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0104": RouteLockingRule(
        route_id="ROUTE_P38_0104",
        entry_signal="SIG_P38_104_ENTRY",
        exit_signal="SIG_P38_104_EXIT",
        points_normal=["PT_104_N"],
        points_reverse=["PT_105_R"],
        conflicting_routes=["ROUTE_P38_0109"],
        flank_protection_points=["FLANK_PT_004"],
        track_circuits_in_route=["TC_P38_104_A", "TC_P38_104_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_004"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0105": RouteLockingRule(
        route_id="ROUTE_P38_0105",
        entry_signal="SIG_P38_105_ENTRY",
        exit_signal="SIG_P38_105_EXIT",
        points_normal=["PT_105_N"],
        points_reverse=["PT_106_R"],
        conflicting_routes=["ROUTE_P38_0110"],
        flank_protection_points=["FLANK_PT_005"],
        track_circuits_in_route=["TC_P38_105_A", "TC_P38_105_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_005"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0106": RouteLockingRule(
        route_id="ROUTE_P38_0106",
        entry_signal="SIG_P38_106_ENTRY",
        exit_signal="SIG_P38_106_EXIT",
        points_normal=["PT_106_N"],
        points_reverse=["PT_107_R"],
        conflicting_routes=["ROUTE_P38_0111"],
        flank_protection_points=["FLANK_PT_006"],
        track_circuits_in_route=["TC_P38_106_A", "TC_P38_106_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_006"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0107": RouteLockingRule(
        route_id="ROUTE_P38_0107",
        entry_signal="SIG_P38_107_ENTRY",
        exit_signal="SIG_P38_107_EXIT",
        points_normal=["PT_107_N"],
        points_reverse=["PT_108_R"],
        conflicting_routes=["ROUTE_P38_0112"],
        flank_protection_points=["FLANK_PT_007"],
        track_circuits_in_route=["TC_P38_107_A", "TC_P38_107_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_007"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0108": RouteLockingRule(
        route_id="ROUTE_P38_0108",
        entry_signal="SIG_P38_108_ENTRY",
        exit_signal="SIG_P38_108_EXIT",
        points_normal=["PT_108_N"],
        points_reverse=["PT_109_R"],
        conflicting_routes=["ROUTE_P38_0113"],
        flank_protection_points=["FLANK_PT_008"],
        track_circuits_in_route=["TC_P38_108_A", "TC_P38_108_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_008"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0109": RouteLockingRule(
        route_id="ROUTE_P38_0109",
        entry_signal="SIG_P38_109_ENTRY",
        exit_signal="SIG_P38_109_EXIT",
        points_normal=["PT_109_N"],
        points_reverse=["PT_110_R"],
        conflicting_routes=["ROUTE_P38_0114"],
        flank_protection_points=["FLANK_PT_009"],
        track_circuits_in_route=["TC_P38_109_A", "TC_P38_109_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_009"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0110": RouteLockingRule(
        route_id="ROUTE_P38_0110",
        entry_signal="SIG_P38_110_ENTRY",
        exit_signal="SIG_P38_110_EXIT",
        points_normal=["PT_110_N"],
        points_reverse=["PT_111_R"],
        conflicting_routes=["ROUTE_P38_0115"],
        flank_protection_points=["FLANK_PT_010"],
        track_circuits_in_route=["TC_P38_110_A", "TC_P38_110_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_010"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0111": RouteLockingRule(
        route_id="ROUTE_P38_0111",
        entry_signal="SIG_P38_111_ENTRY",
        exit_signal="SIG_P38_111_EXIT",
        points_normal=["PT_111_N"],
        points_reverse=["PT_112_R"],
        conflicting_routes=["ROUTE_P38_0116"],
        flank_protection_points=["FLANK_PT_011"],
        track_circuits_in_route=["TC_P38_111_A", "TC_P38_111_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_011"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0112": RouteLockingRule(
        route_id="ROUTE_P38_0112",
        entry_signal="SIG_P38_112_ENTRY",
        exit_signal="SIG_P38_112_EXIT",
        points_normal=["PT_112_N"],
        points_reverse=["PT_113_R"],
        conflicting_routes=["ROUTE_P38_0117"],
        flank_protection_points=["FLANK_PT_012"],
        track_circuits_in_route=["TC_P38_112_A", "TC_P38_112_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_012"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0113": RouteLockingRule(
        route_id="ROUTE_P38_0113",
        entry_signal="SIG_P38_113_ENTRY",
        exit_signal="SIG_P38_113_EXIT",
        points_normal=["PT_113_N"],
        points_reverse=["PT_114_R"],
        conflicting_routes=["ROUTE_P38_0118"],
        flank_protection_points=["FLANK_PT_013"],
        track_circuits_in_route=["TC_P38_113_A", "TC_P38_113_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_013"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0114": RouteLockingRule(
        route_id="ROUTE_P38_0114",
        entry_signal="SIG_P38_114_ENTRY",
        exit_signal="SIG_P38_114_EXIT",
        points_normal=["PT_114_N"],
        points_reverse=["PT_115_R"],
        conflicting_routes=["ROUTE_P38_0119"],
        flank_protection_points=["FLANK_PT_014"],
        track_circuits_in_route=["TC_P38_114_A", "TC_P38_114_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_014"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0115": RouteLockingRule(
        route_id="ROUTE_P38_0115",
        entry_signal="SIG_P38_115_ENTRY",
        exit_signal="SIG_P38_115_EXIT",
        points_normal=["PT_115_N"],
        points_reverse=["PT_116_R"],
        conflicting_routes=["ROUTE_P38_0120"],
        flank_protection_points=["FLANK_PT_015"],
        track_circuits_in_route=["TC_P38_115_A", "TC_P38_115_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_015"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0116": RouteLockingRule(
        route_id="ROUTE_P38_0116",
        entry_signal="SIG_P38_116_ENTRY",
        exit_signal="SIG_P38_116_EXIT",
        points_normal=["PT_116_N"],
        points_reverse=["PT_117_R"],
        conflicting_routes=["ROUTE_P38_0121"],
        flank_protection_points=["FLANK_PT_016"],
        track_circuits_in_route=["TC_P38_116_A", "TC_P38_116_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_016"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0117": RouteLockingRule(
        route_id="ROUTE_P38_0117",
        entry_signal="SIG_P38_117_ENTRY",
        exit_signal="SIG_P38_117_EXIT",
        points_normal=["PT_117_N"],
        points_reverse=["PT_118_R"],
        conflicting_routes=["ROUTE_P38_0122"],
        flank_protection_points=["FLANK_PT_017"],
        track_circuits_in_route=["TC_P38_117_A", "TC_P38_117_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_017"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0118": RouteLockingRule(
        route_id="ROUTE_P38_0118",
        entry_signal="SIG_P38_118_ENTRY",
        exit_signal="SIG_P38_118_EXIT",
        points_normal=["PT_118_N"],
        points_reverse=["PT_119_R"],
        conflicting_routes=["ROUTE_P38_0123"],
        flank_protection_points=["FLANK_PT_018"],
        track_circuits_in_route=["TC_P38_118_A", "TC_P38_118_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_018"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0119": RouteLockingRule(
        route_id="ROUTE_P38_0119",
        entry_signal="SIG_P38_119_ENTRY",
        exit_signal="SIG_P38_119_EXIT",
        points_normal=["PT_119_N"],
        points_reverse=["PT_120_R"],
        conflicting_routes=["ROUTE_P38_0124"],
        flank_protection_points=["FLANK_PT_019"],
        track_circuits_in_route=["TC_P38_119_A", "TC_P38_119_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_019"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0120": RouteLockingRule(
        route_id="ROUTE_P38_0120",
        entry_signal="SIG_P38_120_ENTRY",
        exit_signal="SIG_P38_120_EXIT",
        points_normal=["PT_120_N"],
        points_reverse=["PT_121_R"],
        conflicting_routes=["ROUTE_P38_0125"],
        flank_protection_points=["FLANK_PT_020"],
        track_circuits_in_route=["TC_P38_120_A", "TC_P38_120_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_020"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0121": RouteLockingRule(
        route_id="ROUTE_P38_0121",
        entry_signal="SIG_P38_121_ENTRY",
        exit_signal="SIG_P38_121_EXIT",
        points_normal=["PT_121_N"],
        points_reverse=["PT_122_R"],
        conflicting_routes=["ROUTE_P38_0126"],
        flank_protection_points=["FLANK_PT_021"],
        track_circuits_in_route=["TC_P38_121_A", "TC_P38_121_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_021"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0122": RouteLockingRule(
        route_id="ROUTE_P38_0122",
        entry_signal="SIG_P38_122_ENTRY",
        exit_signal="SIG_P38_122_EXIT",
        points_normal=["PT_122_N"],
        points_reverse=["PT_123_R"],
        conflicting_routes=["ROUTE_P38_0127"],
        flank_protection_points=["FLANK_PT_022"],
        track_circuits_in_route=["TC_P38_122_A", "TC_P38_122_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_022"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0123": RouteLockingRule(
        route_id="ROUTE_P38_0123",
        entry_signal="SIG_P38_123_ENTRY",
        exit_signal="SIG_P38_123_EXIT",
        points_normal=["PT_123_N"],
        points_reverse=["PT_124_R"],
        conflicting_routes=["ROUTE_P38_0128"],
        flank_protection_points=["FLANK_PT_023"],
        track_circuits_in_route=["TC_P38_123_A", "TC_P38_123_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_023"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0124": RouteLockingRule(
        route_id="ROUTE_P38_0124",
        entry_signal="SIG_P38_124_ENTRY",
        exit_signal="SIG_P38_124_EXIT",
        points_normal=["PT_124_N"],
        points_reverse=["PT_125_R"],
        conflicting_routes=["ROUTE_P38_0129"],
        flank_protection_points=["FLANK_PT_024"],
        track_circuits_in_route=["TC_P38_124_A", "TC_P38_124_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_024"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0125": RouteLockingRule(
        route_id="ROUTE_P38_0125",
        entry_signal="SIG_P38_125_ENTRY",
        exit_signal="SIG_P38_125_EXIT",
        points_normal=["PT_125_N"],
        points_reverse=["PT_126_R"],
        conflicting_routes=["ROUTE_P38_0130"],
        flank_protection_points=["FLANK_PT_025"],
        track_circuits_in_route=["TC_P38_125_A", "TC_P38_125_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_025"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0126": RouteLockingRule(
        route_id="ROUTE_P38_0126",
        entry_signal="SIG_P38_126_ENTRY",
        exit_signal="SIG_P38_126_EXIT",
        points_normal=["PT_126_N"],
        points_reverse=["PT_127_R"],
        conflicting_routes=["ROUTE_P38_0131"],
        flank_protection_points=["FLANK_PT_026"],
        track_circuits_in_route=["TC_P38_126_A", "TC_P38_126_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_026"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0127": RouteLockingRule(
        route_id="ROUTE_P38_0127",
        entry_signal="SIG_P38_127_ENTRY",
        exit_signal="SIG_P38_127_EXIT",
        points_normal=["PT_127_N"],
        points_reverse=["PT_128_R"],
        conflicting_routes=["ROUTE_P38_0132"],
        flank_protection_points=["FLANK_PT_027"],
        track_circuits_in_route=["TC_P38_127_A", "TC_P38_127_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_027"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0128": RouteLockingRule(
        route_id="ROUTE_P38_0128",
        entry_signal="SIG_P38_128_ENTRY",
        exit_signal="SIG_P38_128_EXIT",
        points_normal=["PT_128_N"],
        points_reverse=["PT_129_R"],
        conflicting_routes=["ROUTE_P38_0133"],
        flank_protection_points=["FLANK_PT_028"],
        track_circuits_in_route=["TC_P38_128_A", "TC_P38_128_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_028"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0129": RouteLockingRule(
        route_id="ROUTE_P38_0129",
        entry_signal="SIG_P38_129_ENTRY",
        exit_signal="SIG_P38_129_EXIT",
        points_normal=["PT_129_N"],
        points_reverse=["PT_130_R"],
        conflicting_routes=["ROUTE_P38_0134"],
        flank_protection_points=["FLANK_PT_029"],
        track_circuits_in_route=["TC_P38_129_A", "TC_P38_129_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_029"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0130": RouteLockingRule(
        route_id="ROUTE_P38_0130",
        entry_signal="SIG_P38_130_ENTRY",
        exit_signal="SIG_P38_130_EXIT",
        points_normal=["PT_130_N"],
        points_reverse=["PT_131_R"],
        conflicting_routes=["ROUTE_P38_0135"],
        flank_protection_points=["FLANK_PT_030"],
        track_circuits_in_route=["TC_P38_130_A", "TC_P38_130_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_030"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0131": RouteLockingRule(
        route_id="ROUTE_P38_0131",
        entry_signal="SIG_P38_131_ENTRY",
        exit_signal="SIG_P38_131_EXIT",
        points_normal=["PT_131_N"],
        points_reverse=["PT_132_R"],
        conflicting_routes=["ROUTE_P38_0136"],
        flank_protection_points=["FLANK_PT_031"],
        track_circuits_in_route=["TC_P38_131_A", "TC_P38_131_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_031"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0132": RouteLockingRule(
        route_id="ROUTE_P38_0132",
        entry_signal="SIG_P38_132_ENTRY",
        exit_signal="SIG_P38_132_EXIT",
        points_normal=["PT_132_N"],
        points_reverse=["PT_133_R"],
        conflicting_routes=["ROUTE_P38_0137"],
        flank_protection_points=["FLANK_PT_032"],
        track_circuits_in_route=["TC_P38_132_A", "TC_P38_132_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_032"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0133": RouteLockingRule(
        route_id="ROUTE_P38_0133",
        entry_signal="SIG_P38_133_ENTRY",
        exit_signal="SIG_P38_133_EXIT",
        points_normal=["PT_133_N"],
        points_reverse=["PT_134_R"],
        conflicting_routes=["ROUTE_P38_0138"],
        flank_protection_points=["FLANK_PT_033"],
        track_circuits_in_route=["TC_P38_133_A", "TC_P38_133_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_033"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0134": RouteLockingRule(
        route_id="ROUTE_P38_0134",
        entry_signal="SIG_P38_134_ENTRY",
        exit_signal="SIG_P38_134_EXIT",
        points_normal=["PT_134_N"],
        points_reverse=["PT_135_R"],
        conflicting_routes=["ROUTE_P38_0139"],
        flank_protection_points=["FLANK_PT_034"],
        track_circuits_in_route=["TC_P38_134_A", "TC_P38_134_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_034"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0135": RouteLockingRule(
        route_id="ROUTE_P38_0135",
        entry_signal="SIG_P38_135_ENTRY",
        exit_signal="SIG_P38_135_EXIT",
        points_normal=["PT_135_N"],
        points_reverse=["PT_136_R"],
        conflicting_routes=["ROUTE_P38_0140"],
        flank_protection_points=["FLANK_PT_035"],
        track_circuits_in_route=["TC_P38_135_A", "TC_P38_135_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_035"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0136": RouteLockingRule(
        route_id="ROUTE_P38_0136",
        entry_signal="SIG_P38_136_ENTRY",
        exit_signal="SIG_P38_136_EXIT",
        points_normal=["PT_136_N"],
        points_reverse=["PT_137_R"],
        conflicting_routes=["ROUTE_P38_0141"],
        flank_protection_points=["FLANK_PT_036"],
        track_circuits_in_route=["TC_P38_136_A", "TC_P38_136_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_036"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0137": RouteLockingRule(
        route_id="ROUTE_P38_0137",
        entry_signal="SIG_P38_137_ENTRY",
        exit_signal="SIG_P38_137_EXIT",
        points_normal=["PT_137_N"],
        points_reverse=["PT_138_R"],
        conflicting_routes=["ROUTE_P38_0142"],
        flank_protection_points=["FLANK_PT_037"],
        track_circuits_in_route=["TC_P38_137_A", "TC_P38_137_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_037"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0138": RouteLockingRule(
        route_id="ROUTE_P38_0138",
        entry_signal="SIG_P38_138_ENTRY",
        exit_signal="SIG_P38_138_EXIT",
        points_normal=["PT_138_N"],
        points_reverse=["PT_139_R"],
        conflicting_routes=["ROUTE_P38_0143"],
        flank_protection_points=["FLANK_PT_038"],
        track_circuits_in_route=["TC_P38_138_A", "TC_P38_138_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_038"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0139": RouteLockingRule(
        route_id="ROUTE_P38_0139",
        entry_signal="SIG_P38_139_ENTRY",
        exit_signal="SIG_P38_139_EXIT",
        points_normal=["PT_139_N"],
        points_reverse=["PT_140_R"],
        conflicting_routes=["ROUTE_P38_0144"],
        flank_protection_points=["FLANK_PT_039"],
        track_circuits_in_route=["TC_P38_139_A", "TC_P38_139_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_039"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0140": RouteLockingRule(
        route_id="ROUTE_P38_0140",
        entry_signal="SIG_P38_140_ENTRY",
        exit_signal="SIG_P38_140_EXIT",
        points_normal=["PT_140_N"],
        points_reverse=["PT_141_R"],
        conflicting_routes=["ROUTE_P38_0145"],
        flank_protection_points=["FLANK_PT_040"],
        track_circuits_in_route=["TC_P38_140_A", "TC_P38_140_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_040"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0141": RouteLockingRule(
        route_id="ROUTE_P38_0141",
        entry_signal="SIG_P38_141_ENTRY",
        exit_signal="SIG_P38_141_EXIT",
        points_normal=["PT_141_N"],
        points_reverse=["PT_142_R"],
        conflicting_routes=["ROUTE_P38_0146"],
        flank_protection_points=["FLANK_PT_041"],
        track_circuits_in_route=["TC_P38_141_A", "TC_P38_141_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_041"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0142": RouteLockingRule(
        route_id="ROUTE_P38_0142",
        entry_signal="SIG_P38_142_ENTRY",
        exit_signal="SIG_P38_142_EXIT",
        points_normal=["PT_142_N"],
        points_reverse=["PT_143_R"],
        conflicting_routes=["ROUTE_P38_0147"],
        flank_protection_points=["FLANK_PT_042"],
        track_circuits_in_route=["TC_P38_142_A", "TC_P38_142_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_042"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0143": RouteLockingRule(
        route_id="ROUTE_P38_0143",
        entry_signal="SIG_P38_143_ENTRY",
        exit_signal="SIG_P38_143_EXIT",
        points_normal=["PT_143_N"],
        points_reverse=["PT_144_R"],
        conflicting_routes=["ROUTE_P38_0148"],
        flank_protection_points=["FLANK_PT_043"],
        track_circuits_in_route=["TC_P38_143_A", "TC_P38_143_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_043"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0144": RouteLockingRule(
        route_id="ROUTE_P38_0144",
        entry_signal="SIG_P38_144_ENTRY",
        exit_signal="SIG_P38_144_EXIT",
        points_normal=["PT_144_N"],
        points_reverse=["PT_145_R"],
        conflicting_routes=["ROUTE_P38_0149"],
        flank_protection_points=["FLANK_PT_044"],
        track_circuits_in_route=["TC_P38_144_A", "TC_P38_144_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_044"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0145": RouteLockingRule(
        route_id="ROUTE_P38_0145",
        entry_signal="SIG_P38_145_ENTRY",
        exit_signal="SIG_P38_145_EXIT",
        points_normal=["PT_145_N"],
        points_reverse=["PT_146_R"],
        conflicting_routes=["ROUTE_P38_0000"],
        flank_protection_points=["FLANK_PT_045"],
        track_circuits_in_route=["TC_P38_145_A", "TC_P38_145_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_045"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0146": RouteLockingRule(
        route_id="ROUTE_P38_0146",
        entry_signal="SIG_P38_146_ENTRY",
        exit_signal="SIG_P38_146_EXIT",
        points_normal=["PT_146_N"],
        points_reverse=["PT_147_R"],
        conflicting_routes=["ROUTE_P38_0001"],
        flank_protection_points=["FLANK_PT_046"],
        track_circuits_in_route=["TC_P38_146_A", "TC_P38_146_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_046"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0147": RouteLockingRule(
        route_id="ROUTE_P38_0147",
        entry_signal="SIG_P38_147_ENTRY",
        exit_signal="SIG_P38_147_EXIT",
        points_normal=["PT_147_N"],
        points_reverse=["PT_148_R"],
        conflicting_routes=["ROUTE_P38_0002"],
        flank_protection_points=["FLANK_PT_047"],
        track_circuits_in_route=["TC_P38_147_A", "TC_P38_147_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_047"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0148": RouteLockingRule(
        route_id="ROUTE_P38_0148",
        entry_signal="SIG_P38_148_ENTRY",
        exit_signal="SIG_P38_148_EXIT",
        points_normal=["PT_148_N"],
        points_reverse=["PT_149_R"],
        conflicting_routes=["ROUTE_P38_0003"],
        flank_protection_points=["FLANK_PT_048"],
        track_circuits_in_route=["TC_P38_148_A", "TC_P38_148_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_048"],
        permissible_aspect="PROCEED_GREEN"
    ),
    "ROUTE_P38_0149": RouteLockingRule(
        route_id="ROUTE_P38_0149",
        entry_signal="SIG_P38_149_ENTRY",
        exit_signal="SIG_P38_149_EXIT",
        points_normal=["PT_149_N"],
        points_reverse=["PT_150_R"],
        conflicting_routes=["ROUTE_P38_0004"],
        flank_protection_points=["FLANK_PT_049"],
        track_circuits_in_route=["TC_P38_149_A", "TC_P38_149_B"],
        approach_locking_timeout_sec=120,
        overlap_track_circuits=["TC_OVL_049"],
        permissible_aspect="PROCEED_GREEN"
    ),
}
