"""Locomotive Diagnostic Telemetry Registry - Modular Log Aggregator."""
from typing import List
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_001 import LocomotiveTelemetryPoint

HISTORICAL_TELEMETRY_LOGS: List[LocomotiveTelemetryPoint] = []

from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_001 import TELEMETRY_LOGS_BATCH_001
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_001)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_002 import TELEMETRY_LOGS_BATCH_002
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_002)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_003 import TELEMETRY_LOGS_BATCH_003
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_003)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_004 import TELEMETRY_LOGS_BATCH_004
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_004)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_005 import TELEMETRY_LOGS_BATCH_005
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_005)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_006 import TELEMETRY_LOGS_BATCH_006
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_006)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_007 import TELEMETRY_LOGS_BATCH_007
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_007)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_008 import TELEMETRY_LOGS_BATCH_008
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_008)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_009 import TELEMETRY_LOGS_BATCH_009
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_009)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_010 import TELEMETRY_LOGS_BATCH_010
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_010)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_011 import TELEMETRY_LOGS_BATCH_011
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_011)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_012 import TELEMETRY_LOGS_BATCH_012
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_012)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_013 import TELEMETRY_LOGS_BATCH_013
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_013)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_014 import TELEMETRY_LOGS_BATCH_014
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_014)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_015 import TELEMETRY_LOGS_BATCH_015
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_015)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_016 import TELEMETRY_LOGS_BATCH_016
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_016)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_017 import TELEMETRY_LOGS_BATCH_017
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_017)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_018 import TELEMETRY_LOGS_BATCH_018
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_018)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_019 import TELEMETRY_LOGS_BATCH_019
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_019)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_020 import TELEMETRY_LOGS_BATCH_020
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_020)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_021 import TELEMETRY_LOGS_BATCH_021
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_021)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_022 import TELEMETRY_LOGS_BATCH_022
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_022)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_023 import TELEMETRY_LOGS_BATCH_023
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_023)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_024 import TELEMETRY_LOGS_BATCH_024
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_024)
from simulation.telemetry.diagnostic_logs.loco_telemetry_batch_025 import TELEMETRY_LOGS_BATCH_025
HISTORICAL_TELEMETRY_LOGS.extend(TELEMETRY_LOGS_BATCH_025)
