"""G&SR Safety Compliance Engine - Modular Rulebook Aggregator."""
from typing import Dict
from simulation.safety.gsr_modules.gsr_rulebook_section_001 import GSRSafetyRule

GSR_REGULATORY_RULES: Dict[str, GSRSafetyRule] = {}

from simulation.safety.gsr_modules.gsr_rulebook_section_001 import GSR_RULEBOOK_SECTION_001
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_001)
from simulation.safety.gsr_modules.gsr_rulebook_section_002 import GSR_RULEBOOK_SECTION_002
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_002)
from simulation.safety.gsr_modules.gsr_rulebook_section_003 import GSR_RULEBOOK_SECTION_003
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_003)
from simulation.safety.gsr_modules.gsr_rulebook_section_004 import GSR_RULEBOOK_SECTION_004
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_004)
from simulation.safety.gsr_modules.gsr_rulebook_section_005 import GSR_RULEBOOK_SECTION_005
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_005)
from simulation.safety.gsr_modules.gsr_rulebook_section_006 import GSR_RULEBOOK_SECTION_006
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_006)
from simulation.safety.gsr_modules.gsr_rulebook_section_007 import GSR_RULEBOOK_SECTION_007
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_007)
from simulation.safety.gsr_modules.gsr_rulebook_section_008 import GSR_RULEBOOK_SECTION_008
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_008)
from simulation.safety.gsr_modules.gsr_rulebook_section_009 import GSR_RULEBOOK_SECTION_009
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_009)
from simulation.safety.gsr_modules.gsr_rulebook_section_010 import GSR_RULEBOOK_SECTION_010
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_010)
from simulation.safety.gsr_modules.gsr_rulebook_section_011 import GSR_RULEBOOK_SECTION_011
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_011)
from simulation.safety.gsr_modules.gsr_rulebook_section_012 import GSR_RULEBOOK_SECTION_012
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_012)
from simulation.safety.gsr_modules.gsr_rulebook_section_013 import GSR_RULEBOOK_SECTION_013
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_013)
from simulation.safety.gsr_modules.gsr_rulebook_section_014 import GSR_RULEBOOK_SECTION_014
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_014)
from simulation.safety.gsr_modules.gsr_rulebook_section_015 import GSR_RULEBOOK_SECTION_015
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_015)
from simulation.safety.gsr_modules.gsr_rulebook_section_016 import GSR_RULEBOOK_SECTION_016
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_016)
from simulation.safety.gsr_modules.gsr_rulebook_section_017 import GSR_RULEBOOK_SECTION_017
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_017)
from simulation.safety.gsr_modules.gsr_rulebook_section_018 import GSR_RULEBOOK_SECTION_018
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_018)
from simulation.safety.gsr_modules.gsr_rulebook_section_019 import GSR_RULEBOOK_SECTION_019
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_019)
from simulation.safety.gsr_modules.gsr_rulebook_section_020 import GSR_RULEBOOK_SECTION_020
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_020)
from simulation.safety.gsr_modules.gsr_rulebook_section_021 import GSR_RULEBOOK_SECTION_021
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_021)
from simulation.safety.gsr_modules.gsr_rulebook_section_022 import GSR_RULEBOOK_SECTION_022
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_022)
from simulation.safety.gsr_modules.gsr_rulebook_section_023 import GSR_RULEBOOK_SECTION_023
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_023)
from simulation.safety.gsr_modules.gsr_rulebook_section_024 import GSR_RULEBOOK_SECTION_024
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_024)
from simulation.safety.gsr_modules.gsr_rulebook_section_025 import GSR_RULEBOOK_SECTION_025
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_025)
from simulation.safety.gsr_modules.gsr_rulebook_section_026 import GSR_RULEBOOK_SECTION_026
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_026)
from simulation.safety.gsr_modules.gsr_rulebook_section_027 import GSR_RULEBOOK_SECTION_027
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_027)
from simulation.safety.gsr_modules.gsr_rulebook_section_028 import GSR_RULEBOOK_SECTION_028
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_028)
from simulation.safety.gsr_modules.gsr_rulebook_section_029 import GSR_RULEBOOK_SECTION_029
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_029)
from simulation.safety.gsr_modules.gsr_rulebook_section_030 import GSR_RULEBOOK_SECTION_030
GSR_REGULATORY_RULES.update(GSR_RULEBOOK_SECTION_030)
